INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Šport', 1, 'Kto vyhral posledný Super Bowl?', 'Chiefs'),
('Šport', 1, 'Aké je najpopulárnejšie športové podujatie na svete?', 'Majstrovstvá sveta'),
('Šport', 1, 'Ktorý šport využíva loptičku a raketu?', 'Tenis'),
('Šport', 1, 'Kto je najúspešnejší plavec všetkých čias?', 'Phelps'),
('Šport', 1, 'Aký šport sa hrá na ľade?', 'Hokej'),
('Šport', 1, 'Ktorý tím vyhral posledný majstrovský titul v NBA?', 'Nuggets'),
('Šport', 1, 'Kto je známy ako "King James"?', 'LeBron'),
('Šport', 1, 'Aký je názov olympijských hier v zime?', 'Zimné'),
('Šport', 1, 'Ktoré mesto hostí letné olympijské hry 2024?', 'Paríž'),
('Šport', 1, 'Kto je najrýchlejší bežec na 100 metrov?', 'Bolt'),
('Šport', 1, 'Ktorý šport sa hrá s balónom a bránkami?', 'Futbal'),
('Šport', 1, 'Kto je najznámejší cyklista?', 'Armstrong'),
('Šport', 1, 'Aké je najvyššie ocenenie v americkom futbale?', 'Super Bowl'),
('Šport', 1, 'Kto je najznámejší futbalista všetkých čias?', 'Pelé'),
('Šport', 1, 'Kto je tréner FC Barcelona?', 'Xavi'),
('Šport', 1, 'Kto je najúspešnejší tenista?', 'Federer'),
('Šport', 1, 'Ktorý šport je známy ako "kráľ športov"?', 'Futbal'),
('Šport', 1, 'Ktoré mesto je domovom klubu Manchester United?', 'Manchester'),
('Šport', 1, 'Kto je najlepším strelec v histórii NHL?', 'Gretzky'),
('Šport', 1, 'Aký šport sa hrá v súťažiach ako Wimbledon?', 'Tenis'),
('Šport', 1, 'Kto je známy ako "Tennis Queen"?', 'Williams'),
('Šport', 1, 'Ktoré krajiny hostia majstrovstvá sveta vo futbale?', 'Katar'),
('Šport', 1, 'Kto vyhral Tour de France 2023?', 'Vingegaard'),
('Šport', 1, 'Aký šport je súčasťou olympijských hier?', 'Atletika'),
('Šport', 1, 'Kto je najlepší strelec v histórii NBA?', 'Kareem'),
('Šport', 1, 'Ktorý šport je známy ako "game of kings"?', 'Šach'),
('Šport', 1, 'Kto vyhral zlato na 100 m v Tokiu?', 'Bromell'),
('Šport', 1, 'Aký šport sa hrá s pingpongovou loptičkou?', 'Stolný tenis'),
('Šport', 1, 'Kto je najúspešnejší futbalový tréner?', 'Ferguson'),
('Šport', 1, 'Ktorý šport sa hrá na piesku?', 'Volejbal'),
('Šport', 1, 'Kto je najznámejší motoristický pretekár?', 'Schumacher'),
('Šport', 1, 'Kto je najúspešnejší športovec v histórii?', 'Jordan'),
('Šport', 1, 'Aké je najpopulárnejšie zimné športové odvetvie?', 'Hokej'),
('Šport', 1, 'Ktorý šport sa hrá s loptou a palicou?', 'Golf'),
('Šport', 1, 'Kto je najznámejší futbalový klub v Taliansku?', 'Juventus'),
('Šport', 1, 'Kto je najmladší víťaz Grand Slamu?', 'Nadal'),
('Šport', 1, 'Aký šport je známy ako "náš národný šport"?', 'Hokej'),
('Šport', 1, 'Kto je najúspešnejší tenista v histórii?', 'Federer'),
('Šport', 1, 'Ktorý šport je známy ako "kráľovská disciplína"?', 'Atletika'),
('Šport', 1, 'Kto je známy ako "futbalový mág"?', 'Messi'),
('Šport', 1, 'Aký je názov najväčšieho cyklistického preteku?', 'Tour'),
('Šport', 1, 'Ktorý šport je súčasťou olympijských hier?', 'Gymnastika'),
('Šport', 1, 'Kto je najúspešnejší maratónsky bežec?', 'Kipruto'),
('Šport', 1, 'Aký šport je populárny v Austrálii a hrá sa na tráve?', 'Rugby'),
('Šport', 1, 'Kto je najznámejší americký futbalista?', 'Brady'),
('Šport', 1, 'Ktoré mesto hostilo olympijské hry 2000?', 'Sydney'),
('Šport', 1, 'Aký je názov najprestížnejšieho futbalového turnaja v Európe?', 'LM'),
('Šport', 1, 'Kto vyhral Golden Boot na MS 2018?', 'Kane'),
('Šport', 1, 'Kto je známy ako "Tiger Woods"?', 'Woods'),
('Šport', 1, 'Ktorý šport je známy ako "biela farba"?', 'Tenis'),
('Šport', 1, 'Kto je známy ako "Rocket"?', 'Ovechkin'),
('Šport', 1, 'Aký je názov najznámejšieho futbalového štadióna?', 'Camp Nou'),
('Šport', 1, 'Kdo je nejznámější cyklistický závodník?', 'Armstrong'),
('Šport', 1, 'Kto je najznámejší hokejista?', 'Gretzky'),
('Šport', 1, 'Kde sa konajú letné olympijské hry?', 'Atény'),
('Šport', 1, 'Aký šport sa hrá vo vode?', 'Plávanie'),
('Šport', 1, 'Kto je najlepší futbalový brankár?', 'Buffon'),
('Šport', 1, 'Ktorý šport sa hrá s loptou a sieťou?', 'Volejbal'),
('Šport', 1, 'Kto je známy ako "Maradona"?', 'Futbalista'),
('Šport', 1, 'Aké je najpopulárnejšie zimné športové podujatie?', 'Olympiáda'),
('Šport', 1, 'Kto je najlepší strelec v histórii futbalu?', 'Pele'),
('Šport', 1, 'Kto je známy ako "Usain Bolt"?', 'Bežec'),
('Šport', 1, 'Kde sa konajú majstrovstvá sveta v hokeji?', 'Rusia'),
('Šport', 1, 'Kto je najúspešnejší golfista?', 'Woods'),
('Šport', 1, 'Aký šport je spojený s gymnastikou?', 'Telesná'),
('Šport', 1, 'Kto je najznámejší pretekár F1?', 'Schumacher'),
('Šport', 1, 'Aké je najvyššie ocenenie v boxe?', 'Majster'),
('Šport', 1, 'Kto je známy ako "Misty May"?', 'Volejbalistka'),
('Šport', 1, 'Aký šport sa hrá na skateboarde?', 'Skateboarding'),
('Šport', 1, 'Kto je najrýchlejší plavec?', 'Phelps'),
('Šport', 1, 'Kto vyhral posledný Wimbledon?', 'Djokovic'),
('Šport', 1, 'Kde sa hrá kriket?', 'Indie'),
('Šport', 1, 'Kto je známy ako "Kobe"?', 'Futbalista'),
('Šport', 1, 'Aký šport je populárny v Južnej Amerike?', 'Futbal'),
('Šport', 1, 'Kto je najlepší tenista na tráve?', 'Federer'),
('Šport', 1, 'Aký šport sa hrá s curlingovými kameňmi?', 'Curling'),
('Šport', 1, 'Kto je najúspešnejší plážový volejbalista?', 'Rogers'),
('Šport', 1, 'Kde sa koná Tour de France?', 'Francúzsko'),
('Šport', 1, 'Kto je najznámejší maratónsky bežec?', 'Bekele'),
('Šport', 1, 'Aký šport sa hrá s raketou a loptičkou?', 'Badminton'),
('Šport', 1, 'Kto je najznámejší jazdec na koni?', 'Seabiscuit'),
('Šport', 1, 'Kde sa konajú majstrovstvá sveta vo futbale?', 'Katar'),
('Šport', 1, 'Kto je najlepší slovenský hokejista?', 'Hasek'),
('Šport', 1, 'Aký šport je známy ako "kráľ športov"?', 'Futbal'),
('Šport', 1, 'Kto je známy ako "The Rock"?', 'Wrestler'),
('Šport', 1, 'Kde sa koná NBA finále?', 'USA'),
('Šport', 1, 'Aký šport sa hrá na sánkach?', 'Sánkovanie'),
('Šport', 1, 'Kto je známy ako "Michaels"?', 'Športovec'),
('Šport', 1, 'Kde sa koná US Open?', 'New York'),
('Šport', 1, 'Kto je najúspešnejší kaskadér?', 'Jackie'),
('Šport', 1, 'Aký šport sa hrá v bazéne?', 'Vodný'),
('Šport', 1, 'Kto je známy ako "Ali"?', 'Boxer'),
('Šport', 1, 'Aký šport je známy ako "noblesse"?', 'Polo'),
('Šport', 1, 'Kto je najznámejší futbalový útočník?', 'Ronaldo'),
('Šport', 1, 'Kde sa konajú majstrovstvá sveta v hokeji?', 'Švédsko'),
('Šport', 1, 'Kto je najlepší futbalový rozhodca?', 'Collina'),
('Šport', 1, 'Aké je najpopulárnejšie vodné športové podujatie?', 'Olympiáda'),
('Šport', 1, 'Kto je známy ako "Bolt"?', 'Bežec'),
('Šport', 1, 'Aký šport sa hrá s raketou a sieťou?', 'Tenis'),
('Šport', 1, 'Kdo je známy ako "Pele"?', 'Futbalista'),
('Šport', 1, 'Kto je najstarší aktívny športovec?', 'Carter'),
('Šport', 1, 'Kde sa konajú majstrovstvá sveta v basketbale?', 'USA'),
('Šport', 1, 'Kto je najúspešnejší hokejový brankár?', 'Broduer'),
('Šport', 1, 'Aký šport je známy ako "golden sport"?', 'Golf'),
('Šport', 1, 'Kto je najznámejší americký bežec?', 'Carl'),
('Šport', 1, 'Kde sa konajú majstrovstvá sveta v cyklistike?', 'Bélgium'),
('Šport', 1, 'Kto je najlepším volejbalistom?', 'Kubiak'),
('Šport', 1, 'Aký šport je známy ako "poker na vode"?', 'Jachting'),
('Šport', 1, 'Kto je známy ako "Shakira"?', 'Speváčka'),
('Šport', 1, 'Kde sa konajú majstrovstvá sveta v triatlone?', 'Zürich'),
('Šport', 2, 'Kto je najúspešnejší tenista v mužskej histórii?', 'Federer'),
('Šport', 2, 'Aký je názov najznámejšieho futbalového klubu v Španielsku?', 'Real Madrid'),
('Šport', 2, 'Kto je známy ako "Svetový šampión" v boxe?', 'Ali'),
('Šport', 2, 'Ktorý tím vyhral posledný Stanley Cup?', 'Avalanche'),
('Šport', 2, 'Kto je najrýchlejší plavec v histórii?', 'Phelps'),
('Šport', 2, 'Aký šport sa hrá na zimných olympijských hrách?', 'Hokej'),
('Šport', 2, 'Ktorý športovec má najviac zlatých medailí?', 'Phelps'),
('Šport', 2, 'Kto je najúspešnejší futbalový hráč vo Francúzsku?', 'Zidane'),
('Šport', 2, 'Kto vyhral posledný Grand Slam v tenise?', 'Djokovic'),
('Šport', 2, 'Aký šport je najpopulárnejší v Anglicku?', 'Futbal'),
('Šport', 2, 'Ktorý tím vyhral posledné majstrovstvá sveta vo futbale?', 'Francúzsko'),
('Šport', 2, 'Kto je známy ako "Babe Ruth" v baseballu?', 'Ruth'),
('Šport', 2, 'Aký šport sa hrá s palicou a loptičkou?', 'Hokej'),
('Šport', 2, 'Kto je najznámejší tenista žien?', 'Williams'),
('Šport', 2, 'Ktoré mesto je známe svojím maratónom?', 'Boston'),
('Šport', 2, 'Kto vyhral Tour de France v 2022?', 'Vingegaard'),
('Šport', 2, 'Aký šport je známy ako "kráľovská hra"?', 'Šach'),
('Šport', 2, 'Kto je najúspešnejší volejbalista?', 'Kurek'),
('Šport', 2, 'Kto je najstarší víťaz v histórii Grand Slamu?', 'Andrescu'),
('Šport', 2, 'Ktorý šport sa hrá na pieskových plážach?', 'Volejbal'),
('Šport', 2, 'Kto je najznámejší skokan do vody?', 'Dahlke'),
('Šport', 2, 'Aké je najprestížnejšie golfové podujatie?', 'Masters'),
('Šport', 2, 'Kto je známy ako "Michael Jordan" basketbalu?', 'Jordan'),
('Šport', 2, 'Ktorý tím vyhral UEFA Champions League v 2021?', 'Chelsea'),
('Šport', 2, 'Kto je najúspešnejší hokejista všetkých čias?', 'Gretzky'),
('Šport', 2, 'Aký šport je populárny v Taliansku?', 'Futbal'),
('Šport', 2, 'Kto je najlepší americký futbalista?', 'Brady'),
('Šport', 2, 'Aký šport je známy ako "pohybujúca sa hra"?', 'Kriket'),
('Šport', 2, 'Kto vyhral posledné majstrovstvá sveta v hokeji?', 'Kanada'),
('Šport', 2, 'Kto je najúspešnejší maratónsky bežec?', 'Bekele'),
('Šport', 2, 'Ktorý atlet je známy ako "najrýchlejší muž"?', 'Bolt'),
('Šport', 2, 'Aký šport je známy ako "súťaž v kráse"?', 'Gymnastika'),
('Šport', 2, 'Kto je známy ako "Kráľ tenisu"?', 'Federer'),
('Šport', 2, 'Kto je najlepším futbalovým brankárom?', 'Buffon'),
('Šport', 2, 'Ktoré mesto hostí Formula 1?', 'Monako'),
('Šport', 2, 'Aký šport sa hrá s raketou a loptou?', 'Badminton'),
('Šport', 2, 'Kto je najúspešnejší cyklista v histórii?', 'Armstrong'),
('Šport', 2, 'Kde sa konajú olympijské hry v roku 2028?', 'Los Angeles'),
('Šport', 2, 'Kto vyhral posledné majstrovstvá sveta v ženského futbale?', 'USA'),
('Šport', 2, 'Kto je známy ako "Kráľ boxu"?', 'Ali'),
('Šport', 2, 'Ktorý šport sa hrá s curlingovými kameňmi?', 'Curling'),
('Šport', 2, 'Kto je najznámejší slovenský futbalista?', 'Hamšík'),
('Šport', 2, 'Aký šport je známy ako "futbal na piesku"?', 'Plážový futbal'),
('Šport', 2, 'Kto je najznámejší chodec?', 'Waldner'),
('Šport', 2, 'Kde sa koná Wimbledon?', 'Londýn'),
('Šport', 2, 'Kto vyhral posledný Super Bowl?', 'Chiefs'),
('Šport', 2, 'Kto je najúspešnejší skokan na lyžiach?', 'Stoch'),
('Šport', 2, 'Aký šport sa hrá na dráhe?', 'Atletika'),
('Šport', 2, 'Ktoré mesto hostilo letné olympijské hry 2008?', 'Peking'),
('Šport', 2, 'Kto je najznámejší pretekár v MotoGP?', 'Rossi'),
('Šport', 2, 'Kto je najúspešnejší športovec v histórii?', 'Jordan'),
('Šport', 2, 'Aký šport sa hrá s palicou a loptičkou?', 'Golf'),
('Šport', 2, 'Kto je najlepší skokan do vody?', 'Daley'),
('Šport', 2, 'Kto vyhral posledné majstrovstvá sveta v rugby?', 'Nový Zéland'),
('Šport', 2, 'Kto vyhral posledný majstrovský titul v Premier League?', 'Manchester City'),
('Šport', 2, 'Kto je najlepším slovenským hokejistom všetkých čias?', 'Peter Šťastný'),
('Šport', 2, 'Aký šport sa hrá na ľade s puku?', 'Hokej'),
('Šport', 2, 'Kto je najrýchlejší muž na svete?', 'Usain Bolt'),
('Šport', 2, 'Kto je najúspešnejší tréner v histórii futbalu?', 'Sir Alex Ferguson'),
('Šport', 2, 'Ktorý tím je známy ako "Bílí Tygři"?', 'Liberec'),
('Šport', 2, 'Kto je najúspešnejší tenista žien?', 'Margaret Court'),
('Šport', 2, 'Aký je názov najprestížnejšieho futbalového turnaja?', 'Liga majstrov'),
('Šport', 2, 'Ktoré mesto hostí tenisové US Open?', 'New York'),
('Šport', 2, 'Kto je najznámejší jazdec na motorke?', 'Valentino Rossi'),
('Šport', 2, 'Ktorý šport je známy ako "kráľovná športov"?', 'Atletika'),
('Šport', 2, 'Kto je najúspešnejší hokejový útočník?', 'Wayne Gretzky'),
('Šport', 2, 'Ktorý šport sa hrá na bežeckých dráhach?', 'Atletika'),
('Šport', 2, 'Kto je najznámejší futbalista Argentíny?', 'Lionel Messi'),
('Šport', 2, 'Kto je najúspešnejší skokan na lyžiach?', 'Matti Nykanen'),
('Šport', 2, 'Aký šport je súčasťou letných olympijských hier?', 'Gymnastika'),
('Šport', 2, 'Kto je najlepším futbalovým brankárom?', 'Lev Yashin'),
('Šport', 2, 'Ktoré mesto hostilo zimné olympijské hry 2010?', 'Vancouver'),
('Šport', 2, 'Kto je najznámejší cyklista všetkých čias?', 'Lance Armstrong'),
('Šport', 2, 'Aký šport je známy ako "hokej na tráve"?', 'Lawn Hockey'),
('Šport', 2, 'Kto vyhral posledný titul vo Formula 1?', 'Max Verstappen'),
('Šport', 2, 'Ktorý šport je známy ako "súťaž v kráse"?', 'Tanečné športy'),
('Šport', 2, 'Kto je najúspešnejší golfista v histórii?', 'Jack Nicklaus'),
('Šport', 2, 'Aký je názov najväčšieho futbalového štadióna v Európe?', 'Camp Nou'),
('Šport', 2, 'Kto je najznámejší zápasník WWE?', 'Dwayne Johnson'),
('Šport', 2, 'Ktorý tím vyhral posledný Stanley Cup?', 'Tampa Bay Lightning'),
('Šport', 2, 'Kto je najznámejší maratónsky bežec?', 'Eliud Kipchoge'),
('Šport', 2, 'Aký šport je známy ako "noblesse"?', 'Polo'),
('Šport', 2, 'Kto je najlepším volejbalistom?', 'Karch Kiraly'),
('Šport', 2, 'Kde sa konajú majstrovstvá sveta v rugby?', 'Južná Afrika'),
('Šport', 2, 'Kto je najúspešnejší pretekár v triatlone?', 'Mark Allen'),
('Šport', 2, 'Aký šport sa hrá na skateboarde?', 'Skateboarding'),
('Šport', 2, 'Kto je najznámejší plážový volejbalista?', 'Kerri Walsh'),
('Šport', 2, 'Kde sa konajú majstrovstvá sveta v atletike?', 'Eugene'),
('Šport', 2, 'Kto vyhral posledný Super Bowl v NFL?', 'Kansas City'),
('Šport', 2, 'Kto je najúspešnejší cyklista Tour de France?', 'Bernard Hinault'),
('Šport', 2, 'Ktoré mesto hostilo olympijské hry 1992?', 'Barcelona'),
('Šport', 2, 'Kto je najlepším slovenským futbalistom?', 'Ľubomír Moravčík'),
('Šport', 2, 'Aký šport je známy ako "súťaž v rýchlosti"?', 'Kriket'),
('Šport', 2, 'Kto je známy ako "Kráľ tenisu"?', 'Roger Federer'),
('Šport', 2, 'Kto je najznámejší futbalový útočník?', 'Ronaldo'),
('Šport', 2, 'Kedy sa konajú majstrovstvá sveta v hokeji?', 'Každoročne'),
('Šport', 2, 'Kto je najúspešnejší plavec v histórii?', 'Michael Phelps'),
('Šport', 2, 'Kto vyhral zlato na olympijských hrách v Tokiu?', 'Caeleb Dressel'),
('Šport', 2, 'Kto je najlepším futbalovým rozhodcom?', 'Pierluigi Collina'),
('Šport', 2, 'Kto je najznámejší slovenský hokejový brankár?', 'Jaroslav Halák'),
('Šport', 2, 'Ktorý šport je známy ako "kráľovská hra"?', 'Šach'),
('Šport', 2, 'Kto je najúspešnejší hokejový tréner?', 'Scotty Bowman'),
('Šport', 2, 'Aké je najväčšie cyklistické preteky?', 'Tour de France'),
('Šport', 2, 'Kto je známy ako "Babe Ruth" baseballu?', 'George Herman'),
('Šport', 2, 'Aký šport sa hrá na pieskových plážach?', 'Plážový volejbal'),
('Šport', 2, 'Kto je najznámejší jazdec v NASCAR?', 'Dale Earnhardt'),
('Šport', 2, 'Ktorý tím vyhral posledný titul v bundeslige?', 'Bayern Mníchov'),
('Šport', 2, 'Kto je najrýchlejší plavec všetkých čias?', 'Michael Phelps'),
('Šport', 2, 'Kto je najúspešnejší maratónsky bežec v histórii?', 'Haile Gebrselassie'),
('Šport', 2, 'Kto je známy ako "Kráľ futbalu"?', 'Pelé'),
('Šport', 2, 'Aký šport je známy ako "tanečný šport"?', 'Ballet'),
('Šport', 3, 'Kto má najviac zlatých medailí na olympiáde?', 'Phelps'),
('Šport', 3, 'Ktorý tím vyhral posledný Copa America?', 'Argentina'),
('Šport', 3, 'Kto je najúspešnejší tréner v histórii NBA?', 'Phil Jackson'),
('Šport', 3, 'Kto je najrýchlejší muž v histórii na 400 m?', 'Wayde van Niekerk'),
('Šport', 3, 'Kto vyhral posledný RWC v rugby?', 'South Africa'),
('Šport', 3, 'Kto je známy ako "The Greatest"?', 'Muhammad Ali'),
('Šport', 3, 'Kto je najúspešnejší plážový volejbalový tím?', 'Kerri Walsh'),
('Šport', 3, 'Kto je najznámejší lyžiar?', 'Lindsey Vonn'),
('Šport', 3, 'Kto má najviac titulov vo Formula 1?', 'Michael Schumacher'),
('Šport', 3, 'Kto vyhral posledný UEFA Euro?', 'Itália'),
('Šport', 3, 'Kto je najúspešnejší jazdec v F1?', 'Lewis Hamilton'),
('Šport', 3, 'Kto je najlepší skokan na lyžiach všetkých čias?', 'Matti Nykanen'),
('Šport', 3, 'Kto je najrýchlejší plavec na 200 m?', 'Michael Phelps'),
('Šport', 3, 'Kto vyhral posledný Wimbledon u žien?', 'Elena Rybakina'),
('Šport', 3, 'Kto je najúspešnejší cyklista na Grand Tour?', 'Eddy Merckx'),
('Šport', 3, 'Kto je najstarší víťaz Tour de France?', 'Firmin Lambot'),
('Šport', 3, 'Kto má najviac titulov v hokeji?', 'Wayne Gretzky'),
('Šport', 3, 'Kto vyhral zlato na 400 m v Tokiu?', 'Karsten Warholm'),
('Šport', 3, 'Kto je najúspešnejší tenista na antuke?', 'Rafael Nadal'),
('Šport', 3, 'Kto je najznámejší zápasník WWE?', 'Stone Cold'),
('Šport', 3, 'Kto vyhral posledný Stanley Cup v NHL?', 'Colorado Avalanche'),
('Šport', 3, 'Kto má najviac zlatých medailí v plávaní?', 'Michael Phelps'),
('Šport', 3, 'Kto je najúspešnejší golfista všetkých čias?', 'Jack Nicklaus'),
('Šport', 3, 'Kto je najlepší slovenský hokejista v NHL?', 'Zdeno Chára'),
('Šport', 3, 'Kto je najúspešnejší futbalista v histórii?', 'Cristiano Ronaldo'),
('Šport', 3, 'Kto je najznámejší skokan na lyžiach?', 'Emanuel S.'),
('Šport', 3, 'Kto je najúspešnejší plavec v histórii?', 'Michael Phelps'),
('Šport', 3, 'Kto vyhral posledný Masters v golfe?', 'Scottie Scheffler'),
('Šport', 3, 'Kto je najrýchlejší atlét na svete?', 'Usain Bolt'),
('Šport', 3, 'Kto je najlepší futbalový útočník v histórii?', 'Gerd Müller'),
('Šport', 3, 'Kto je najznámejší futbalový brankár?', 'Lev Yashin'),
('Šport', 3, 'Kto je najúspešnejší futbalový tím v histórii?', 'Real Madrid'),
('Šport', 3, 'Kto je najúspešnejší tenista vo Wimbledone?', 'Roger Federer'),
('Šport', 3, 'Kto vyhral posledný Grand Prix v formule?', 'Max Verstappen'),
('Šport', 3, 'Kto je známy ako "Kráľ futbalu"?', 'Pelé'),
('Šport', 3, 'Kto je najúspešnejší športovec vo futbale?', 'Cristiano Ronaldo'),
('Šport', 3, 'Kto vyhral posledný ročník Tour de France?', 'Jonas Vingegaard'),
('Šport', 3, 'Kto je najúspešnejší futbalový tréner v histórii?', 'Sir Alex Ferguson'),
('Šport', 3, 'Kto je najznámejší americký futbalista?', 'Tom Brady'),
('Šport', 3, 'Kto je najlepší slovenský tenista?', 'Dominik Hrbatý'),
('Šport', 3, 'Kto vyhral posledný šampionát v boxe?', 'Saúl Álvarez'),
('Šport', 3, 'Kto je najznámejší pretekár v NASCAR?', 'Dale Earnhardt'),
('Šport', 3, 'Kto je najúspešnejší skokan do vody?', 'Greg Louganis'),
('Šport', 3, 'Kto má najviac titulov v hokeji?', 'Wayne Gretzky'),
('Šport', 3, 'Kto vyhral posledný šampionát v basketbale?', 'Milwaukee Bucks'),
('Šport', 3, 'Kto je najúspešnejší skater?', 'Tony Hawk'),
('Šport', 3, 'Kto je najznámejší tréner v histórii?', 'Phil Jackson'),
('Šport', 3, 'Kto vyhral posledné majstrovstvá sveta v hokeji?', 'Kanada'),
('Šport', 3, 'Kto je najúspešnejší hokejový brankár?', 'Martin Brodeur'),
('Šport', 3, 'Kto je najrýchlejší muž na 100 m?', 'Usain Bolt'),
('Šport', 3, 'Kto je najúspešnejší futbalový brankár?', 'Lev Yashin'),
('Šport', 3, 'Kto je najznámejší tenista?', 'Roger Federer'),
('Šport', 3, 'Kto vyhral posledný šampionát v MMA?', 'Islam Makhachev'),
('Šport', 3, 'Kto je najúspešnejší cyklista v histórii?', 'Eddy Merckx'),
('Šport', 3, 'Kto je najstarší víťaz v histórii Grand Slamu?', 'Ken Rosewall'),
('Šport', 3, 'Kto je najznámejší futbalový útočník?', 'Pelé'),
('Šport', 3, 'Kto vyhral posledný Super Bowl v NFL?', 'Kansas City Chiefs'),
('Šport', 3, 'Kto je najúspešnejší tenista všetkých čias?', 'Roger Federer'),
('Šport', 3, 'Kto je najúspešnejší skokan na lyžiach všetkých čias?', 'Janne Ahonen'),
('Šport', 3, 'Kto vyhral Tour de France v 2021?', 'Tadej Pogačar'),
('Šport', 3, 'Aký šport je známy ako "pohybujúca sa hra"?', 'Futbal'),
('Šport', 3, 'Kto je najrýchlejší muž na 400 metrov?', 'Wayde van Niekerk'),
('Šport', 3, 'Kto je najznámejší futbalista Nemecka?', 'Franz Beckenbauer'),
('Šport', 3, 'Kto je najúspešnejší tenista na antuke?', 'Rafael Nadal'),
('Šport', 3, 'Kto vyhral posledný Stanley Cup v NHL?', 'Colorado Avalanche'),
('Šport', 3, 'Kto je najlepší hokejový útočník v histórii?', 'Wayne Gretzky'),
('Šport', 3, 'Aký šport sa hrá na pieskových plážach?', 'Plážový volejbal'),
('Šport', 3, 'Kto je najznámejší cyklista v histórii?', 'Eddy Merckx'),
('Šport', 3, 'Kto je najúspešnejší plavec na svete?', 'Michael Phelps'),
('Šport', 3, 'Kto je najznámejší futbalista v Taliansku?', 'Roberto Baggio'),
('Šport', 3, 'Kto je najúspešnejší golfista v histórii?', 'Jack Nicklaus'),
('Šport', 3, 'Kto je najznámejší motoristický pretekár?', 'Ayrton Senna'),
('Šport', 3, 'Kto vyhral posledné majstrovstvá sveta v rugby?', 'South Africa'),
('Šport', 3, 'Kto je najúspešnejší futbalový brankár?', 'Lev Yashin'),
('Šport', 3, 'Kto je najznámejší jazdec v F1?', 'Lewis Hamilton'),
('Šport', 3, 'Kto je najúspešnejší tenista v mužskej histórii?', 'Roger Federer'),
('Šport', 3, 'Kto vyhral posledný RWC v rugby?', 'South Africa'),
('Šport', 3, 'Kto je najúspešnejší športovec v histórii?', 'Michael Phelps'),
('Šport', 3, 'Kto je najstarší víťaz Tour de France?', 'Firmin Lambot'),
('Šport', 3, 'Kto je najúspešnejší maratónsky bežec?', 'Eliud Kipchoge'),
('Šport', 3, 'Kto je najznámejší futbalový tréner?', 'Sir Alex Ferguson'),
('Šport', 3, 'Kto je najúspešnejší hokejový brankár?', 'Dominik Hašek'),
('Šport', 3, 'Kto je známy ako "Kráľ futbalu"?', 'Pelé'),
('Šport', 3, 'Kto je najúspešnejší futbalista vo Francúzsku?', 'Zinedine Zidane'),
('Šport', 3, 'Kto vyhral posledný UEFA Euro?', 'Itália'),
('Šport', 3, 'Kto je najznámejší pretekár v MotoGP?', 'Valentino Rossi'),
('Šport', 3, 'Kto je najrýchlejší muž na 200 m?', 'Usain Bolt'),
('Šport', 3, 'Kto je najúspešnejší tenista všetkých čias?', 'Roger Federer'),
('Šport', 3, 'Kto je najúspešnejší strelec v histórii NHL?', 'Wayne Gretzky'),
('Šport', 3, 'Kto je najznámejší futbalový útočník?', 'Cristiano Ronaldo'),
('Šport', 3, 'Kto je najúspešnejší hokejový tím?', 'Montreal Canadiens'),
('Šport', 3, 'Kto je najlepší futbalový brankár všetkých čias?', 'Lev Yashin'),
('Šport', 3, 'Kto je najznámejší futbalový útočník v histórii?', 'Pelé'),
('Šport', 3, 'Kto je najúspešnejší tenista žien?', 'Serena Williams'),
('Šport', 3, 'Kto je najstarší víťaz Grand Slamu?', 'Ken Rosewall'),
('Šport', 3, 'Kto vyhral posledné majstrovstvá sveta vo futbale?', 'Francúzsko'),
('Šport', 3, 'Kto je najúspešnejší športovec v cyklistike?', 'Eddy Merckx'),
('Šport', 3, 'Kto je najznámejší jazdec na koni?', 'Zara Phillips'),
('Šport', 3, 'Kto je najúspešnejší golfista všetkých čias?', 'Tiger Woods'),
('Šport', 3, 'Kto je najznámejší futbalista Argentíny?', 'Diego Maradona'),
('Šport', 3, 'Kto vyhral poslednú olympiádu v plávaní?', 'Caeleb Dressel'),
('Šport', 3, 'Kto je známy ako "Kráľ boxu"?', 'Muhammad Ali'),
('Šport', 3, 'Kto je najznámejší pretekár v NASCAR?', 'Dale Earnhardt'),
('Šport', 3, 'Kto je najúspešnejší skokan do vody?', 'Greg Louganis'),
('Šport', 3, 'Kto je najznámejší futbalista v Anglicku?', 'Bobby Moore'),
('Šport', 3, 'Kto je najúspešnejší pretekár v triatlone?', 'Mark Allen'),
('Šport', 3, 'Kto je najznámejší skokan na lyžiach?', 'Kamil Stoch'),
('Šport', 3, 'Kto je najúspešnejší futbalista v histórii?', 'Cristiano Ronaldo'),
('Šport', 3, 'Kto je najznámejší futbalový brankár v histórii?', 'Lev Yashin'),
('Šport', 3, 'Kto je najúspešnejší futbalista v Nemecku?', 'Franz Beckenbauer'),
('Šport', 3, 'Kto je najznámejší zápasník MMA?', 'Conor McGregor'),
('Šport', 3, 'Kto je najúspešnejší volejbalista?', 'Kerri Walsh'),
('Šport', 3, 'Kto je najznámejší tenista na trávnatých kurtoch?', 'Roger Federer'),
('Šport', 3, 'Kto vyhral posledný šampionát v golfu?', 'Collin Morikawa'),
('Šport', 3, 'Kto je najznámejší plážový volejbalista?', 'Kerri Walsh'),
('Šport', 3, 'Kto je najúspešnejší bežec na 100 m?', 'Usain Bolt'),
('Aktuálne dianie', 1, 'Kto je prezidentom USA?', 'Biden'),
('Aktuálne dianie', 1, 'Ktorá krajina usporiadala olympijské hry v roku 2021?', 'Japonsko'),
('Aktuálne dianie', 1, 'Kto je generálnym tajomníkom OSN?', 'Guterres'),
('Aktuálne dianie', 1, 'Aký je názov najnovšieho filmu o Jamesovi Bondovi?', 'No Time'),
('Aktuálne dianie', 1, 'Ktorá krajina bola prvou, ktorá schválila vakcínu proti COVID-19?', 'Veľká Británia'),
('Aktuálne dianie', 1, 'Kto je zakladateľom Facebooku?', 'Zuckerberg'),
('Aktuálne dianie', 1, 'Aká je hlavná město Francúzska?', 'Paríž'),
('Aktuálne dianie', 1, 'Kto objavil penicilín?', 'Fleming'),
('Aktuálne dianie', 1, 'Ktorá krajina má najvyššiu populáciu na svete?', 'Čína'),
('Aktuálne dianie', 1, 'Kto je hlavný vyjednávač EÚ pre brexit?', 'Barnier'),
('Aktuálne dianie', 1, 'Ktorý spevák vydal album „30“?', 'Adele'),
('Aktuálne dianie', 1, 'Kto je autorom teórie relativity?', 'Einstein'),
('Aktuálne dianie', 1, 'Kde sa nachádza Eiffelova veža?', 'Paríž'),
('Aktuálne dianie', 1, 'Kto je najbohatším človekom na svete v roku 2023?', 'Musk'),
('Aktuálne dianie', 1, 'Aký je názov najväčšej sociálnej siete?', 'Facebook'),
('Aktuálne dianie', 1, 'Kto bol prvým černošským prezidentom USA?', 'Obama'),
('Aktuálne dianie', 1, 'Aký je názov najnovšej klimatickej konferencie?', 'COP28'),
('Aktuálne dianie', 1, 'Kto je premiérom Spojeného kráľovstva?', 'Sunak'),
('Aktuálne dianie', 1, 'Ktorá krajina vyhrala posledný futbalový svetový pohár?', 'Francúzsko'),
('Aktuálne dianie', 1, 'Kto je autorom knižnej série Harry Potter?', 'Rowling'),
('Aktuálne dianie', 1, 'Ktorá krajina je známa svojimi tulipánmi?', 'Holandsko'),
('Aktuálne dianie', 1, 'Kto je prezidentom Ukrajiny?', 'Zelenskyj'),
('Aktuálne dianie', 1, 'Kto je hlavnou postavou seriálu „Hra o tróny“?', 'Jon Snow'),
('Aktuálne dianie', 1, 'Aký je názov najväčšieho jazera na svete?', 'Kaspické'),
('Aktuálne dianie', 1, 'Kto je známy ako „otec internetu“?', 'Cerf'),
('Aktuálne dianie', 1, 'Kto je riaditeľom WHO?', 'Ghebreyesus'),
('Aktuálne dianie', 1, 'Ktorá krajina je známa svojimi pyramídami?', 'Egypt'),
('Aktuálne dianie', 1, 'Aký je názov najnovšej verzie operačného systému Windows?', 'Windows 11'),
('Aktuálne dianie', 1, 'Kto je najúspešnejším tenistom v histórii?', 'Federer'),
('Aktuálne dianie', 1, 'Kto napísal „Veľkého Gatsbyho“?', 'Fitzgerald'),
('Aktuálne dianie', 1, 'Ktorý štát je známy svojou kultúrou sushi?', 'Japonsko'),
('Aktuálne dianie', 1, 'Kto je zakladateľom Tesly?', 'Musk'),
('Aktuálne dianie', 1, 'Ktorá krajina je najväčšia na svete?', 'Rusko'),
('Aktuálne dianie', 1, 'Kto je najznámejším astronautom?', 'Armstrong'),
('Aktuálne dianie', 1, 'Kto je riaditeľom FBI?', 'Wray'),
('Aktuálne dianie', 1, 'Ktorá krajina je známa svojim čokoládovým výrobkom?', 'Švajčiarsko'),
('Aktuálne dianie', 1, 'Kto je najlepším strelec v histórii futbalu?', 'Pelé'),
('Aktuálne dianie', 1, 'Ktorý štát je známy svojou kultúrou flamenga?', 'Španielsko'),
('Aktuálne dianie', 1, 'Kto je aktuálnym prezidentom Francúzska?', 'Macron'),
('Aktuálne dianie', 1, 'Aký je názov najväčšej korporácie na svete?', 'Apple'),
('Aktuálne dianie', 1, 'Kto je najznámejším režisérom filmov o superhrdinoch?', 'Marvel'),
('Aktuálne dianie', 1, 'Kto je autorom „1984“?', 'Orwell'),
('Aktuálne dianie', 1, 'Kto je riaditeľom NASA?', 'Nelson'),
('Aktuálne dianie', 1, 'Ktorý šport sa hrá na tenisovom kurte?', 'Tenis'),
('Aktuálne dianie', 1, 'Kto napísal „Moby Dicka“?', 'Melville'),
('Aktuálne dianie', 1, 'Kto je najznámejším spevákom popu?', 'Jackson'),
('Aktuálne dianie', 1, 'Aký je názov najnovšej verzia iOS?', 'iOS 16'),
('Aktuálne dianie', 1, 'Ktorý kraj je známy svojou kultúrou kebabu?', 'Turecko'),
('Aktuálne dianie', 1, 'Kto je autorom „Pána prsteňov“?', 'Tolkien'),
('Aktuálne dianie', 1, 'Aký je názov najväčšej cirkvi na svete?', 'Basilika'),
('Aktuálne dianie', 1, 'Kto je známy ako „kráľ rock and rollu“?', 'Elvis'),
('Aktuálne dianie', 1, 'Kto je zakladateľom Microsoftu?', 'Gates'),
('Aktuálne dianie', 1, 'Kto je prezidentom Ruska?', 'Putin'),
('Aktuálne dianie', 1, 'Ktorý športovec vyhral najviac zlatých medailí na olympiádach?', 'Phelps'),
('Aktuálne dianie', 1, 'Kto je najznámejším britským hercom?', 'Cumberbatch'),
('Politika', 1, 'Kto je premiérom Českej republiky?', 'Fiala'),
('Kultúra', 1, 'Kto napísal „Pýcha a predsudok“?', 'Austen'),
('Ekonomika', 1, 'Ktorá mena sa používa v Japonsku?', 'Jen'),
('Sport', 1, 'Kto vyhral posledný Wimbledon?', 'Djoković'),
('Technológie', 1, 'Kto je CEO spoločnosti Apple?', 'Cook'),
('Ekológia', 1, 'Ktorá krajina je známa ako „Zelený kraj“?', 'Nový Zéland'),
('Veda', 1, 'Kto je známy ako „otec genetiky“?', 'Mendel'),
('Zdravie', 1, 'Aký je názov vakcíny od Pfizeru?', 'Comirnaty'),
('Kultúra', 1, 'Kto je autorom „Malého princa“?', 'Saint-Exupéry'),
('Politika', 1, 'Kto je prezidentom Nemecka?', 'Steinmeier'),
('Sport', 1, 'Ktorý tím vyhral posledný Super Bowl?', 'Chiefs'),
('Veda', 1, 'Aký je názov najbližšej hviezdnej sústavy?', 'Proxima'),
('Technológie', 1, 'Kto vytvoril Android?', 'Google'),
('Ekonomika', 1, 'Ktorá krajina má euro ako svoju menu?', 'Nemecko'),
('Historie', 1, 'Kto bol prvým človekom na Mesiaci?', 'Armstrong'),
('Kultúra', 1, 'Aký je názov hlavného mesta Talianska?', 'Rím'),
('Politika', 1, 'Kto je predsedom Európskej komisie?', 'von der Leyen'),
('Sport', 1, 'Ktorý šport sa hrá na zimných olympiádach?', 'Hokej'),
('Zdravie', 1, 'Aké ochorenie spôsobuje vírus HIV?', 'AIDS'),
('Technológie', 1, 'Kto je zakladateľom SpaceX?', 'Musk'),
('Veda', 1, 'Kto objavil zákony pohybu?', 'Newton'),
('Kultúra', 1, 'Kto je známy ako „kráľ popu“?', 'Jackson'),
('Politika', 1, 'Kto je predsedom vlády Talianska?', 'Meloni'),
('Sport', 1, 'Kto vyhral posledný majstrovstvá sveta v hokeji?', 'Kanada'),
('Ekonomika', 1, 'Ktorá firma vyrába iPad?', 'Apple'),
('Zdravie', 1, 'Kto je riaditeľom CDC?', 'Walensky'),
('Technológie', 1, 'Kto je zakladateľom Amazonu?', 'Bezos'),
('Kultúra', 1, 'Aký je názov najznámejšieho obrazu od Moneta?', 'Lekná'),
('Politika', 1, 'Kto je prezidentom Južnej Kórey?', 'Yoon'),
('Sport', 1, 'Ktorý tím vyhral posledný Euro?', 'Taliansko'),
('Veda', 1, 'Aké je chemické symbol zlata?', 'Au'),
('Ekologické', 1, 'Ktorá krajina je najväčším producentom ropy?', 'USA'),
('Zdravie', 1, 'Aký je názov choroby, ktorá spôsobuje cukrovku?', 'Diabetes'),
('Technológie', 1, 'Ktorý vyhľadávač vlastní Google?', 'YouTube'),
('Kultúra', 1, 'Kto napísal „Romeo a Júlia“?', 'Shakespeare'),
('Politika', 1, 'Kto je premiérom Kanady?', 'Trudeau'),
('Sport', 1, 'Kto vyhral poslednú Tour de France?', 'Vingegaard'),
('Ekonomika', 1, 'Ktorá mena sa používa v Spojenom kráľovstve?', 'Libra'),
('Veda', 1, 'Aký je názov najväčšej planéty v slnečnej sústave?', 'Jupiter'),
('Technológie', 1, 'Ktorá firma vyrába Galaxy?', 'Samsung'),
('Kultúra', 1, 'Kto je autorom „Vojny a mieru“?', 'Tolstoj'),
('Politika', 1, 'Kto je prezidentom Francúzska?', 'Macron'),
('Sport', 1, 'Ktorý tím vyhral posledné MS vo futbale?', 'Argentina'),
('Zdravie', 1, 'Ktorý vírus spôsobuje chrípku?', 'Influenza'),
('Veda', 1, 'Kto je známy ako „otec moderného chémie“?', 'Lavoisier'),
('Technológie', 1, 'Kto je CEO spoločnosti Microsoft?', 'Nadella'),
('Kultúra', 1, 'Aký je názov najpopulárnejšieho muzikálu na Broadwayi?', 'Hamilton'),
('Politika', 1, 'Kto je predsedom Senátu USA?', 'Schumer'),
('Aktuálne dianie', 2, 'Kto je premiérom Maďarska?', 'Viktor Orbán'),
('Aktuálne dianie', 2, 'Kto je prezidentom Brazílie?', 'Lula da Silva'),
('Aktuálne dianie', 2, 'Aká je názov poslednej klimatickej konferencie OSN?', 'COP28'),
('Aktuálne dianie', 2, 'Kto je generálnym tajomníkom NATO?', 'Jens Stoltenberg'),
('Aktuálne dianie', 2, 'Ktorá krajina prijala nové klimatické zákony v 2023?', 'Nemecko'),
('Aktuálne dianie', 2, 'Kto je prezidentom Turecka?', 'Recep Erdoğan'),
('Aktuálne dianie', 2, 'Kto je známy ako "kráľovná popu" v súčasnosti?', 'Madonna'),
('Aktuálne dianie', 2, 'Kto je prezidentom Juhoafrickej republiky?', 'Cyril Ramaphosa'),
('Aktuálne dianie', 2, 'Kto je riaditeľom Medzinárodného menového fondu?', 'Kristalina Georgieva'),
('Aktuálne dianie', 2, 'Ktorá krajina vyhrala Eurovision 2023?', 'Švédsko'),
('Aktuálne dianie', 2, 'Kto je zakladateľom a CEO spoločnosti Twitter?', 'Elon Musk'),
('Aktuálne dianie', 2, 'Kto je víťazom posledného Oscarového ceremoniálu za najlepší film?', 'Everything Everywhere'),
('Aktuálne dianie', 2, 'Kto je riaditeľom spoločnosti Tesla?', 'Elon Musk'),
('Aktuálne dianie', 2, 'Kto je prezidentom Ukrajiny?', 'Volodymyr Zelenskyj'),
('Aktuálne dianie', 2, 'Kto je víťazom posledného majstrovstva sveta v krikete?', 'Indie'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Japonska?', 'Fumio Kishida'),
('Aktuálne dianie', 2, 'Ktorá krajina zrušila povinné očkovanie proti COVID-19?', 'Írsko'),
('Aktuálne dianie', 2, 'Kto je prezidentom Argentíny?', 'Javier Milei'),
('Aktuálne dianie', 2, 'Kto je riaditeľom spoločnosti Google?', 'Sundar Pichai'),
('Aktuálne dianie', 2, 'Kto je víťazom posledného Grand Prix v F1?', 'Max Verstappen'),
('Aktuálne dianie', 2, 'Kto je prezidentom Mexika?', 'Andrés Manuel'),
('Aktuálne dianie', 2, 'Ktorá krajina prijala nové zákony proti dezinformáciám?', 'Austrália'),
('Aktuálne dianie', 2, 'Kto je prezidentom Filipín?', 'Ferdinand Marcos'),
('Aktuálne dianie', 2, 'Kto je víťazom posledného Wimbledon?', 'Carlos Alcaraz'),
('Aktuálne dianie', 2, 'Kto je predsekom Európskeho parlamentu?', 'Roberta Metsola'),
('Aktuálne dianie', 2, 'Kto je prezidentom Rumunska?', 'Klaus Iohannis'),
('Aktuálne dianie', 2, 'Ktorá krajina má najvyšší počet utečencov v 2023?', 'Turecko'),
('Aktuálne dianie', 2, 'Kto je známy ako "otec popu" v súčasnosti?', 'Michael Jackson'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Španielska?', 'Pedro Sánchez'),
('Aktuálne dianie', 2, 'Kto je prezidentom Kórejskej republiky?', 'Yoon Suk-yeol'),
('Aktuálne dianie', 2, 'Kto je riaditeľom organizácie UNICEF?', 'Catherine Russell'),
('Aktuálne dianie', 2, 'Kto je víťazom posledného Super Bowlu?', 'Kansas City'),
('Aktuálne dianie', 2, 'Kto je prezidentom Poľska?', 'Andrzej Duda'),
('Aktuálne dianie', 2, 'Ktorá krajina má najvyššiu životnosť?', 'Japonsko'),
('Aktuálne dianie', 2, 'Kto je známy ako "otec moderného umenia"?', 'Pablo Picasso'),
('Aktuálne dianie', 2, 'Kto je prezidentom Indie?', 'Droupadi Murmu'),
('Aktuálne dianie', 2, 'Kto je najbohatším človekom v Ázii?', 'Mukesh Ambani'),
('Aktuálne dianie', 2, 'Kto je premiérom Kanady?', 'Justin Trudeau'),
('Aktuálne dianie', 2, 'Kto je riaditeľom spoločnosti Netflix?', 'Ted Sarandos'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Talianska?', 'Giorgia Meloni'),
('Aktuálne dianie', 2, 'Kto je prezidentom Srbska?', 'Aleksandar Vučić'),
('Aktuálne dianie', 2, 'Kto je víťazom posledných majstrovstiev sveta v basketbale?', 'USA'),
('Aktuálne dianie', 2, 'Kto je prezidentom Bieloruska?', 'Alexander Lukašenko'),
('Aktuálne dianie', 2, 'Kto je zakladateľom firmy SpaceX?', 'Elon Musk'),
('Aktuálne dianie', 2, 'Kto je víťazom posledného majstrovstva sveta vo futbale?', 'Argentína'),
('Aktuálne dianie', 2, 'Kto je prezidentom Českej republiky?', 'Petr Pavel'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Nemecka?', 'Olaf Scholz'),
('Aktuálne dianie', 2, 'Kto je prezidentom Estónska?', 'Alar Karis'),
('Aktuálne dianie', 2, 'Kto je riaditeľom Medzinárodnej agentúry pre atómovú energiu?', 'Rafael Grossi'),
('Aktuálne dianie', 2, 'Kto je víťazom Nobelovej ceny za mier 2023?', 'Ales Bialiatski'),
('Aktuálne dianie', 2, 'Kto je premiérom Talianska?', 'Giorgia Meloni'),
('Aktuálne dianie', 2, 'Ktorá krajina hostila COP28?', 'Spojené arabské emiráty'),
('Aktuálne dianie', 2, 'Kto je prezidentom Kolumbie?', 'Gustavo Petro'),
('Aktuálne dianie', 2, 'Kto je generálnym tajomníkom NATO?', 'Jens Stoltenberg'),
('Aktuálne dianie', 2, 'Ktorá krajina sa stala členom EÚ v roku 2023?', 'Chorvátsko'),
('Aktuálne dianie', 2, 'Kto je prezidentom Fínska?', 'Sauli Niinistö'),
('Aktuálne dianie', 2, 'Aká je mena v Turecku?', 'Lira'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Indie?', 'Narendra Modi'),
('Aktuálne dianie', 2, 'Ktorý kraj zrušil COVID-19 obmedzenia v 2023?', 'Dánsko'),
('Aktuálne dianie', 2, 'Kto je prezidentom Iránu?', 'Ebrahim Raisi');