INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Biológia', 1, 'Aký je najmenší kostný ústroj v tele?', 'Stredné ucho'),
('Biológia', 1, 'Ktoré zviera je známe svojím pomalým pohybom?', 'Lenochod'),
('Biológia', 1, 'Aká je základná jednotka života?', 'Bunka'),
('Biológia', 1, 'Ktorý vitamín je známy ako „vitamín slnka“?', 'Vitamín D'),
('Biológia', 1, 'Aký proces sa používa na rast rastlín?', 'Fotosyntéza'),
('Biológia', 1, 'Ktorý typ buniek prenáša kyslík?', 'Červené krvinky'),
('Biológia', 1, 'Aké je najväčšie zviera na súši?', 'Slon'),
('Biológia', 1, 'Ktorá rastlina sa často používa na výrobu papiera?', 'Bambus'),
('Biológia', 1, 'Aký orgán je zodpovedný za trávenie?', 'Žalúdok'),
('Biológia', 1, 'Ktorý hmyz má najviac druhov?', 'Chrobák'),
('Biológia', 1, 'Ktorý orgán produkuje inzulín?', 'Pankreas'),
('Biológia', 1, 'Ktorá časť rastliny absorbuje vodu?', 'Korene'),
('Biológia', 1, 'Ktoré zviera je známe svojou dlhoročnou pamäťou?', 'Slon'),
('Biológia', 1, 'Aký je najdôležitejší plyn v atmosfére?', 'Kyslík'),
('Biológia', 1, 'Ktorý typ buniek bojuje proti infekciám?', 'Imunitné bunky'),
('Biológia', 1, 'Aký je hlavný zdroj energie pre rastliny?', 'Slnko'),
('Biológia', 1, 'Ktorý orgán je centrom nervovej sústavy?', 'Mozog'),
('Biológia', 1, 'Aký typ štruktúry je DNA?', 'Dvojitá helix'),
('Biológia', 1, 'Ktorá časť bunky obsahuje genetický materiál?', 'Jadro'),
('Biológia', 1, 'Ktorý organismus môže prežiť v extrémnych podmienkach?', 'Mikrobi'),
('Biológia', 1, 'Ktorá rastlina je známa ako liečivá?', 'Aloe'),
('Biológia', 1, 'Ktorý proces sa používa na rozmnožovanie rastlín?', 'Opeľovanie'),
('Biológia', 1, 'Ktorý druh živočícha kladie vajíčka?', 'Ovocný mušky'),
('Biológia', 1, 'Aký je najbežnejší typ tkaniva v tele?', 'Epitel'),
('Biológia', 1, 'Ktoré zviera je známe svojou schopnosťou kamufláže?', 'Chameleón'),
('Biológia', 1, 'Aký typ potravín je bohatý na bielkoviny?', 'Mäso'),
('Biológia', 1, 'Ktorý proces sa používa na výrobu tepla v tele?', 'Metabolizmus'),
('Biológia', 1, 'Aký je najväčší orgán v tele?', 'Koža'),
('Biológia', 1, 'Ktorý hmyz je známy svojou schopnosťou lietať?', 'Včela'),
('Biológia', 1, 'Ktorý typ rastlín nemá kvety?', 'Paprade'),
('Biológia', 1, 'Ktoré živočíchy sú známe svojím ostatným spôsobom života?', 'Korytnačky'),
('Biológia', 1, 'Aký je základný stavebný kameň bielkovín?', 'Amino kyseliny'),
('Biológia', 1, 'Ktorý typ baktérií je prospešný pre trávenie?', 'Probiotiká'),
('Biológia', 1, 'Ktorý orgán je zodpovedný za detoxikáciu?', 'Pečeň'),
('Biológia', 1, 'Ktorý typ mäsa je najkonzumovanejší?', 'Kuracie'),
('Biológia', 1, 'Aký typ živočíchov sa množí pučaním?', 'Medúza'),
('Biológia', 1, 'Ktoré zviera je známe svojou rýchlosťou?', 'Gepard'),
('Biológia', 1, 'Ktorý typ rastliny je známy svojou odolnosťou voči suchu?', 'Kaktus'),
('Biológia', 1, 'Aký je najväčší predátor na súši?', 'Medveď'),
('Biológia', 1, 'Ktoré zviera má najväčšiu dĺžku života?', 'Žralok'),
('Biológia', 1, 'Ktorý typ tkaniva má schopnosť sťahovať sa?', 'Svalové'),
('Biológia', 1, 'Aký proces sa používa na výrobu kyslíka rastlinami?', 'Fotosyntéza'),
('Biológia', 1, 'Ktoré zviera je známe svojou vysokou inteligenciou?', 'Delfín'),
('Biológia', 1, 'Aký je najmenší živý organizmus?', 'Baktéria'),
('Biológia', 1, 'Ktorý typ živočícha je najviac ohrozený?', 'Kriticky ohrozený'),
('Biológia', 1, 'Ktorá časť rastliny je zodpovedná za fotosyntézu?', 'Listy'),
('Biológia', 1, 'Ktorý typ buniek je zodpovedný za zrážanie krvi?', 'Krvné doštičky'),
('Biológia', 1, 'Aký je najčastejší typ rakoviny u mužov?', 'Prostaty'),
('Biológia', 1, 'Aký orgán je zodpovedný za dýchanie?', 'Pľúca'),
('Biológia', 1, 'Aká je najmenšia jednotka života?', 'Bunka'),
('Biológia', 1, 'Ktorá rastlina produkuje najviac kyslíka?', 'Mikroalga'),
('Biológia', 1, 'Ktoré zviera je známe ako „kráľ džungle“?', 'Lev'),
('Biológia', 1, 'Ktorý vitamín sa nachádza v citrusoch?', 'C'),
('Biológia', 1, 'Aký je najčastejší typ tkaniva v rastlinách?', 'Pletivové'),
('Biológia', 1, 'Ktoré zviera má najväčšie uši?', 'Slon'),
('Biológia', 1, 'Aká je základná zložka DNA?', 'Nukleotid'),
('Biológia', 1, 'Ktorý proces zabezpečuje rast rastlín?', 'Fotosyntéza'),
('Biológia', 1, 'Aký je najbežnejší typ buniek v krvi?', 'Erytrocyty'),
('Biológia', 1, 'Ktoré zviera je známe svojou rýchlou regeneráciou?', 'Axolotl'),
('Biológia', 1, 'Ktoré rastliny sa často používajú na varenie?', 'Bylinky'),
('Biológia', 1, 'Aký je najväčší druh žraloka?', 'Bielej'),
('Biológia', 1, 'Ktorý orgán je zodpovedný za produkciu žlče?', 'Pečeň'),
('Biológia', 1, 'Ktoré zviera je známe svojou dlhou migráciou?', 'Losos'),
('Biológia', 1, 'Ktorá časť bunky je zodpovedná za energiu?', 'Mitochondrie'),
('Biológia', 1, 'Aký je najúčinnejší prenosový prostriedok pre choroby?', 'Voda'),
('Biológia', 1, 'Ktoré živočíchy sú známe svojou schopnosťou lietať?', 'VTÁKY'),
('Biológia', 1, 'Aký je najväčší kvet na svete?', 'Rafflesia'),
('Biológia', 1, 'Ktorý orgán je zodpovedný za imunitu?', 'Slezina'),
('Biológia', 1, 'Aký je najbežnejší typ rastlín na Zemi?', 'C3'),
('Biológia', 1, 'Ktoré zviera je známe svojou schopnosťou orientovať sa?', 'Delfín'),
('Biológia', 1, 'Aký je najvyšší strom na svete?', 'Sekvoja'),
('Biológia', 1, 'Ktorý typ tkaniva je zodpovedný za pohyb?', 'Svalové'),
('Biológia', 1, 'Ktoré zviera má najväčšie srdce?', 'Sperma'),
('Biológia', 1, 'Aký je najmenší cicavec?', 'Bumblebee'),
('Biológia', 1, 'Ktoré zviera je známe svojím dlhým krkom?', 'Žirafa'),
('Biológia', 1, 'Aká je základná zložka bielkovín?', 'Amino'),
('Biológia', 1, 'Ktorý typ bunky je najpočetnejší v tele?', 'Erytrocyt'),
('Biológia', 1, 'Ktorá časť rastliny je zodpovedná za reprodukciu?', 'Kvet'),
('Biológia', 1, 'Aký je najbežnejší typ uhľohydrátov?', 'Glukóza'),
('Biológia', 1, 'Ktorý proces je zodpovedný za uvoľnenie energie?', 'Respirácia'),
('Biológia', 1, 'Kto je považovaný za otca genetiky?', 'Mendel'),
('Biológia', 1, 'Ktorá rastlina je známa svojou jedovatou šťavou?', 'Ricinus'),
('Biológia', 1, 'Aký je najväčší predátor v oceáne?', 'Žralok'),
('Biológia', 1, 'Ktoré zviera je známe svojou schopnosťou maskovania?', 'Chameleón'),
('Biológia', 1, 'Aký je najbežnejší typ plesní?', 'Aspergillus'),
('Biológia', 1, 'Ktorý orgán je zodpovedný za vnímanie chuti?', 'Jazyk'),
('Biológia', 1, 'Aký je najväčší plaz na svete?', 'Krokodíl'),
('Biológia', 1, 'Ktorý typ hmyzu je známy svojím rojom?', 'Včely'),
('Biológia', 1, 'Ktorý proces sa používa na výrobu mlieka?', 'Laktácia'),
('Biológia', 1, 'Ktorý orgán je zodpovedný za rovnováhu?', 'Ucho'),
('Biológia', 1, 'Aký je najbežnejší typ hmyzu?', 'Mravec'),
('Biológia', 1, 'Ktoré zviera je známe svojou dlhou životnosťou?', 'Žralok'),
('Biológia', 1, 'Ktorá časť rastliny je zodpovedná za fotosyntézu?', 'List'),
('Biológia', 1, 'Ktoré zviera je známe svojím silným zrakom?', 'Sova'),
('Biológia', 1, 'Ktorý typ rastlín nemá korene?', 'Morské'),
('Biológia', 1, 'Aký typ živočíchov sa žije vo vode?', 'Vodné'),
('Biológia', 1, 'Ktorý vitamín je dôležitý pre zrážanie krvi?', 'K'),
('Biológia', 1, 'Ktorý orgán je zodpovedný za metabolizmus?', 'Pečeň'),
('Biológia', 1, 'Aký je najbežnejší typ hmyzu na svete?', 'Chrobák'),
('Biológia', 1, 'Ktoré zviera je známe svojou schopnosťou plávať?', 'Rybka'),
('Biológia', 1, 'Ktorý orgán je zodpovedný za citlivosť na svetlo?', 'Oko'),
('Biológia', 2, 'Ktorý typ rastlín je známy svojím vzdušným koreňom?', 'Orchidey'),
('Biológia', 2, 'Aký je hlavný pigment zodpovedný za fotosyntézu?', 'Chlórfyly'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou regenerácie?', 'Axolotl'),
('Biológia', 2, 'Ktorý typ buniek sa podieľa na imunitnej odpovedi?', 'Lymfocyty'),
('Biológia', 2, 'Aký je najbežnejší typ hmyzu vo svete?', 'Mravec'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v púšti?', 'Kameňák'),
('Biológia', 2, 'Aký je základný stavebný kameň DNA?', 'Nukleotid'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za spracovanie informácií?', 'Mozog'),
('Biológia', 2, 'Aký je najbežnejší typ tkaniva u cicavcov?', 'Epitel'),
('Biológia', 2, 'Ktorá časť rastliny je zodpovedná za fotosyntézu?', 'Listy'),
('Biológia', 2, 'Ktoré zviera je známe svojím hmatom?', 'Tarantula'),
('Biológia', 2, 'Aký proces sa používa na výrobu mlieka?', 'Laktácia'),
('Biológia', 2, 'Ktorý typ baktérií je známy svojou odolnosťou?', 'Termofily'),
('Biológia', 2, 'Ktorý vitamín je dôležitý pre zdravé kosti?', 'Vitamín D'),
('Biológia', 2, 'Aký je najbežnejší typ uhľohydrátov?', 'Glukóza'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou orientovať sa v tme?', 'Netopier'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za produkciu hormónov?', 'Žľaza'),
('Biológia', 2, 'Ktorá časť bunky je zodpovedná za syntézu bielkovín?', 'Ribozómy'),
('Biológia', 2, 'Ktorý typ hmyzu je známy svojou schopnosťou tancovať?', 'Včela'),
('Biológia', 2, 'Aký je typický znak pre bezstavovce?', 'Chýbajúce kosti'),
('Biológia', 2, 'Ktoré zviera je známe svojou dlhoročnou pamäťou?', 'Slon'),
('Biológia', 2, 'Ktorá rastlina je známa svojou vysokou toxicitou?', 'Ricinus'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za čuch?', 'Nos'),
('Biológia', 2, 'Aký je najväčší vnútorný orgán?', 'Pečeň'),
('Biológia', 2, 'Ktorý typ živočíchov je známy pre svoju symbiózu?', 'Koraly'),
('Biológia', 2, 'Ktorý proces zabezpečuje regeneráciu buniek?', 'Mitoza'),
('Biológia', 2, 'Aký je hlavný zdroj sacharidov v rastlinách?', 'Škrob'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť pod vodou?', 'Tulen'),
('Biológia', 2, 'Ktorý typ buniek je zodpovedný za prenos nervových impulzov?', 'Neuróny'),
('Biológia', 2, 'Ktorá časť rastliny je zodpovedná za uchovanie vody?', 'Korene'),
('Biológia', 2, 'Ktorá rastlina je známa svojou schopnosťou prežiť v extrémnych podmienkach?', 'Sukulenty'),
('Biológia', 2, 'Aký je typický znak pre stavovce?', 'Chrbtica'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za produkciu hormónov rastu?', 'Hypofýza'),
('Biológia', 2, 'Ktorý typ živočíchov má najväčšie množstvo druhov?', 'Hmyz'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou lietať?', 'Sovy'),
('Biológia', 2, 'Aké je hlavné zloženie buniek?', 'Voda'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za vylučovanie odpadu?', 'Obličky'),
('Biológia', 2, 'Aký je typický znak pre rastliny?', 'Chlórfyly'),
('Biológia', 2, 'Ktorá časť bunky je zodpovedná za energetický metabolizmus?', 'Mitochondrie'),
('Biológia', 2, 'Ktorý typ tkaniva je zodpovedný za transport živín?', 'Cievne'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou skryť sa pred predátormi?', 'Chameleón'),
('Biológia', 2, 'Aký je typický znak pre šelmy?', 'Ostré zuby'),
('Biológia', 2, 'Ktorý proces je zodpovedný za rast a opravu buniek?', 'Regenerácia'),
('Biológia', 2, 'Ktorá časť rastliny produkuje semienka?', 'Kvet'),
('Biológia', 2, 'Aký je najbežnejší typ proteínov v tele?', 'Kolagén'),
('Biológia', 2, 'Ktorá rastlina je známa svojou schopnosťou absorbovať ťažké kovy?', 'Biely kvet'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v chladnom podnebí?', 'Tučniak'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za produkciu tepla?', 'Srdce'),
('Biológia', 2, 'Aký je najbežnejší typ tkaniva v rastlinách?', 'Parenchým'),
('Biológia', 2, 'Ktorý typ živočíchov je najčastejšie na Zemi?', 'Cicavce'),
('Biológia', 2, 'Aký je najmenší druh včely?', 'Trúd'),
('Biológia', 2, 'Ktorý organismus je známy svojou bioluminiscenciou?', 'Medúza'),
('Biológia', 2, 'Aký je najväčší druh papagája?', 'Ara'),
('Biológia', 2, 'Ktorý typ tkaniva je najviac elastický?', 'Pružné'),
('Biológia', 2, 'Aký je najbežnejší druh rýb v oceáne?', 'Sardinka'),
('Biológia', 2, 'Ktorá časť bunky obsahuje mitochondrie?', 'Cytoplazma'),
('Biológia', 2, 'Ktoré zviera má najväčšie oči?', 'Ostriež'),
('Biológia', 2, 'Aká je funkcia chlorofylu?', 'Fotosyntéza'),
('Biológia', 2, 'Ktorý typ buniek je zodpovedný za prenos kyslíka?', 'Erytrocyty'),
('Biológia', 2, 'Ktorý typ hmyzu sa množí pučaním?', 'Medúza'),
('Biológia', 2, 'Aký je najväčší stavovec?', 'Veľryba'),
('Biológia', 2, 'Ktorý proces zabezpečuje výmenu plynov?', 'Dýchanie'),
('Biológia', 2, 'Ktoré zviera je známe svojou dlhoročnou migráciou?', 'Losos'),
('Biológia', 2, 'Aká je základná zložka bunkovej membrány?', 'Fosfolipidy'),
('Biológia', 2, 'Ktorý vitamín je dôležitý pre zrak?', 'A'),
('Biológia', 2, 'Ktorá časť rastliny je zodpovedná za uchovanie živín?', 'Korene'),
('Biológia', 2, 'Ktorý typ živočíchov má najväčší počet druhov?', 'Hmyz'),
('Biológia', 2, 'Aký je najbežnejší typ uhľohydrátov?', 'Glukóza'),
('Biológia', 2, 'Ktorý organismus je známy svojou schopnosťou fototropizmu?', 'Rastlina'),
('Biológia', 2, 'Ktorý typ tkaniva je zodpovedný za ochranu?', 'Epitel'),
('Biológia', 2, 'Aký je najbežnejší typ proteínov v tele?', 'Kolagén'),
('Biológia', 2, 'Ktorá časť rastliny je zodpovedná za reprodukciu?', 'Kvet'),
('Biológia', 2, 'Aký je najväčší druh netopiera?', 'Lietač'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v extrémnych podmienkach?', 'Tardigrád'),
('Biológia', 2, 'Ktorý proces sa používa na premenenie glukózy na energiu?', 'Glykolýza'),
('Biológia', 2, 'Aký je najbežnejší typ rýb v sladkých vodách?', 'Šťuka'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za rovnováhu?', 'Ucho'),
('Biológia', 2, 'Ktorý typ baktérií je známy svojou schopnosťou fotosyntézy?', 'Cyanobaktérie'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou regenerácie?', 'Axolotl'),
('Biológia', 2, 'Ktorý proces zabezpečuje rozklad organických látok?', 'Degradácia'),
('Biológia', 2, 'Aký je najbežnejší typ parazitov?', 'Červy'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou skryť sa?', 'Chameleón'),
('Biológia', 2, 'Ktorý vitamín sa nachádza v rybách?', 'D'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za vylučovanie moču?', 'Obličky'),
('Biológia', 2, 'Aký je najbežnejší typ tkaniva u rastlín?', 'Parenchým'),
('Biológia', 2, 'Ktorá časť bunky je zodpovedná za syntézu proteínov?', 'Ribozómy'),
('Biológia', 2, 'Ktorý typ buniek je zodpovedný za imunitu?', 'Lymfocyty'),
('Biológia', 2, 'Aký je najbežnejší typ mäsa v strave?', 'Hydina'),
('Biológia', 2, 'Ktorý proces zabezpečuje rozmnožovanie?', 'Množenie'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou plávať?', 'Delfín'),
('Biológia', 2, 'Ktorý typ hmyzu má najviac druhov?', 'Chrobák'),
('Biológia', 2, 'Aký je najväčší druh kraba?', 'Krab'),
('Biológia', 2, 'Ktoré zviera je známe svojou dlhoročnou pamäťou?', 'Slon'),
('Biológia', 2, 'Aký je najbežnejší typ sopky?', 'Štítová'),
('Biológia', 2, 'Ktorý proces zabezpečuje uvoľnenie tepla?', 'Metabolizmus'),
('Biológia', 2, 'Ktoré rastliny produkujú najviac kyslíka?', 'Stromy'),
('Biológia', 2, 'Ktoré zviera je známe svojou schopnosťou prispôsobiť sa?', 'Krysa'),
('Biológia', 2, 'Aký je najbežnejší typ bielkovín v rastlinách?', 'Globulíny'),
('Biológia', 2, 'Ktoré živočíchy sú známe svojou schopnosťou adaptácie?', 'Hmyz'),
('Biológia', 2, 'Ktorý orgán je zodpovedný za spracovanie potravy?', 'Žalúdok'),
('Biológia', 2, 'Ktorý typ buniek je zodpovedný za zrážanie?', 'Trombocyty'),
('Biológia', 3, 'Aký je najväčší druh medúzy?', 'Medúza lunárna'),
('Biológia', 3, 'Ktorý typ vírusov napadá bakteriálne bunky?', 'Bakteriofág'),
('Biológia', 3, 'Ktorý orgán u cicavcov je zodpovedný za čuch?', 'Nosová dutina'),
('Biológia', 3, 'Aký je najmenší druh ryby?', 'Paedocypris progenetica'),
('Biológia', 3, 'Aký je hlavný pigment zodpovedný za farbu rastlín?', 'Chlorofyl'),
('Biológia', 3, 'Ktorý typ tkaniva je zodpovedný za prenos nervových signálov?', 'Nervové tkanivo'),
('Biológia', 3, 'Aký je najväčší druh žraloka?', 'Žralok veľrybí'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za detoxikáciu alkoholu?', 'Pečeň'),
('Biológia', 3, 'Ktorý typ rastlín sa rozmnožuje pomocou spór?', 'Brynky'),
('Biológia', 3, 'Ktoré zviera je známe svojou schopnosťou regenerácie končatín?', 'Axolotl'),
('Biológia', 3, 'Aký je najbežnejší typ tkaniva u rastlín?', 'Pletivové tkanivo'),
('Biológia', 3, 'Ktorý druh hmyzu je známy svojou schopnosťou produkovať med?', 'Včela'),
('Biológia', 3, 'Ktorý orgán produkuje hemoglobín?', 'Kostná dreň'),
('Biológia', 3, 'Aký je najväčší druh pavúka?', 'Goliáš'),
('Biológia', 3, 'Ktorý typ baktérií sa používa na fermentáciu?', 'Laktobacily'),
('Biológia', 3, 'Ktorý proces je zodpovedný za tvorbu bielkovín v bunkách?', 'Translácia'),
('Biológia', 3, 'Ktorý typ živočíchov sa množí partenogenézou?', 'Niektoré plazy'),
('Biológia', 3, 'Ktorý typ tkaniva je zodpovedný za ukladanie tukov?', 'Tukové tkanivo'),
('Biológia', 3, 'Ktorý orgán reguluje hladinu cukru v krvi?', 'Pankreas'),
('Biológia', 3, 'Ktorá časť bunky je zodpovedná za výrobu energie?', 'Mitochondrie'),
('Biológia', 3, 'Aký je najdôležitejší hormón v stresovej reakcii?', 'Adrenalín'),
('Biológia', 3, 'Ktoré zviera je známe svojim útokom na ľudí?', 'Hroch'),
('Biológia', 3, 'Ktorý typ buniek produkuje protilátky?', 'B lymphocyty'),
('Biológia', 3, 'Ktorá časť rastliny je zodpovedná za transport vody?', 'Koreň'),
('Biológia', 3, 'Aký je najväčší plaz?', 'Krokodíl'),
('Biológia', 3, 'Ktorá časť oka je zodpovedná za farbu?', 'Dúhovka'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za vnímanie vôní?', 'Nos'),
('Biológia', 3, 'Aké je najdôležitejšie zloženie bunkovej membrány?', 'Fosfolipidy'),
('Biológia', 3, 'Ktorý typ bielkovín je zodpovedný za svalový pohyb?', 'Svalové bielkoviny'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za produkciu hlienu?', 'Priechodky'),
('Biológia', 3, 'Ktoré zviera je známe svojím sluchom?', 'Sovy'),
('Biológia', 3, 'Aký je hlavný účel fotosyntézy?', 'Výroba glukózy'),
('Biológia', 3, 'Ktorá rastlina je známa svojou schopnosťou prežiť v suchu?', 'Kaktus'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za teplotnú reguláciu?', 'Koža'),
('Biológia', 3, 'Ktorý typ tkaniva je zodpovedný za pohyb svalov?', 'Svalové tkanivo'),
('Biológia', 3, 'Aký je najbežnejší organický materiál v prírode?', 'Celulóza'),
('Biológia', 3, 'Ktorý druh baktérií je známy svojou schopnosťou prežiť v extrémnych podmienkach?', 'Extremofily'),
('Biológia', 3, 'Ktorá časť rastliny je zodpovedná za fotosyntézu?', 'Listy'),
('Biológia', 3, 'Ktorý typ vírusov je najčastejšie spôsobený nachladnutím?', 'Rhinovírus'),
('Biológia', 3, 'Aký je hlavný zdroj energie pre živočíchy?', 'Glukóza'),
('Biológia', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť bez vody?', 'Krysa'),
('Biológia', 3, 'Ktorý typ buniek je zodpovedný za transport živín?', 'Krvné bunky'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za metabolizmus?', 'Pečeň'),
('Biológia', 3, 'Aký je najbežnejší typ parazitov u cicavcov?', 'Škrkavky'),
('Biológia', 3, 'Ktorý proces je zodpovedný za vznik mutácií?', 'Replikácia'),
('Biológia', 3, 'Ktorý typ hmyzu je známy svojou schopnosťou prežiť mráz?', 'Mravce'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za produkciu slín?', 'Slinné žľazy'),
('Biológia', 3, 'Aký je najbežnejší typ mäsa v strave?', 'Hydina'),
('Biológia', 3, 'Ktorý vitamín je dôležitý pre zdravie kože?', 'Vitamín E'),
('Biológia', 3, 'Ktoré zviera je známe svojím silným čuchom?', 'Pes'),
('Biológia', 3, 'Ktorý typ baktérií sa používa na čistenie odpadových vôd?', 'Aeróbne baktérie'),
('Biológia', 3, 'Aký je hlavný zdroj energie pre rastliny?', 'Slnko'),
('Biológia', 3, 'Ktorý orgán reguluje hladinu hormónov?', 'Štítna žľaza'),
('Biológia', 3, 'Ktorý proces premieňa svetlo na energiu?', 'Fotosyntéza'),
('Biológia', 3, 'Ktorá časť nervovej sústavy riadi reflexy?', 'Miecha'),
('Biológia', 3, 'Ktoré rastliny sú známe ako sukulenty?', 'Cactus'),
('Biológia', 3, 'Ktorý typ DNA je prítomný v mitochondriách?', 'mtDNA'),
('Biológia', 3, 'Ktoré zviera má najväčší počet kociek v tele?', 'Hmyz'),
('Biológia', 3, 'Ktorý proces prebieha v chloroplastoch?', 'Fotosyntéza'),
('Biológia', 3, 'Ktorý typ buniek produkuje inzulín?', 'Beta'),
('Biológia', 3, 'Ktorá časť mozgu je zodpovedná za pamäť?', 'Hippokampus'),
('Biológia', 3, 'Ktorá rastlina je známa ako africký fialový?', 'Saintpaulia'),
('Biológia', 3, 'Ktorý typ buniek reguluje imunitu?', 'Lymfocyty'),
('Biológia', 3, 'Aké je hlavné zloženie bunkových membrán?', 'Fosfolipidy'),
('Biológia', 3, 'Ktorý typ tkaniva je najviac vzácny?', 'Nervové'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za rovnováhu?', 'Ucho'),
('Biológia', 3, 'Ktorý typ huby je známy svojou toxicitou?', 'Amanita'),
('Biológia', 3, 'Ktorý proces sa nazýva anaeróbna respirácia?', 'Fermentácia'),
('Biológia', 3, 'Ktorý typ živočíchov sa množí oviparitou?', 'Vtáky'),
('Biológia', 3, 'Ktoré zviera je známe svojou schopnosťou hibernácie?', 'Medveď'),
('Biológia', 3, 'Ktorý typ parazitov spôsobuje maláriu?', 'Plasmodium'),
('Biológia', 3, 'Ktoré hormóny sú produkované nadobličkami?', 'Adrenalín'),
('Biológia', 3, 'Ktorý typ tkaniva je zodpovedný za transport vody v rastlinách?', 'Xylém'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za syntézu hormónov?', 'Hypofýza'),
('Biológia', 3, 'Ktoré zviera je známe svojou schopnosťou plávať na dlhé vzdialenosti?', 'Sardinka'),
('Biológia', 3, 'Ktorý typ buniek sa podieľa na zrážaní krvi?', 'Trombocyty'),
('Biológia', 3, 'Ktorý organismus je známy svojou schopnosťou fotosyntézy?', 'Riasa'),
('Biológia', 3, 'Ktorá časť mozgu je zodpovedná za motorické funkcie?', 'Mozgová kôra'),
('Biológia', 3, 'Ktoré zviera má najväčšie pľúca?', 'Modrý veľryb'),
('Biológia', 3, 'Ktorý typ buniek je zodpovedný za spracovanie informácií?', 'Neuróny'),
('Biológia', 3, 'Ktorý proces zabezpečuje rast buniek?', 'Mitóza'),
('Biológia', 3, 'Ktorá časť rastliny je zodpovedná za absorpciu živín?', 'Korene'),
('Biológia', 3, 'Ktoré zviera je známe svojou schopnosťou orientovať sa pomocou echolokácie?', 'Netopier'),
('Biológia', 3, 'Ktorý typ rastlín je známy svojou odolnosťou voči chladu?', 'Mrazuvzdorné'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za spracovanie tukov?', 'Pečeň'),
('Biológia', 3, 'Ktorý typ buniek je zodpovedný za transport kyslíka?', 'Červené'),
('Biológia', 3, 'Ktorá časť rastliny je zodpovedná za rozšírenie semien?', 'Plody'),
('Biológia', 3, 'Ktorý proces je zodpovedný za redukciu CO2 na glukózu?', 'Calvinov cyklus'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za produkciu žlče?', 'Pečeň'),
('Biológia', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v extrémnych podmienkach?', 'Tardigrád'),
('Biológia', 3, 'Ktorý typ rastlín sa rozmnožuje vegetatívne?', 'Sukulent'),
('Biológia', 3, 'Ktorý proces je zodpovedný za premenu glukózy na energiu?', 'Glykolýza'),
('Biológia', 3, 'Ktorý typ buniek je zodpovedný za produkciu protilátok?', 'B-bunky'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za metabolizmus sacharidov?', 'Pečeň'),
('Biológia', 3, 'Ktorá časť bunky je zodpovedná za syntézu lipidov?', 'Smooth ER'),
('Biológia', 3, 'Ktoré zviera je známe svojím schopnosťou prežiť v tme?', 'Slepý'),
('Biológia', 3, 'Ktorý typ hmyzu je známy svojou schopnosťou tancovať?', 'Včela'),
('Biológia', 3, 'Ktorá rastlina je známa svojou jedovatou šťavou?', 'Krajina'),
('Biológia', 3, 'Ktorý proces je zodpovedný za rast a vývoj embryí?', 'Ontogenéza'),
('Biológia', 3, 'Ktorý typ živočíchov je známy pre svoju symbiózu s koralmi?', 'Rybky'),
('Biológia', 3, 'Ktoré zviera je známe svojou dlhoročnou pamäťou?', 'Slon'),
('Biológia', 3, 'Ktorý orgán je zodpovedný za produkciu erytrocytov?', 'Kosť'),
('Biológia', 3, 'Ktorý typ baktérií je známy svojou schopnosťou bioremediácie?', 'Degradujúce'),
('Botanika', 1, 'Aká je najväčšia rastlina na Zemi?', 'Sekvoja'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou prežiť v suchých podmienkach?', 'Kaktus'),
('Botanika', 1, 'Aký je názov najbežnejšej zeleniny na svete?', 'Zemiak'),
('Botanika', 1, 'Čo produkujú rastliny počas fotosyntézy?', 'Kyslík'),
('Botanika', 1, 'Aký je najvyšší strom na svete?', 'Hyperion'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi farebnými kvetmi a vôňou?', 'Ruža'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu čaju?', 'Čajovník'),
('Botanika', 1, 'Ktorá rastlina má jedlé plody nazývané bobule?', 'Malina'),
('Botanika', 1, 'Aká je najznámejšia liečivá rastlina?', 'Aloe'),
('Botanika', 1, 'Ktorá rastlina je symbolom pokoja?', 'Olivovník'),
('Botanika', 1, 'Aké je názov rastliny, ktorá sa používa na výrobu vína?', 'Hrozno'),
('Botanika', 1, 'Ktoré rastliny majú listy v tvare ihly?', 'Borovice'),
('Botanika', 1, 'Aký je názov rastliny, ktorá produkuje med?', 'Kvety'),
('Botanika', 1, 'Aký je názov rastliny, ktorú používame na korenenie jedál?', 'Bazalka'),
('Botanika', 1, 'Ktoré rastliny sú známe svojou schopnosťou čistiť vzduch?', 'Pokojné rastliny'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou krásnou vôňou?', 'Levanduľa'),
('Botanika', 1, 'Ktorá rastlina je považovaná za symbol lásky?', 'Ruža'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu parfémov?', 'Jazmín'),
('Botanika', 1, 'Ktoré rastliny sú známe svojimi veľkými listami?', 'Tropické rastliny'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé plody nazývané fíky?', 'Fíkovník'),
('Botanika', 1, 'Ktorá rastlina sa často používa na liečbu popálenín?', 'Aloe'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu čokolády?', 'Kakaovník'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi žltými kvetmi a liečivými vlastnosťami?', 'Nechtík'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou prilákať motýle?', 'Levanduľa'),
('Botanika', 1, 'Ktorá rastlina sa používa na prípravu pesto?', 'Bazalka'),
('Botanika', 1, 'Aká je najbežnejšia zelenina na svete?', 'Mrkva'),
('Botanika', 1, 'Ktorá rastlina má plody nazývané jablká?', 'Jabloň'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé semienka a používa sa na výrobu oleja?', 'Slnečnica'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou rásť v mokrých oblastiach?', 'Trstina'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojimi modrými kvetmi?', 'Hortenzia'),
('Botanika', 1, 'Ktorá rastlina sa používa na výrobu vína?', 'Hrozno'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má charakteristické listy?', 'Bambus'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou prežiť v extrémnych podmienkach?', 'Sukulenty'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na korenie jedál?', 'Korenie'),
('Botanika', 1, 'Ktorá rastlina je symbolom priateľstva?', 'Šalvia'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé listy?', 'Špenát'),
('Botanika', 1, 'Ktorá rastlina je známa svojou krásou a vôňou?', 'Ruža'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť vo vode?', 'Räčica'),
('Botanika', 1, 'Ktorá rastlina produkuje med?', 'Kvety'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé plody nazývané hrozno?', 'Hrozno'),
('Botanika', 1, 'Ktorá rastlina je symbolom múdrosti?', 'Bambus'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa často používa na čaj?', 'Ružový čaj'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou čistiť vodu?', 'Räčica'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu liekov?', 'Aloe'),
('Botanika', 1, 'Ktorá rastlina je známa svojou zelenou farbou?', 'Tráva'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi malými bielymi kvetmi?', 'Pivonka'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu kávy?', 'Káva'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi veľkými žltými kvetmi?', 'Slnečnica'),
('Botanika', 1, 'Aká je najznámejšia rastlina v púšti?', 'Kaktus'),
('Botanika', 1, 'Ktorá rastlina má listy v tvare srdca?', 'Břečťan'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa často používa na liečbu nachladnutia?', 'Zázvor'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou rásť na skalách?', 'Moss'),
('Botanika', 1, 'Aká je najobľúbenejšia izbová rastlina?', 'Sanjvital'),
('Botanika', 1, 'Ktorá rastlina je známa svojím jedovatým mliekom?', 'Ricinus'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé korenie známe ako škorica?', 'Škorica'),
('Botanika', 1, 'Ktorá rastlina má listy, ktoré sa používajú na čaj?', 'Mäta'),
('Botanika', 1, 'Aký je názov rastliny s jemnými, bielymi kvetmi a zelenými listami?', 'Jazmín'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi jedlými hľuzami?', 'Zemiak'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé plody nazývané marhule?', 'Marhuľa'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou prežiť v chladných oblastiach?', 'Bór'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu olivového oleja?', 'Oliva'),
('Botanika', 1, 'Ktorá rastlina je známa svojím bohatým obsahom vitamínu C?', 'Citrón'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má charakteristické modré kvety?', 'Iris'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou rásť v piesočnatých pôdach?', 'Tamarisk'),
('Botanika', 1, 'Aká je najznámejšia rastlina v tropických lesoch?', 'Palma'),
('Botanika', 1, 'Ktorá rastlina je považovaná za symbol jari?', 'Tulipán'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa často používa na korenie ryže?', 'Koriander'),
('Botanika', 1, 'Ktorá rastlina má listy, ktoré menia farbu na jeseň?', 'Javor'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojím rýchlym rastom?', 'Bamboo'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi vysokými, štíhlymi stonkami?', 'Fíkovník'),
('Botanika', 1, 'Aká je najobľúbenejšia kvetina na svete?', 'Ruža'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou absorbovať vlhkosť?', 'Sukulenty'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu parfémov?', 'Levanduľa'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi jedlými kvetmi?', 'Nasturtium'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu zubnej pasty?', 'Sage'),
('Botanika', 1, 'Ktorá rastlina má plody nazývané melón?', 'Melón'),
('Botanika', 1, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané hrušky?', 'Hruška'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou prežiť v slaných vodách?', 'Mangrov'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé korenie známe ako čierne korenie?', 'Piper'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi žltými kvetmi a vysokou výškou?', 'Kvetina'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou odolnosťou voči chladu?', 'Horská'),
('Botanika', 1, 'Ktorá rastlina sa často používa na výrobu jemného oleja?', 'Mandľa'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé plody nazývané pomaranče?', 'Pomaranč'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou prežiť v extrémnych podmienkach?', 'Cactus'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé listy a používa sa na šaláty?', 'Špenát'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi voňavými kvetmi?', 'Ruža'),
('Botanika', 1, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané ananás?', 'Ananás'),
('Botanika', 1, 'Ktorá rastlina je známa svojou liečivou schopnosťou?', 'Aloe'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu olivového oleja?', 'Olivovník'),
('Botanika', 1, 'Ktorá rastlina má listy, ktoré sú jedlé a používané v kuchyni?', 'Bazalka'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu čajov?', 'Čajovník'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi modrými kvetmi?', 'Hortenzia'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé plody nazývané čerešne?', 'Čerešňa'),
('Botanika', 1, 'Ktorá rastlina sa používa na výrobu medu?', 'Včelí kvet'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa často používa na výrobu korenia?', 'Paprika'),
('Botanika', 1, 'Ktorá rastlina sa používa na varenie polievok?', 'Petržlen'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé plody nazývané slivky?', 'Slivka'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou bojovať proti škodcom?', 'Nechtík'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je bežnou izbovou rastlinou?', 'Fikus'),
('Botanika', 1, 'Ktorá rastlina je známa svojou bielou farbou kvetov?', 'Ľalia'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má plody nazývané citrón?', 'Citrón'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou rásť na slnku?', 'Sukulent'),
('Botanika', 1, 'Aký je názov rastliny s jedlými kvetmi, často používanými na dekoráciu?', 'Náprstník'),
('Botanika', 1, 'Ktorá rastlina je známa svojou krásou a používa sa na svadbách?', 'Ruža'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu zubného prášku?', 'Sage'),
('Botanika', 1, 'Ktorá rastlina je známa svojou žltou farbou a rastie na lúkach?', 'Kopretina'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé listy známe ako rukola?', 'Rukola'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou rásť v tieni?', 'Papraď'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojich voňavých kvetoch?', 'Levanduľa'),
('Botanika', 1, 'Ktorá rastlina má jedlé plody známe ako avokádo?', 'Avokádo'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu fenyklu?', 'Fenykl'),
('Botanika', 1, 'Ktorá rastlina je známa svojou liečivou schopnosťou?', 'Aloe'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je považovaná za symbol pokoja?', 'Olive'),
('Botanika', 1, 'Ktorá rastlina má plody nazývané čučoriedky?', 'Čučoriedka'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu esenciálnych olejov?', 'Eukalyptus'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou absorbovať toxíny?', 'Sansevieria'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu medu?', 'Medovka'),
('Botanika', 1, 'Ktorá rastlina je známa svojimi voňavými listami?', 'Basil'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé listy známe ako špenát?', 'Špenát'),
('Botanika', 1, 'Ktorá rastlina má jedlé plody nazývané mandarínky?', 'Mandarínka'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v mokrých oblastiach?', 'Rákos'),
('Botanika', 1, 'Ktorá rastlina je známa svojou liečivou schopnosťou na trávenie?', 'Zázvor'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu terpenov?', 'Terpén'),
('Botanika', 1, 'Ktorá rastlina má plody nazývané kiwi?', 'Kivi'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v chudobných pôdach?', 'Tráva'),
('Botanika', 1, 'Ktorá rastlina je známa svojou voňavou kôrou?', 'Cimín'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé semienka známe ako chia?', 'Chia'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou rásť na piesku?', 'Kaktus'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou krásou a farbami?', 'Orchidea'),
('Botanika', 1, 'Ktorá rastlina má plody nazývané papája?', 'Papája'),
('Botanika', 1, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané hrozno?', 'Hrozno'),
('Botanika', 1, 'Ktorá rastlina je známa svojou schopnosťou rásť v chladných oblastiach?', 'Borovica'),
('Botanika', 1, 'Aký je názov rastliny, ktorá má jedlé plody nazývané maliny?', 'Malina'),
('Botanika', 1, 'Ktorá rastlina je známa svojou liečivou schopnosťou na kožné problémy?', 'Nechtík'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu oleja z orechov?', 'Orech'),
('Botanika', 1, 'Ktorá rastlina má plody nazývané marhule?', 'Marhuľa'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou čistiť vzduch?', 'Pilea'),
('Botanika', 1, 'Ktorá rastlina je známa svojím rýchlym rastom?', 'Tráva'),
('Botanika', 1, 'Aký je názov rastliny, ktorá sa používa na výrobu čaju z byliniek?', 'Harmanček'),
('Botanika', 1, 'Ktorá rastlina má jedlé plody známe ako melón?', 'Melón'),
('Botanika', 1, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v suchých oblastiach?', 'Kaktus'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi jedlými hľuzami?', 'Zemiak'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu piva?', 'Chmeľ'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané citrón?', 'Citrónovník'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou vôňou?', 'Ruža'),
('Botanika', 2, 'Ktorá rastlina má jedlé listy a používa sa na korenie?', 'Petržlen'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje kakaové bôby?', 'Kakaovník'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť na skalách?', 'Sukulenty'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody nazývané broskyne?', 'Broskyňa'),
('Botanika', 2, 'Ktorá rastlina je symbolom šťastia?', 'Šťastná rastlina'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu vína?', 'Hrozno'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané papája?', 'Papája'),
('Botanika', 2, 'Aký je názov rastliny, ktorá vyrastá z cibule?', 'Cibuľa'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi liečivými vlastnosťami?', 'Aloe'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé listy známe ako šalát?', 'Šalát'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou absorbovať znečistenie?', 'Breza'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má kvety v tvare zvončeka?', 'Zvonkohra'),
('Botanika', 2, 'Ktorá rastlina produkuje jedlé plody nazývané maliny?', 'Malinovník'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou trvácnosťou?', 'Bambus'),
('Botanika', 2, 'Ktorá rastlina má listy známe ako mäta?', 'Mäta'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou vôňou a používa sa na čaj?', 'Harmanček'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané limetky?', 'Limetovník'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť na piesku?', 'Piesočná tráva'),
('Botanika', 2, 'Ktorá rastlina je známa svojou liečivou schopnosťou na bolesť hlavy?', 'Levanduľa'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu zubného oleja?', 'Tea tree'),
('Botanika', 2, 'Ktorá rastlina má jedlé plody nazývané čierne ríbezle?', 'Ríbezľa'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v morských oblastiach?', 'Mangrovník'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v chudobných pôdach?', 'Púpava'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu ovocných štiav?', 'Ovocný strom'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané figy?', 'Fíkovník'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou jedovatou kôrou?', 'Ricinus'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou prežiť v extrémnej zime?', 'Borovica'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu trávy na ihriskách?', 'Trávnik'),
('Botanika', 2, 'Ktorá rastlina má listy známe ako bazalka?', 'Bazalka'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané granátové jablká?', 'Granátovník'),
('Botanika', 2, 'Ktorá rastlina má kvety známe ako slnečnice?', 'Slnečnica'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané čučoriedky?', 'Čučoriedka'),
('Botanika', 2, 'Ktorá rastlina je symbolom pokoja?', 'Biele kvety'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojimi voňavými listami?', 'Petržlen'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané grapefruit?', 'Grapefruit'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu omáčok?', 'Rajčinovník'),
('Botanika', 2, 'Ktorá rastlina je známa svojou liečivou schopnosťou na trávenie?', 'Fenykl'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané avokádo?', 'Avokádovník'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v blízkosti vody?', 'Rákos'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody známe ako zázvor?', 'Zázvor'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť na brehu?', 'Trstina'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé kvety známe ako kapary?', 'Kapara'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou absorbovať vlhkosť?', 'Sukulenty'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané hrozno?', 'Hrozno'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi modrými kvetmi?', 'Hortenzia'),
('Botanika', 2, 'Aká je najznámejšia rastlina v Európe?', 'Bórax'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou prežiť v arktických oblastiach?', 'Líška'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou liečivou schopnosťou?', 'Aloe'),
('Botanika', 2, 'Ktorá rastlina sa používa na výrobu medu?', 'Náprstník'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody nazývané jablká?', 'Jabloň');