INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Technológie', 3, 'Kto je zakladateľom spoločnosti LinkedIn?', 'Reid Hoffman'),
('Technológie', 3, 'Ktorý jazyk sa používa na analýzu dát v reálnom čase?', 'Java'),
('Technológie', 3, 'Aký je názov pre jazyk vyvinutý spoločnosťou Google?', 'Dart'),
('Technológie', 3, 'Kto je autorom technológie TensorFlow?', 'Google'),
('Technológie', 3, 'Aký jazyk je známy pre spracovanie prirodzeného jazyka?', 'Python'),
('Technológie', 3, 'Aký je názov pre technológiu pre mobilné platby?', 'NFC'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti Zoom?', 'Eric Yuan'),
('Technológie', 3, 'Aký je názov pre technológiu pre rozpoznávanie obrazov?', 'Computer Vision'),
('Technológie', 3, 'Ktorý jazyk sa používa na webovú analýzu?', 'R'),
('Technológie', 3, 'Aký je názov pre technológiu na analýzu dát?', 'Big Data'),
('Technológie', 3, 'Kto je známy za vývoj jazykov Go a Rust?', 'Rob Pike'),
('Technológie', 3, 'Aký je názov pre technológiu na hlasové ovládanie?', 'Voice Recognition'),
('Technológie', 3, 'Kto je autorom prvej verzie operačného systému Linux?', 'Linus Torvalds'),
('Technológie', 3, 'Aký je názov pre technológiu pre digitálne podpisy?', 'PKI'),
('Technológie', 3, 'Ktorý jazyk je známy pre serverové aplikácie?', 'Node.js'),
('Technológie', 3, 'Aký je názov pre technológiu na analýzu dát pomocou neurónových sietí?', 'Deep Learning'),
('Technológie', 3, 'Kto je známy za vývoj jazykov Haskell a Lisp?', 'John Backus'),
('Technológie', 3, 'Aký jazyk sa používa na správu databáz?', 'SQL'),
('Technológie', 3, 'Aký je názov pre technológiu na spracovanie videa?', 'Video Processing'),
('Technológie', 3, 'Kto je autorom teórie grafov?', 'Leonhard Euler'),
('Technológie', 3, 'Aký jazyk je známy pre programovanie mikrokontrolérov?', 'C'),
('Technológie', 3, 'Aký je názov pre technológiu na analýzu sentimentu v textoch?', 'Sentiment Analysis'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti Adobe?', 'John Warnock'),
('Výtvarné umenie', 1, 'Kto namaľoval Monu Lízu?', 'Da Vinci'),
('Výtvarné umenie', 1, 'Aké farby sú primárne?', 'Červená modrá'),
('Výtvarné umenie', 1, 'Aký štýl umenia je spojený s Picassom?', 'Kubizmus'),
('Výtvarné umenie', 1, 'Kto je autorom diela Hlas ľudu?', 'Kollár'),
('Výtvarné umenie', 1, 'Aké je hlavné médium v maľbe?', 'Farba'),
('Výtvarné umenie', 1, 'Čo je socha?', 'Trojrozmerný objekt'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje surrealistické maľby?', 'Dalí'),
('Výtvarné umenie', 1, 'Ktorý maliar je známy pre svoje kvety?', 'Van Gogh'),
('Výtvarné umenie', 1, 'Čo je to grafika?', 'Tlačová technika'),
('Výtvarné umenie', 1, 'Aká technika sa používa na maľovanie na plátno?', 'Olejná'),
('Výtvarné umenie', 1, 'Kto vytvoril sochu Davida?', 'Michelangelo'),
('Výtvarné umenie', 1, 'Aký je názov známej galérie v Paríži?', 'Louvre'),
('Výtvarné umenie', 1, 'Čo je to freska?', 'Nástenná maľba'),
('Výtvarné umenie', 1, 'Ktoré obdobie predchádzalo renesancii?', 'Gotika'),
('Výtvarné umenie', 1, 'Kto je autorom diela Posledná večera?', 'Da Vinci'),
('Výtvarné umenie', 1, 'Ktorý umelec je známy pre svoj expresionizmus?', 'Munch'),
('Výtvarné umenie', 1, 'Aký je názov najznámejšieho obrazu Edvarda Muncha?', 'Výkrik'),
('Výtvarné umenie', 1, 'Kto je považovaný za otca moderného umenia?', 'Cézanne'),
('Výtvarné umenie', 1, 'Aký je hlavný materiál v sochárstve?', 'Kameň'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje abstraktné obrazy?', 'Pollock'),
('Výtvarné umenie', 1, 'Ktorá technika sa používa na vytváranie mozaík?', 'Kameninová'),
('Výtvarné umenie', 1, 'Čo je to koláž?', 'Zloženie obrázkov'),
('Výtvarné umenie', 1, 'Kto namaľoval dielo Stvorenie Adama?', 'Michelangelo'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú ceruzky?', 'Kresba'),
('Výtvarné umenie', 1, 'Kto je autorom diela Slečna Lise?', 'Vermeer'),
('Výtvarné umenie', 1, 'Ktoré obdobie umenia sa zaoberalo romantizmom?', '19. storočie'),
('Výtvarné umenie', 1, 'Kto je autorom diela Venuša z Milo?', 'Neznámy'),
('Výtvarné umenie', 1, 'Aké sú hlavné zložky olejových farieb?', 'Oleje pigmenty'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje kockové maľby?', 'Lichtenstein'),
('Výtvarné umenie', 1, 'Ktoré mesto je známe svojou sochou Slobody?', 'New York'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje pop-art dielo?', 'Warhol'),
('Výtvarné umenie', 1, 'Aký je názov najznámejšieho obrazu Gustava Klimta?', 'Bozk'),
('Výtvarné umenie', 1, 'Kto je autorom diela Krik?', 'Munch'),
('Výtvarné umenie', 1, 'Aké sú hlavné farby v teórii farieb?', 'Primárne sekundárne'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Srdce?', 'Kandinskij'),
('Výtvarné umenie', 1, 'Ktoré obdobie sa zaoberalo barokom?', '17. storočie'),
('Výtvarné umenie', 1, 'Kto je autorom diela Dama s hranostajom?', 'Da Vinci'),
('Výtvarné umenie', 1, 'Aký je názov známej výstavy v Benátkach?', 'Bienále'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Orezaná kvetina?', 'Van Gogh'),
('Výtvarné umenie', 1, 'Čo je to skulptúra?', 'Sochárske dielo'),
('Výtvarné umenie', 1, 'Kto je považovaný za predstaviteľa impresionizmu?', 'Monet'),
('Výtvarné umenie', 1, 'Ktorá krajina je známa pre svoje maľby kvetov?', 'Holandsko'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Nočná stráž?', 'Rembrandt'),
('Výtvarné umenie', 1, 'Ktoré obdobie v umení sa zaoberalo surrealizmom?', '20. storočie'),
('Výtvarné umenie', 1, 'Kto je autorom obrazu Dievča s perlou?', 'Vermeer'),
('Výtvarné umenie', 1, 'Ktorá technika sa používa na maľovanie akvarelom?', 'Voda farba'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Dni v Paríži?', 'Gauguin'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú pastelky?', 'Pastel'),
('Výtvarné umenie', 1, 'Kto je autorom obrazu Venuša?', 'Botticelli'),
('Výtvarné umenie', 1, 'Ktorý umelec sa preslávil sochou Pieta?', 'Michelangelo'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Múza?', 'Giacometti'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú olejové farby?', 'Maľba'),
('Výtvarné umenie', 1, 'Kto je autorom diela Zimná krajina?', 'Bruegel'),
('Výtvarné umenie', 1, 'Kto je autorom diela Hlava medúzy?', 'Caravaggio'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú akrylové farby?', 'Akryl'),
('Výtvarné umenie', 1, 'Kto je známy pre dielo Deti v Paríži?', 'Renoir'),
('Výtvarné umenie', 1, 'Aký je názov slávneho múzea v Londýne?', 'British Museum'),
('Výtvarné umenie', 1, 'Kto namaľoval Obraz s červenou zápalkou?', 'Mondrian'),
('Výtvarné umenie', 1, 'Kto je autorom diela Kryštálové srdce?', 'Kandinsky'),
('Výtvarné umenie', 1, 'Aký je názov známeho obrazu s nožnicami?', 'Kvetina'),
('Výtvarné umenie', 1, 'Kto je považovaný za zakladateľa kubizmu?', 'Braque'),
('Výtvarné umenie', 1, 'Aká je technika, pri ktorej sa používajú oleje?', 'Olejomaľba'),
('Výtvarné umenie', 1, 'Kto je autorom diela Skleník?', 'Hopper'),
('Výtvarné umenie', 1, 'Aký je názov známeho výtvarného diela od Daliho?', 'Persistencia'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Hlava?', 'Picasso'),
('Výtvarné umenie', 1, 'Kto namaľoval dielo Hlava medúzy?', 'Caravaggio'),
('Výtvarné umenie', 1, 'Kto je autorom obrazu Tanečníci?', 'Degas'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú spreje?', 'Graffiti'),
('Výtvarné umenie', 1, 'Kto je autorom diela Zelená krava?', 'Matisse'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje portréty?', 'Van Gogh'),
('Výtvarné umenie', 1, 'Kto je autorom diela Hviezdna noc?', 'Van Gogh'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Slnečnice?', 'Van Gogh'),
('Výtvarné umenie', 1, 'Aký je názov obdobia umenia v 17. storočí?', 'Barok'),
('Výtvarné umenie', 1, 'Kto je autorom diela Venuša?', 'Botticelli'),
('Výtvarné umenie', 1, 'Kto namaľoval dielo Snívajúca žena?', 'Kahlo'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú vodové farby?', 'Akvarel'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje maľby v štýle pop-art?', 'Warhol'),
('Výtvarné umenie', 1, 'Kto je autorom diela Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 1, 'Aký je názov známeho obrazu od Klimta?', 'Bozk'),
('Výtvarné umenie', 1, 'Kto je autorom obrazu Lesný potok?', 'Monet'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje impresionistické dielo?', 'Monet'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú vlnité papiere?', 'Origami'),
('Výtvarné umenie', 1, 'Kto je autorom diela Dve sestry?', 'Renoir'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje abstraktné dielo?', 'Pollock'),
('Výtvarné umenie', 1, 'Aký je názov slávneho diela od Goya?', 'Satyry'),
('Výtvarné umenie', 1, 'Kto je autorom obrazu Vdova?', 'Hopper'),
('Výtvarné umenie', 1, 'Aká technika sa používa pri výrobe keramických výrobkov?', 'Keramika'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje surrealistické obrazy?', 'Dali'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú drôty?', 'Drôtovanie'),
('Výtvarné umenie', 1, 'Kto je autorom diela Zelený oblek?', 'Matisse'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Posledná večera?', 'Leonardo'),
('Výtvarné umenie', 1, 'Aký je názov známej galérie v New Yorku?', 'MoMA'),
('Výtvarné umenie', 1, 'Kto je autorom diela Májové ráno?', 'Monet'),
('Výtvarné umenie', 1, 'Kto je známy svojou sochou Mária?', 'Michelangelo'),
('Výtvarné umenie', 1, 'Kto je autorom obrazu Požiar v Paríži?', 'Hopper'),
('Výtvarné umenie', 1, 'Aký je názov známej techniky v umení s drevom?', 'Drevoresba'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Kocúrik?', 'Hockney'),
('Výtvarné umenie', 1, 'Kto je autorom diela Záhrada?', 'Monet'),
('Výtvarné umenie', 1, 'Aký je názov techniky, pri ktorej sa používajú kamene?', 'Mozaika'),
('Výtvarné umenie', 1, 'Kto je autorom diela Zimná krajina?', 'Bruegel'),
('Výtvarné umenie', 1, 'Kto je známy pre svoje dielo Vojna?', 'Goya'),
('Výtvarné umenie', 1, 'Aký je názov slávneho obrazu od Daliho?', 'Tvrdenie času'),
('Výtvarné umenie', 2, 'Kto je autorom obrazu Voda z riek?', 'Kandinskij'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Van Gogha?', 'Hviezdna noc'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Dievča s perlou?', 'Vermeer'),
('Výtvarné umenie', 2, 'Aký je názov známej techniky v sochárstve?', 'Bronz'),
('Výtvarné umenie', 2, 'Kto je autorom malieb na strop Sixtínskej kaplnky?', 'Michelangelo'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Skúmanie?', 'Kandinskij'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú farby na vodnej báze?', 'Akvarel'),
('Výtvarné umenie', 2, 'Kto je autorom diela Kúpeľná dievča?', 'Botticelli'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Edvarda Muncha?', 'Krik'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú voskové farby?', 'Enkaustika'),
('Výtvarné umenie', 2, 'Kto je autorom diela Rozprávka o jarnej noci?', 'Klimt'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje geometrické obrazy?', 'Mondrian'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Fridy Kahlo?', 'Dve Fridy'),
('Výtvarné umenie', 2, 'Kto je autorom diela Východ slnka?', 'Monet'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje maľby s morskými scenériami?', 'Turner'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú šablóny?', 'Stenciling'),
('Výtvarné umenie', 2, 'Kto je autorom diela Príbeh o štyroch ročných obdobiach?', 'Arcimboldo'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú piešťaly?', 'Pasta'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Mladá žena s kvetinou?', 'Renoir'),
('Výtvarné umenie', 2, 'Aký je názov známeho obrazu od Goya?', 'Satyra'),
('Výtvarné umenie', 2, 'Kto je autorom diela Zimné scenérie?', 'Caspar'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje fúkané sklo?', 'Murano'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú kovové plechy?', 'Frotáž'),
('Výtvarné umenie', 2, 'Kto je autorom diela Múza?', 'Manet'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Raffaela?', 'Škola Atén'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Západ slnka?', 'Gauguin'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa farby nanášajú špachtľou?', 'Impasto'),
('Výtvarné umenie', 2, 'Kto je autorom diela Dievča s broskyňou?', 'Chagall'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Oheň?', 'Kandinskij'),
('Výtvarné umenie', 2, 'Aký je názov známeho obrazu od Daliho?', 'Persistencia pamäti'),
('Výtvarné umenie', 2, 'Kto je autorom diela Architektúra?', 'Klee'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Kvetinová dievčina?', 'Sargent'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú sklenené fragmenty?', 'Mozaika'),
('Výtvarné umenie', 2, 'Kto je autorom diela Krajina s mostom?', 'Monet'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Rybár?', 'Cézanne'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Gaugina?', 'Brahma'),
('Výtvarné umenie', 2, 'Kto je autorom diela Tanečníci?', 'Degas'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Pani Bovary?', 'Flaubert'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú rybárske siete?', 'Textil'),
('Výtvarné umenie', 2, 'Kto je autorom diela Zelený svadobný?', 'Matisse'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Krajina s jazerom?', 'Hokusai'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Van Eycka?', 'Arnolfini'),
('Výtvarné umenie', 2, 'Kto je autorom diela Cyklista?', 'Botticelli'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Rybár?', 'Constable'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú voľné štetce?', 'Sprejovanie'),
('Výtvarné umenie', 2, 'Kto je autorom diela Portrét?', 'Bacon'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Záhrada?', 'Monet'),
('Výtvarné umenie', 2, 'Aký je názov známeho obrazu od Rothka?', 'Červená a čierna'),
('Výtvarné umenie', 2, 'Kto je autorom diela Noc hviezdnej noci?', 'Van Gogh'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používa uhlík?', 'Uhlová kresba'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Krásna krajina?', 'Botticelli'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú akvarelové farby?', 'Akvarel'),
('Výtvarné umenie', 2, 'Kto je autorom diela Chlapec s kvetom?', 'Sargent'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú olejové farby?', 'Olejomaľba'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Venuša?', 'Botticelli'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú farebné ceruzky?', 'Kresba'),
('Výtvarné umenie', 2, 'Kto je autorom diela Východ slnka nad Morom?', 'Turner'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú pigmenty?', 'Pigmentácia'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje maľby s pohľadom na krajinu?', 'Constable'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú lepidlá?', 'Lepidlo'),
('Výtvarné umenie', 2, 'Kto je autorom diela Dievča s perlovou náušnicou?', 'Vermeer'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Krik?', 'Munch'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú voskové farby?', 'Enkaustika'),
('Výtvarné umenie', 2, 'Kto je autorom diela Dielo o umení?', 'Aristotel'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú zlaté listy?', 'Zlatotepectvo'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Zimná krajina?', 'Caspar'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú sklenené fragmenty?', 'Mozaika'),
('Výtvarné umenie', 2, 'Kto je autorom diela Krajina s riekou?', 'Turner'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú hladké povrchy?', 'Sprej'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Pani Bovary?', 'Flaubert'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú strieborné plechy?', 'Fotografia'),
('Výtvarné umenie', 2, 'Kto je autorom diela Dvaja muži?', 'Gustave Courbet'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú drevené bloky?', 'Rytina'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Hlava medúzy?', 'Caravaggio'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú grafické tablety?', 'Digitálna grafika'),
('Výtvarné umenie', 2, 'Kto je autorom diela Kvetinová ženská postava?', 'Kahlo'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú kriedy?', 'Krieda'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Obraz s červenou zápalkou?', 'Rothko'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú šablóny?', 'Stenciling'),
('Výtvarné umenie', 2, 'Kto je autorom diela Rybár?', 'Soutine'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú akvarelové ceruzky?', 'Akvarelové ceruzky'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Pani Bovary?', 'Flaubert'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú zubné farby?', 'Zubná maľba'),
('Výtvarné umenie', 2, 'Kto je autorom diela Zelené pole?', 'Monet'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú zlaté listy?', 'Zlatotepectvo'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú olejové farby?', 'Olejomaľba'),
('Výtvarné umenie', 2, 'Kto je autorom diela Venuša?', 'Botticelli'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú akvarelové farby?', 'Akvarel'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú sklenené fragmenty?', 'Mozaika'),
('Výtvarné umenie', 2, 'Kto je autorom diela Príbeh o štyroch ročných obdobiach?', 'Alfred Sisley'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Starý muž a more?', 'Hemingway'),
('Výtvarné umenie', 2, 'Kto je autorom diela Kráľovná Alžbeta?', 'Goya'),
('Výtvarné umenie', 2, 'Aký je názov slávneho obrazu od Picassa?', 'Guernica'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje maľby s morskými scenériami?', 'Turner'),
('Výtvarné umenie', 2, 'Kto je autorom diela Pani Bovary?', 'Flaubert'),
('Výtvarné umenie', 2, 'Aký je názov známeho obrazu od Monet?', 'Lekná'),
('Výtvarné umenie', 2, 'Kto je autorom diela Čierna mačka?', 'Goya'),
('Výtvarné umenie', 2, 'Aký je názov slávneho obrazu od Da Vinciho?', 'Posledná večera'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Dievča s perlovou náušnicou?', 'Vermeer'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú pastelky?', 'Pastel'),
('Výtvarné umenie', 2, 'Kto je autorom diela Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 2, 'Aký je názov známeho obrazu od Van Gogha?', 'Slnečnice'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Chlapec s kvetom?', 'Renoir'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú akvarelové farby?', 'Akvarel'),
('Výtvarné umenie', 2, 'Kto je autorom diela Zátišie?', 'Cézanne'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú uhlík?', 'Uhlíková'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Kvetinová žena?', 'Kahlo'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú olejové farby?', 'Olejomaľba'),
('Výtvarné umenie', 2, 'Kto je autorom diela Vojna?', 'Goya'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Krajina s jazerom?', 'Monet'),
('Výtvarné umenie', 2, 'Aký je názov známeho obrazu od Van Eycka?', 'Arnolfini'),
('Výtvarné umenie', 2, 'Kto je autorom diela Múza?', 'Botticelli'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú sklenené fragmenty?', 'Mozaika'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Zimná krajina?', 'Caspar'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Klimta?', 'Bozk'),
('Výtvarné umenie', 2, 'Kto je autorom diela Sestry?', 'Bonnard'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú šablóny?', 'Stencil'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Snívajúca žena?', 'Kahlo'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú voskové farby?', 'Enkaustika'),
('Výtvarné umenie', 2, 'Kto je autorom diela Zelený obraz?', 'Matisse'),
('Výtvarné umenie', 2, 'Aký je názov známeho obrazu od Rothka?', 'Bez názvu'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Dva muži?', 'Botticelli'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú drevené bloky?', 'Drevo'),
('Výtvarné umenie', 2, 'Kto je autorom diela Kvetinová žena?', 'Kahlo'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú farebné ceruzky?', 'Kresba'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Oheň?', 'Kandinsky'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú zlaté listy?', 'Zlatolepenie'),
('Výtvarné umenie', 2, 'Kto je autorom diela Portrét?', 'Sargent'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú vodové farby?', 'Akvarel'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Rybár?', 'Hopper'),
('Výtvarné umenie', 2, 'Aký je názov známeho diela od Edvarda Muncha?', 'Krik'),
('Výtvarné umenie', 2, 'Kto je autorom diela Krajina s riekou?', 'Constable'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú pigmenty?', 'Pigmentácia'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Slnečnice?', 'Van Gogh'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú strieborné plechy?', 'Strieborné'),
('Výtvarné umenie', 2, 'Kto je autorom diela Dievča s broskyňou?', 'Lempicka'),
('Výtvarné umenie', 2, 'Aký je názov techniky, pri ktorej sa používajú voľné štetce?', 'Maliarska'),
('Výtvarné umenie', 2, 'Kto je známy pre svoje dielo Hlava?', 'Munch'),
('Výtvarné umenie', 3, 'Kto je autorom obrazu Stvorenie Adama?', 'Michelangelo'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Dievča s perlovou náušnicou?', 'Vermeer'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krik?', 'Munch'),
('Výtvarné umenie', 3, 'Ktorý umelec je známy svojou technikou drip painting?', 'Pollock'),
('Výtvarné umenie', 3, 'Kto je autorom diela Noc hviezdnej noci?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Západ slnka?', 'Turner'),
('Výtvarné umenie', 3, 'Kto je autorom diela Mária s Ježišom?', 'Raphael'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Dve sestry?', 'Renoir'),
('Výtvarné umenie', 3, 'Kto je autorom fresiek v Sixtínskej kaplnke?', 'Michelangelo'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje surrealistické obrazy?', 'Dalí'),
('Výtvarné umenie', 3, 'Kto je autorom diela Zátišie s ovocím?', 'Cézanne'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Múza?', 'Picasso'),
('Výtvarné umenie', 3, 'Kto je autorom obrazu Orezaná žena?', 'Kahlo'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Kto je autorom diela Portrét Adele Bloch-Bauer?', 'Klimt'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Križovanie?', 'Cézanne'),
('Výtvarné umenie', 3, 'Kto je autorom diela Dama s hranostajom?', 'Leonardo'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Pani Bovary?', 'Flaubert'),
('Výtvarné umenie', 3, 'Kto je autorom diela Kráľovná Alžbeta?', 'Zoffany'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Hlava medúzy?', 'Caravaggio'),
('Výtvarné umenie', 3, 'Kto je autorom diela Venuša?', 'Botticelli'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Fáza?', 'Kandinsky'),
('Výtvarné umenie', 3, 'Kto je autorom diela Voda z riek?', 'Monet'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Kvetinová žena?', 'Kahlo'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krajina s jazerom?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Pani Bovary?', 'Flaubert'),
('Výtvarné umenie', 3, 'Kto je autorom diela Kvetinový veniec?', 'Renoir'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Kto je autorom diela Vysoké hory?', 'Kandinsky'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Rybár?', 'Gauguin'),
('Výtvarné umenie', 3, 'Kto je autorom diela Zimná krajina?', 'Hokusai'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Snívajúca žena?', 'Kahlo'),
('Výtvarné umenie', 3, 'Kto je autorom diela Anatomické štúdie?', 'Da Vinci'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Krásna krajina?', 'Monet'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krajina s mostom?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Zimná krajina?', 'Gauguin'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krik?', 'Munch'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Kvetinová žena?', 'Kahlo'),
('Výtvarné umenie', 3, 'Kto je autorom diela Venuša s morskou peni?', 'Botticelli'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Dve sestry?', 'Renoir'),
('Výtvarné umenie', 3, 'Kto je autorom diela Tanečníci?', 'Degas'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Zimná krajina?', 'Gauguin'),
('Výtvarné umenie', 3, 'Kto je autorom diela Orezaná kvetina?', 'Kahlo'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Posledná večera?', 'Da Vinci'),
('Výtvarné umenie', 3, 'Kto je autorom diela Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Hlava?', 'Kandinsky'),
('Výtvarné umenie', 3, 'Kto je autorom diela Stvorenie Adama?', 'Michelangelo'),
('Výtvarné umenie', 3, 'Kto je autorom diela Sklenený muž?', 'Niki de Saint Phalle'),
('Výtvarné umenie', 3, 'Aký je názov obrazu od Van Gogha s hviezdami?', 'Hviezdna noc'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Orezaná žena?', 'Amedeo Modigliani'),
('Výtvarné umenie', 3, 'Kto je autorom diela Tanečníci?', 'Henri Matisse'),
('Výtvarné umenie', 3, 'Kto sa preslávil maľbami s morskými scenériami?', 'J.M.W. Turner'),
('Výtvarné umenie', 3, 'Aký je názov slávneho obrazu od Edvarda Muncha?', 'Krik'),
('Výtvarné umenie', 3, 'Kto je autorom diela Dama s hranostajom?', 'Leonardo da Vinci'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Vincent van Gogh'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú farebné piesky?', 'Sandpainting'),
('Výtvarné umenie', 3, 'Kto je autorom diela Múza?', 'Giorgio de Chirico'),
('Výtvarné umenie', 3, 'Aký je názov známeho diela od Michelangela?', 'Pieta'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Zimná krajina?', 'Caspar David Friedrich'),
('Výtvarné umenie', 3, 'Kto je autorom obrazu Snívajúca žena?', 'Giorgio de Chirico'),
('Výtvarné umenie', 3, 'Kto je autorom diela Zátišie s ovocím?', 'Paul Cézanne'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú skicáre?', 'Charcoal drawing'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Tanečníci?', 'Henri Matisse'),
('Výtvarné umenie', 3, 'Kto je autorom diela Rybár?', 'Joaquín Sorolla'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Krásna krajina?', 'Claude Monet'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú drôty?', 'Wire sculpture'),
('Výtvarné umenie', 3, 'Kto je autorom diela Dve sestry?', 'Auguste Renoir'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Príbeh o štyroch ročných obdobiach?', 'Giuseppe Arcimboldo'),
('Výtvarné umenie', 3, 'Kto je autorom diela Architektúra?', 'Piet Mondrian'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú zlaté listy?', 'Gilding'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Záhrada?', 'Claude Monet'),
('Výtvarné umenie', 3, 'Kto je autorom diela Mária s Ježišom?', 'El Greco'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Zimná krajina?', 'Caspar David Friedrich'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú šablóny?', 'Stenciling'),
('Výtvarné umenie', 3, 'Kto je autorom diela Vysoké hory?', 'Caspar David Friedrich'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Západ slnka?', 'J.M.W. Turner'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú akvarelové farby?', 'Watercoloring'),
('Výtvarné umenie', 3, 'Kto je autorom diela Kvetinový veniec?', 'Alfred Sisley'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Múza?', 'Giorgio de Chirico'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú olejové farby?', 'Oils'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krásna krajina?', 'Claude Monet'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Oheň?', 'Giorgio de Chirico'),
('Výtvarné umenie', 3, 'Kto je autorom diela Zelený obraz?', 'Henri Matisse'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú sklenené fragmenty?', 'Mosaic'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Vincent van Gogh'),
('Výtvarné umenie', 3, 'Kto je autorom diela Portrét Adele Bloch-Bauer?', 'Gustav Klimt'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú farebné ceruzky?', 'Color pencil drawing'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Zimná krajina?', 'Caspar David Friedrich'),
('Výtvarné umenie', 3, 'Kto je autorom diela Kvetinová žena?', 'Frida Kahlo'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú akvarelové farby?', 'Watercoloring'),
('Výtvarné umenie', 3, 'Kto je autorom diela Anatomické štúdie?', 'Leonardo da Vinci'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Krásna krajina?', 'Claude Monet'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú olejové farby?', 'Oils'),
('Výtvarné umenie', 3, 'Kto je autorom diela Dama s hranostajom?', 'Leonardo da Vinci'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Západ slnka?', 'J.M.W. Turner'),
('Výtvarné umenie', 3, 'Kto je autorom obrazu Muž s modrým klobúkom?', 'Picasso'),
('Výtvarné umenie', 3, 'Aký je názov diela od Van Gogha o slnečniciach?', 'Slnečnice'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje obrazy s červenými kvety?', 'Monet'),
('Výtvarné umenie', 3, 'Kto je autorom diela Tanečníci na lúke?', 'Cézanne'),
('Výtvarné umenie', 3, 'Aké je hlavné médium v sochárstve?', 'Kameň'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krásna krajina?', 'Kandinsky'),
('Výtvarné umenie', 3, 'Ktorý umelec je známy svojou technikou pointilizmu?', 'Seurat'),
('Výtvarné umenie', 3, 'Kto je autorom diela Venuša de Milo?', 'Neznámy'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú zlaté listy?', 'Gilding'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Červené stromy?', 'Matisse'),
('Výtvarné umenie', 3, 'Kto je autorom diela Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Aký je názov známeho obrazu od Daliho o pretečení?', 'Persistencia'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Múza?', 'Picasso'),
('Výtvarné umenie', 3, 'Kto je autorom diela Voda?', 'Hopper'),
('Výtvarné umenie', 3, 'Ktorý umelec sa špecializoval na maľby s morskými scenériami?', 'Turner'),
('Výtvarné umenie', 3, 'Kto je autorom diela Snívajúca žena?', 'Kahlo'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú čierne uhly?', 'Charcoal'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Dievča s perlovou náušnicou?', 'Vermeer'),
('Výtvarné umenie', 3, 'Kto je autorom diela Posledná večera?', 'Leonardo'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa vytvárajú abstraktné obrazy?', 'Súčasné'),
('Výtvarné umenie', 3, 'Kto je autorom diela Rybár?', 'Balthus'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Zimná krajina?', 'Hopper'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú pastelky?', 'Pastel'),
('Výtvarné umenie', 3, 'Kto je autorom diela Umenie?', 'Pollock'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Mária?', 'Michelangelo'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú špachtle?', 'Impasto'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krik?', 'Munch'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú zlaté listy?', 'Gilding'),
('Výtvarné umenie', 3, 'Kto je autorom diela Ráno?', 'Monet'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Tanečníci?', 'Degas'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú olejové farby?', 'Olejomaľba'),
('Výtvarné umenie', 3, 'Kto je autorom diela Čierna diera?', 'Kandinsky'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Západ slnka?', 'Turner'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú akrylové farby?', 'Akril'),
('Výtvarné umenie', 3, 'Kto je autorom diela Portrét Adele?', 'Klimt'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Nočná kaviareň?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú drôty?', 'Drôtovanie'),
('Výtvarné umenie', 3, 'Kto je autorom diela Zimná krajina?', 'Hopper'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Kvetinový veniec?', 'Kahlo'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú akvarelové farby?', 'Akvarel'),
('Výtvarné umenie', 3, 'Kto je autorom diela Jeseň?', 'Monet'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Orezaná kvetina?', 'Van Gogh'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú farby na vodnej báze?', 'Akvarel'),
('Výtvarné umenie', 3, 'Kto je autorom diela Voda?', 'Hopper'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Krásna krajina?', 'Kandinsky'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú voskové farby?', 'Vosk'),
('Výtvarné umenie', 3, 'Kto je autorom diela Kvetinová žena?', 'Kahlo'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Venuša?', 'Botticelli'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú kovové plechy?', 'Tiffany'),
('Výtvarné umenie', 3, 'Kto je autorom diela Dievča s broskyňou?', 'Renoir'),
('Výtvarné umenie', 3, 'Kto je známy pre svoje dielo Vysoké hory?', 'Hopper'),
('Výtvarné umenie', 3, 'Aký je názov techniky, pri ktorej sa používajú šablóny?', 'Stencil'),
('Výtvarné umenie', 3, 'Kto je autorom diela Krásna krajina?', 'Cézanne');