INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť na skalách?', 'Sukulenty'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je symbolom šťastia?', 'Bambus'),
('Botanika', 2, 'Ktorá rastlina má jedlé kvety známe ako kapary?', 'Kapara'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu esenciálnych olejov?', 'Levanduľa'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi voňavými listami?', 'Mäta'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa často používa na liečbu kožných problémov?', 'Harmanček'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané čerešne?', 'Čerešňa'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou absorbovať znečistenie?', 'Pohánka'),
('Botanika', 2, 'Ktorá rastlina je známa svojou krásou a voňavými kvetmi?', 'Ruža'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody nazývané broskyne?', 'Broskyňa'),
('Botanika', 2, 'Ktorá rastlina je považovaná za symbol lásky?', 'Ruža'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu čaju?', 'Zelený čaj'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi žltými kvetmi?', 'Slnečnica'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu olivového oleja?', 'Olivovník'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané melón?', 'Melón'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané figy?', 'Fíkovník'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v suchých oblastiach?', 'Kaktus'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé listy známe ako rukola?', 'Rukola'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi voňavými kvetmi a rastie v záhradách?', 'Jasmin'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané avokádo?', 'Avokádo'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou prežiť vo vlhkých oblastiach?', 'Trstina'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je často používaná na liečbu nachladnutia?', 'Zázvor'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané kiwi?', 'Kiwifruit'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť na brehu?', 'Ibištek'),
('Botanika', 2, 'Ktorá rastlina je známa svojou liečivou schopnosťou na trávenie?', 'Mäta'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu piva?', 'Chmeľ'),
('Botanika', 2, 'Ktorá rastlina má jedlé semienka známe ako chia?', 'Chia'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou odolnosťou voči chladu?', 'Fialka'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi jedlými hľuzami?', 'Zemiak'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody známe ako slivky?', 'Slivka'),
('Botanika', 2, 'Ktorá rastlina má jedlé kvety známe ako ružičkový kel?', 'Kel'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu liekov?', 'Aloe'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v blízkosti vody?', 'Rákos'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má charakteristické listy?', 'Javor'),
('Botanika', 2, 'Ktorá rastlina je symbolom múdrosti?', 'Bambus'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má plody nazývané pomaranče?', 'Pomarančovník'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou bojovať proti škodcom?', 'Nechtík'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu kávy?', 'Kávovník'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané citrón?', 'Citrónovník'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou absorbovať toxíny?', 'Pohánka'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi jedlými kvetmi?', 'Nasturtium'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi drobnými kvetmi?', 'Kryštálik'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody známe ako jahody?', 'Jahoda'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť na mokrých miestach?', 'Rákos'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má plody nazývané papája?', 'Papája'),
('Botanika', 2, 'Ktorá rastlina produkuje jedlé plody známe ako marhule?', 'Marhuľa'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa často používa na korenie?', 'Cezmína'),
('Botanika', 2, 'Ktorá rastlina je známa svojou liečivou schopnosťou na bolesť hlavy?', 'Levanduľa'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojimi špicatými listami?', 'Agávia'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané černice?', 'Černica'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu zubnej pasty?', 'Mäta'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou absorbovať toxíny?', 'Sanseveria'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé listy známe ako šalát?', 'Šalát'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi modrými kvetmi?', 'Hortenzia'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané figy?', 'Figa'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v suchých oblastiach?', 'Kaktus'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu vína?', 'Hrozno'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané čučoriedky?', 'Čučoriedka'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu oleja?', 'Slnečnica'),
('Botanika', 2, 'Ktorá rastlina má listy známe ako bazalka?', 'Bazalka'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody známe ako slivky?', 'Slivka'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v piesku?', 'Pšeničná tráva'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé listy známe ako rukola?', 'Rukola'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi žltými kvetmi?', 'Kvet slnečnice'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu fenyklu?', 'Fenykl'),
('Botanika', 2, 'Ktorá rastlina je známa svojimi jedlými hľuzami?', 'Zemiak'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má plody nazývané pomaranče?', 'Pomaranč'),
('Botanika', 2, 'Ktorá rastlina má jedlé plody známe ako kiwi?', 'Kivi'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou krásou a farbami?', 'Ruža'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v blízkosti vody?', 'Rákos'),
('Botanika', 2, 'Aký je názov rastliny, ktorá produkuje kakaové bôby?', 'Kakaovník'),
('Botanika', 2, 'Ktorá rastlina má plody nazývané marhule?', 'Marhuľa'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou prežiť v morských oblastiach?', 'Mangrovník'),
('Botanika', 2, 'Ktorá rastlina je známa svojou liečivou schopnosťou na kožné problémy?', 'Aloe'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má kvety v tvare zvončeka?', 'Zvonček'),
('Botanika', 2, 'Ktorá rastlina produkuje jedlé plody nazývané ananás?', 'Ananás'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody nazývané pomaranče?', 'Pomaranč'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou rásť v tme?', 'Kaktus'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu terpenov?', 'Borovica'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou absorbovať vlhkosť?', 'Bambus'),
('Botanika', 2, 'Aký je názov rastliny, ktorá má jedlé plody nazývané granátové jablká?', 'Granát'),
('Botanika', 2, 'Ktorá rastlina je známa svojím rýchlym rastom?', 'Tráva'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu oleja z orechov?', 'Orech'),
('Botanika', 2, 'Ktorá rastlina má jedlé listy známe ako špenát?', 'Špenát'),
('Botanika', 2, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v chudobných pôdach?', 'Púpava'),
('Botanika', 2, 'Ktorá rastlina je známa svojou schopnosťou absorbovať znečistenie?', 'Filodendron'),
('Botanika', 2, 'Aký je názov rastliny, ktorá sa používa na výrobu ovocných štiav?', 'Jahoda'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané čučoriedky?', 'Čučoriedka'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na skalách?', 'Skalník'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou jedovatou kôrou?', 'Ricinus'),
('Botanika', 3, 'Ktorá rastlina má jedlé plody nazývané granátové jablká?', 'Granátovník'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu esenciálnych olejov?', 'Levanduľa'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť vo vlhkých oblastiach?', 'Súšnik'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má plody nazývané limetky?', 'Limetka'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou absorbovať toxíny?', 'Aloe'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou odolnosťou voči chladu?', 'Kryštál'),
('Botanika', 3, 'Ktorá rastlina produkuje jedlé plody nazývané maliny?', 'Malinovník'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu kávy?', 'Kávovník'),
('Botanika', 3, 'Ktorá rastlina má plody nazývané broskyne?', 'Broskyňa'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť na piesku?', 'Pieskovník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou liečivou schopnosťou na bolesť hlavy?', 'Mäta'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má kvety v tvare zvončeka?', 'Bellflower'),
('Botanika', 3, 'Ktorá rastlina produkuje jedlé plody nazývané karambola?', 'Karambola'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu piva?', 'Chmeľ'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi žltými kvetmi?', 'Kvetináč'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé plody nazývané jablká?', 'Jabloň'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou prežiť v arktických oblastiach?', 'Arktická'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu fenyklu?', 'Fenykl'),
('Botanika', 3, 'Ktorá rastlina má jedlé listy známe ako rukola?', 'Rukola'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je symbolom múdrosti?', 'Olivovník'),
('Botanika', 3, 'Ktorá rastlina má jedlé plody nazývané hrozno?', 'Hrozno'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané figy?', 'Figa'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť v tme?', 'Tma'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé listy známe ako šalát?', 'Šalát'),
('Botanika', 3, 'Ktorá rastlina je známa svojou krásou a farbami?', 'Kvetina'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu terpenov?', 'Terpen'),
('Botanika', 3, 'Ktorá rastlina má kvety známe ako slnečnice?', 'Slnečnica'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé plody nazývané avokádo?', 'Avokádo'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na brehu?', 'Brežný'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou trvácnosťou?', 'Trvácna'),
('Botanika', 3, 'Ktorá rastlina má plody nazývané čierne ríbezle?', 'Ríbezľa'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané hrozno?', 'Hroznovník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na mokrých miestach?', 'Mokrič'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je považovaná za symbol pokoja?', 'Pokojník'),
('Botanika', 3, 'Ktorá rastlina má jedlé plody nazývané čučoriedky?', 'Čučoriednik'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu medu?', 'Medovník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou absorbovať vlhkosť?', 'Vlhkomil'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé listy známe ako špenát?', 'Špenát'),
('Botanika', 3, 'Ktorá rastlina je známa svojou liečivou schopnosťou na trávenie?', 'Petržlen'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané broskyne?', 'Broskyňa'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť v chudobných pôdach?', 'Chudobník'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má plody nazývané citrón?', 'Citrónovník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou liečivou schopnosťou na kožné problémy?', 'Aloe vera'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé plody známe ako karambola?', 'Karambola'),
('Botanika', 3, 'Aká rastlina je známa svojou schopnosťou rásť na piesku?', 'Púštny akáciový strom'),
('Botanika', 3, 'Ktorá rastlina produkuje jedlé plody nazývané granátové jablká?', 'Granátovník'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v chudobných pôdach?', 'Kaktus'),
('Botanika', 3, 'Ktorá rastlina má plody známe ako hrušky?', 'Hruška'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu esenciálnych olejov?', 'Levanduľa'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi jedlými hľuzami a pestuje sa v zemi?', 'Zemiak'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu olivového oleja?', 'Olivovník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou liečivou schopnosťou na trávenie?', 'Púpava'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má plody známe ako čierne ríbezle?', 'Čierny ríbezľ'),
('Botanika', 3, 'Ktorá rastlina je považovaná za symbol šťastia?', 'Bambus'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje kakaové bôby?', 'Kakaovník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť v extrémnych podmienkach?', 'Sukulenty'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé plody nazývané černice?', 'Ostružina'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou čistiť vzduch?', 'Sansevieria'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu piva?', 'Chmeľ'),
('Botanika', 3, 'Ktorá rastlina má jedlé semienka známe ako chia?', 'Salvia'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané papája?', 'Papája'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi voňavými kvetmi?', 'Ruža'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu liekov?', 'Aloe'),
('Botanika', 3, 'Ktorá rastlina má plody nazývané mandľe?', 'Mandľovník'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojimi žltými kvetmi?', 'Slnečnica'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou absorbovať znečistenie?', 'Breza'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé listy známe ako rukola?', 'Rukola'),
('Botanika', 3, 'Ktorá rastlina je symbolom múdrosti?', 'Olive'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou krásou a farbami?', 'Orchidea'),
('Botanika', 3, 'Ktorá rastlina má plody známe ako figy?', 'Figa'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané jablká?', 'Jabloň'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na strmých svahoch?', 'Brezový strom'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť vo vlhkých oblastiach?', 'Rybíz'),
('Botanika', 3, 'Ktorá rastlina má listy známe ako mäta?', 'Mäta'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou prežiť v suchých oblastiach?', 'Agáve'),
('Botanika', 3, 'Ktorá rastlina produkuje jedlé plody nazývané hrozno?', 'Hroznovník'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé plody známe ako broskyne?', 'Broskyňovník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou absorbovať vlhkosť?', 'Ibištek'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu fenyklu?', 'Fenykl'),
('Botanika', 3, 'Ktorá rastlina má plody nazývané čučoriedky?', 'Čučoriedka'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody známe ako ananás?', 'Ananás'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi modrými kvetmi?', 'Modrá zvonček'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v chladných oblastiach?', 'Borovica'),
('Botanika', 3, 'Ktorá rastlina produkuje jedlé plody nazývané marhule?', 'Marhuľa'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou prežiť v slaných vodách?', 'Halofyt'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na skalách?', 'Skalník'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť v arktických podmienkach?', 'Lopúch'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané maliny?', 'Rubus'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi jedovatými plodmi?', 'Ricinus'),
('Botanika', 3, 'Ktorá rastlina je považovaná za kráľovnú kvetín?', 'Ruža'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť na púšťach?', 'Agáve'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou prežiť v extrémnom teple?', 'Sukulent'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa často používa na výrobu liekov?', 'Aloe'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi plodmi nazývanými dračie ovocie?', 'Pitaya'),
('Botanika', 3, 'Aký je názov rastliny, ktorá prežije v morských oblastiach?', 'Halofyt'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi jedlými listami a používa sa v kuchyni?', 'Špenát'),
('Botanika', 3, 'Ktorá rastlina má plody známe ako granátové jablko?', 'Punica'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou odolnosťou voči chladu?', 'Cibule'),
('Botanika', 3, 'Ktorá rastlina sa používa na výrobu medu?', 'Baza'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má plody známe ako papája?', 'Carica'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou absorbovať toxíny?', 'Scindapsus'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé plody nazývané pomaranče?', 'Citrus'),
('Botanika', 3, 'Ktorá rastlina je známa svojou liečivou schopnosťou na trávenie?', 'Mäta'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou trvácnosťou?', 'Juka'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi modrými kvetmi a liečivými vlastnosťami?', 'Perovskia'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu terpenov?', 'Borievka'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na strmých svahoch?', 'Kozlík'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané čučoriedky?', 'Vaccinium'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť v piesku?', 'Púšťový trávnik'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa často používa na výrobu čajov?', 'Rooibos'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť v blízkosti vody?', 'Rákos'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má plody nazývané figy?', 'Ficus'),
('Botanika', 3, 'Ktorá rastlina je známa svojou liečivou schopnosťou na bolesť hlavy?', 'Levanduľa'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu olivového oleja?', 'Olivovník'),
('Botanika', 3, 'Ktorá rastlina má plody známe ako indická datľa?', 'Phoenix'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa často používa na liečbu kožných problémov?', 'Tea tree'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi žltými kvetmi a rastie na lúkach?', 'Harmanček'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu čokolády?', 'Kakaovník'),
('Botanika', 3, 'Ktorá rastlina má plody známe ako hrušky?', 'Pyrus'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou rásť v morských oblastiach?', 'Zelená riasa'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou absorbovať vlhkosť?', 'Bambus'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané višne?', 'Prunus'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na slnečných miestach?', 'Cactaceae'),
('Botanika', 3, 'Aký je názov rastliny, ktorá je známa svojou schopnosťou bojovať proti škodcom?', 'Kopřiva'),
('Botanika', 3, 'Ktorá rastlina je známa svojimi jedlými hľuzami?', 'Zemiak'),
('Botanika', 3, 'Aký je názov rastliny, ktorá sa používa na výrobu medu?', 'Kvet hlohu'),
('Botanika', 3, 'Ktorá rastlina má kvety známe ako slnečnice?', 'Helianthus'),
('Botanika', 3, 'Aký je názov rastliny, ktorá produkuje jedlé plody nazývané ananás?', 'Ananas'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou rásť na strmých svahoch?', 'Súmračná tráva'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má jedlé plody známe ako granátové jablká?', 'Punica'),
('Botanika', 3, 'Ktorá rastlina je známa svojou schopnosťou prežiť v extrémnych podmienkach?', 'Túlavá tráva'),
('Botanika', 3, 'Aký je názov rastliny, ktorá má kvety v tvare zvončeka?', 'Campanula'),
('Chémia', 1, 'Aký je chemický symbol pre vodík?', 'H'),
('Chémia', 1, 'Ktorý prvok má chemický symbol O?', 'Kyslík'),
('Chémia', 1, 'Aké je chemické zloženie vody?', 'H2O'),
('Chémia', 1, 'Aký je chemický symbol pre zlato?', 'Au'),
('Chémia', 1, 'Ktorý plyn dýchame?', 'Kyslík'),
('Chémia', 1, 'Aký je chemický symbol pre sodík?', 'Na'),
('Chémia', 1, 'Ktorý prvok je najhojnejší vo vesmíre?', 'Vodík'),
('Chémia', 1, 'Aký je chemický symbol pre uhlík?', 'C'),
('Chémia', 1, 'Ktorá kyselina je v citrónoch?', 'Citrónová'),
('Chémia', 1, 'Aký je chemický symbol pre železo?', 'Fe'),
('Chémia', 1, 'Ktorý prvok je v tabuľke prvkov na pozícii 1?', 'Vodík'),
('Chémia', 1, 'Aký je chemický symbol pre vápnik?', 'Ca'),
('Chémia', 1, 'Ktorý plyn je bezfarebný a bez zápachu?', 'Hélium'),
('Chémia', 1, 'Aký je chemický symbol pre rýchlosť svetla?', 'C'),
('Chémia', 1, 'Ktorý prvok je základom všetkého života?', 'Uhlík'),
('Chémia', 1, 'Aká je chemická zlúčenina pre soľ?', 'NaCl'),
('Chémia', 1, 'Ktorý plyn je hlavnou zložkou vzduchu?', 'Dusík'),
('Chémia', 1, 'Aký je chemický symbol pre meď?', 'Cu'),
('Chémia', 1, 'Ktorá kyselina je známa ako "olejová"?', 'Oleínová'),
('Chémia', 1, 'Aký je chemický symbol pre striebro?', 'Ag'),
('Chémia', 1, 'Ktorý prvok je známy ako "uhlíkový" prvok?', 'Uhlík'),
('Chémia', 1, 'Aká je chemická zlúčenina pre amoniak?', 'NH3'),
('Chémia', 1, 'Ktorý prvok je rádioaktívny a má symbol U?', 'Uran'),
('Chémia', 1, 'Aký je chemický symbol pre ortuť?', 'Hg'),
('Chémia', 1, 'Ktorá zlúčenina je známa ako "kyselina octová"?', 'Octová'),
('Chémia', 1, 'Aký je chemický symbol pre fosfor?', 'P'),
('Chémia', 1, 'Ktorý plyn je známy ako "snežný"?', 'Oxid uhličitý'),
('Chémia', 1, 'Aký je chemický symbol pre bór?', 'B'),
('Chémia', 1, 'Ktorý prvok je známy ako "majster v elektronech"?', 'Zinok'),
('Chémia', 1, 'Aká je chemická zlúčenina pre kyselinu sírovú?', 'H2SO4'),
('Chémia', 1, 'Ktorý prvok je známy ako "zelený fosfór"?', 'Fosfor'),
('Chémia', 1, 'Aký je chemický symbol pre bróm?', 'Br'),
('Chémia', 1, 'Ktorý prvok má symbol Kr?', 'Kriptón'),
('Chémia', 1, 'Aký je chemický symbol pre chlór?', 'Cl'),
('Chémia', 1, 'Ktorý plyn je známy ako "plyn smrti"?', 'Chlór'),
('Chémia', 1, 'Aký je chemický symbol pre selén?', 'Se'),
('Chémia', 1, 'Ktorý prvok je základom organickej chémie?', 'Uhlík'),
('Chémia', 1, 'Aká je chemická zlúčenina pre metán?', 'CH4'),
('Chémia', 1, 'Ktorý prvok je známy ako "kyslík v pečeni"?', 'Fosfor'),
('Chémia', 1, 'Aký je chemický symbol pre nikel?', 'Ni'),
('Chémia', 1, 'Ktorý prvok je známy ako "neviditeľný"?', 'Argón'),
('Chémia', 1, 'Aký je chemický symbol pre zirkón?', 'Zr'),
('Chémia', 1, 'Ktorý prvok je známy ako "žltý fosfór"?', 'Fosfor'),
('Chémia', 1, 'Aká je chemická zlúčenina pre etanol?', 'C2H5OH'),
('Chémia', 1, 'Ktorý prvok má symbol Rn?', 'Radón'),
('Chémia', 1, 'Aký je chemický symbol pre titán?', 'Ti'),
('Chémia', 1, 'Ktorý prvok je známy ako "vodný" prvok?', 'Vodík'),
('Chémia', 1, 'Aká je chemická zlúčenina pre propán?', 'C3H8'),
('Chémia', 1, 'Ktorý prvok má symbol S?', 'Síra'),
('Chémia', 1, 'Aký je chemický symbol pre bárium?', 'Ba'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 1?', 'Vodík'),
('Chémia', 1, 'Aký je chemický symbol pre argón?', 'Ar'),
('Chémia', 1, 'Ktorý prvok je známy ako "železný" prvok?', 'Železo\nChémia'),
('Chémia', 1, 'Ktorý plyn je známy ako "oxid uhličitý"?', 'CO2'),
('Chémia', 1, 'Aký je chemický symbol pre zlúčeninu amoniaku?', 'NH3'),
('Chémia', 1, 'Ktorý prvok má chemický symbol Ca?', 'Vápnik'),
('Chémia', 1, 'Aký je chemický symbol pre zirkón?', 'Zr'),
('Chémia', 1, 'Ktorá zlúčenina je známa ako "kyselina sírová"?', 'H2SO4'),
('Chémia', 1, 'Aký je chemický symbol pre fosfor?', 'P'),
('Chémia', 1, 'Ktorý prvok je známy ako "zelený fosfór"?', 'P3'),
('Chémia', 1, 'Aký je chemický symbol pre argón?', 'Ar'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 29?', 'Meď'),
('Chémia', 1, 'Aký je chemický symbol pre neón?', 'Ne'),
('Chémia', 1, 'Ktorý plyn je známy ako "pouličný"?', 'C2H4'),
('Chémia', 1, 'Aký je chemický symbol pre síru?', 'S'),
('Chémia', 1, 'Ktorý prvok má chemický symbol Au?', 'Zlato'),
('Chémia', 1, 'Aký je chemický symbol pre draslík?', 'K'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 6?', 'Uhlík'),
('Chémia', 1, 'Aký je chemický symbol pre hliník?', 'Al'),
('Chémia', 1, 'Ktorý prvok je známy ako "zelený plyn"?', 'Cl2'),
('Chémia', 1, 'Aká je chemická zlúčenina pre uhľovodík?', 'C'),
('Chémia', 1, 'Ktorý plyn je známy ako "kyslík"?', 'O2'),
('Chémia', 1, 'Aký je chemický symbol pre cín?', 'Sn'),
('Chémia', 1, 'Ktorý prvok má symbol I?', 'Jód'),
('Chémia', 1, 'Aký je chemický symbol pre nikel?', 'Ni'),
('Chémia', 1, 'Ktorý prvok je známy ako "čierny uhlík"?', 'C'),
('Chémia', 1, 'Aký je chemický symbol pre stroncium?', 'Sr'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 8?', 'Kyslík'),
('Chémia', 1, 'Aký je chemický symbol pre vápnik?', 'Ca'),
('Chémia', 1, 'Ktorý prvok má chemický symbol Mg?', 'Horčík'),
('Chémia', 1, 'Aký je chemický symbol pre telúr?', 'Te'),
('Chémia', 1, 'Ktorý prvok je známy ako "drogový"?', 'C4H10'),
('Chémia', 1, 'Aký je chemický symbol pre bór?', 'B'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 15?', 'Fosfor'),
('Chémia', 1, 'Aký je chemický symbol pre rýz?', 'Rh'),
('Chémia', 1, 'Ktorý prvok je známy ako "modrý" prvok?', 'Cu'),
('Chémia', 1, 'Aký je chemický symbol pre striebro?', 'Ag'),
('Chémia', 1, 'Ktorá zlúčenina je známa ako "kyselina dusičná"?', 'HNO3'),
('Chémia', 1, 'Aký je chemický symbol pre bárium?', 'Ba'),
('Chémia', 1, 'Ktorý prvok má chemický symbol Zn?', 'Zinok'),
('Chémia', 1, 'Aký je chemický symbol pre kryptón?', 'Kr'),
('Chémia', 1, 'Ktorý prvok je známy ako "červený fosfór"?', 'P2'),
('Chémia', 1, 'Aký je chemický symbol pre selén?', 'Se'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 33?', 'Arzén'),
('Chémia', 1, 'Aký je chemický symbol pre hafnium?', 'Hf'),
('Chémia', 1, 'Ktorý prvok je známy ako "kovový vodík"?', 'H2'),
('Chémia', 1, 'Aký je chemický symbol pre berylium?', 'Be'),
('Chémia', 1, 'Ktorý prvok má symbol C?', 'Uhlík'),
('Chémia', 1, 'Aký je chemický symbol pre osmium?', 'Os'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 12?', 'Horčík'),
('Chémia', 1, 'Aký je chemický symbol pre kadmium?', 'Cd'),
('Chémia', 1, 'Ktorý prvok je známy ako "noble gas"?', 'Ne'),
('Chémia', 1, 'Aký je chemický symbol pre urán?', 'U'),
('Chémia', 1, 'Ktorý prvok má chemický symbol Tl?', 'Talium'),
('Chémia', 1, 'Aký je chemický symbol pre gália?', 'Ga'),
('Chémia', 1, 'Ktorý prvok je známy ako "plyn kyseliny"?', 'H2S'),
('Chémia', 1, 'Aký je chemický symbol pre nikl?', 'Ni'),
('Chémia', 1, 'Ktorý prvok má atomové číslo 47?', 'Striebro'),
('Chémia', 2, 'Ktorý prvok má symbol Fe?', 'Železo'),
('Chémia', 2, 'Aká je chemická zlúčenina pre oxid uhličitý?', 'CO2'),
('Chémia', 2, 'Ktorý prvok je známy ako "tekutý kov"?', 'Zlato'),
('Chémia', 2, 'Aký je chemický symbol pre hliník?', 'Al'),
('Chémia', 2, 'Ktorý plyn sa používa na zváranie?', 'Argón'),
('Chémia', 2, 'Aký je chemický symbol pre síru?', 'S'),
('Chémia', 2, 'Ktorý prvok má chemický symbol Na?', 'Sodík'),
('Chémia', 2, 'Aká je chemická zlúčenina pre metanol?', 'CH3OH'),
('Chémia', 2, 'Ktorý prvok je známy ako "zelený plyn"?', 'Chlór'),
('Chémia', 2, 'Ktorá zlúčenina je známa ako "kyselina dusičná"?', 'HNO3'),
('Chémia', 2, 'Aký je chemický symbol pre kadmium?', 'Cd'),
('Chémia', 2, 'Ktorý prvok je známy ako "čierny uhlík"?', 'Uhlík'),
('Chémia', 2, 'Aký je chemický symbol pre strontium?', 'Sr'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 15?', 'Fosfor'),
('Chémia', 2, 'Aký je chemický symbol pre platinu?', 'Pt'),
('Chémia', 2, 'Ktorý prvok je známy ako "noble gas"?', 'Neón'),
('Chémia', 2, 'Aká je chemická zlúčenina pre síran?', 'SO4'),
('Chémia', 2, 'Ktorý prvok má chemický symbol I?', 'Jód'),
('Chémia', 2, 'Aký je chemický symbol pre bór?', 'B'),
('Chémia', 2, 'Ktorý prvok je základom organickej chémie?', 'Uhlík'),
('Chémia', 2, 'Aký je chemický symbol pre rubídium?', 'Rb'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 26?', 'Železo'),
('Chémia', 2, 'Aký je chemický symbol pre zlúčeninu amoniaku?', 'NH3'),
('Chémia', 2, 'Ktorý prvok je známy ako "modrý fosfór"?', 'Fosfor'),
('Chémia', 2, 'Aký je chemický symbol pre xenón?', 'Xe'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 30?', 'Zinok'),
('Chémia', 2, 'Aký je chemický symbol pre titán?', 'Ti'),
('Chémia', 2, 'Ktorý prvok je známy ako "kyselina sírová"?', 'H2SO4'),
('Chémia', 2, 'Aký je chemický symbol pre zirkón?', 'Zr'),
('Chémia', 2, 'Ktorý prvok je známy ako "meď"?', 'Cu'),
('Chémia', 2, 'Aký je chemický symbol pre ortuť?', 'Hg'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 14?', 'Kremík'),
('Chémia', 2, 'Aký je chemický symbol pre fosfor?', 'P'),
('Chémia', 2, 'Ktorý prvok je známy ako "biely fosfór"?', 'Fosfor'),
('Chémia', 2, 'Aký je chemický symbol pre kadmium?', 'Cd'),
('Chémia', 2, 'Ktorý prvok má symbol Tl?', 'Tál'),
('Chémia', 2, 'Aký je chemický symbol pre selén?', 'Se'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 47?', 'Striebro'),
('Chémia', 2, 'Aký je chemický symbol pre hafnium?', 'Hf'),
('Chémia', 2, 'Ktorý prvok je známy ako "vodíkový"?', 'H'),
('Chémia', 2, 'Aký je chemický symbol pre zirkón?', 'Zr'),
('Chémia', 2, 'Ktorý prvok má chemický symbol K?', 'Draslík'),
('Chémia', 2, 'Aký je chemický symbol pre gália?', 'Ga'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 11?', 'Sodík'),
('Chémia', 2, 'Aký je chemický symbol pre vápnik?', 'Ca'),
('Chémia', 2, 'Ktorý prvok má chemický symbol Sn?', 'Cín'),
('Chémia', 2, 'Aký je chemický symbol pre rhenium?', 'Re'),
('Chémia', 2, 'Ktorý prvok je známy ako "žltý fosfór"?', 'Fosfor'),
('Chémia', 2, 'Aký je chemický symbol pre tantál?', 'Ta'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 19?', 'Draslík'),
('Chémia', 2, 'Aký je chemický symbol pre urán?', 'U'),
('Chémia', 2, 'Ktorý prvok je známy ako "kovový vodík"?', 'H'),
('Chémia', 2, 'Aký je chemický symbol pre berylium?', 'Be'),
('Chémia', 2, 'Ktorý prvok má symbol Co?', 'Kobalt'),
('Chémia', 2, 'Aký je chemický symbol pre osmium?', 'Os'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 47?', 'Striebro'),
('Chémia', 2, 'Ktorý prvok má chemický symbol Hg?', 'Ortuť'),
('Chémia', 2, 'Aká je chemická zlúčenina pre oxid sodný?', 'Soľ'),
('Chémia', 2, 'Ktorý plyn je známy ako "kyselina karbónová"?', 'Oxid uhličitý'),
('Chémia', 2, 'Aký je chemický symbol pre molybden?', 'Mo'),
('Chémia', 2, 'Ktorý prvok je základom skla?', 'Kremík'),
('Chémia', 2, 'Aký je chemický symbol pre niób?', 'Nb'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 12?', 'Horčík'),
('Chémia', 2, 'Aká je chemická zlúčenina pre etylén?', 'C2H4'),
('Chémia', 2, 'Ktorý prvok je známy ako "tekutý plyn"?', 'Amoniak'),
('Chémia', 2, 'Aký je chemický symbol pre berylium?', 'Be'),
('Chémia', 2, 'Ktorý prvok je známy ako "kyslík v atmosfére"?', 'Ozon'),
('Chémia', 2, 'Aký je chemický symbol pre palládium?', 'Pd'),
('Chémia', 2, 'Ktorá zlúčenina je známa ako "kyselina citrónová"?', 'C6H8O7'),
('Chémia', 2, 'Ktorý prvok má chemický symbol As?', 'Arzén'),
('Chémia', 2, 'Aký je chemický symbol pre stroncium?', 'Sr'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 38?', 'Stroncium'),
('Chémia', 2, 'Ktorá zlúčenina je známa ako "kyselina fosforečná"?', 'H3PO4'),
('Chémia', 2, 'Aký je chemický symbol pre platinu?', 'Pt'),
('Chémia', 2, 'Ktorý prvok je známy ako "kyslík v tkanivách"?', 'Hemoglobín'),
('Chémia', 2, 'Aký je chemický symbol pre cer?', 'Ce'),
('Chémia', 2, 'Ktorý plyn je známy ako "ozón"?', 'O3'),
('Chémia', 2, 'Aký je chemický symbol pre lanthan?', 'La'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 20?', 'Vápnik'),
('Chémia', 2, 'Aká je chemická zlúčenina pre kyselinu uhličitú?', 'H2CO3'),
('Chémia', 2, 'Ktorý prvok má chemický symbol Cs?', 'Césium'),
('Chémia', 2, 'Aký je chemický symbol pre rhenium?', 'Re'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 11?', 'Sodík'),
('Chémia', 2, 'Aká je chemická zlúčenina pre polyetylén?', 'C2H4'),
('Chémia', 2, 'Ktorý prvok má chemický symbol S?', 'Síra'),
('Chémia', 2, 'Aký je chemický symbol pre kadmium?', 'Cd'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 29?', 'Meď'),
('Chémia', 2, 'Aký je chemický symbol pre zinok?', 'Zn'),
('Chémia', 2, 'Ktorý prvok je známy ako "kovový sodík"?', 'Sodík'),
('Chémia', 2, 'Aká je chemická zlúčenina pre kyselinu sírovú?', 'H2SO4'),
('Chémia', 2, 'Ktorý prvok má chemický symbol Ne?', 'Neón'),
('Chémia', 2, 'Aký je chemický symbol pre gália?', 'Ga'),
('Chémia', 2, 'Ktorá zlúčenina je známa ako "kyselina sírová"?', 'H2SO4'),
('Chémia', 2, 'Aký je chemický symbol pre ródium?', 'Rh'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 47?', 'Striebro'),
('Chémia', 2, 'Aká je chemická zlúčenina pre acetón?', 'C3H6O'),
('Chémia', 2, 'Ktorý prvok je známy ako "čierny oxid"?', 'Oxid železa'),
('Chémia', 2, 'Aký je chemický symbol pre gélium?', 'He'),
('Chémia', 2, 'Ktorý prvok má chemický symbol Y?', 'Yttrium'),
('Chémia', 2, 'Aký je chemický symbol pre antimón?', 'Sb'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 53?', 'Jód'),
('Chémia', 2, 'Aký je chemický symbol pre bór?', 'B'),
('Chémia', 2, 'Ktorý prvok má chemický symbol In?', 'Indium'),
('Chémia', 2, 'Aký je chemický symbol pre molybdén?', 'Mo'),
('Chémia', 2, 'Ktorý prvok má atomové číslo 4?', 'Bežná'),
('Chémia', 2, 'Aká je chemická zlúčenina pre kyselinu mravčiu?', 'HCOOH'),
('Chémia', 2, 'Ktorý prvok je známy ako "kyselina sírová"?', 'Síra'),
('Chémia', 2, 'Aký je chemický symbol pre thalium?', 'Tl'),
('Chémia', 3, 'Aký je chemický symbol pre zlúčeninu uhličitanu vápenatého?', 'CaCO3'),
('Chémia', 3, 'Ktorý prvok je známy ako "ťažký vodík"?', 'Deuterium'),
('Chémia', 3, 'Aká je chemická zlúčenina pre kyselinu chlorovodíkovú?', 'HCl'),
('Chémia', 3, 'Ktorý izotop uhlíka sa používa v datovaní?', 'C14'),
('Chémia', 3, 'Aký je chemický symbol pre kobalt?', 'Co'),
('Chémia', 3, 'Ktorý prvok je základom sklenených vlákien?', 'Kremík'),
('Chémia', 3, 'Aký je chemický symbol pre dusičnan?', 'NO3'),
('Chémia', 3, 'Ktorá kyselina je známa ako "baterková"?', 'Kyselina sírová'),
('Chémia', 3, 'Aký je chemický symbol pre ortuť?', 'Hg'),
('Chémia', 3, 'Ktorý prvok je známy ako "nobelium"?', 'No'),
('Chémia', 3, 'Aký je chemický symbol pre kadmium?', 'Cd'),
('Chémia', 3, 'Ktorý plyn je v atmosfére v najväčšej koncentrácii?', 'Dusík'),
('Chémia', 3, 'Aký je chemický symbol pre paládium?', 'Pd'),
('Chémia', 3, 'Ktorý prvok je známy ako "kyselina boritá"?', 'B'),
('Chémia', 3, 'Aký je chemický symbol pre triódiom?', 'Ti'),
('Chémia', 3, 'Ktorý plyn je známy ako "skleníkový plyn"?', 'CO2'),
('Chémia', 3, 'Aký je chemický symbol pre zlúčeninu síranu?', 'SO4'),
('Chémia', 3, 'Ktorý prvok je známy ako "platinový"?', 'Pt'),
('Chémia', 3, 'Aký je chemický symbol pre cer?', 'Ce'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 86?', 'Radón'),
('Chémia', 3, 'Aká je chemická zlúčenina pre etylén?', 'C2H4'),
('Chémia', 3, 'Ktorý plyn je výsledkom fotosyntézy?', 'Kyslík'),
('Chémia', 3, 'Aký je chemický symbol pre wolfram?', 'W'),
('Chémia', 3, 'Ktorý prvok je známy ako "zlatý" prvok?', 'Au'),
('Chémia', 3, 'Aká je chemická zlúčenina pre kyselinu octovú?', 'CH3COOH'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 33?', 'Arzén'),
('Chémia', 3, 'Aký je chemický symbol pre niób?', 'Nb'),
('Chémia', 3, 'Ktorý prvok je známy ako "tekutý kov"?', 'Rtuť'),
('Chémia', 3, 'Aký je chemický symbol pre antimon?', 'Sb'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 4?', 'Beryl'),
('Chémia', 3, 'Aká je chemická zlúčenina pre hexán?', 'C6H14'),
('Chémia', 3, 'Ktorý prvok je známy ako "zelený fosfór"?', 'P'),
('Chémia', 3, 'Aký je chemický symbol pre hafnium?', 'Hf'),
('Chémia', 3, 'Ktorý prvok je základom DNA?', 'Uhlík'),
('Chémia', 3, 'Aký je chemický symbol pre strontium?', 'Sr'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 118?', 'Oganesson'),
('Chémia', 3, 'Aká je chemická zlúčenina pre síran amónny?', 'NH4SO4'),
('Chémia', 3, 'Ktorý prvok je známy ako "kovový sodík"?', 'Na'),
('Chémia', 3, 'Aký je chemický symbol pre kobalt?', 'Co'),
('Chémia', 3, 'Ktorý plyn je známy ako "ozón"?', 'O3'),
('Chémia', 3, 'Aký je chemický symbol pre bárium?', 'Ba'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 20?', 'Vápnik'),
('Chémia', 3, 'Aká je chemická zlúčenina pre acetylén?', 'C2H2'),
('Chémia', 3, 'Ktorý prvok je známy ako "tekutý vzduch"?', 'Argón'),
('Chémia', 3, 'Aký je chemický symbol pre urán?', 'U'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 29?', 'Meď'),
('Chémia', 3, 'Aká je chemická zlúčenina pre kyselinu fosforečnú?', 'H3PO4'),
('Chémia', 3, 'Ktorý prvok je známy ako "tantal"?', 'Ta'),
('Chémia', 3, 'Aký je chemický symbol pre rhenium?', 'Re'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 30?', 'Zinok'),
('Chémia', 3, 'Aká je chemická zlúčenina pre kyselinu mravčiu?', 'HCOOH'),
('Chémia', 3, 'Ktorý plyn je známy ako "kyselina uhličitá"?', 'CO2'),
('Chémia', 3, 'Aký je chemický symbol pre zlúčeninu síranu?', 'SO2'),
('Chémia', 3, 'Ktorý prvok je známy ako "tekutý hliník"?', 'Al'),
('Chémia', 3, 'Aká je chemická zlúčenina pre propylén?', 'C3H6'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 12?', 'Horčík'),
('Chémia', 3, 'Aký je chemický symbol pre praseodym?', 'Pr'),
('Chémia', 3, 'Aký je chemický symbol pre tantal?', 'Ta'),
('Chémia', 3, 'Ktorý prvok má atomové číslo 76?', 'Os'),
('Chémia', 3, 'Aká je chemická zlúčenina pre tetrafluórovaný metán?', 'CF4'),
('Chémia', 3, 'Ktorý prvok je známy ako "kyslík v atmosfére"?', 'O2'),
('Chémia', 3, 'Aký je chemický symbol pre technécium?', 'Tc');