INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou prežiť v extrémnych podmienkach?', 'Tučniak'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím zlatým sfarbením?', 'Zlatá rybka'),
('Ríša zvierat', 1, 'Ktoré zviera je najväčším predátorom?', 'Tiger'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím veľkým rozpätím krídel?', 'Orol'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím ostrým tichom?', 'Puma'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou prítomnosťou v domácnostiach?', 'Mačka'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím spevom v prírode?', 'Cvrček'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou odolnosťou voči chladu?', 'Tučniak'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou prežiť v piesku?', 'Korytnačka'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím dlhým jazykom?', 'Slon'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou lietať?', 'Netopier'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou schopnosťou žiť vo vode?', 'Rybka'),
('Ríša zvierat', 1, 'Ktoré zviera je najväčšie na súši?', 'Slon'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou plávať?', 'Delfín'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou skákať?', 'Kangúr'),
('Ríša zvierat', 1, 'Aké zviera je známe svojím špecifickým zápachom?', 'Mysi'),
('Ríša zvierat', 1, 'Ktoré zviera sa považuje za symbol moci?', 'Lev'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou bielou farbou?', 'Mrož'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím čiernym sfarbením?', 'Panda'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou rýchlosťou?', 'Gepard'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou skryť sa?', 'Chameleon'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou agresivitou?', 'Krokodíl'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojim dlhým chvostom?', 'Kocúr'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím spevom?', 'Slávik'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou vynikajúcou pamäťou?', 'Slon'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou pomalou chôdzou?', 'Žirafa'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou schopnosťou tancovať?', 'Pavúk'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím ostrým zrakom?', 'Sova'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím hlasným volaním?', 'Havran'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou dlhou životnosťou?', 'Žralok'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou prežiť v piesku?', 'Korytnačka'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím rozkošným vzhľadom?', 'Koala'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím žltým sfarbením?', 'Kanárik'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím bleskovým pohybom?', 'Rybka'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím rýchlym behom?', 'Zajac'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Papagáj'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou silou?', 'Medveď'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím rozšírením?', 'Holub'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím vynikajúcim sluchom?', 'Psa'),
('Ríša zvierat', 1, 'Ktoré zviera je najmenšie v lese?', 'Mravec'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím skrytým životom?', 'Tajomný'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou životaschopnosťou?', 'Krysa'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím osamotením?', 'Puma'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím roztomilým správaním?', 'Panda'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou dlhou nohou?', 'Žirafa'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou veľmi silnou čelusťou?', 'Aligátor'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím útokom v noci?', 'Sova'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou láskyplnosťou?', 'Pes'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou odolnosťou voči teplu?', 'Kozoroh'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou bodkovanou kožou?', 'Jaguár'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou veľkou silou?', 'Slon'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojimi dlhými ušami?', 'Zajac'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím veľkým rozšírením?', 'Holub'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím dlhým krkom?', 'Žirafa'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím rýchlym pohybom?', 'Krysa'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím čiernym a bielym sfarbením?', 'Panda'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím spevom v noci?', 'Sova'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou žiť na stromoch?', 'Veverička'),
('Ríša zvierat', 1, 'Ktoré zviera je najobľúbenejším domácim miláčikom?', 'Mačka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe ako "pán mora"?', 'Krokodíl'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou orientovať sa pomocou echolokácie?', 'Netopier'),
('Ríša zvierat', 2, 'Aké zviera je najväčším suchozemským predátorom?', 'Ľadový medveď'),
('Ríša zvierat', 2, 'Ktoré zviera dokáže prežiť v extrémnych podmienkach Arktídy?', 'Tučniak'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím tkaním sietí?', 'Pavúk'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou plávať na veľké vzdialenosti?', 'Delfín'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojim špecifickým správaním pri migrácii?', 'Husi'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou chodiť po vode?', 'Bohužiaľ'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím schopným útekom pred predátormi?', 'Srnka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť bez vody dlhší čas?', 'Kameňožrút'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou mimoriadnou rýchlosťou v behu?', 'Gepard'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou vytvárať zvuky na komunikáciu?', 'Delfín'),
('Ríša zvierat', 2, 'Ktoré zviera sa považuje za najinteligentnejšie na Zemi?', 'Delfín'),
('Ríša zvierat', 2, 'Aké zviera je známe svojím spevom pri východe slnka?', 'Pavúk'),
('Ríša zvierat', 2, 'Ktoré zviera má schopnosť regenerácie končatín?', 'Axolotl'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou zmeniť farbu?', 'Chameleón'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou odolnosťou voči jedom?', 'Súmračný had'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou dlhodobou pamäťou?', 'Slon'),
('Ríša zvierat', 2, 'Aké zviera je známe svojimi prednými zubami?', 'Bobor'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou vynikajúcou rovnováhou?', 'Koala'),
('Ríša zvierat', 2, 'Ktoré zviera je najväčší známy cicavec?', 'Modrý veľryb'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím tancovaním pri náboru partnera?', 'Jazvec'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou lietať vysokými rýchlosťami?', 'Sokol'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým krkom a nohami?', 'Žirafa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou precíznou koordináciou pohybov?', 'Mačka'),
('Ríša zvierat', 2, 'Ktoré zviera sa považuje za najväčšieho predátora v oceáne?', 'Žralok'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou skákať do výšky?', 'Kangúr'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojimi mimoriadnymi akrobatickými schopnosťami?', 'Lemur'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou loviť vo dne aj v noci?', 'Sovy'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou silou a výdržou pri ťahaní?', 'Hroch'),
('Ríša zvierat', 2, 'Aké zviera je známe svojím veľkým rozšírením po celom svete?', 'Holub'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou žiť na extrémne nízkych teplotách?', 'Tučniak'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Papagáj'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v púšti?', 'Púštny vrabec'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojim jedinečným spôsobom lovu?', 'Orol'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím veľmi silným čelusťom?', 'Krokodíl'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým letom?', 'Migrujúca vtáka'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou získať energiu z jedla?', 'Vlk'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím špecifickým správaním pri nábore partnera?', 'Páv'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím rýchlym pohybom v noci?', 'Puma'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou skryť sa?', 'Chameleón'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou orientovať sa v tme?', 'Netopier'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v horúčavách?', 'Kameň'),
('Ríša zvierat', 2, 'Ktoré zviera sa považuje za symbol Škótska?', 'Jednorožec'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou loviť v noci?', 'Sova'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým jazykom?', 'Chameleón'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou plávať v ľadovej vode?', 'Tulene'),
('Ríša zvierat', 2, 'Aké zviera je najväčším cicavcom v mori?', 'Modrá veľryba'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou zmeniť farbu?', 'Chameleón'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím mimoriadnym sluchom?', 'Sovy'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v tme?', 'Rybka'),
('Ríša zvierat', 2, 'Aké zviera je známe svojím skvelým zrakom pri súmraku?', 'Mačka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím vynikajúcim čuchom?', 'Pes'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou pomalou chôdzou a dlhým životom?', 'Žirafa'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou migrovať na dlhé vzdialenosti?', 'Losos'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím vynikajúcim skrytým životom?', 'Krysa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím pestrým sfarbením v prírode?', 'Motýľ'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou tancovať na slnku?', 'Pavúk'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou silou a schopnosťou ťahať?', 'Kôň'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím rozšíreným biotopom?', 'Holub'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou agresivitou vo vojne?', 'Hroch'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou plávať v riekach?', 'Korytnačka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím špecifickým výskytom v lesoch?', 'Medveď'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou získať energiu zo slnka?', 'Tráva'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou loviť vo dne?', 'Orol'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím hniezdením na stromoch?', 'Vták'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou plávať pod vodou?', 'Rybka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v horúčavách?', 'Krysa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím veľmi silným čelusťom?', 'Krokodíl'),
('Ríša zvierat', 2, 'Aké zviera je známe svojím tkaním sietí?', 'Pavúk'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v piesku?', 'Krysa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Papagáj'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou skákať do výšky?', 'Kangaroo'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím hlasným volaním?', 'Kohút'),
('Ríša zvierat', 2, 'Ktoré zviera sa považuje za symbol moci?', 'Orol'),
('Ríša zvierat', 2, 'Aké zviera je známe svojou schopnosťou prežiť vo vode?', 'Rybka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým chvostom a špecifickým správaním?', 'Mačka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím rozšírením po celom svete?', 'Holub'),
('Ríša zvierat', 2, 'Aké zviera je známe svojím dlhým krkom?', 'Žirafa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou plávať v mori?', 'Delfín'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím spevom v noci?', 'Sova'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím jedinečným správaním pri nábore partnera?', 'Páv'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím spevom na jar?', 'Slávik'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou skryť sa v piesku?', 'Chameleón'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou čiernou a bielou srsťou?', 'Panda'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou plávať v riekach?', 'Samica lososa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou mimoriadnou rýchlosťou v behu?', 'Gepard'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou vynikajúcou pamäťou?', 'Slon'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v arktických podmienkach?', 'Ľadový medveď'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým chvostom a schopnosťou skákať?', 'Kangaroo'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Papagáj'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím schopným sluchom?', 'Sova'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou migrovať na dlhé vzdialenosti?', 'Losos'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím spevom v noci?', 'Sova'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím tkaním sietí?', 'Pavúk'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v extrémnych teplotách?', 'Krysa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou rýchlosťou v mori?', 'Morsky lev'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím spevom pri východe slnka?', 'Čajka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou lietať?', 'Kolibrík'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím bleskovým pohybom?', 'Mantis'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou vynikajúcou koordináciou pohybov?', 'Kočka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou orientovať sa v tme?', 'Netopier'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím rozkošným správaním?', 'Koala'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím spevom v prírode?', 'Hlasná žaba'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou plávať pod vodou?', 'Delfín'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou odolnosťou voči jedom?', 'Zelený mamba'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím tancovaním pri nábore partnera?', 'Pavúk'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím silným hlasom?', 'Krahulec'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím rozšírením vo svete?', 'Holub'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím veľmi silným čelusťom?', 'Krokodíl'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím špecifickým správaním pri migrácii?', 'Vták'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým jazykom?', 'Hroch'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v púšti?', 'Púštny potkan'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím jedinečným spôsobom lovu?', 'Súhvezdie'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím špecifickým správaním?', 'Veľryba'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým letom?', 'Albatros'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou silou a výdržou pri ťahaní?', 'Pony'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť v hlbokom mori?', 'Morsky had'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím silným a hlasným volaním?', 'Lev'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím vynikajúcim skrytým životom?', 'Jelen'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím pestrým sfarbením v prírode?', 'Rybárik'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou prežiť bez vody?', 'Cicavec'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím dlhým krkom?', 'Žirafa'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojou schopnosťou plávať v riekach?', 'Korytnačka'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím špecifickým správaním pri nábore partnera?', 'Hrdlička'),
('Ríša zvierat', 2, 'Ktoré zviera je známe svojím skvelým zrakom pri súmraku?', 'Mačka'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou echolokácie?', 'Delfín'),
('Ríša zvierat', 3, 'Ktoré zviera má najdlhšie migračné trasy?', 'Labuť'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v hlbokom mori?', 'Gulóny'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím mimoriadne silným čelusťom?', 'Hroš'),
('Ríša zvierat', 3, 'Ktoré zviera je najväčším suchozemským predátorom?', 'Ľadový medveď'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím tkaním sietí?', 'Pavúk'),
('Ríša zvierat', 3, 'Ktoré zviera má najväčšiu pamäť?', 'Slon'),
('Ríša zvierat', 3, 'Ktoré zviera dokáže prežiť v najextrémnejších podmienkach?', 'Tardigrád'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou zmeniť farbu?', 'Chameleon'),
('Ríša zvierat', 3, 'Ktoré zviera je najväčším cicavcom?', 'Modrý veľryb'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou loviť v noci?', 'Sova'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať v ľadovej vode?', 'Tuleni'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím spôsobom migrácie?', 'Losos'),
('Ríša zvierat', 3, 'Ktoré zviera dokáže prežiť bez vody dlhší čas?', 'Kameň'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou jedinečnou schopnosťou orientovať sa pomocou magnetických polí?', 'Holub'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť s minimom potravy?', 'Krysa'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou agresívnou povahou?', 'Hroch'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať na veľké vzdialenosti?', 'Žralok'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou vysokou inteligenciou?', 'Krkavec'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím spevom počas párenia?', 'Páv'),
('Ríša zvierat', 3, 'Ktoré zviera je najrýchlejším predátorom v mori?', 'Mako'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou regenerácie?', 'Axolotl'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím schopným chovaním pri migrácii?', 'Láskyplný vrabec'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím dlhým ťahom za potravou?', 'Včela'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou skryť sa v piesku?', 'Súšky'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím jedinečným spôsobom prežitia v púšti?', 'Kameleón'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať v riekach?', 'Korytnačka'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím výnimočným tancom pri nábore partnera?', 'Baldachýn'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím jedinečným spôsobom lovu?', 'Vydra'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou orientovať sa vo vode?', 'Rybárik'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Papagáj'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou žiť vo výškach?', 'Orol'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojimi akrobatickými schopnosťami?', 'Morské kone'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou odolnosťou voči chladu?', 'Arktický vlk'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím orientovaním sa v tme?', 'Netopier'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím rýchlym pohybom vo vode?', 'Tropický krab'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím spevom na jar?', 'Slávik'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v lesoch?', 'Medveď'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím rozšírením po celom svete?', 'Potkan'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím tkaním sietí?', 'Pavúk'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Gekón'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím spevom po východe slnka?', 'Škovránok'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím špecifickým správaním pri nábore partnera?', 'Kolibrík'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím tkaním sietí na lov?', 'Pavúk'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v horúčavách?', 'Kameň'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím spôsobom lovu vo vode?', 'Rybárik'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v piesku?', 'Korytnačka'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou echolokácie?', 'Delfín'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v extrémne vysokých nadmorských výškach?', 'Vysokohorský kozorožec'),
('Ríša zvierat', 3, 'Aké zviera je najväčším suchozemským cicavcom?', 'Slon'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou mimoriadnou schopnosťou regenerácie?', 'Axolotl'),
('Ríša zvierat', 3, 'Ktoré zviera sa považuje za najinteligentnejšie na svete?', 'Delfín'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím pestrým sfarbením?', 'Krajta'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať na dlhé vzdialenosti?', 'Vták'),
('Ríša zvierat', 3, 'Ktoré zviera prekonáva najdlhšiu migráciu?', 'Tuleň'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou skryť sa v piesku?', 'Chameleón'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím tkaním sietí?', 'Spidermonkey'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím dlhým ťahom za potravou?', 'Orol'),
('Ríša zvierat', 3, 'Ktoré zviera prežije v ľadových podmienkach?', 'Tulene'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím špecifickým správaním pri nábore partnera?', 'Páv'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou špecifickou mechanikou chôdze?', 'Korytnačka'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou orientovať sa v tme?', 'Netopier'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím rozšírením po celom svete?', 'Krysa'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť vo výškach?', 'Vták'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím spevom pri východe slnka?', 'Slávik'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím jedinečným spôsobom lovu?', 'Hroch'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím mimoriadnym sluchom?', 'Sovy'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou prežiť v púšti?', 'Kameň'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím špecifickým správaním pri migrácii?', 'Rys'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v arktických podmienkach?', 'Nork'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím veľmi silným čelusťom?', 'Krokodíl'),
('Ríša zvierat', 3, 'Aké zviera je najväčším predátorom v mori?', 'Žralok'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať v ľadovej vode?', 'Polárny medveď'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím dlhým letom?', 'Orol'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v hlbokom mori?', 'Rybka'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím rozkošným správaním?', 'Koala'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou orientovať sa pomocou magnetických polí?', 'Holub'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou silou a výdržou pri ťahaní?', 'Bizon'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou skákať do výšky?', 'Skokan'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím špecifickým správaním?', 'Hlava'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť s minimom potravy?', 'Zebry'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou agresivitou vo vojne?', 'Lev'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím spevom počas párenia?', 'Kanárik'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím dlhým jazykom?', 'Jazvec'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať v riekach?', 'Losos'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím jedinečným spôsobom skrytia?', 'Chameleón'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím spevom v noci?', 'Sova'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím tkaním sietí na lov?', 'Spidermonkey'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím výnimočným tancom pri párení?', 'Páv'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou prežiť v horúčavách?', 'Kameň'),
('Ríša zvierat', 3, 'Aké zviera má najväčšiu migráciu na svete?', 'Pštros'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou echolokácie?', 'Delfín'),
('Ríša zvierat', 3, 'Aké zviera sa považuje za najinteligentnejšie hmyz?', 'Včela'),
('Ríša zvierat', 3, 'Ktoré zviera dokáže prežiť v extrémnych podmienkach púšte?', 'Púštny ježko'),
('Ríša zvierat', 3, 'Ktoré zviera má najdlhší život na Zemi?', 'Tučniak'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať v mori?', 'Chobotnica'),
('Ríša zvierat', 3, 'Aké zviera je najväčším predátorom na pevnine?', 'Grizzly'),
('Ríša zvierat', 3, 'Ktoré zviera má najdlhší krk?', 'Žirafa'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím mimoriadne silným čelusťom?', 'Hroch'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v hlbokom mori?', 'Biely žralok'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou skryť sa medzi listami?', 'Chameleón'),
('Ríša zvierat', 3, 'Ktoré zviera je najrýchlejším plazom?', 'Krajta'),
('Ríša zvierat', 3, 'Aké zviera sa považuje za najstaršie na svete?', 'Žralok'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť bez jedla dlhú dobu?', 'Korytnačka'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou loviť v noci?', 'Sova'),
('Ríša zvierat', 3, 'Aké zviera má najväčšiu silu v pomere k svojej veľkosti?', 'Mravec'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v arktických podmienkach?', 'Tulene'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou skákať do výšky?', 'Kangúr'),
('Ríša zvierat', 3, 'Aké zviera je považované za symbol múdrosti?', 'Sova'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Papagáj'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím vynikajúcim sluchom?', 'Netopier'),
('Ríša zvierat', 3, 'Aké zviera je najväčším cicavcom na svete?', 'Modrý veľryb'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou zmeniť farbu?', 'Chameleón'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou agresivitou vo vojne?', 'Rys'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím tkaním sietí?', 'Pavúk'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím vynikajúcim zrakom?', 'Orol'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou skryť sa vo vode?', 'Korytnačka'),
('Ríša zvierat', 3, 'Aké zviera je známe svojím hlasným volaním?', 'Lemur'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť v piesku?', 'Púštny krtko'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou loviť vo dne aj v noci?', 'Kočka'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím pestrým sfarbením v prírode?', 'Tropická ryba'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou plávať v riekach?', 'Losos'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou prežiť v extrémne nízkych teplotách?', 'Tučniak'),
('Ríša zvierat', 3, 'Ktoré zviera je najväčším suchozemským predátorom?', 'Leopard'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím tkaním sietí na lov?', 'Pavúk'),
('Ríša zvierat', 3, 'Ktoré zviera sa považuje za symbol Škótska?', 'Jednorožec'),
('Ríša zvierat', 3, 'Aké zviera je známe svojou schopnosťou skryť sa v tme?', 'Sova'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou orientovať sa pomocou echolokácie?', 'Netopier'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojím pestrým sfarbením?', 'Korálovec'),
('Ríša zvierat', 3, 'Ktoré zviera má najdlhšie migračné trasy?', 'Hus'),
('Ríša zvierat', 3, 'Ktoré zviera je známe svojou schopnosťou prežiť s minimom potravy?', 'Cicavec'),
('Slovenský jazyk', 1, 'Aké je hlavné mesto Slovenska?', 'Bratislava'),
('Slovenský jazyk', 1, 'Aký jazyk je úradný na Slovensku?', 'Slovenčina'),
('Slovenský jazyk', 1, 'Aký je najvyšší vrch Slovenska?', 'Gerlachovský štít'),
('Slovenský jazyk', 1, 'Kto napísal pieseň "Túlavá"?', 'Janko'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "Czechoslovakia"?', 'Československo'),
('Slovenský jazyk', 1, 'Čo je to "hádanka"?', 'Otázka'),
('Slovenský jazyk', 1, 'Kto je autorom "Krajina pod Mračnom"?', 'Hronský'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "book"?', 'Kniha'),
('Slovenský jazyk', 1, 'Aké je najznámejšie slovenské jedlo?', 'Bryndzové halušky'),
('Slovenský jazyk', 1, 'Ktorý jazyk je blízky slovenčine?', 'Čeština'),
('Slovenský jazyk', 1, 'Čo znamená slovo "srdce"?', 'Orgán'),
('Slovenský jazyk', 1, 'Aká je najdlhšia rieka na Slovensku?', 'Dunaj'),
('Slovenský jazyk', 1, 'Kedy sa oslavuje Deň učiteľov?', '28. marec'),
('Slovenský jazyk', 1, 'Aké je hlavné mesto Maďarska?', 'Budapešť'),
('Slovenský jazyk', 1, 'Aká je farba slovenského národného znaku?', 'Modrá'),
('Slovenský jazyk', 1, 'Kto napísal "Jozefa Mak"?', 'Kukučín'),
('Slovenský jazyk', 1, 'Aký jazyk je úradný v Česku?', 'Čeština'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "family"?', 'Rodina'),
('Slovenský jazyk', 1, 'Kto je autorom "Slovenských pohľadov"?', 'Križan'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "friend"?', 'Priateľ'),
('Slovenský jazyk', 1, 'Kto je autorom "Zlatého klasu"?', 'Sládkovič'),
('Slovenský jazyk', 1, 'Ktorý jazyk je najrozšírenejší na svete?', 'Angličtina'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "love"?', 'Láska'),
('Slovenský jazyk', 1, 'Kto je autorom "Pohádok"?', 'Kollár'),
('Slovenský jazyk', 1, 'Kedy sa oslavuje Deň slovenskej kultúry?', '5. február'),
('Slovenský jazyk', 1, 'Aké je najznámejšie slovenské mesto?', 'Bratislava'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "holiday"?', 'Prázdniny'),
('Slovenský jazyk', 1, 'Kto napísal "Reštart"?', 'Krištúfek'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "school"?', 'Škola'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "water"?', 'Voda'),
('Slovenský jazyk', 1, 'Kto je autorom "Búrlivého vína"?', 'Zúrik'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "city"?', 'Mesto'),
('Slovenský jazyk', 1, 'Kde sa nachádza Bratislava?', 'Na Slovensku'),
('Slovenský jazyk', 1, 'Kto je najznámejší slovenský spisovateľ?', 'Kukučín'),
('Slovenský jazyk', 1, 'Aká je slovenská mena?', 'Euro'),
('Slovenský jazyk', 1, 'Kedy sa oslavuje Deň štátnosti?', '1. september'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "teacher"?', 'Učiteľ'),
('Slovenský jazyk', 1, 'Kto napísal "Osudy dobrého vojáka Švejka"?', 'Hašek'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "friendship"?', 'Priateľstvo'),
('Slovenský jazyk', 1, 'Aké je hlavné mesto Česka?', 'Praha'),
('Slovenský jazyk', 1, 'Kto je autorom "Kniha o Slovensku"?', 'Pavlík'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "music"?', 'Hudba'),
('Slovenský jazyk', 1, 'Kedy sa koná festival "Pohoda"?', 'Júl'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "language"?', 'Jazyk'),
('Slovenský jazyk', 1, 'Kto je autorom "Básní"?', 'Hviezdoslav'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "art"?', 'Umenie'),
('Slovenský jazyk', 1, 'Kto napísal "Malý princ"?', 'Saint-Exupéry'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "sun"?', 'Slnko'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "star"?', 'Hvězda'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "joy"?', 'Radosť'),
('Slovenský jazyk', 1, 'Kto je autorom "Dielo"?', 'Rázus'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "dream"?', 'Snívanie'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "peace"?', 'Mier'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "apple"?', 'jablko'),
('Slovenský jazyk', 1, 'Čo je to "príslovie"?', 'výrok'),
('Slovenský jazyk', 1, 'Kto je autorom "Panta Rhei"?', 'Milan Kňažko'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "house"?', 'dom'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "tree"?', 'strom'),
('Slovenský jazyk', 1, 'Kto napísal "Kocúr v čižmách"?', 'Perrault'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "bird"?', 'vták'),
('Slovenský jazyk', 1, 'Ktorý deň sa oslavuje Deň materského jazyka?', '21. február'),
('Slovenský jazyk', 1, 'Čo znamená slovo "kniha"?', 'publikácia'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "mountain"?', 'hora'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "friend"?', 'priateľ'),
('Slovenský jazyk', 1, 'Kto je autorom "Slovenských rozprávok"?', 'J. S. B.'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "gift"?', 'dar'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "family"?', 'rodina'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "star"?', 'hviezda'),
('Slovenský jazyk', 1, 'Kto napísal "Horehronie"?', 'Ján Smrek'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "moon"?', 'mesiac'),
('Slovenský jazyk', 1, 'Čo je to "verš"?', 'poetická forma'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "food"?', 'jedlo'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "ocean"?', 'oceán'),
('Slovenský jazyk', 1, 'Kto je autorom "Poesie"?', 'Ján Kostra'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "school"?', 'škola'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "light"?', 'svetlo'),
('Slovenský jazyk', 1, 'Kto napísal "Básne"?', 'Ján Smrek'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "city"?', 'mesto'),
('Slovenský jazyk', 1, 'Ktorý jazyk je najrozšírenejší v Európe?', 'angličtina'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "friendship"?', 'priatelstvo'),
('Slovenský jazyk', 1, 'Kto je autorom "Kvetináč"?', 'Jozef Gregor Tajovský'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "water"?', 'voda'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "love"?', 'láska'),
('Slovenský jazyk', 1, 'Kto napísal "Báseň o jari"?', 'Ján Smrek'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "friend"?', 'priateľ'),
('Slovenský jazyk', 1, 'Kedy sa oslavuje Deň slovenského jazyka?', '1. február'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "sun"?', 'slnko'),
('Slovenský jazyk', 1, 'Čo znamená slovo "sny"?', 'predstavy'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "dog"?', 'pes'),
('Slovenský jazyk', 1, 'Kto je autorom "Červená Karkulka"?', 'Perrault'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "peace"?', 'mír'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "heart"?', 'srdce'),
('Slovenský jazyk', 1, 'Čo je to "epika"?', 'literárny žáner'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "sky"?', 'nebo'),
('Slovenský jazyk', 1, 'Kedy sa oslavuje Deň písania?', '8. november'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "happiness"?', 'šťastie'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "wind"?', 'vietor'),
('Slovenský jazyk', 1, 'Čo je to "literatúra"?', 'umenie písania'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "rain"?', 'dážď'),
('Slovenský jazyk', 1, 'Kto napísal "Prvý krok"?', 'Milan Kňažko'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "time"?', 'čas'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "fire"?', 'oheň'),
('Slovenský jazyk', 1, 'Kto je autorom "Krajina snov"?', 'Milan Rúfus'),
('Slovenský jazyk', 1, 'Aké je slovenské slovo pre "child"?', 'dieťa'),
('Slovenský jazyk', 1, 'Aký je slovenský názov pre "dream"?', 'sen'),
('Slovenský jazyk', 1, 'Čo je to "rozprávka"?', 'príbeh'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "family tree"?', 'Rodokmeň'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "dictionary"?', 'Slovník'),
('Slovenský jazyk', 2, 'Kto je autorom "Maturitnej otázky"?', 'F. X. Šalda'),
('Slovenský jazyk', 2, 'Kto napísal "Pieseň bez mena"?', 'Milan Rúfus'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "poem"?', 'Báseň'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "literature"?', 'Literatúra'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "novel"?', 'Román'),
('Slovenský jazyk', 2, 'Kto napísal "Cintorín zvierat"?', 'Stephen King'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "narrative"?', 'Rozprávanie'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "verse"?', 'Verš'),
('Slovenský jazyk', 2, 'Kto napísal "Pani Bovaryová"?', 'Gustave Flaubert'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "prose"?', 'Proza'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "sentence"?', 'Veta'),
('Slovenský jazyk', 2, 'Kto je autorom "Kvetinový román"?', 'B. Slančík'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "punctuation"?', 'Interpunkcia'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "grammar"?', 'Gramatika'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "fiction"?', 'Fikcia'),
('Slovenský jazyk', 2, 'Kto napísal "Rozprávky"?', 'Hans Christian Andersen'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "essay"?', 'Esej'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "character"?', 'Postava'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "theme"?', 'Téma'),
('Slovenský jazyk', 2, 'Kto napísal "Básne z Krajiny"?', 'Ján Štrasser'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "speech"?', 'Reč'),
('Slovenský jazyk', 2, 'Kto je autorom "Klasika slovenskej poézie"?', 'Pavol Országh Hviezdoslav'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "dialogue"?', 'Dialóg'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "metaphor"?', 'Metafora'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "symbol"?', 'Symbol'),
('Slovenský jazyk', 2, 'Kto napísal "Kniha o Slovensku"?', 'Milan Krajniak'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "summary"?', 'Zhrnutie'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "analogy"?', 'Analógia'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "chronicle"?', 'Kronika'),
('Slovenský jazyk', 2, 'Kto napísal "Vtáčik a kvet"?', 'Milan Rúfus'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "rhyme"?', 'Rým'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "contrast"?', 'Kontrast'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "narrator"?', 'Rozprávač'),
('Slovenský jazyk', 2, 'Kto napísal "Svetlo v tme"?', 'Jozef Cíger Hronský'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "adjective"?', 'Prídavné meno'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "style"?', 'Štýl'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "audience"?', 'Publikum'),
('Slovenský jazyk', 2, 'Kto napísal "Krajina srdca"?', 'Daniel Hevier'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "plot"?', 'Zápletka'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "interpretation"?', 'Interpretácia'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "perspective"?', 'Perspektíva'),
('Slovenský jazyk', 2, 'Kto napísal "Moje deti"?', 'Jozef Gregor Tajovsky'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "quotation"?', 'Citát'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "context"?', 'Kontext'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "philosophy"?', 'Filozofia'),
('Slovenský jazyk', 2, 'Kto napísal "Dielo"?', 'Milan Krajniak'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "inspiration"?', 'Inšpirácia'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "analysis"?', 'Analýza'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "literary"?', 'Literárny'),
('Slovenský jazyk', 2, 'Kto napísal "Pohľady na svet"?', 'Milan Krajniak'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "poet"?', 'Básnik'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "emotion"?', 'Emócia'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "characterization"?', 'Charakterizácia'),
('Slovenský jazyk', 2, 'Kto napísal "Poézia a realita"?', 'Pavol Országh Hviezdoslav'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "epic"?', 'Epika'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "narrative voice"?', 'Rozprávačský hlas'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "theme"?', 'Téma'),
('Slovenský jazyk', 2, 'Kto napísal "Svetlo v tme"?', 'Jozef Cíger Hronský'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "library"?', 'Knižnica'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "poetry"?', 'Poézia'),
('Slovenský jazyk', 2, 'Kto napísal "Návrat"?', 'V. K.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "culture"?', 'Kultúra'),
('Slovenský jazyk', 2, 'Ktorý autor napísal "Krajina v srdci"?', 'M. K.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "history"?', 'História'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "theater"?', 'Divadlo'),
('Slovenský jazyk', 2, 'Kto napísal "Hlava XXII"?', 'J. Heller'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "novel"?', 'Román'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "journal"?', 'Časopis'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "article"?', 'Článok'),
('Slovenský jazyk', 2, 'Kto je autorom "Kniha snov"?', 'A. B.'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "play"?', 'Hra'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "author"?', 'Autor'),
('Slovenský jazyk', 2, 'Kto napísal "Slovenské rozprávky"?', 'J. F.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "character"?', 'Postava'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "critique"?', 'Kritika'),
('Slovenský jazyk', 2, 'Kto napísal "Pohľadnice"?', 'J. K.');