INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Dejiny', 1, 'Kto bol kráľom Anglicka počas Veľkej vojny?', 'Henrich'),
('Dejiny', 1, 'Kde sa narodil Napoleon?', 'Korzika'),
('Dejiny', 1, 'Kto napísal "Zločin a trest"?', 'Dostojevskij'),
('Dejiny', 1, 'Kto je známy ako "otec histórie"?', 'Herodotos'),
('Dejiny', 1, 'Ktorá krajina bola domovom Mayskej civilizácie?', 'Mexiko'),
('Dejiny', 1, 'Kedy bola objavená Amerika?', '1492'),
('Dejiny', 1, 'Kto bol prvým človekom na Mesiaci?', 'Armstrong'),
('Dejiny', 1, 'Ktorá ríša bola známa svojou hodvábnou cestou?', 'Rímska'),
('Dejiny', 1, 'Aký je hlavný jazyk v Taliansku?', 'Taliančina'),
('Dejiny', 1, 'Kto viedol Americkú revolúciu?', 'Washington'),
('Dejiny', 1, 'Kde sa nachádza Stonehenge?', 'Anglicko'),
('Dejiny', 1, 'Kto bol prvým prezidentom Československa?', 'Masaryk'),
('Dejiny', 1, 'Kto napísal "Pán prsteňov"?', 'Tolkien'),
('Dejiny', 1, 'Kedy sa uskutočnila 1. svetová vojna?', '1914'),
('Dejiny', 1, 'Kde bola založená Aténska demokracia?', 'Atény'),
('Dejiny', 1, 'Kto bol vynálezcom parného stroja?', 'Watt'),
('Dejiny', 1, 'Aká bola hlavná náboženská tradícia v starovekom Egypte?', 'Polyteizmus'),
('Dejiny', 1, 'Kto bol vodcom nacistického Nemecka?', 'Hitler'),
('Dejiny', 1, 'Kedy bola vyhlásená nezávislosť USA?', '1776'),
('Dejiny', 1, 'Kto napísal "Božskú komédiu"?', 'Dante'),
('Dejiny', 1, 'Kto bol kráľom Francúzska počas revolúcie?', 'Ľudovít'),
('Dejiny', 1, 'Kde sa nachádza Koloseum?', 'Rím'),
('Dejiny', 1, 'Kto bol prvým prezidentom Ruska?', 'Jelcin'),
('Dejiny', 1, 'Ktorý štát je známy svojou históriou samurajov?', 'Japonsko'),
('Dejiny', 1, 'Kto je známy ako "srdce Indického národa"?', 'Gándhí'),
('Dejiny', 1, 'Kedy bola postavená Veľká pyramída?', '2580 pred n.l.'),
('Dejiny', 1, 'Kto bol posledným faraónom Egypta?', 'Kleopatra'),
('Dejiny', 1, 'Kto vynašiel kníhtlač?', 'Gutenberg'),
('Dejiny', 1, 'Aký spôsob vlády existoval v starovekom Grécku?', 'Demokracia'),
('Dejiny', 1, 'Kto bol autorom "Mníchovskej dohody"?', 'Chamberlain'),
('Dejiny', 1, 'Kto bol zakladateľom Mongolskej ríše?', 'Čingischán'),
('Dejiny', 1, 'Kedy vznikla Európska únia?', '1993'),
('Dejiny', 1, 'Kto bol vodcom Francúzskej revolúcie?', 'Robespierre'),
('Dejiny', 1, 'Kto napísal "Vojnu a mier"?', 'Tolstoj'),
('Dejiny', 1, 'Kde sa narodil Albert Einstein?', 'Nemecko'),
('Dejiny', 1, 'Kto bol zakladateľom Facebooku?', 'Zuckerberg'),
('Dejiny', 1, 'Aký je hlavný jazyk v Indii?', 'Hindčina'),
('Dejiny', 1, 'Ktorá krajina bola známa ako "Zem vychádzajúceho slnka"?', 'Japonsko'),
('Dejiny', 1, 'Kto bol prvým prezidentom Južnej Kórey?', 'Rhee'),
('Dejiny', 1, 'Kto bol prvým rímskym cisárom?', 'Augustus'),
('Dejiny', 1, 'Kedy sa konal pád Berlín Wall?', '1989'),
('Dejiny', 1, 'Kto napísal "Všeobecnú históriu"?', 'Herodotos'),
('Dejiny', 1, 'Aká bola hlavná náboženská tradícia v starovekom Ríme?', 'Pohanstvo'),
('Dejiny', 1, 'Ktorý kráľ Anglicka bol popravený?', 'Karel'),
('Dejiny', 1, 'Kde sa uskutočnil súd s čarodejnicami?', 'Salem'),
('Dejiny', 1, 'Kto bol vodcom americkej občianskej vojny?', 'Lincoln'),
('Dejiny', 1, 'Kedy sa konala bitka pri Waterloo?', '1815'),
('Dejiny', 1, 'Kto bol prvým prezidentom Francúzskej republiky?', 'Léon'),
('Dejiny', 1, 'Ktorá krajina zrušila otroctvo ako prvá?', 'Haití'),
('Dejiny', 1, 'Kto bol známy ako "Železný kancelár"?', 'Bismarck'),
('Dejiny', 1, 'Kedy bola objavená penicilín?', '1928'),
('Dejiny', 1, 'Kto bol prvým ženou vo vláde USA?', 'Eleanor'),
('Dejiny', 1, 'Aká bola hlavným mestom starovekého Egypta?', 'Théb'),
('Dejiny', 1, 'Kto bol vodcom Indického hnutia za nezávislosť?', 'Gándhí'),
('Dejiny', 1, 'Kedy bola založená OSN?', '1945'),
('Dejiny', 1, 'Kto bol najznámejším egyptským faraónom?', 'Tutanchamon'),
('Dejiny', 1, 'Kde sa nachádza Taj Mahal?', 'India'),
('Dejiny', 1, 'Kto bol vodcom sovietskej revolúcie?', 'Lenin'),
('Dejiny', 1, 'Kto napísal "Povstanie v Gulagu"?', 'Solženicyn'),
('Dejiny', 1, 'Kedy bola prvá ľudská expedícia na Mesiac?', '1969'),
('Dejiny', 1, 'Kto bol posledným panovníkom Ruského impéria?', 'Nikolaj'),
('Dejiny', 1, 'Kto objavil teórie relativity?', 'Einstein'),
('Dejiny', 1, 'Kedy bola vyhlásená Deklarácia práv človeka?', '1789'),
('Dejiny', 1, 'Kto bol prvý muž, ktorý prešiel cez pól?', 'Peary'),
('Dejiny', 1, 'Kde sa konala Prvá svetová vojna?', 'Európa'),
('Dejiny', 1, 'Kto bol najznámejším vodcom zabezpečenia demokracie?', 'Churchill'),
('Dejiny', 1, 'Kto bol vynálezcom telegrafu?', 'Morse'),
('Dejiny', 1, 'Kedy bol spustený Titanic?', '1911'),
('Dejiny', 1, 'Kto bol zakladateľom Rímskej ríše?', 'Rím'),
('Dejiny', 1, 'Kedy bola založená Veľká Británia?', '1707'),
('Dejiny', 1, 'Kto bol prvým prezidentom Indie?', 'Nehru'),
('Dejiny', 1, 'Kde sa nachádza pyramída v Gíze?', 'Egypt'),
('Dejiny', 1, 'Kto napísal "Knihu o duši"?', 'Plato'),
('Dejiny', 1, 'Kedy bola založená NATO?', '1949'),
('Dejiny', 1, 'Kto bol zakladateľom Mongolskej ríše?', 'Čingischán'),
('Dejiny', 1, 'Kde sa nachádza Pompei?', 'Taliansko'),
('Dejiny', 1, 'Kto bol vodcom Francúzskej revolúcie?', 'Robespierre'),
('Dejiny', 1, 'Kedy bola postavená Veľká čínská múr?', '5 st.'),
('Dejiny', 1, 'Kto bol posledným cisárom Japonska?', 'Hirohito'),
('Dejiny', 1, 'Kde sa narodil Leonardo da Vinci?', 'Taliansko'),
('Dejiny', 1, 'Kto vymyslel teóriu evolúcie?', 'Darwin'),
('Dejiny', 1, 'Kedy sa konala bitka pri Stalingrade?', '1942'),
('Dejiny', 1, 'Kto bol zakladateľom Ruskej revolúcie?', 'Lenin'),
('Dejiny', 1, 'Kde sa nachádza Akropolis?', 'Atény'),
('Dejiny', 1, 'Kto bol prvým prezidentom Talianska?', 'Einaudi'),
('Dejiny', 1, 'Kedy bola prvá svetová vojna?', '1914'),
('Dejiny', 1, 'Kto napísal "Ferdydurke"?', 'Gombrowicz'),
('Dejiny', 1, 'Kde sa uskutočnila bitka pri Gettysburgu?', 'USA'),
('Dejiny', 1, 'Kto bol zakladateľom Ottomanskej ríše?', 'Osman'),
('Dejiny', 1, 'Kedy bola skončená studená vojna?', '1991'),
('Dejiny', 1, 'Kto bol posledným kráľom Francúzska?', 'Ludvik'),
('Dejiny', 1, 'Kde sa nachádzajú Stonehenge?', 'Anglicko'),
('Dejiny', 1, 'Kto bol zakladateľom Facebooku?', 'Zuckerberg'),
('Dejiny', 2, 'Kto bol prvým prezidentom Španielska?', 'Primo de Rivera'),
('Dejiny', 2, 'Aké mesto bolo hlavným mestom Rímskej ríše?', 'Rím'),
('Dejiny', 2, 'Kedy bola podpísaná Magna carta?', '1215'),
('Dejiny', 2, 'Kto bol prvým prezidentom Turecka?', 'Mustafa Kemal'),
('Dejiny', 2, 'Ktorá krajina bola domovom Inkov?', 'Peru'),
('Dejiny', 2, 'Kedy sa skončila studená vojna?', '1991'),
('Dejiny', 2, 'Kto bol zakladateľom Carthage?', 'Dido'),
('Dejiny', 2, 'Kedy bola založená Veľká Británia?', '1707'),
('Dejiny', 2, 'Kto bol vodcom Rímskej republiky?', 'César'),
('Dejiny', 2, 'Kde sa nachádza historické mesto Petra?', 'Jordánsko'),
('Dejiny', 2, 'Kto bol posledným kráľom Ríma?', 'Tarquin'),
('Dejiny', 2, 'Kedy došlo k padu Konstantinopolu?', '1453'),
('Dejiny', 2, 'Kto bol prvým prezidentom Mexika?', 'Guadalupe Victoria'),
('Dejiny', 2, 'Kde sa nachádza Akropolis?', 'Atény'),
('Dejiny', 2, 'Kto bol zakladateľom dynastie Ming?', 'Zhu Yuanzhang'),
('Dejiny', 2, 'Kedy bola objavená Amerika Kolumbom?', '1492'),
('Dejiny', 2, 'Kto napísal "Vojna a mier"?', 'Tolstoj'),
('Dejiny', 2, 'Kto bol prvým cisárom Japonska?', 'Jimmu'),
('Dejiny', 2, 'Kedy bola zrušená otroctvo v USA?', '1865'),
('Dejiny', 2, 'Kto bol vodcom Francúzskej revolúcie?', 'Robespierre'),
('Dejiny', 2, 'Kedy bola založená Európska únia?', '1993'),
('Dejiny', 2, 'Kto bol prvým prezidentom Argentíny?', 'Bernardino Rivadavia'),
('Dejiny', 2, 'Kde sa nachádza historické mesto Machu Picchu?', 'Peru'),
('Dejiny', 2, 'Kto viedol revolúciu v Rusku?', 'Lenin'),
('Dejiny', 2, 'Kedy bola založená Rímska ríša?', '27 pred n.l.'),
('Dejiny', 2, 'Kto bol posledným faraónom?', 'Cleopatra'),
('Dejiny', 2, 'Kde bola podpísaná Versailleská zmluva?', 'Versailles'),
('Dejiny', 2, 'Kto bol vodcom britského impéria?', 'Winston Churchill'),
('Dejiny', 2, 'Kedy sa konala bitka pri Hastings?', '1066'),
('Dejiny', 2, 'Kto bol prvým prezidentom Indie?', 'Nehru'),
('Dejiny', 2, 'Kde sa nachádza hrad Windsor?', 'Anglicko'),
('Dejiny', 2, 'Kto bol známy ako "Otec národa" v Indii?', 'Gandhi'),
('Dejiny', 2, 'Kedy bola založená OSN?', '1945'),
('Dejiny', 2, 'Kto bol prvým prezidentom Talianska?', 'Enrico De Nicola'),
('Dejiny', 2, 'Kde sa konala bitka pri Waterloo?', 'Belgicko'),
('Dejiny', 2, 'Kto bol posledným cisárom Rakúska?', 'Karl I.'),
('Dejiny', 2, 'Kedy bola prvá svetová vojna?', '1914'),
('Dejiny', 2, 'Kto bol zakladateľom Rímskej republiky?', 'Brutus'),
('Dejiny', 2, 'Kedy bola objavená teória relativity?', '1905'),
('Dejiny', 2, 'Kto bol posledným kráľom Anglicka?', 'George VI'),
('Dejiny', 2, 'Kde sa nachádza socha Slobody?', 'USA'),
('Dejiny', 2, 'Kto bol vodcom americkej občianskej vojny?', 'Lincoln'),
('Dejiny', 2, 'Kedy sa konala bitka pri Stalingrade?', '1942'),
('Dejiny', 2, 'Kto napísal "Pán prsteňov"?', 'Tolkien'),
('Dejiny', 2, 'Kde sa nachádza Berlín?', 'Nemecko'),
('Dejiny', 2, 'Kto bol prvým prezidentom Južnej Kórey?', 'Syngman Rhee'),
('Dejiny', 2, 'Kedy bola založená NATO?', '1949'),
('Dejiny', 2, 'Kto bol zakladateľom Ottomanskej ríše?', 'Osman I.'),
('Dejiny', 2, 'Kde sa nachádza historické mesto Pompeje?', 'Taliansko'),
('Dejiny', 2, 'Kto bol vodcom talianskej fašistickej strany?', 'Mussolini'),
('Dejiny', 2, 'Kedy bol spustený Titanic?', '1912'),
('Dejiny', 2, 'Kto bol prvým rímskym senátorom?', 'Romulus'),
('Dejiny', 2, 'Kedy bola podpísaná Trianonská zmluva?', '1920'),
('Dejiny', 2, 'Kto bol autorom "Mein Kampf"?', 'Hitler'),
('Dejiny', 2, 'Kde sa nachádza historické mesto Petra?', 'Jordánsko'),
('Dejiny', 2, 'Kto písal "Knihu mŕtvych"?', 'Egyptania'),
('Dejiny', 2, 'Kedy bola postavená Veľká pyramída?', '2580'),
('Dejiny', 2, 'Kto bol vodcom národného hnutia v Indii?', 'Gándhí'),
('Dejiny', 2, 'Kedy bola založená Rímska ríša?', '27'),
('Dejiny', 2, 'Kto bol prvým prezidentom Talianska?', 'Emanuele'),
('Dejiny', 2, 'Kde sa konala bitka pri Agincourte?', 'Francúzsko'),
('Dejiny', 2, 'Kto bol vodcom Sovietov po Stalinovi?', 'Chruščov'),
('Dejiny', 2, 'Kto bol autorom "Vojny a mier"?', 'Tolstoj'),
('Dejiny', 2, 'Kedy bola založená UNESCO?', '1945'),
('Dejiny', 2, 'Kto bol prvým premiérom Británie?', 'Pitt'),
('Dejiny', 2, 'Kde sa nachádza Hadriánov múr?', 'Anglicko'),
('Dejiny', 2, 'Kto bol prvým rímskym cisárom?', 'Augustus'),
('Dejiny', 2, 'Kedy sa konal pád Západorímskej ríše?', '476'),
('Dejiny', 2, 'Kto bol autorom "Svetovej histórie"?', 'Herodotos'),
('Dejiny', 2, 'Kde sa narodila Kleopatra?', 'Egypt'),
('Dejiny', 2, 'Kto bol vodcom Mexickej revolúcie?', 'Zapata'),
('Dejiny', 2, 'Kedy sa konala bitka pri Trafalgare?', '1805'),
('Dejiny', 2, 'Kto bol posledným panovníkom Francúzska?', 'Ludovít'),
('Dejiny', 2, 'Kedy bola objavená Antarktída?', '1820'),
('Dejiny', 2, 'Kto napísal "Knihu o duši"?', 'Európa'),
('Dejiny', 2, 'Kde sa konala bitka pri Verdune?', 'Francúzsko'),
('Dejiny', 2, 'Kto bol vodcom Rímskej republiky?', 'Caesar'),
('Dejiny', 2, 'Kedy bola zrušená otroctvo v Británii?', '1833'),
('Dejiny', 2, 'Kto bol zakladateľom dynastie Yuan?', 'Kublaj'),
('Dejiny', 2, 'Kedy bola založená Spoločnosť národov?', '1920'),
('Dejiny', 2, 'Kto bol posledným cisárom Japonska?', 'Hirohito'),
('Dejiny', 2, 'Kde sa nachádza Palác Potala?', 'Tibet'),
('Dejiny', 2, 'Kto bol vodcom Habsburskej monarchie?', 'František'),
('Dejiny', 2, 'Kedy bola vyhlásená nezávislosť Grécka?', '1821'),
('Dejiny', 2, 'Kto bol vynálezcom parného vlaku?', 'Stephenson'),
('Dejiny', 2, 'Kde sa nachádza hrad Alhambra?', 'Španielsko'),
('Dejiny', 2, 'Kto bol prvým prezidentom Južnej Afriky?', 'Mandela'),
('Dejiny', 2, 'Kedy sa konala bitka pri Stalingrade?', '1942'),
('Dejiny', 2, 'Kto bol vodcom boja za občianske práva?', 'King'),
('Dejiny', 2, 'Kedy bola podpísaná Versailleská zmluva?', '1919'),
('Dejiny', 2, 'Kto bol autorom "Pán prsteňov"?', 'Tolkien'),
('Dejiny', 2, 'Kde sa nachádza Slnečný chrám?', 'Peru'),
('Dejiny', 2, 'Kto bol prvým prezidentom Írska?', 'De Valera'),
('Dejiny', 2, 'Kedy bola založená Rímska ríša?', '27'),
('Dejiny', 2, 'Kto bol vodcom Francúzskej revolúcie?', 'Robespierre'),
('Dejiny', 2, 'Kde sa narodil Karl Marx?', 'Nemecko'),
('Dejiny', 2, 'Kto bol posledným kráľom Anglicka?', 'Richard'),
('Dejiny', 2, 'Kedy bola objavená Amerika?', '1492'),
('Dejiny', 2, 'Kto bol prvým prezidentom USA?', 'Washington'),
('Dejiny', 2, 'Kde sa nachádza Koloseum?', 'Rím'),
('Dejiny', 2, 'Kto viedol vojnu secesiu?', 'Lincoln'),
('Dejiny', 2, 'Kedy sa konal pád Berlín Wall?', '1989'),
('Dejiny', 2, 'Kto bol vodcom talianskej fašistickej strany?', 'Mussolini'),
('Dejiny', 2, 'Kde sa nachádza historické mesto Machu Picchu?', 'Peru'),
('Dejiny', 3, 'Kto bol posledným cisárom Rímskej ríše?', 'Romulus Augustulus'),
('Dejiny', 3, 'Kedy vzniklo Mayské písmo?', '300 p.n.l.'),
('Dejiny', 3, 'Kto napísal "Vojnu a mier"?', 'Lev Tolstoj'),
('Dejiny', 3, 'Kedy sa odohrala bitka pri Stalingrade?', '1942'),
('Dejiny', 3, 'Kto bol vodcom ZSSR po Stalinovi?', 'Khrushchev'),
('Dejiny', 3, 'Kedy bola podpísaná Trianonská zmluva?', '1920'),
('Dejiny', 3, 'Kto bol zakladateľom dynastie Ming?', 'Zhu Yuanzhang'),
('Dejiny', 3, 'Kto bol vynálezcom telegrafu?', 'Samuel Morse'),
('Dejiny', 3, 'Kedy bola vyhlásená nezávislosť Indie?', '1947'),
('Dejiny', 3, 'Kto bol posledným kráľom Francúzska?', 'Louis-Philippe'),
('Dejiny', 3, 'Kto napísal "Mein Kampf"?', 'Adolf Hitler'),
('Dejiny', 3, 'Kedy bola založená Spoločnosť národov?', '1920'),
('Dejiny', 3, 'Kto bol vodcom Mexickej revolúcie?', 'Emiliano Zapata'),
('Dejiny', 3, 'Kedy bola objavená Antarktída?', '1820'),
('Dejiny', 3, 'Kto bol zakladateľom Ottomanskej ríše?', 'Osman I.'),
('Dejiny', 3, 'Kedy bola založená UNESCO?', '1945'),
('Dejiny', 3, 'Kto bol posledným panovníkom Ruského impéria?', 'Nikolaj II.'),
('Dejiny', 3, 'Kto napísal "Povstanie v Gulagu"?', 'Aleksandr Solženicyn'),
('Dejiny', 3, 'Kto bol autorom "Svetovej histórie"?', 'Hernán Cortés'),
('Dejiny', 3, 'Kto bol vodcom Britského impéria?', 'Winston Churchill'),
('Dejiny', 3, 'Kedy bol spustený Titanic?', '1912'),
('Dejiny', 3, 'Kto bol prvým prezidentom Turecka?', 'Mustafa Kemal'),
('Dejiny', 3, 'Kde sa nachádza Palác Potala?', 'Tibet'),
('Dejiny', 3, 'Kedy bola založená Rímska ríša?', '27 p.n.l.'),
('Dejiny', 3, 'Kto bol prvým prezidentom Írska?', 'Douglas Hyde'),
('Dejiny', 3, 'Kto bol vynálezcom parného vlaku?', 'George Stephenson'),
('Dejiny', 3, 'Kedy bola založená Veľká Británia?', '1707'),
('Dejiny', 3, 'Kto bol vodcom Habsburskej monarchie?', 'František Jozef I.'),
('Dejiny', 3, 'Kedy sa konal pád Západorímskej ríše?', '476'),
('Dejiny', 3, 'Kto bol známy ako "Železný kancelár"?', 'Otto von Bismarck'),
('Dejiny', 3, 'Kedy bola vyhlásená Deklarácia práv človeka?', '1789'),
('Dejiny', 3, 'Kto bol prvým prezidentom Južnej Afriky?', 'Nelson Mandela'),
('Dejiny', 3, 'Kedy sa konala bitka pri Trafalgare?', '1805'),
('Dejiny', 3, 'Kto napísal "Zločin a trest"?', 'Fjodor Dostojevskij'),
('Dejiny', 3, 'Kto bol prvým prezidentom Mexika?', 'Guadalupe Victoria'),
('Dejiny', 3, 'Kedy bola založená NATO?', '1949'),
('Dejiny', 3, 'Kto bol známy ako "Otec národa" v Indii?', 'Mahatma Gandhi'),
('Dejiny', 3, 'Kde sa nachádza hrad Alhambra?', 'Španielsko'),
('Dejiny', 3, 'Kedy sa konala bitka pri Agincourte?', '1415'),
('Dejiny', 3, 'Kto bol posledným cisárom Japonska?', 'Hirohito'),
('Dejiny', 3, 'Kedy bola zrušená otroctvo v Británii?', '1833'),
('Dejiny', 3, 'Kto bol autorom "Ferdydurke"?', 'Witold Gombrowicz'),
('Dejiny', 3, 'Kedy bola objavená teória relativity?', '1905'),
('Dejiny', 3, 'Kto bol prvým prezidentom Argentíny?', 'Bernardino Rivadavia'),
('Dejiny', 3, 'Kedy sa konala bitka pri Hastings?', '1066'),
('Dejiny', 3, 'Kto bol zakladateľom dynastie Yuan?', 'Kublaj Chán'),
('Dejiny', 3, 'Kedy bola založená Rímska republika?', '509 p.n.l.'),
('Dejiny', 3, 'Kto bol zakladateľom dynastie Romanov?', 'Michał Romanov'),
('Dejiny', 3, 'Kedy došlo k padu Konstantinopolu?', '1453'),
('Dejiny', 3, 'Kto bol vodcom Indického hnutia za nezávislosť?', 'Jawaharlal Nehru'),
('Dejiny', 3, 'Kedy bola podpísaná Magna Carta?', '1215'),
('Dejiny', 3, 'Kto napísal "Božskú komédiu"?', 'Dante Alighieri'),
('Dejiny', 3, 'Kto bol prvým rímskym senátorom?', 'Lucius Junius Brutus'),
('Dejiny', 3, 'Kedy bola objavená Amerika Kolumbom?', '1492'),
('Dejiny', 3, 'Kto bol posledným faraónom Egypta?', 'Cleopatra VII.'),
('Dejiny', 3, 'Kto bol vodcom talianskej fašistickej strany?', 'Benito Mussolini'),
('Dejiny', 3, 'Kedy sa konala Prvá svetová vojna?', '1914-1918'),
('Dejiny', 3, 'Kto bol zakladateľom Rímskej republiky?', 'Brutus'),
('Dejiny', 3, 'Kedy bol zavraždený Ján Pavol II.?', '1981'),
('Dejiny', 3, 'Kde sa nachádza historické mesto Petra?', 'Jordánsko'),
('Dejiny', 3, 'Kto napísal "Knihu mŕtvych"?', 'Anonym'),
('Dejiny', 3, 'Kedy bola vyhlásená nezávislosť Grécka?', '1821'),
('Dejiny', 3, 'Kto bol prvým prezidentom Mexika?', 'Guadalupe Victoria'),
('Dejiny', 3, 'Kedy bola podpísaná Trianonská zmluva?', '1920'),
('Dejiny', 3, 'Kto bol posledným cisárom Japonska?', 'Hirohito'),
('Dejiny', 3, 'Kedy bola založená Spoločnosť národov?', '1920'),
('Dejiny', 3, 'Kto bol vynálezcom telegrafu?', 'Samuel Morse'),
('Dejiny', 3, 'Kde sa konala bitka pri Verdune?', 'Francúzsko'),
('Dejiny', 3, 'Kto bol vodcom národného hnutia v Indii?', 'Gandhi'),
('Dejiny', 3, 'Kedy bola zrušená otroctvo v Británii?', '1833'),
('Dejiny', 3, 'Kto viedol revolúciu v Rusku?', 'Lenin'),
('Dejiny', 3, 'Kedy bola objavená Antarktída?', '1820'),
('Dejiny', 3, 'Kto bol posledným kráľom Francúzska?', 'Louis Philippe'),
('Dejiny', 3, 'Kedy došlo k padu Západorímskej ríše?', '476'),
('Dejiny', 3, 'Kto bol autorom "Mein Kampf"?', 'Hitler'),
('Dejiny', 3, 'Kedy bola prvá svetová vojna?', '1914'),
('Dejiny', 3, 'Kto bol zakladateľom Ottomanskej ríše?', 'Osman I'),
('Dejiny', 3, 'Kde sa nachádza Hadriánov múr?', 'Británia'),
('Dejiny', 3, 'Kto bol autorom "Vojny a mier"?', 'Tolstoj'),
('Dejiny', 3, 'Kedy bola objavená teória relativity?', '1905'),
('Dejiny', 3, 'Kto bol posledným panovníkom Ruského impéria?', 'Nikola II'),
('Dejiny', 3, 'Kde sa nachádza Palác Potala?', 'Tibet'),
('Dejiny', 3, 'Kto bol vodcom Francúzskej revolúcie?', 'Robespierre'),
('Dejiny', 3, 'Kedy bola objavená Amerika Kolumbom?', '1492'),
('Dejiny', 3, 'Kto bol prvým prezidentom Talianska?', 'Enrico De Nicola'),
('Dejiny', 3, 'Kedy sa konala bitka pri Hastings?', '1066'),
('Dejiny', 3, 'Kto bol známy ako "Železný kancelár"?', 'Bismarck'),
('Dejiny', 3, 'Kedy bola založená NATO?', '1949'),
('Dejiny', 3, 'Kto bol prvým prezidentom Južnej Afriky?', 'Nelson Mandela'),
('Dejiny', 3, 'Kedy bola založená Rímska republika?', '509 pred Kr.'),
('Dejiny', 3, 'Kto napísal "Božskú komédiu"?', 'Dante'),
('Dejiny', 3, 'Kde sa nachádza historické mesto Machu Picchu?', 'Peru'),
('Dejiny', 3, 'Kto bol vodcom talianskej fašistickej strany?', 'Mussolini'),
('Dejiny', 3, 'Kedy bola vyhlásená Deklarácia práv človeka?', '1789'),
('Dejiny', 3, 'Kto bol zakladateľom dynastie Romanov?', 'Mikhail Romanov'),
('Dejiny', 3, 'Kedy sa konala bitka pri Trafalgare?', '1805'),
('Dejiny', 3, 'Kto napísal "Pán prsteňov"?', 'Tolkien'),
('Dejiny', 3, 'Kto bol prvým rímskym cisárom?', 'Augustus'),
('Dejiny', 3, 'Kde sa narodil Karl Marx?', 'Pruská'),
('Dejiny', 3, 'Kedy bola založená UNESCO?', '1945'),
('Dejiny', 3, 'Kto bol vodcom boja za občianske práva?', 'King'),
('Dejiny', 3, 'Kedy bola založená Veľká Británia?', '1707'),
('Dejiny', 3, 'Kto bol posledným cisárom Rakúska?', 'Karl I'),
('Dejiny', 3, 'Kedy bola založená Rímska ríša?', '27 pred Kr.'),
('Dejiny', 3, 'Kto bol posledným kráľom Anglicka?', 'Charles I'),
('Dejiny', 3, 'Kde sa nachádza socha Slobody?', 'New York'),
('Dejiny', 3, 'Kedy sa konala bitka pri Stalingrade?', '1942'),
('Dejiny', 3, 'Kto bol prvým prezidentom Turecka?', 'Mustafa Kemal'),
('Dejiny', 3, 'Kedy bola objavená teória relativity?', '1905'),
('Dejiny', 3, 'Kto bol zakladateľom dynastie Ming?', 'Zhu Yuanzhang'),
('Filmy a seriály', 1, 'Kto hrá hlavnú postavu v filme Titanic?', 'DiCaprio'),
('Filmy a seriály', 1, 'Aký je názov populárneho seriálu o rodine Simpsonovcov?', 'Simpsonovci'),
('Filmy a seriály', 1, 'Ktorý film získal Oscara za najlepší film v roku 2020?', 'Parasite'),
('Filmy a seriály', 1, 'Aký je názov najznámejšieho čarodejníka v literatúre a filmoch?', 'Harry Potter'),
('Filmy a seriály', 1, 'Kto režíroval film Jurský park?', 'Spielberg'),
('Filmy a seriály', 1, 'Aký je názov filmu, kde hrá Keanu Reeves postavu menom Neo?', 'Matrix'),
('Filmy a seriály', 1, 'Kto je hlavný antagonist v sérii filmov o Batmanovi?', 'Joker'),
('Filmy a seriály', 1, 'Aký je názov filmovej série o agentovi Jamesovi Bondovi?', 'Bond'),
('Filmy a seriály', 1, 'Kto je autorom knižnej predlohy pre film Hra o tróny?', 'Martin'),
('Filmy a seriály', 1, 'Aký je názov populárneho seriálu o zločinoch v New Yorku?', 'Zločin'),
('Filmy a seriály', 1, 'Kto hral rolu Toma Hanka vo filme Forrest Gump?', 'Hanks'),
('Filmy a seriály', 1, 'Aký je názov filmu o robotovi menom WALL-E?', 'WALL-E'),
('Filmy a seriály', 1, 'Kto sa stal najmladším hercom, ktorý získal Oscara?', 'Tatum'),
('Filmy a seriály', 1, 'Aký je názov filmu, kde sa objavuje postava Indiana Jones?', 'Indiana'),
('Filmy a seriály', 1, 'Kto hral rolu Holly Golightly vo filme Raňajky u Tiffanyho?', 'Hepburn'),
('Filmy a seriály', 1, 'Aký je názov filmu o superhrdinovi menom Spider-Man?', 'Spider-Man'),
('Filmy a seriály', 1, 'Kto hrá postavu Katniss Everdeen v Hladových hrách?', 'Lawrence'),
('Filmy a seriály', 1, 'Aký je názov animovaného filmu o levovi menom Simba?', 'Lev'),
('Filmy a seriály', 1, 'Kto je hlavným protagonistom v seriáli Breaking Bad?', 'White'),
('Filmy a seriály', 1, 'Aký je názov filmu o rodine Addamsovcov?', 'Addams'),
('Filmy a seriály', 1, 'Kto režíroval film Pán prsteňov?', 'Jackson'),
('Filmy a seriály', 1, 'Aký je názov filmu o vojne medzi Avatarmi?', 'Avatar'),
('Filmy a seriály', 1, 'Kto hral rolu Jacka Sparrowa v Pirátoch z Karibiku?', 'Depp'),
('Filmy a seriály', 1, 'Aký je názov filmu, kde vystupuje postava Forrest Gump?', 'Forrest'),
('Filmy a seriály', 1, 'Kto je autorom knižnej predlohy pre Twilight?', 'Meyer'),
('Filmy a seriály', 1, 'Aký je názov kultového hororu od Alfreda Hitchcocka?', 'Psycho'),
('Filmy a seriály', 1, 'Kto hral rolu Harryho Pottera vo filmovej sérii?', 'Radcliffe'),
('Filmy a seriály', 1, 'Aký je názov romantickej komédie s Meg Ryan a Tomom Hanksom?', 'Sleepless'),
('Filmy a seriály', 1, 'Kto je autorom populárnej série kníh o detektívovi Sherlockovi Holmesovi?', 'Doyle'),
('Filmy a seriály', 1, 'Aký je názov filmu o skupine priateľov v New Yorku?', 'Priatelia'),
('Filmy a seriály', 1, 'Kto hral hlavnú postavu vo filme Gladiátor?', 'Crowe'),
('Filmy a seriály', 1, 'Aký je názov animovaného filmu o rybe menom Nemo?', 'Nemo'),
('Filmy a seriály', 1, 'Kto režíroval film Pulp Fiction?', 'Tarantino'),
('Filmy a seriály', 1, 'Aký je názov filmu, kde hrá Robert Downey Jr. Iron Mana?', 'Iron'),
('Filmy a seriály', 1, 'Kto je hlavnou postavou v seriáli Priatelia?', 'Rachel'),
('Filmy a seriály', 1, 'Aký je názov filmu o superhrdinovi menom Thor?', 'Thor'),
('Filmy a seriály', 1, 'Kto hral vo filme Rýchlo a zbesilo?', 'Diesel'),
('Filmy a seriály', 1, 'Aký je názov animovaného filmu o dinosaure?', 'Dinosaurus'),
('Filmy a seriály', 1, 'Kto je autorom série kníh o Harrym Potterovi?', 'Rowling'),
('Filmy a seriály', 1, 'Aký je názov série filmov o Star Wars?', 'Star Wars'),
('Filmy a seriály', 1, 'Kto hral rolu v seriáli Hra o tróny?', 'Harington'),
('Filmy a seriály', 1, 'Aký je názov filmu, kde sa objavuje postava Sherlock Holmes?', 'Holmes'),
('Filmy a seriály', 1, 'Kto režíroval film Avatar?', 'Cameron'),
('Filmy a seriály', 1, 'Aký je názov filmu s postavou Jacka Dawson?', 'Titanic'),
('Filmy a seriály', 1, 'Kto hral rolu v seriáli Zúfalé manželky?', 'Huffman'),
('Filmy a seriály', 1, 'Aký je názov populárneho animovaného filmu o hračkách?', 'Hračky'),
('Filmy a seriály', 1, 'Kto je hlavným hrdinom v filme Iron Man?', 'Tony Stark'),
('Filmy a seriály', 1, 'Aký je názov populárneho seriálu s postavou Walter White?', 'Breaking Bad'),
('Filmy a seriály', 1, 'Kto hral hlavnú postavu v snímke Gladiátor?', 'Maximus'),
('Filmy a seriály', 1, 'Aký je názov filmu s modrými humanoidmi?', 'Avatar'),
('Filmy a seriály', 1, 'Kto je autorom série kníh o Percy Jacksonovi?', 'Rick Riordan'),
('Filmy a seriály', 1, 'Aký je názov filmu s postavou Jacka Dawson?', 'Titanic'),
('Filmy a seriály', 1, 'Kto režíroval film Inception?', 'Christopher Nolan'),
('Filmy a seriály', 1, 'Aký je názov seriálu o detektívovi, ktorý žije v Londýne?', 'Sherlock'),
('Filmy a seriály', 1, 'Kto hral rolu vo filme Múmia?', 'Brendan Fraser'),
('Filmy a seriály', 1, 'Aký je názov animovaného filmu o aute menom Lightning McQueen?', 'Cars'),
('Filmy a seriály', 1, 'Kto je hlavnou postavou v Harrym Potterovi?', 'Harry Potter'),
('Filmy a seriály', 1, 'Aký je názov filmu s postavou Elsa?', 'Frozen'),
('Filmy a seriály', 1, 'Kto hral rolu v populárnom seriáli Priatelia?', 'Jennifer Aniston'),
('Filmy a seriály', 1, 'Aký je názov filmu o superhrdinovi menom Batman?', 'Batman'),
('Filmy a seriály', 1, 'Kto je hlavným antagonistom v filme Avengers?', 'Thanos'),
('Filmy a seriály', 1, 'Aký je názov filmu s postavou Rocky Balboa?', 'Rocky'),
('Filmy a seriály', 1, 'Kto režíroval film Forrest Gump?', 'Robert Zemeckis'),
('Filmy a seriály', 1, 'Aký je názov populárneho sci-fi seriálu o vesmíre?', 'Star Trek'),
('Filmy a seriály', 1, 'Kto hral rolu v animovanom filme Shrek?', 'Mike Myers'),
('Filmy a seriály', 1, 'Aký je názov filmu o superhrdinovi menom Wonder Woman?', 'Wonder Woman'),
('Filmy a seriály', 1, 'Kto je autorom knižnej predlohy pre Pána prsteňov?', 'J.R.R. Tolkien'),
('Filmy a seriály', 1, 'Aký je názov filmu o skupine priateľov v New Yorku?', 'Friends'),
('Filmy a seriály', 1, 'Kto hral vo filme Jurský park?', 'Sam Neill'),
('Filmy a seriály', 1, 'Aký je názov filmu s postavou Hannibala Lectera?', 'Silence of the Lambs'),
('Filmy a seriály', 1, 'Kto režíroval film Hladné hry?', 'Gary Ross'),
('Filmy a seriály', 1, 'Aký je názov populárneho seriálu o kriminálnych prípadoch?', 'CSI'),
('Filmy a seriály', 1, 'Kto hral rolu v snímke Statečné srdce?', 'Mel Gibson'),
('Filmy a seriály', 1, 'Aký je názov filmu s postavou Mufasa?', 'Lion King'),
('Filmy a seriály', 1, 'Kto je hlavným hrdinom v snímke Kniha džunglí?', 'Mowgli'),
('Filmy a seriály', 1, 'Aký je názov populárneho hororu od Stephen Kinga?', 'It'),
('Filmy a seriály', 1, 'Kto hral vo filme Matrix?', 'Keanu Reeves'),
('Filmy a seriály', 1, 'Aký je názov filmu o rodine z Fantastických zverov?', 'Fantastic Beasts'),
('Filmy a seriály', 1, 'Kto režíroval film Zelená kniha?', 'Peter Farrelly'),
('Filmy a seriály', 1, 'Aký je názov animovaného filmu o medveďovi Paddington?', 'Paddington'),
('Filmy a seriály', 1, 'Kto hral vo filme Vojna svetov?', 'Tom Cruise'),
('Filmy a seriály', 1, 'Aký je názov seriálu o zločinoch v Los Angeles?', 'L.A. Law'),
('Filmy a seriály', 1, 'Kto je hlavným hrdinom v snímke Agent bez minulosti?', 'Jason Bourne'),
('Filmy a seriály', 1, 'Aký je názov filmu o malom chlapcovi menom Kevin?', 'Home Alone'),
('Filmy a seriály', 1, 'Kto režíroval film Siedmy pocit?', 'David Fincher'),
('Filmy a seriály', 1, 'Aký je názov filmu o rodine Incredibles?', 'The Incredibles'),
('Filmy a seriály', 1, 'Kto hral vo filme Diabol nosí Pradu?', 'Meryl Streep'),
('Filmy a seriály', 1, 'Aký je názov populárneho sci-fi filmu s postavou Ripley?', 'Alien'),
('Filmy a seriály', 1, 'Kto je hlavnou postavou v snímke Terminátor?', 'Sarah Connor'),
('Filmy a seriály', 1, 'Aký je názov filmu o podvodníkovi menom Catch Me If You Can?', 'Catch Me'),
('Filmy a seriály', 1, 'Kto hral vo filme Skryté čísla?', 'Taraji P. Henson'),
('Filmy a seriály', 1, 'Aký je názov filmu, kde hrá postavu Meridy?', 'Brave'),
('Filmy', 1, 'Aký je názov série filmov o čarodejníckej škole?', 'Harry Potter'),
('Filmy', 1, 'Kto je hlavný protagonista vo filme Terminátor?', 'John Connor'),
('Filmy', 1, 'Kto hral rolu v snímke Rýchlo a zbesilo?', 'Vin Diesel'),
('Filmy', 1, 'Aký je názov animovaného filmu o pandovi?', 'Kung Fu Panda'),
('Filmy', 1, 'Kto je režisérom filmu Star Wars?', 'George Lucas'),
('Filmy', 1, 'Aký je názov filmu s postavou Jacka Dawson?', 'Titanic'),
('Filmy', 1, 'Kto hral hlavnú postavu vo filme Joker?', 'Joaquin Phoenix'),
('Filmy', 1, 'Aký je názov filmu o superhrdinoch z Marvelu?', 'Avengers'),
('Filmy', 1, 'Kto je autorom knižnej predlohy pre film Duna?', 'Frank Herbert'),
('Filmy', 1, 'Aký je názov populárneho muzikálu o priateľstve?', 'Mamma Mia'),
('Filmy', 1, 'Kto hral vo filme Hľadá sa Nemo?', 'Albert Brooks'),
('Filmy', 1, 'Aký je názov filmu o rodine Incredibles?', 'The Incredibles'),
('Filmy', 1, 'Kto je hlavným hrdinom v snímke Život je krásny?', 'Guido Orefice'),
('Filmy', 1, 'Aký je názov filmu o chlapcovi, ktorý sa stane superhrdinom?', 'Kôň'),
('Filmy', 1, 'Kto hral rolu v snímke Smečka?', 'Gina Rodriguez'),
('Filmy', 1, 'Aký je názov populárneho sci-fi filmu s robotmi?', 'Transformers'),
('Filmy', 1, 'Kto hral vo filme Zelená kniha?', 'Mahershala Ali'),
('Filmy', 1, 'Aký je názov filmu s postavou E.T.?', 'E.T.'),
('Filmy', 1, 'Kto je hlavnou postavou v snímke Gladiátor?', 'Maximus'),
('Filmy', 1, 'Aký je názov animovaného filmu o krysa?', 'Ratatouille'),
('Filmy', 1, 'Kto hral rolu v filme Všetko o Adamovi?', 'Jesse Eisenberg'),
('Filmy', 1, 'Aký je názov filmu o záchrane Titanic?', 'Titanic'),
('Filmy', 1, 'Kto je autorom ságy Hra o tróny?', 'George R.R. Martin'),
('Filmy', 1, 'Aký je názov hororového filmu s názvom Kúzlo?', 'The Conjuring'),
('Filmy', 1, 'Kto hral vo filme Muži v čiernom?', 'Will Smith'),
('Filmy', 1, 'Aký je názov filmu o ceste do stredu Zeme?', 'Journey'),
('Filmy', 1, 'Kto režíroval film Pán prsteňov?', 'Peter Jackson'),
('Filmy', 1, 'Aký je názov filmu o rodine Addamsovcov?', 'The Addams Family'),
('Filmy', 1, 'Kto hral postavu Tonyho Starka?', 'Robert Downey Jr.'),
('Filmy', 1, 'Aký je názov filmu o superhrdinoch z DC?', 'Justice League'),
('Filmy', 1, 'Kto režíroval film V hlavnej úlohe?', 'Richard Linklater'),
('Filmy', 1, 'Aký je názov filmu o dobrodružstve v džungli?', 'Jungle Cruise'),
('Filmy', 1, 'Kto hral vo filme Základný inštinkt?', 'Sharon Stone'),
('Filmy', 1, 'Aký je názov romantického filmu s názvom Notting Hill?', 'Notting Hill'),
('Filmy', 1, 'Kto je hlavnou postavou vo filme Tetris?', 'Henk Rogers'),
('Filmy', 1, 'Aký je názov filmu o lietajúcom sloníkovi?', 'Dumbo'),
('Filmy', 1, 'Kto hral vo filme Zelená kniha?', 'Viggo Mortensen'),
('Filmy', 1, 'Aký je názov animovaného filmu o dinosauroch?', 'The Good Dinosaur'),
('Filmy', 1, 'Kto je autorom komiksov o Spider-Manovi?', 'Stan Lee'),
('Filmy', 1, 'Aký je názov filmu s postavou Zorra?', 'The Mask of Zorro'),
('Filmy', 1, 'Kto hral vo filme Piráti z Karibiku?', 'Johnny Depp'),
('Filmy', 1, 'Aký je názov filmu o rodine Incredibles?', 'Incredibles'),
('Filmy', 1, 'Kto hral v snímke Jurský park?', 'Sam Neill'),
('Filmy', 1, 'Aký je názov filmu o superhrdinovi menom Deadpool?', 'Deadpool'),
('Filmy', 1, 'Kto režíroval film Čarodejnice?', 'Robert Eggers'),
('Filmy', 1, 'Aký je názov filmu s postavou Elsa?', 'Frozen'),
('Filmy', 1, 'Kto hral vo filme Dobrý Will Hunting?', 'Matt Damon'),
('Filmy', 1, 'Aký je názov filmu o záchrane vojakov?', 'Saving Private Ryan'),
('Filmy', 1, 'Kto hral vo filme Tenet?', 'John David Washington'),
('Filmy', 1, 'Aký je názov filmu o legendárnom boxerovi?', 'Rocky'),
('Filmy', 1, 'Kto je autorom knihy pre film Hladné hry?', 'Suzanne Collins'),
('Filmy a seriály', 2, 'Kto hral postavu Jacka Ryan v série filmov?', 'Harrison Ford'),
('Filmy a seriály', 2, 'Aký je názov filmu o preteku s časom?', 'Päť dní'),
('Filmy a seriály', 2, 'Kto režíroval film Skryté čísla?', 'Theodore Melfi'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinoch z Avengers?', 'Avengers'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Gladiátor?', 'Russell Crowe'),
('Filmy a seriály', 2, 'Aký je názov filmovej série o čarodejníckom učni?', 'Harry Potter'),
('Filmy a seriály', 2, 'Kto hral rolu vo filme Hľadá sa Nemo?', 'Albert Brooks'),
('Filmy a seriály', 2, 'Aký je názov animovaného filmu o malom chlapcovi?', 'Coco'),
('Filmy a seriály', 2, 'Kto hral vo filme Zelená kniha?', 'Mahershala Ali'),
('Filmy a seriály', 2, 'Aký je názov populárneho sci-fi filmu s robotom?', 'Terminator'),
('Filmy a seriály', 2, 'Kto je hlavná postava v snímke Matrix?', 'Neo'),
('Filmy a seriály', 2, 'Aký je názov filmu o záchrane Titanic?', 'Titanic'),
('Filmy a seriály', 2, 'Kto režíroval film Všetko o Adamovi?', 'Ján Koleník'),
('Filmy a seriály', 2, 'Aký je názov filmu s postavou Harryho Pottera?', 'Harry Potter'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Múmia?', 'Brendan Fraser'),
('Filmy a seriály', 2, 'Aký je názov populárneho seriálu o upíroch?', 'Upírske denníky'),
('Filmy a seriály', 2, 'Kto je hlavnou postavou v snímke Pán prsteňov?', 'Frodo'),
('Filmy a seriály', 2, 'Aký je názov filmu o vojenskej jednotke?', 'Zachráňte vojaka Ryana'),
('Filmy a seriály', 2, 'Kto hral vo filme Vojna svetov?', 'Tom Cruise'),
('Filmy a seriály', 2, 'Aký je názov animovaného filmu o medveďovi?', 'Paddington'),
('Filmy a seriály', 2, 'Kto režíroval film Avatar?', 'James Cameron'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdine?', 'Iron Man'),
('Filmy a seriály', 2, 'Kto hral vo filme Pán prsteňov?', 'Elijah Wood'),
('Filmy a seriály', 2, 'Aký je názov populárneho seriálu o detektívovi?', 'Sherlock'),
('Filmy a seriály', 2, 'Kto je autorom knižnej predlohy pre film Duna?', 'Frank Herbert'),
('Filmy a seriály', 2, 'Aký je názov filmu o priateľstve?', 'The Intouchables'),
('Filmy a seriály', 2, 'Kto hral vo filme Amélia z Montmartru?', 'Audrey Tautou'),
('Filmy a seriály', 2, 'Aký je názov populárneho muzikálu o priateľstve?', 'Wicked'),
('Filmy a seriály', 2, 'Kto režíroval film Čarodejnice?', 'Robert Zemeckis'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinoch z DC?', 'Justice League'),
('Filmy a seriály', 2, 'Kto hral vo filme Kráľovná?', 'Helen Mirren'),
('Filmy a seriály', 2, 'Aký je názov filmu o záchrane vojakov?', 'Hrdinovia'),
('Filmy a seriály', 2, 'Kto hral vo filme Dobrý Will Hunting?', 'Matt Damon'),
('Filmy a seriály', 2, 'Aký je názov filmu o dobrodruhovi?', 'Indiana Jones'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Zelená kniha?', 'Viggo Mortensen'),
('Filmy a seriály', 2, 'Aký je názov filmu o dinosaurách?', 'Jurský park'),
('Filmy a seriály', 2, 'Kto je hlavný protagonista vo filme Terminátor?', 'Arnold Schwarzenegger'),
('Filmy a seriály', 2, 'Aký je názov filmu s postavou Raymana?', 'Rayman'),
('Filmy a seriály', 2, 'Kto hral vo filme Tancuj, ako sa ti páči?', 'Hugh Jackman'),
('Filmy a seriály', 2, 'Aký je názov romantického filmu o plávaní?', 'Hladný'),
('Filmy a seriály', 2, 'Kto režíroval film Kráľovná?', 'Stephen Frears'),
('Filmy a seriály', 2, 'Aký je názov filmu o záchrane Titanic?', 'Titanic'),
('Filmy a seriály', 2, 'Kto hral vo filme Základný inštinkt?', 'Sharon Stone'),
('Filmy a seriály', 2, 'Aký je názov filmu o malom chlapcovi?', 'Kevin'),
('Filmy a seriály', 2, 'Kto režíroval film Múmia?', 'Stephen Sommers'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinovi menom Deadpool?', 'Deadpool'),
('Filmy a seriály', 2, 'Kto hral postavu vo filme Muži v čiernom?', 'Will Smith'),
('Filmy a seriály', 2, 'Aký je názov animovaného filmu o dinosauroch?', 'Pravekí'),
('Filmy a seriály', 2, 'Kto je hlavným hrdinom v snímke Agent bez minulosti?', 'Matt Damon'),
('Filmy a seriály', 2, 'Kto je režisérom filmu Inception?', 'Nolan');