INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Mýtológia', 1, 'Kto je bohyňou morskej fauny?', 'Amfitrité'),
('Mýtológia', 1, 'Kto je bohyňou spravodlivosti?', 'Themis'),
('Mýtológia', 1, 'Kto je bohyňa vojny?', 'Athéna'),
('Mýtológia', 1, 'Kto je bohom moci?', 'Zeus'),
('Mýtológia', 1, 'Kto je bohom lásky?', 'Eros'),
('Mýtológia', 1, 'Kto je bohom predkov?', 'Hades'),
('Mýtológia', 1, 'Kto je bohyňou neba?', 'Gaia'),
('Mýtológia', 1, 'Kto je bohom múz?', 'Apollón'),
('Mýtológia', 1, 'Kto je bohom času?', 'Chronos'),
('Mýtológia', 1, 'Kto je bohyňa vína?', 'Bacchus'),
('Mýtológia', 1, 'Kto je bohom búrky?', 'Zeus'),
('Mytológia', 1, 'Kto je bohom morských vĺn?', 'Poseidón'),
('Mytológia', 1, 'Kto je bohyňou múdrosti?', 'Athéna'),
('Mytológia', 1, 'Kto je bohom ohňa?', 'Hefestos'),
('Mytológia', 1, 'Kto je kráľom bohov v rímskej mytológii?', 'Jupiter'),
('Mytológia', 1, 'Kto je bohyňa lásky v gréckej mytológii?', 'Afrodíta'),
('Mytológia', 1, 'Kto je bohom smrteľných?', 'Hádés'),
('Mytológia', 1, 'Kto je bohyňou vína?', 'Dionýzos'),
('Mytológia', 1, 'Kto je bohom neba?', 'Uranus'),
('Mytológia', 1, 'Kto je bohyňa plodnosti v rímskej mytológii?', 'Ceres'),
('Mytológia', 1, 'Kto je bohyňou rodiny?', 'Héra'),
('Mytológia', 1, 'Kto je bohom poľovníctva?', 'Artemis'),
('Mytológia', 1, 'Kto je bohom búrky v gréckej mytológii?', 'Zeus'),
('Mytológia', 1, 'Kto je bohom umenia a poézie?', 'Apollón'),
('Mytológia', 1, 'Kto je bohyňa slnka?', 'Helios'),
('Mytológia', 1, 'Kto je bohom vojenskej stratégie?', 'Ares'),
('Mytológia', 1, 'Kto je bohyňa morskej hladiny?', 'Amfitríté'),
('Mytológia', 1, 'Kto je bohom cesty a obchodovania?', 'Hermes'),
('Mytológia', 1, 'Kto je bohom podsvetia v gréckej mytológii?', 'Hádés'),
('Mytológia', 1, 'Kto je bohyňa osudu?', 'Moiry'),
('Mytológia', 1, 'Kto je bohyňa moci?', 'Héra'),
('Mytológia', 1, 'Kto je bohom chaosu?', 'Khaos'),
('Mytológia', 1, 'Kto je bohyňou noci?', 'Nyx'),
('Mytológia', 1, 'Kto je bohom svetla v gréckej mytológii?', 'Apollón'),
('Mytológia', 1, 'Kto je bohyňa jari?', 'Persefona'),
('Mytológia', 1, 'Kto je bohyňa smrti?', 'Thanatos'),
('Mytológia', 1, 'Kto je bohom múz?', 'Apollón'),
('Mytológia', 1, 'Kto je bohyňa krásy?', 'Afrodíta'),
('Mytológia', 1, 'Kto je bohom zeme?', 'Gaiá'),
('Mytológia', 1, 'Kto je bohyňa plodnosti v gréckej mytológii?', 'Deméter'),
('Mytológia', 1, 'Kto je bohom neviditeľnosti?', 'Hádés'),
('Mytológia', 1, 'Kto je bohyňa vojny v rímskej mytológii?', 'Bellona'),
('Mytológia', 1, 'Kto je bohom šťastia?', 'Fortúna'),
('Mytológia', 1, 'Kto je bohyňa osudu v rímskej mytológii?', 'Parcae'),
('Mytológia', 1, 'Kto je bohom vojny?', 'Mars'),
('Mytológia', 1, 'Kto je bohyňa múz?', 'Kalliope'),
('Mytológia', 1, 'Kto je bohom múz a inšpirácie?', 'Apollón'),
('Mytológia', 1, 'Kto je bohyňa zákona?', 'Temis'),
('Mytológia', 1, 'Kto je bohom prírodných síl?', 'Pan'),
('Mytológia', 1, 'Kto je bohyňa lásky v rímskej mytológii?', 'Venus'),
('Mytológia', 1, 'Kto je bohom pomsty?', 'Nemesis'),
('Mytológia', 1, 'Kto je bohyňa zeme?', 'Gaia'),
('Mytológia', 1, 'Kto je bohom času?', 'Chronos'),
('Mytológia', 1, 'Kto je bohyňa jari v gréckej mytológii?', 'Persefona'),
('Mytológia', 1, 'Kto je bohom vojny v rímskej mytológii?', 'Mars'),
('Mytológia', 1, 'Kto je bohyňa zeme v rímskej mytológii?', 'Tellus'),
('Mytológia', 1, 'Kto je bohom zveri?', 'Artemis'),
('Mytológia', 1, 'Kto je bohyňa šťastia?', 'Fortuna'),
('Mytológia', 1, 'Kto je bohom zeme v gréckej mytológii?', 'Gaia'),
('Mytológia', 2, 'Kto je bohom podsvetia v gréckej mytológii?', 'Hades'),
('Mytológia', 2, 'Kto je bohyňa plodnosti v rímskej mytológii?', 'Ceres'),
('Mytológia', 2, 'Kto je bohom oblohy v gréckej mytológii?', 'Zeus'),
('Mytológia', 2, 'Kto je bohyňa lásky v severskej mytológii?', 'Freyja'),
('Mytológia', 2, 'Kto je bohom svetla v rímskej mytológii?', 'Apollo'),
('Mytológia', 2, 'Ktorá bohyně je známa svojou krásou?', 'Venus'),
('Mytológia', 2, 'Kto je bohom zeme v rímskej mytológii?', 'Tellus'),
('Mytológia', 2, 'Kto je bohom smrti v gréckej mytológii?', 'Thanatos'),
('Mytológia', 2, 'Kto je bohyňou vojny v gréckej mytológii?', 'Athena'),
('Mytológia', 2, 'Kto je bohom morských hlbín?', 'Poseidón'),
('Mytológia', 2, 'Kto je bohyňa jari v rímskej mytológii?', 'Flora'),
('Mytológia', 2, 'Kto je bohom vína v rímskej mytológii?', 'Bacchus'),
('Mytológia', 2, 'Kto je bohyňa múdrosti v gréckej mytológii?', 'Athena'),
('Mytológia', 2, 'Kto je bohom vojenského umenia?', 'Ares'),
('Mytológia', 2, 'Kto je bohyňa noci v gréckej mytológii?', 'Nyx'),
('Mytológia', 2, 'Ktorý hrdina je známy svojim bojom s hydrou?', 'Herakles'),
('Mytológia', 2, 'Kto je bohom chaosu v gréckej mytológii?', 'Erebus'),
('Mytológia', 2, 'Kto je bohyňa osudu v gréckej mytológii?', 'Moiry'),
('Mytológia', 2, 'Kto je bohom vzduchu?', 'Aeolus'),
('Mytológia', 2, 'Kto je bohyňa plodnosti v gréckej mytológii?', 'Demetra'),
('Mytológia', 2, 'Kto je bohom múz a umenia?', 'Apollón'),
('Mytológia', 2, 'Kto je božstvo zeme v severskej mytológii?', 'Jörmungandr'),
('Mytológia', 2, 'Kto je bohyňa lásky v severskej mytológii?', 'Freyja'),
('Mytológia', 2, 'Kto je bohom vína v gréckej mytológii?', 'Dionýsos'),
('Mytológia', 2, 'Kto je bohyňa smrti?', 'Thanatos'),
('Mytológia', 2, 'Kto je bohom plodnosti v rímskej mytológii?', 'Faunus'),
('Mytológia', 2, 'Kto je bohyňa múdrosti v rímskej mytológii?', 'Minerva'),
('Mytológia', 2, 'Kto je bohom vetra?', 'Boreas'),
('Mytológia', 2, 'Kto je bohyňa spravodlivosti?', 'Dike'),
('Mytológia', 2, 'Kto je bohom slnka?', 'Helios'),
('Mytológia', 2, 'Kto je bohyňa osudu v rímskej mytológii?', 'Fortuna'),
('Mytológia', 2, 'Kto je bohom búrky v rímskej mytológii?', 'Jupiter'),
('Mytológia', 2, 'Kto je bohyňa plodnosti a úrody?', 'Ceres'),
('Mytológia', 2, 'Kto je bohom vojny v severskej mytológii?', 'Týr'),
('Mytológia', 2, 'Kto je bohyňa noci v severskej mytológii?', 'Nótt'),
('Mytológia', 2, 'Kto je bohom zeme?', 'Gaia'),
('Mytológia', 2, 'Kto je bohyňa krásy v rímskej mytológii?', 'Venus'),
('Mytológia', 2, 'Kto je bohom srdca?', 'Eros'),
('Mytológia', 2, 'Kto je bohyňa vína?', 'Bacchus'),
('Mytológia', 2, 'Kto je bohom osudu?', 'Moira'),
('Mytológia', 2, 'Kto je bohyňa múz v rímskej mytológii?', 'Musa'),
('Mytológia', 2, 'Kto je bohom plodnosti v severskej mytológii?', 'Freyr'),
('Mytológia', 2, 'Kto je bohom času v gréckej mytológii?', 'Chronos'),
('Mytológia', 2, 'Kto je bohyňa vojny a múdrosti?', 'Athena'),
('Mytológia', 2, 'Kto je bohom moci?', 'Zeus'),
('Mytológia', 2, 'Kto je bohyňa smrti v gréckej mytológii?', 'Persefona'),
('Mytológia', 2, 'Kto je bohom vína v gréckej mytológii?', 'Dionýsos'),
('Mytológia', 2, 'Kto je bohyňa slnka v rímskej mytológii?', 'Sol'),
('Mytológia', 2, 'Kto je bohom morskej fauny?', 'Poseidón'),
('Mytológia', 2, 'Kto je bohyňa moci v gréckej mytológii?', 'Hera'),
('Mytológia', 2, 'Kto je bohom vojny v gréckej mytológii?', 'Ares'),
('Mytológia', 2, 'Kto je bohyňa krásy a lásky?', 'Afrodite'),
('Mytológia', 2, 'Kto je bohom morských vĺn?', 'Poseidón'),
('Mytológia', 2, 'Kto je bohyňa jari?', 'Persefona'),
('Mytológia', 2, 'Kto je bohom rýchlosti v rímskej mytológii?', 'Mercurius'),
('Mytológia', 2, 'Kto je bohyňou plodnosti v gréckej mytológii?', 'Demetra'),
('Mytológia', 2, 'Kto je bohom smrti v rímskej mytológii?', 'Thanatos'),
('Mytológia', 2, 'Kto je bohyňa vína v gréckej mytológii?', 'Dionýza'),
('Mytológia', 2, 'Kto je bohom morských vĺn v gréckej mytológii?', 'Poseidón'),
('Mytológia', 2, 'Kto je bohyňa múdrosti v rímskej mytológii?', 'Minerva'),
('Mytológia', 2, 'Kto je bohom ochrany v gréckej mytológii?', 'Hermes'),
('Mytológia', 2, 'Kto je bohyňa noci v rímskej mytológii?', 'Nyx'),
('Mytológia', 2, 'Kto je bohom vojenskej sily v gréckej mytológii?', 'Ares'),
('Mytológia', 2, 'Kto je bohyňa krásy a lásky v gréckej mytológii?', 'Afrodíté'),
('Mytológia', 2, 'Kto je bohom múz v rímskej mytológii?', 'Apollón'),
('Mytológia', 2, 'Kto je bohyňa jari v gréckej mytológii?', 'Persefóna'),
('Mytológia', 2, 'Kto je bohom hromu v rímskej mytológii?', 'Jupiter'),
('Mytológia', 2, 'Kto je bohyňa osudu v gréckej mytológii?', 'Moiry'),
('Mytológia', 2, 'Kto je bohom slnka v rímskej mytológii?', 'Sol'),
('Mytológia', 2, 'Kto je bohyňa úrody v rímskej mytológii?', 'Ceres'),
('Mytológia', 2, 'Kto je bohom chaosu v rímskej mytológii?', 'Erebus'),
('Mytológia', 2, 'Kto je bohyňa vína v rímskej mytológii?', 'Bacchus'),
('Mytológia', 2, 'Kto je bohom umenia a poézie v gréckej mytológii?', 'Apollón'),
('Mytológia', 2, 'Kto je bohyňa múdrosti v severskej mytológii?', 'Frigg'),
('Mytológia', 2, 'Kto je bohom morských hlbín?', 'Nereus'),
('Mytológia', 2, 'Kto je bohyňa smrti v severskej mytológii?', 'Hel'),
('Mytológia', 2, 'Kto je bohom cnosti v gréckej mytológii?', 'Hérakles'),
('Mytológia', 2, 'Kto je bohyňa plodnosti v rímskej mytológii?', 'Venus'),
('Mytológia', 2, 'Kto je bohom vojny a múdrosti?', 'Athéna'),
('Mytológia', 2, 'Kto je bohyňa materskej lásky?', 'Rhea'),
('Mytológia', 2, 'Kto je bohom obchodu v rímskej mytológii?', 'Mercurius'),
('Mytológia', 2, 'Kto je bohyňa noci v gréckej mytológii?', 'Selene'),
('Mytológia', 2, 'Kto je bohom slnka v gréckej mytológii?', 'Helios'),
('Mytológia', 2, 'Kto je bohyňa lásky v severskej mytológii?', 'Freya'),
('Mytológia', 2, 'Kto je bohom zemetrasenia?', 'Poseidón'),
('Mytológia', 2, 'Kto je bohyňa plodnosti v severskej mytológii?', 'Jörð'),
('Mytológia', 2, 'Kto je bohom podsvetia v rímskej mytológii?', 'Pluto'),
('Mytológia', 2, 'Kto je bohyňa jari v rímskej mytológii?', 'Flóra'),
('Mytológia', 2, 'Kto je bohom svetla v gréckej mytológii?', 'Apollo'),
('Mytológia', 2, 'Kto je bohyňa úrody v gréckej mytológii?', 'Demetra'),
('Mytológia', 2, 'Kto je bohom búrky v severskej mytológii?', 'Thor'),
('Mytológia', 2, 'Kto je bohyňa rodiny v rímskej mytológii?', 'Vesta'),
('Mytológia', 2, 'Kto je bohom plodnosti v gréckej mytológii?', 'Priapus'),
('Mytológia', 2, 'Kto je bohyňa múz v gréckej mytológii?', 'Calliope'),
('Mytológia', 2, 'Kto je bohom poézie v rímskej mytológii?', 'Apollo'),
('Mytológia', 2, 'Kto je bohyňa spravodlivosti v gréckej mytológii?', 'Themis'),
('Mytológia', 2, 'Kto je bohom vína v severskej mytológii?', 'Bacchus'),
('Mytológia', 2, 'Kto je bohyňa noci v severskej mytológii?', 'Nótt'),
('Mytológia', 2, 'Kto je bohom vojenskej stratégie v gréckej mytológii?', 'Ares'),
('Mytológia', 2, 'Kto je bohyňa krásy v severskej mytológii?', 'Sif'),
('Mytológia', 2, 'Kto je bohom morskej fauny?', 'Poseidón'),
('Mytológia', 2, 'Kto je bohyňa múdrosti v rímskej mytológii?', 'Minerva'),
('Mytológia', 2, 'Kto je bohom neba v rímskej mytológii?', 'Uranus'),
('Mytológia', 2, 'Kto je bohyňa osudu v gréckej mytológii?', 'Moiry'),
('Mytológia', 3, 'Kto je bohom múdrosti v severskej mytológii?', 'Odín'),
('Mytológia', 3, 'Ktoré zviera je spájané s bohynou Artemis?', 'Jelen'),
('Mytológia', 3, 'Aké je meno boha podsvetia v gréckej mytológii?', 'Hádés'),
('Mytológia', 3, 'Kto je bohom času v gréckej mytológii?', 'Chronos'),
('Mytológia', 3, 'Kto je bohyňou vojny v severskej mytológii?', 'Freyja'),
('Mytológia', 3, 'Kto je bohom búrky v severskej mytológii?', 'Thor'),
('Mytológia', 3, 'Kto je matkou boha Apolla?', 'Leto'),
('Mytológia', 3, 'Ktorý hrdina sa plavil na lodi Argo?', 'Jason'),
('Mytológia', 3, 'Kto je bohom lásky v severskej mytológii?', 'Freyr'),
('Mytológia', 3, 'Kto je bohyňou plodnosti v gréckej mytológii?', 'Demeter'),
('Mytológia', 3, 'Kto je bohom umenia a poézie v rímskej mytológii?', 'Apollón'),
('Mytológia', 3, 'Kto je bohyňa spravodlivosti v rímskej mytológii?', 'Justitia'),
('Mytológia', 3, 'Kto je bohom chaosu v severskej mytológii?', 'Loki'),
('Mytológia', 3, 'Kto je bohom vína v gréckej mytológii?', 'Dionýsos'),
('Mytológia', 3, 'Kto je bohyňa lásky a krásy v gréckej mytológii?', 'Afrodita'),
('Mytológia', 3, 'Kto je bohom smrti v gréckej mytológii?', 'Thanatos'),
('Mytológia', 3, 'Kto je bohyňa noci v gréckej mytológii?', 'Nyx'),
('Mytológia', 3, 'Kto je bohom morskej hladiny?', 'Poseidón'),
('Mytológia', 3, 'Kto je bohyňa jari v gréckej mytológii?', 'Persefona'),
('Mytológia', 3, 'Kto je bohom vína v rímskej mytológii?', 'Bacchus'),
('Mytológia', 3, 'Kto je bohyňa osudu v gréckej mytológii?', 'Moirai'),
('Mytológia', 3, 'Kto je bohom svetla v severskej mytológii?', 'Baldr'),
('Mytológia', 3, 'Kto je bohyňa múdrosti v rímskej mytológii?', 'Minerva'),
('Mytológia', 3, 'Kto je kráľom podsvetia v gréckej mytológii?', 'Hádés'),
('Mytológia', 3, 'Kto je bohom vojny v gréckej mytológii?', 'Ares'),
('Mytológia', 3, 'Ktorý hrdina sa postavil proti Chimére?', 'Bellerofontes'),
('Mytológia', 3, 'Kto je bohyňa morskej fauny?', 'Amfitríté'),
('Mytológia', 3, 'Kto je bohom ohňa a kováčstva?', 'Hefestos'),
('Mytológia', 3, 'Kto je bohyňa úrody v gréckej mytológii?', 'Demeter'),
('Mytológia', 3, 'Kto je bohom vojenskej stratégie?', 'Ares'),
('Mytológia', 3, 'Kto je bohyňa slnka v severskej mytológii?', 'Sól'),
('Mytológia', 3, 'Kto je bohom lásky v rímskej mytológii?', 'Cupid'),
('Mytológia', 3, 'Kto je bohyňa vína v gréckej mytológii?', 'Dionýza'),
('Mytológia', 3, 'Kto je bohom vzduchu v gréckej mytológii?', 'Éolus'),
('Mytológia', 3, 'Kto je bohyňa slnka v gréckej mytológii?', 'Helios'),
('Mytológia', 3, 'Kto je bohom morskej fauny v rímskej mytológii?', 'Neptún'),
('Mytológia', 3, 'Kto je kráľom bohov v rímskej mytológii?', 'Jupiter'),
('Mytológia', 3, 'Kto je bohyňa zeme v gréckej mytológii?', 'Gaia'),
('Mytológia', 3, 'Kto je bohom múz a inšpirácie?', 'Apollón'),
('Mytológia', 3, 'Kto je bohyňa krásy v gréckej mytológii?', 'Afrodita'),
('Mytológia', 3, 'Kto je bohom smrti v rímskej mytológii?', 'Orcus'),
('Mytológia', 3, 'Kto je bohyňa materskej lásky?', 'Rhea'),
('Mytológia', 3, 'Kto je bohom vojny v severskej mytológii?', 'Týr'),
('Mytológia', 3, 'Kto je bohyňa vína v rímskej mytológii?', 'Bacchus'),
('Mytológia', 3, 'Kto je bohom plodnosti v rímskej mytológii?', 'Faunus'),
('Mytológia', 3, 'Kto je bohyňa noci v severskej mytológii?', 'Nótt'),
('Mytológia', 3, 'Kto je bohom smrti v severskej mytológii?', 'Hel'),
('Mytológia', 3, 'Kto je bohyňa jari v severskej mytológii?', 'Idunn'),
('Mytológia', 3, 'Kto je bohom plodnosti v gréckej mytológii?', 'Priapus'),
('Mytológia', 3, 'Kto je bohom múz v severskej mytológii?', 'Bragi'),
('Mytológia', 3, 'Kto je bohyňa osudu v severskej mytológii?', 'Skuld'),
('Mytológia', 3, 'Kto je bohom múdrosti v severskej mytológii?', 'Odin'),
('Mytológia', 3, 'Kto je manželkou boha Hadesa?', 'Persefona'),
('Mytológia', 3, 'Kto je bohom chaosu v gréckej mytológii?', 'Khaos'),
('Mytológia', 3, 'Ktorý hrdina sa postavil proti Medúze?', 'Perzeus'),
('Mytológia', 3, 'Kto je bohom poézie a umenia?', 'Apollo'),
('Mytológia', 3, 'Kto je bohyňa lásky a krásy v rímskej mytológii?', 'Venus'),
('Mytológia', 3, 'Kto je bohom vojenskej stratégie v rímskej mytológii?', 'Mars'),
('Mytológia', 3, 'Kto je bohom zeme v severskej mytológii?', 'Njord'),
('Mytológia', 3, 'Kto je bohyňa úrody v gréckej mytológii?', 'Demetra'),
('Mytológia', 3, 'Kto je bohom vína a osláv v rímskej mytológii?', 'Bacchus'),
('Mytológia', 3, 'Kto je bohyňa lásky v gréckej mytológii?', 'Aphrodite'),
('Mytológia', 3, 'Kto je bohom vojenského umenia v gréckej mytológii?', 'Ares'),
('Mytológia', 3, 'Kto je bohyňa noci v severskej mytológii?', 'Nótt'),
('Mytológia', 3, 'Kto je bohom hromu v severskej mytológii?', 'Thor'),
('Mytológia', 3, 'Kto je bohyňa plodnosti v rímskej mytológii?', 'Ceres'),
('Mytológia', 3, 'Kto je bohom podsvetia v severskej mytológii?', 'Hel'),
('Mytológia', 3, 'Kto je bohyňa osudu v severskej mytológii?', 'Norny'),
('Mytológia', 3, 'Kto je bohom času v rímskej mytológii?', 'Chronos'),
('Mytológia', 3, 'Kto je bohyňa múdrosti v gréckej mytológii?', 'Athena'),
('Mytológia', 3, 'Kto je bohom obchodu a zisku?', 'Hermes'),
('Mytológia', 3, 'Kto je bohyňa pomsty v gréckej mytológii?', 'Nemesis'),
('Mytológia', 3, 'Kto je bohom svetla v severskej mytológii?', 'Baldr'),
('Mytológia', 3, 'Kto je bohyňa jari v severskej mytológii?', 'Freyja'),
('Mytológia', 3, 'Kto je bohom predkov v gréckej mytológii?', 'Hades'),
('Mytológia', 3, 'Kto je bohyňa krásy v rímskej mytológii?', 'Venus'),
('Mytológia', 3, 'Kto je bohom morskej fauny v gréckej mytológii?', 'Poseidón'),
('Mytológia', 3, 'Kto je bohyňa vína v severskej mytológii?', 'Skaði'),
('Mytológia', 3, 'Kto je bohom plodnosti v gréckej mytológii?', 'Dionysos'),
('Mytológia', 3, 'Kto je bohyňa múz v severskej mytológii?', 'Sól'),
('Mytológia', 3, 'Kto je bohom vojny v severskej mytológii?', 'Týr'),
('Mytológia', 3, 'Kto je bohyňa smrti v gréckej mytológii?', 'Thanatos'),
('Mytológia', 3, 'Kto je bohom morských hlbín v gréckej mytológii?', 'Poseidón'),
('Mytológia', 3, 'Kto je bohyňa lásky v severskej mytológii?', 'Freyja'),
('Mytológia', 3, 'Kto je bohom hromu v gréckej mytológii?', 'Zeus'),
('Mytológia', 3, 'Kto je bohyňa spravodlivosti v rímskej mytológii?', 'Justitia'),
('Mytológia', 3, 'Kto je bohom vína v gréckej mytológii?', 'Dionysos'),
('Mytológia', 3, 'Kto je bohyňa jari v gréckej mytológii?', 'Persephone'),
('Mytológia', 3, 'Kto je bohom srdca v gréckej mytológii?', 'Eros'),
('Mytológia', 3, 'Kto je bohyňa noci v gréckej mytológii?', 'Nyx'),
('Mytológia', 3, 'Kto je bohom vína v severskej mytológii?', 'Bacchus'),
('Mytológia', 3, 'Kto je bohyňa múdrosti v severskej mytológii?', 'Frigg'),
('Mytológia', 3, 'Kto je bohom vojenskej stratégie v gréckej mytológii?', 'Athena'),
('Mytológia', 3, 'Kto je bohyňa krásy v severskej mytológii?', 'Freyja'),
('Mytológia', 3, 'Kto je bohom morských vĺn v gréckej mytológii?', 'Poseidón'),
('Mytológia', 3, 'Kto je bohyňa osudu v rímskej mytológii?', 'Fortuna'),
('Mytológia', 3, 'Kto je bohom času v severskej mytológii?', 'Kronos'),
('Mytológia', 3, 'Kto je bohom vína v severskej mytológii?', 'Baldur'),
('Mytológia', 3, 'Kto je matkou boha Thora?', 'Jörð'),
('Mytológia', 3, 'Kto je bohom liečenia a medicíny v gréckej mytológii?', 'Asklepios'),
('Mytológia', 3, 'Ktorý hrdina sa plavil na lodi Argo?', 'Jason'),
('Mytológia', 3, 'Kto je bohom vojny v hinduistickej mytológii?', 'Kártikéja'),
('Mytológia', 3, 'Kto je bohyňou plodnosti v severskej mytológii?', 'Frigg'),
('Mytológia', 3, 'Kto je bohom chaosu v severskej mytológii?', 'Loki'),
('Mytológia', 3, 'Kto je bohyňa múdrosti a vojny v gréckej mytológii?', 'Athéna'),
('Mytológia', 3, 'Kto je bohom podsvetia v severskej mytológii?', 'Hel'),
('Mytológia', 3, 'Kto je vládcom podsvetia v gréckej mytológii?', 'Hades'),
('Mytológia', 3, 'Kto je bohom srdca v gréckej mytológii?', 'Eros'),
('Mytológia', 3, 'Kto je bohyňou osudu v gréckej mytológii?', 'Moiry'),
('Mytológia', 3, 'Kto je bohom múz a poézie?', 'Apollón'),
('Mytológia', 3, 'Kto je bohyňou lásky a krásy v rímskej mytológii?', 'Venus'),
('Mytológia', 3, 'Kto je bohom vojny a smrti v severskej mytológii?', 'Týr'),
('Mytológia', 3, 'Kto je bohyňa plodnosti a úrody v rímskej mytológii?', 'Ceres'),
('Mytológia', 3, 'Kto je bohom slnka a svetla v severskej mytológii?', 'Baldr'),
('Mytológia', 3, 'Kto je bohyňa noci v gréckej mytológii?', 'Nyx'),
('Mytológia', 3, 'Kto je bohom vojenského umenia v rímskej mytológii?', 'Mars'),
('Mytológia', 3, 'Kto je bohyňa smrti v severskej mytológii?', 'Hel'),
('Mytológia', 3, 'Kto je bohom vína a osláv v gréckej mytológii?', 'Dionýsos'),
('Mytológia', 3, 'Kto je bohyňa krásy a lásky v gréckej mytológii?', 'Afrodíté'),
('Mytológia', 3, 'Kto je bohom zeme v severskej mytológii?', 'Njörd'),
('Mytológia', 3, 'Kto je bohyňa lásky v hinduistickej mytológii?', 'Rati'),
('Mytológia', 3, 'Kto je bohyňa múz a inšpirácie v gréckej mytológii?', 'Kalliope'),
('Mytológia', 3, 'Kto je bohom ohňa a kováčstva v gréckej mytológii?', 'Hefestos'),
('Mytológia', 3, 'Kto je bohyňa lásky a krásy v severskej mytológii?', 'Sif'),
('Mytológia', 3, 'Kto je bohom vojny v japonskej mytológii?', 'Hachiman'),
('Mytológia', 3, 'Kto je bohyňou plodnosti v gréckej mytológii?', 'Deméter'),
('Mytológia', 3, 'Kto je bohom smrti v egyptských mýtoch?', 'Anubis'),
('Mytológia', 3, 'Kto je bohyňa jari v gréckej mytológii?', 'Persefona'),
('Mytológia', 3, 'Kto je bohom slnka v egyptských mýtoch?', 'Ra'),
('Mytológia', 3, 'Kto je bohyňa úrody v gréckej mytológii?', 'Deméter'),
('Mytológia', 3, 'Kto je bohom vojny v mexickej mytológii?', 'Huitzilopochtli'),
('Mytológia', 3, 'Kto je bohyňa múdrosti v egyptských mýtoch?', 'Seshat'),
('Mytológia', 3, 'Kto je bohom zeme v gréckej mytológii?', 'Gaia'),
('Mytológia', 3, 'Kto je bohyňa osudu v severskej mytológii?', 'Norny'),
('Mytológia', 3, 'Kto je bohom múz v rímskej mytológii?', 'Apollo'),
('Mytológia', 3, 'Kto je bohyňa noci v egyptských mýtoch?', 'Nut'),
('Mytológia', 3, 'Kto je bohom chaosu v gréckej mytológii?', 'Erebus'),
('Mytológia', 3, 'Kto je bohyňa smrti a vína v ruských mýtoch?', 'Marzanna'),
('Mytológia', 3, 'Kto je bohom vojny a vlády?', 'Ares'),
('Mytológia', 3, 'Kto je bohyňa krásy v rímskej mytológii?', 'Venus'),
('Mytológia', 3, 'Kto je bohom múz a umenia v rímskej mytológii?', 'Apollo'),
('Mytológia', 3, 'Kto je bohyňa vína v indickej mytológii?', 'Durga'),
('Mytológia', 3, 'Kto je bohom smrti v gréckej mytológii?', 'Thanatos'),
('Mytológia', 3, 'Kto je bohyňa lásky a plodnosti v hindských mýtoch?', 'Lakšmí'),
('Mytológia', 3, 'Kto je bohom vojny v africkej mytológii?', 'Ogun'),
('Mytológia', 3, 'Kto je bohyňa múdrosti v gréckej mytológii?', 'Athena'),
('Náboženstvo', 1, 'Kto je zakladateľom kresťanstva?', 'Ježiš Kristus'),
('Náboženstvo', 1, 'Ktorá kniha je považovaná za svätú v islame?', 'Korán'),
('Náboženstvo', 1, 'Aký deň sa oslavuje Veľká noc?', 'Nedeľa'),
('Náboženstvo', 1, 'Kto je hlavným bohom v hinduizme?', 'Brahma'),
('Náboženstvo', 1, 'Akým jazykom je napísaná Biblia?', 'Hebrejčina'),
('Náboženstvo', 1, 'Aký je symbol kresťanstva?', 'Kríž'),
('Náboženstvo', 1, 'Aké náboženstvo sa zakladá na učeniach Budhu?', 'Buddhizmus'),
('Náboženstvo', 1, 'Kto je prorok v islame?', 'Mohamed'),
('Náboženstvo', 1, 'Kto bol Mojžiš?', 'Prorok'),
('Náboženstvo', 1, 'Aké je najrozšírenejšie náboženstvo na svete?', 'Kresťanstvo'),
('Náboženstvo', 1, 'Ktorý sviatok oslavujú Židia na pamiatku úniku z Egypta?', 'Pesach'),
('Náboženstvo', 1, 'Ktorá postava je známa ako "otec národov" v islame?', 'Abraham'),
('Náboženstvo', 1, 'Ako sa volá indický festival svetiel?', 'Diwali'),
('Náboženstvo', 1, 'Ktorá kniha je základom judaizmu?', 'Tóra'),
('Náboženstvo', 1, 'Kto je najvyššou autoritou v katolíckej cirkvi?', 'Pápež'),
('Náboženstvo', 1, 'Aký je názov modlitby moslimov?', 'Salát'),
('Náboženstvo', 1, 'Kto napísal knihu "Kniha mŕtvych"?', 'Egypt'),
('Náboženstvo', 1, 'Aké sú štyri pravdy v buddhizme?', 'Štyri'),
('Náboženstvo', 1, 'Aký je názov najväčšej kresťanskej cirkvi?', 'Katolícka'),
('Náboženstvo', 1, 'Ktorý deň v týždni je zasvätený v judaizme?', 'Šabat'),
('Náboženstvo', 1, 'Aká je hlavná modlitba v judaizme?', 'Šema'),
('Náboženstvo', 1, 'Ktorý náboženský text obsahuje "Bhagavad Gítu"?', 'Mahábhárata'),
('Náboženstvo', 1, 'Aký je názov islamského pôstu?', 'Ramadán'),
('Náboženstvo', 1, 'Kto je bohom vojny v gréckej mytológii?', 'Ares'),
('Náboženstvo', 1, 'Ako sa volá duchovný vodca v budhizme?', 'Dalajláma'),
('Náboženstvo', 1, 'Ktoré mesto je považované za sväté v islame?', 'Mekka'),
('Náboženstvo', 1, 'Aký je názov modlitby v kresťanstve?', 'Otče náš'),
('Náboženstvo', 1, 'Kto je bohom múdrosti v hinduizme?', 'Sarasvati'),
('Náboženstvo', 1, 'Aký je názov kresťanského sviatku narodenia Ježiša?', 'Vianoce'),
('Náboženstvo', 1, 'Kto je zakladateľom islamu?', 'Mohamed'),
('Náboženstvo', 1, 'Aký je názov svätého miesta v Jeruzaleme?', 'Západná zeď'),
('Náboženstvo', 1, 'Ktorá kniha je považovaná za svätú v hinduizme?', 'Védy'),
('Náboženstvo', 1, 'Kto je bohom lásky v gréckej mytológii?', 'Eros'),
('Náboženstvo', 1, 'Aký je názov náboženského sviatku oslavujúceho pôst?', 'Ramadán'),
('Náboženstvo', 1, 'Kto napísal "Knihu mŕtvych"?', 'Egypt'),
('Náboženstvo', 1, 'Aký je hlavný symbol buddhizmu?', 'Lotus'),
('Náboženstvo', 1, 'Kto je bohom hromu v severskej mytológii?', 'Thor'),
('Náboženstvo', 1, 'Aká je najposvätnejšia kniha v kresťanstve?', 'Biblia'),
('Náboženstvo', 1, 'Aký je názov najstaršieho náboženstva na svete?', 'Hinduizmus'),
('Náboženstvo', 1, 'Kto je autorom "Talmudu"?', 'Rabíni'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid'),
('Náboženstvo', 1, 'Ktorá postava je považovaná za matku Ježiša?', 'Mária'),
('Náboženstvo', 1, 'Kto je bohom slnka v egyptskom náboženstve?', 'Ra'),
('Náboženstvo', 1, 'Kto je považovaný za posledného proroka v islame?', 'Mohamed'),
('Náboženstvo', 1, 'Aké je najväčšie náboženstvo v Indii?', 'Hinduizmus'),
('Náboženstvo', 1, 'Kto je považovaný za zakladateľa buddhizmu?', 'Šákjamuni'),
('Náboženstvo', 1, 'Ktorý sviatok oslavujú kresťania na pamiatku ukrižovania Ježiša?', 'Veľký piatok'),
('Náboženstvo', 1, 'Aké je posolstvo "Desatora"?', 'Prikázania'),
('Náboženstvo', 1, 'Kto je hlavným bohom v kresťanstve?', 'Boh'),
('Náboženstvo', 1, 'Aký je názov moslimskej svätyne v Mekke?', 'Kaaba'),
('Náboženstvo', 1, 'Kto je zakladateľom judaizmu?', 'Abrahám'),
('Náboženstvo', 1, 'Aký je názov modlitby v islame?', 'Salát'),
('Náboženstvo', 1, 'Kto je považovaný za zakladateľa kresťanstva?', 'Ježiš'),
('Náboženstvo', 1, 'Ktorý sviatok oslavujú kresťania na Veľký piatok?', 'Ukrižovanie'),
('Náboženstvo', 1, 'Aký je názov svätého textu v hinduizme?', 'Védy'),
('Náboženstvo', 1, 'Kto je bohom vojny v hinduizme?', 'Krišna'),
('Náboženstvo', 1, 'Aký je názov kresťanského sviatku, ktorý oslavuje vzkriesenie?', 'Veľká noc'),
('Náboženstvo', 1, 'Kto je patrónom katolíckej cirkvi?', 'Pápež'),
('Náboženstvo', 1, 'Aký je názov základného textu buddhizmu?', 'Tripitaka'),
('Náboženstvo', 1, 'Aký deň sa považuje za sabat?', 'Sobota'),
('Náboženstvo', 1, 'Kde sa narodil Budha?', 'Nepál'),
('Náboženstvo', 1, 'Kto je bohom mŕtvych v egyptskom náboženstve?', 'Osiris'),
('Náboženstvo', 1, 'Aký je názov modlitby v hinduizme?', 'Pújdža'),
('Náboženstvo', 1, 'Kto je bohom lásky v hinduizme?', 'Káma'),
('Náboženstvo', 1, 'Aký je symbol judaizmu?', 'Hvězda'),
('Náboženstvo', 1, 'Kto je bohom múdrosti v gréckej mytológii?', 'Athéna'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Náboženstvo', 1, 'Kde sa nachádza Vatikán?', 'Rím'),
('Náboženstvo', 1, 'Kto je bohom zeme v gréckej mytológii?', 'Gaia'),
('Náboženstvo', 1, 'Aký je názov najstaršej kresťanskej cirkvi?', 'Apostolská'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje príchod Ducha Svätého?', 'Turíce'),
('Náboženstvo', 1, 'Kto je považovaný za prvého budhistu?', 'Budha'),
('Náboženstvo', 1, 'Aký je symbol kresťanstva?', 'Kríž'),
('Náboženstvo', 1, 'Kto je bohom slnka v hinduizme?', 'Surja'),
('Náboženstvo', 1, 'Aký je názov festivalu, ktorý oslavuje víťazstvo svetla nad tmou?', 'Diwali'),
('Náboženstvo', 1, 'Kto je posol boží v judaizme?', 'Mojžiš'),
('Náboženstvo', 1, 'Aký je názov židovskej modlitby?', 'Šema'),
('Náboženstvo', 1, 'Kto je zakladateľom šintoizmu?', 'Tenshi'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje príchod jari v hinduizme?', 'Holi'),
('Náboženstvo', 1, 'Kto je považovaný za proroka v judaizme?', 'Eliáš'),
('Náboženstvo', 1, 'Aký je názov veľkého rímskeho chrámu?', 'Pantheon'),
('Náboženstvo', 1, 'Kto je bohom múdrosti v egyptskom náboženstve?', 'Thovt'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje úrodu v judaizme?', 'Šavuot'),
('Náboženstvo', 1, 'Kto je bohom vojny v rímskej mytológii?', 'Mars'),
('Náboženstvo', 1, 'Aký je názov najvyššieho boha v hinduizme?', 'Brahman'),
('Náboženstvo', 1, 'Kto je patrónom remeselníkov v katolicizme?', 'Jozef'),
('Náboženstvo', 1, 'Aký je názov modlitby pred jedlom v judaizme?', 'Brachá'),
('Náboženstvo', 1, 'Kto je bohom chaosu v egyptskom náboženstve?', 'Seth'),
('Náboženstvo', 1, 'Aký je názov festivalu, ktorý oslavuje vďaku v USA?', 'Deň vďakyvzdania'),
('Náboženstvo', 1, 'Kto je matkou Ježiša?', 'Mária'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje pôst v katolicizme?', 'Pôst'),
('Náboženstvo', 1, 'Kto je bohom obchodu v gréckej mytológii?', 'Hermés'),
('Náboženstvo', 1, 'Aký je názov modlitby, ktorú čítajú moslimovia?', 'Ájátu'),
('Náboženstvo', 1, 'Kto je bohom smrti v hinduizme?', 'Šiva'),
('Náboženstvo', 1, 'Kto je patrónom detí v katolicizme?', 'Anjel'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje koniec pôstu?', 'Eid'),
('Náboženstvo', 1, 'Kto je zakladateľom šintoizmu?', 'Šinto'),
('Náboženstvo', 1, 'Ktorý deň je zasvätený v kresťanstve?', 'Nedeľa'),
('Náboženstvo', 1, 'Aký je názov modlitby v katolicizme?', 'Otče náš'),
('Náboženstvo', 1, 'Kto je považovaný za proroka v islame?', 'Mojžiš'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Náboženstvo', 1, 'Kto je bohom lásky v rímskej mytológii?', 'Venuša'),
('Náboženstvo', 1, 'Kto je zakladateľom taoizmu?', 'Lao-c'''),
('Náboženstvo', 1, 'Aký je názov modlitby v judaizme?', 'Šema'),
('Náboženstvo', 1, 'Kto je bohom plodnosti v gréckej mytológii?', 'Démétér'),
('Náboženstvo', 1, 'Kto je bohom vojny v egyptskom náboženstve?', 'Seth'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje pôst v judaizme?', 'Jom Kipur'),
('Náboženstvo', 1, 'Kto je patrónom umelcov v katolicizme?', 'Svätý Lukáš'),
('Náboženstvo', 1, 'Kto je bohom mŕtvych v hinduizme?', 'Yama'),
('Náboženstvo', 1, 'Kto je bohom múdrosti v rímskej mytológii?', 'Merkúr'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid'),
('Náboženstvo', 1, 'Kto je bohom slnka v rímskej mytológii?', 'Apollo'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje pôst v budhizme?', 'Uposatha'),
('Náboženstvo', 1, 'Kto je bohom moci v hinduizme?', 'Šiva'),
('Náboženstvo', 1, 'Kto je patrónom lekárov v katolicizme?', 'Svätý Kozma'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje narodenie Ježiša?', 'Vianoce'),
('Náboženstvo', 1, 'Kto je bohom obchodu v hinduizme?', 'Lakšmí'),
('Náboženstvo', 1, 'Kto je bohom múdrosti v hinduizme?', 'Sarasvatí'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje príchod jari v judaizme?', 'Pesach'),
('Náboženstvo', 1, 'Kto je bohom zeme v hinduizme?', 'Prithvi'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje víťazstvo dobra nad zlom?', 'Dípaúvalí'),
('Náboženstvo', 1, 'Kto je bohom hromu v hinduizme?', 'Indra'),
('Náboženstvo', 1, 'Kto je patrónom detí v katolicizme?', 'Svätý Jozef'),
('Náboženstvo', 1, 'Aký je názov modlitby pred jedlom v katolicizme?', 'Benedikcia'),
('Náboženstvo', 1, 'Kto je bohom smrti v gréckej mytológii?', 'Thanatos'),
('Náboženstvo', 1, 'Kto je bohom víťazstva v hinduizme?', 'Ganéša'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje úrodu v hinduizme?', 'Makar Sankranti'),
('Náboženstvo', 1, 'Kto je bohom liečenia v gréckej mytológii?', 'Asklepios'),
('Náboženstvo', 1, 'Kto je patrónom remeselníkov v gréckej mytológii?', 'Hefest'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Buddha Jayanti'),
('Náboženstvo', 1, 'Kto je bohom vína v rímskej mytológii?', 'Bacchus'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje slávnosť v katolicizme?', 'Kvetná nedeľa'),
('Náboženstvo', 1, 'Kto je bohom plodnosti v hinduizme?', 'Kartikeya'),
('Náboženstvo', 1, 'Kto je patrónom umelcov v gréckej mytológii?', 'Apollón'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje radosť?', 'Diwali'),
('Náboženstvo', 1, 'Kto je bohom neba v gréckej mytológii?', 'Zeus'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje príchod nového roka v judaizme?', 'Rosh Hashaná'),
('Náboženstvo', 1, 'Kto je bohom slnka v azteckej mytológii?', 'Huitzilopochtli'),
('Náboženstvo', 1, 'Kto je bohom vojny v budhizme?', 'Brahmá'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje zber úrody v judaizme?', 'Sukkot'),
('Náboženstvo', 1, 'Kto je bohom vánku v hinduizme?', 'Vayu'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje pamiatku zosnulých?', 'Dušičky'),
('Náboženstvo', 1, 'Kto je bohom lásky v budhizme?', 'Amita'),
('Náboženstvo', 1, 'Aký je názov sviatku, ktorý oslavuje vieru?', 'Duchovný deň'),
('Náboženstvo', 2, 'Kto napísal "Knihu židovských zákonov"?', 'Maimonides'),
('Náboženstvo', 2, 'Aké je hlavné mesto Vatikánu?', 'Vatikán'),
('Náboženstvo', 2, 'Ktoré náboženstvo vzniklo na Indickom subkontinente?', 'Hinduizmus'),
('Náboženstvo', 2, 'Kto je považovaný za zakladateľa protestantizmu?', 'Martin Luther'),
('Náboženstvo', 2, 'Aký je názov modlitby v katolíckej cirkvi?', 'Otče náš'),
('Náboženstvo', 2, 'Ktoré náboženstvo je známe učením Lao-c'' ?', 'Taoizmus'),
('Náboženstvo', 2, 'Kto je bohom vojny v rímskej mytológii?', 'Mars'),
('Náboženstvo', 2, 'Ktorý deň začína židovský sabat?', 'Piatok'),
('Náboženstvo', 2, 'Aký je názov posvätnej knihy sikhizmu?', 'Guru Granth'),
('Náboženstvo', 2, 'Kto je zakladateľom Bahá''í?', 'Bahá''u''lláh'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje oslavu svetla?', 'Diwali'),
('Náboženstvo', 2, 'Kto je bohom múdrosti v hinduizme?', 'Saraswati'),
('Náboženstvo', 2, 'Ktorý sviatok oslavujú kresťania na Veľkú noc?', 'Veľkonočné sviatky'),
('Náboženstvo', 2, 'Kto je považovaný za zakladateľa zoroastriánstva?', 'Zoroaster'),
('Náboženstvo', 2, 'Aký je názov modlitby, ktorú recitujú moslimovia pred jedlom?', 'Bismillah'),
('Náboženstvo', 2, 'Ktorý deň sa považuje za svätý v kresťanstve?', 'Nedeľa'),
('Náboženstvo', 2, 'Kto je bohom smrti v egyptskom náboženstve?', 'Anubis'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod jari?', 'Holi'),
('Náboženstvo', 2, 'Kto je hlavným bohom gréckej mytológie?', 'Zeus'),
('Náboženstvo', 2, 'Ktorá kniha je považovaná za svätú v hinduizme?', 'Védy'),
('Náboženstvo', 2, 'Kto je zakladateľom rehole jezuitov?', 'Ignác z Loyoly'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid al-Fitr'),
('Náboženstvo', 2, 'Kto je bohom lásky v gréckej mytológii?', 'Eros'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje úrodu v hinduizme?', 'Pongal'),
('Náboženstvo', 2, 'Kto je bohom slnka v aztéckej mytológii?', 'Huitzilopochtli'),
('Náboženstvo', 2, 'Kto je patrónom umelcov v katolicizme?', 'Svätý Lukáš'),
('Náboženstvo', 2, 'Aký je názov židovského sviatku oslavujúceho oslobodenie od otroctva?', 'Pesach'),
('Náboženstvo', 2, 'Kto je bohom obchodu v rímskej mytológii?', 'Merkúr'),
('Náboženstvo', 2, 'Aký je názov posvätnej knihy šintoizmu?', 'Kojiki'),
('Náboženstvo', 2, 'Kto je duchovným vodcom v sikhizme?', 'Guru'),
('Náboženstvo', 2, 'Ktorý deň sa považuje za svätý v islame?', 'Piatok'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje narodenie Ježiša?', 'Vianoce'),
('Náboženstvo', 2, 'Kto je zakladateľom scientológie?', 'L. Ron Hubbard'),
('Náboženstvo', 2, 'Aký je názov modlitby v budhizme?', 'Metta'),
('Náboženstvo', 2, 'Kto je bohom plodnosti v rímskej mytológii?', 'Ceres'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje pamiatku zosnulých?', 'Dušičky'),
('Náboženstvo', 2, 'Kto je považovaný za prvého pápeža?', 'Svätý Peter'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje zber úrody v hinduizme?', 'Onam'),
('Náboženstvo', 2, 'Kto je bohom vánku v gréckej mytológii?', 'Eurus'),
('Náboženstvo', 2, 'Aký je názov festivalu, ktorý oslavuje víťazstvo dobra nad zlom?', 'Dussehra'),
('Náboženstvo', 2, 'Kto je bohom múdrosti v severskej mytológii?', 'Odín'),
('Náboženstvo', 2, 'Ktorý sviatok oslavujú kresťania na Pamiatku všetkých svätých?', 'Dušičky'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod Ducha Svätého?', 'Zoslanie Ducha'),
('Náboženstvo', 2, 'Kto je bohom liečenia v gréckej mytológii?', 'Asklepios'),
('Náboženstvo', 2, 'Aký je názov modlitby, ktorú recitujú katolíci?', 'Zdravas Mária'),
('Náboženstvo', 2, 'Kto je bohom plodnosti v rímskej mytológii?', 'Venus'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje víťazstvo svetla?', 'Hanukkah');