INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Filmy a seriály', 2, 'Aký je názov hororu od Stepena Kinga?', 'To'),
('Filmy a seriály', 2, 'Kto hrá Superman vo filme Man of Steel?', 'Cavill'),
('Filmy a seriály', 2, 'Aký je názov populárneho seriálu o zločinech?', 'CSI'),
('Filmy a seriály', 2, 'Kto hral v snímke Vynaliezavá Princezná?', 'Anderson'),
('Filmy a seriály', 2, 'Ktorý film sa zaoberá ženou s psychickými problémami?', 'Black Swan'),
('Filmy a seriály', 2, 'Kto je autorom knižnej predlohy pre film Duna?', 'Herbert'),
('Filmy a seriály', 2, 'Aký je názov filmu s robotom menom Chappie?', 'Chappie'),
('Filmy a seriály', 2, 'Kto hral v snímke Hľadá sa Dory?', 'Ellen'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinoch z Avengers?', 'Infinity War'),
('Filmy a seriály', 2, 'Kto režíroval film Gladiátor?', 'Scott'),
('Filmy a seriály', 2, 'Aký je názov filmu, kde hrá Tom Cruise agenta?', 'Mission Impossible'),
('Filmy a seriály', 2, 'Kto je hlavnou postavou vo filme Matrix?', 'Neo'),
('Filmy a seriály', 2, 'Aký je názov filmu o priateľstve medzi psom a chlapcom?', 'Milo'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Dobrý Will Hunting?', 'Damon'),
('Filmy a seriály', 2, 'Aký je názov populárneho muzikálu o láske?', 'Mamma Mia'),
('Filmy a seriály', 2, 'Kto je hlavným antagonistom v snímke Joker?', 'Perry'),
('Filmy a seriály', 2, 'Aký je názov filmu o vianočných tradíciách?', 'Elf'),
('Filmy a seriály', 2, 'Kto hral vo filme Vykúpenie z väznice Shawshank?', 'Freeman'),
('Filmy a seriály', 2, 'Aký je názov filmu, kde sa objavuje postava Thor?', 'Thor'),
('Filmy a seriály', 2, 'Kto hral v populárnom seriáli The Office?', 'Carell'),
('Filmy a seriály', 2, 'Aký je názov filmu o kráľovi Leonovi?', 'Lion King'),
('Filmy a seriály', 2, 'Kto je autorom knižnej predlohy pre film Harry Potter?', 'Rowling'),
('Filmy a seriály', 2, 'Aký je názov filmu o odvahe a priateľstve?', 'The Help'),
('Filmy a seriály', 2, 'Kto hral vo filme Láska cez internet?', 'Ryan'),
('Filmy a seriály', 2, 'Aký je názov filmu s postavou Zorra?', 'Zorro'),
('Filmy a seriály', 2, 'Kto je hlavným hrdinom vo filme Smečka?', 'Hugh'),
('Filmy a seriály', 2, 'Aký je názov populárneho hororu s duchmi?', 'Insidious'),
('Filmy a seriály', 2, 'Kto hral vo filme Zelená kniha?', 'Ali'),
('Filmy a seriály', 2, 'Aký je názov filmu o vojne v Iraku?', 'American Sniper'),
('Filmy a seriály', 2, 'Kto režíroval film Mad Max?', 'Miller'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinoch z DC?', 'Aquaman'),
('Filmy a seriály', 2, 'Kto hral vo filme Na druhej strane?', 'Hanks'),
('Filmy a seriály', 2, 'Aký je názov filmu o podvodníkovi?', 'Catch Me'),
('Filmy a seriály', 2, 'Kto je hlavným protagonistom v snímke Piráti z Karibiku?', 'Sparrow'),
('Filmy a seriály', 2, 'Aký je názov filmu o záchrane Titanic?', 'Titanic'),
('Filmy a seriály', 2, 'Kto hral vo filme Hľadá sa Nemo?', 'Ellen'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinoch z Marvelu?', 'Avengers'),
('Filmy a seriály', 2, 'Kto režíroval film Zelená kniha?', 'Farrelly'),
('Filmy a seriály', 2, 'Aký je názov filmu o priateľstve?', 'Stand By Me'),
('Filmy a seriály', 2, 'Kto hral vo filme Múmia?', 'Fraser'),
('Filmy a seriály', 2, 'Aký je názov filmu s postavou Meridy?', 'Brave'),
('Filmy a seriály', 2, 'Kto hral vo filme Batman?', 'Bale'),
('Filmy a seriály', 2, 'Aký je názov filmu o vojne medzi svetmi?', 'World War'),
('Filmy a seriály', 2, 'Kto hral v snímke Notting Hill?', 'Grant'),
('Filmy a seriály', 2, 'Aký je názov filmu s postavou Elsa?', 'Frozen'),
('Filmy a seriály', 2, 'Kto hral vo filme Matrix?', 'Reeves'),
('Filmy a seriály', 2, 'Aký je názov filmu o africkej savane?', 'The Lion'),
('Filmy a seriály', 2, 'Kto režíroval film Forest Gump?', 'Zemeckis'),
('Filmy a seriály', 2, 'Kto hral hlavnú postavu v snímke Gladiátor?', 'Russell Crowe'),
('Filmy a seriály', 2, 'Aký je názov série filmov o čarodejníckej škole?', 'Harry Potter'),
('Filmy a seriály', 2, 'Kto je hlavným antagonistom v snímke Avengers?', 'Thanos'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinoch z Marvelu?', 'Avengers'),
('Filmy a seriály', 2, 'Kto režíroval film Inception?', 'Christopher Nolan'),
('Filmy a seriály', 2, 'Aký je názov populárneho seriálu o rodine?', 'Modern Family'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Vykúpenie z väznice Shawshank?', 'Tim Robbins'),
('Filmy a seriály', 2, 'Aký je názov filmu o robotovi menom Chappie?', 'Chappie'),
('Filmy a seriály', 2, 'Kto hral vo filme Hľadá sa Dory?', 'Ellen DeGeneres'),
('Filmy a seriály', 2, 'Aký je názov filmu o záchrane vojakov?', 'Zachráňte vojaka Ryana'),
('Filmy a seriály', 2, 'Kto je hlavným hrdinom v snímke Tetris?', 'Tetris'),
('Filmy a seriály', 2, 'Aký je názov filmu o vojenskej jednotke?', 'Fúz'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Amélia?', 'Audrey Tautou'),
('Filmy a seriály', 2, 'Aký je názov filmu o priateľstve medzi psom a chlapcom?', 'Hachi'),
('Filmy a seriály', 2, 'Kto režíroval film Mad Max?', 'George Miller'),
('Filmy a seriály', 2, 'Aký je názov romantického filmu s názvom Notting Hill?', 'Notting Hill'),
('Filmy a seriály', 2, 'Kto hral hlavnú postavu vo filme Joker?', 'Joaquin Phoenix'),
('Filmy a seriály', 2, 'Aký je názov populárneho muzikálu o priateľstve?', 'Rent'),
('Filmy a seriály', 2, 'Kto hral vo filme Tenet?', 'John David Washington'),
('Filmy a seriály', 2, 'Aký je názov filmu o záchrane Titanic?', 'Titanic'),
('Filmy a seriály', 2, 'Kto je autorom knižnej predlohy pre film Duna?', 'Frank Herbert'),
('Filmy a seriály', 2, 'Aký je názov filmu o dobrodruhovi?', 'Indiana Jones'),
('Filmy a seriály', 2, 'Kto hral vo filme Diabol nosí Pradu?', 'Meryl Streep'),
('Filmy a seriály', 2, 'Aký je názov filmu o africkej savane?', 'Král lev'),
('Filmy a seriály', 2, 'Kto je hlavným hrdinom v snímke Smečka?', 'Liam Neeson'),
('Filmy a seriály', 2, 'Aký je názov filmu o vojne medzi svetmi?', 'War of the Worlds'),
('Filmy a seriály', 2, 'Kto režíroval film Gladiátor?', 'Ridley Scott'),
('Filmy a seriály', 2, 'Aký je názov populárneho hororu s duchmi?', 'Duch'),
('Filmy a seriály', 2, 'Kto hral postavu vo filme Muži v čiernom?', 'Will Smith'),
('Filmy a seriály', 2, 'Aký je názov filmu s postavou E.T.?', 'E.T.'),
('Filmy a seriály', 2, 'Kto hral vo filme Kráľovná?', 'Helen Mirren'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinoch z DC?', 'Justice League'),
('Filmy a seriály', 2, 'Kto hral vo filme Zelená kniha?', 'Mahershala Ali'),
('Filmy a seriály', 2, 'Aký je názov filmu o podvodníkovi?', 'Catch Me If You Can'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Statečné srdce?', 'Mel Gibson'),
('Filmy a seriály', 2, 'Aký je názov filmu o odvahe a priateľstve?', 'Hľadá sa Nemo'),
('Filmy a seriály', 2, 'Kto hral v populárnom seriáli The Office?', 'Steve Carell'),
('Filmy a seriály', 2, 'Aký je názov filmu o záchrane Titanic?', 'Titanic'),
('Filmy a seriály', 2, 'Kto režíroval film Hladné hry?', 'Gary Ross'),
('Filmy a seriály', 2, 'Aký je názov filmu o skupine priateľov?', 'Priatelia'),
('Filmy a seriály', 2, 'Kto hral vo filme Vojna svetov?', 'Tom Cruise'),
('Filmy a seriály', 2, 'Aký je názov filmu o vojne v Iraku?', 'American Sniper'),
('Filmy a seriály', 2, 'Kto hral rolu v snímke Dobrý Will Hunting?', 'Matt Damon'),
('Filmy a seriály', 2, 'Aký je názov filmu o chlapcovi menom Kevin?', 'Sám doma'),
('Filmy a seriály', 2, 'Kto hral hlavnú postavu v snímke Gladiátor?', 'Russell Crowe'),
('Filmy a seriály', 2, 'Aký je názov filmu o superhrdinovi menom Deadpool?', 'Deadpool'),
('Filmy a seriály', 2, 'Kto je hlavným antagonistom v snímke Joker?', 'Thomas Wayne'),
('Filmy a seriály', 2, 'Aký je názov filmu s postavou Jacka Sparowa?', 'Piráti z Karibiku'),
('Filmy a seriály', 3, 'Kto režíroval film Memento?', 'Nolan'),
('Filmy a seriály', 3, 'Kto hrá hlavnú postavu vo filme Joker?', 'Phoenix'),
('Filmy a seriály', 3, 'Aký je názov filmu o osude lásky v New Yorku?', 'Her'),
('Filmy a seriály', 3, 'Kto je autorom knižnej predlohy pre film Duna?', 'Herbert'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde hrá Leonardo DiCaprio postavu Franka W. Abagnalea?', 'Catch Me'),
('Filmy a seriály', 3, 'Kto režíroval film Interstellar?', 'Nolan'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Lisbeth Salander?', 'Millennium'),
('Filmy a seriály', 3, 'Kto je hlavným protagonistom vo filme The Revenant?', 'DiCaprio'),
('Filmy a seriály', 3, 'Aký je názov filmu o vojine v Iraku s postavou Williama Jamesa?', 'Hurt Locker'),
('Filmy a seriály', 3, 'Kto hral vo filme The Sixth Sense?', 'Osment'),
('Filmy a seriály', 3, 'Aký je názov filmu o skupine preživších v zombie apokalypse?', 'The Walking'),
('Filmy a seriály', 3, 'Kto je autorom knižnej predlohy pre film Kniha džunglí?', 'Kipling'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde vystupuje postava Forrest Gump?', 'Gump'),
('Filmy a seriály', 3, 'Kto hral hlavnú postavu vo filme No Country for Old Men?', 'Bardem'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Tyler Durden?', 'Fight Club'),
('Filmy a seriály', 3, 'Kto režíroval film The Godfather?', 'Coppola'),
('Filmy a seriály', 3, 'Aký je názov filmu o detektívovi v Los Angeles?', 'Chinatown'),
('Filmy a seriály', 3, 'Kto hral vo filme The Social Network?', 'Eisenberg'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Amélie Poulain?', 'Amélie'),
('Filmy a seriály', 3, 'Kto je hlavným antagonistom vo filme The Dark Knight?', 'Joker'),
('Filmy a seriály', 3, 'Aký je názov filmu o cestovaní v čase s postavou Marty McFly?', 'Back to'),
('Filmy a seriály', 3, 'Kto režíroval film Saving Private Ryan?', 'Spielberg'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde hrá Tom Hanks postavu v lietadle?', 'Sully'),
('Filmy a seriály', 3, 'Kto hral vo filme The Shawshank Redemption?', 'Freeman'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Elizabeth Bennet?', 'Pride'),
('Filmy a seriály', 3, 'Kto režíroval film Black Swan?', 'Aronofsky'),
('Filmy a seriály', 3, 'Aký je názov filmu o vzostupe a páde rockovej kapely?', 'Bohemian'),
('Filmy a seriály', 3, 'Kto hral vo filme The Grand Budapest Hotel?', 'Fiennes'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Memento Mori?', 'Memento'),
('Filmy a seriály', 3, 'Kto je hlavným protagonistom vo filme Mad Max: Fury Road?', 'Hardy'),
('Filmy a seriály', 3, 'Aký je názov filmu o umení manipulácie?', 'The Prestige'),
('Filmy a seriály', 3, 'Kto režíroval film The Shape of Water?', 'Del Toro'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Lisbeth Salander?', 'The Girl'),
('Filmy a seriály', 3, 'Kto hral vo filme The Matrix?', 'Reeves'),
('Filmy a seriály', 3, 'Aký je názov filmu o poslednej bitke v Stalingrade?', 'Enemy at'),
('Filmy a seriály', 3, 'Kto režíroval film La La Land?', 'Chazelle'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Jack Torrance?', 'The Shining'),
('Filmy a seriály', 3, 'Kto hral vo filme Spotlight?', 'Ruffalo'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Clarice Starling?', 'Silence'),
('Filmy a seriály', 3, 'Kto je hlavným protagonistom vo filme Whiplash?', 'Teller'),
('Filmy a seriály', 3, 'Aký je názov filmu o cyklistickom preteku Tour de France?', 'The Program'),
('Filmy a seriály', 3, 'Kto režíroval film Memento?', 'Nolan'),
('Filmy a seriály', 3, 'Ktorý film má postavu Tylera Durdena?', 'Fight Club'),
('Filmy a seriály', 3, 'Kto hrá postavu Lisbeth Salander v The Girl with the Dragon Tattoo?', 'Rapace'),
('Filmy a seriály', 3, 'Kto režíroval film The Social Network?', 'Fincher'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa postava Marty McFly vracia v čase?', 'Back to the Future'),
('Filmy a seriály', 3, 'Kto hral hlavnú postavu vo filme No Country for Old Men?', 'Bardem'),
('Filmy a seriály', 3, 'Kto napísal knihu, na ktorej je založený film The Shawshank Redemption?', 'King'),
('Filmy a seriály', 3, 'Aký je názov filmu s postavou Willy Wonka?', 'Charlie and the Chocolate Factory'),
('Filmy a seriály', 3, 'Kto režíroval film The Godfather?', 'Coppola'),
('Filmy a seriály', 3, 'Kto hral hlavnú postavu vo filme The Revenant?', 'DiCaprio'),
('Filmy a seriály', 3, 'Ktorý film získal Oscara za najlepší film v roku 1994?', 'Forrest Gump'),
('Filmy a seriály', 3, 'Kto je autorom knižnej predlohy pre film Duna?', 'Herbert'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde hrá postavu Amélie Poulain?', 'Amélie'),
('Filmy a seriály', 3, 'Kto režíroval film Black Swan?', 'Aronofsky'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa postava Jack Torrance zblázni v hoteli?', 'The Shining'),
('Filmy a seriály', 3, 'Kto hral vo filme The Matrix?', 'Reeves'),
('Filmy a seriály', 3, 'Kto je autorom knižnej predlohy pre film Kniha džunglí?', 'Kipling'),
('Filmy a seriály', 3, 'Aký je názov filmu o poslednej bitke v Stalingrade?', 'Enemy at the Gates'),
('Filmy a seriály', 3, 'Kto režíroval film Saving Private Ryan?', 'Spielberg'),
('Filmy a seriály', 3, 'Kto hral vo filme Spotlight?', 'Keaton'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Clarice Starling?', 'Silence of the Lambs'),
('Filmy a seriály', 3, 'Kto režíroval film La La Land?', 'Chazelle'),
('Filmy a seriály', 3, 'Kto hral v snímke The Grand Budapest Hotel?', 'Fiennes'),
('Filmy a seriály', 3, 'Aký je názov filmu o umení manipulácie?', 'American Psycho'),
('Filmy a seriály', 3, 'Kto režíroval film The Shape of Water?', 'Del Toro'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa postava Memento Mori objavuje?', 'Memento'),
('Filmy a seriály', 3, 'Kto je hlavným antagonistom vo filme The Dark Knight?', 'Joker'),
('Filmy a seriály', 3, 'Ktorý film sa zaoberá ženou s psychickými problémami?', 'Black Swan'),
('Filmy a seriály', 3, 'Aký je názov filmu o skupine preživších v zombie apokalypse?', 'World War Z'),
('Filmy a seriály', 3, 'Kto hral vo filme The Sixth Sense?', 'Osment'),
('Filmy a seriály', 3, 'Ktorý film má postavu Williama Jamesa?', 'The Hurt Locker'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde postava Elizabeth Bennet čelí spoločenským normám?', 'Pride and Prejudice'),
('Filmy a seriály', 3, 'Kto hral vo filme The Imitation Game?', 'Cumberbatch'),
('Filmy a seriály', 3, 'Aký je názov filmu o cyklistickom preteku Tour de France?', 'The Program'),
('Filmy a seriály', 3, 'Kto režíroval film 12 Angry Men?', 'Lumet'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde hrá postavu Jacka Dawson?', 'Titanic'),
('Filmy a seriály', 3, 'Kto je hlavnou postavou vo filme Whiplash?', 'Miles'),
('Filmy a seriály', 3, 'Aký je názov filmu o vzostupe a páde rockovej kapely?', 'Almost Famous'),
('Filmy a seriály', 3, 'Kto režíroval film The Tree of Life?', 'Malick'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Franka W. Abagnalea?', 'Catch Me If You Can'),
('Filmy a seriály', 3, 'Kto hral vo filme The Incredibles?', 'Holly'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa objavuje postava Hannibala Lectera?', 'Silence of the Lambs'),
('Filmy a seriály', 3, 'Kto režíroval film The King''s Speech?', 'Hooper'),
('Filmy a seriály', 3, 'Kto hral vo filme The Social Network?', 'Eisenberg'),
('Filmy a seriály', 3, 'Aký je názov filmu o umení manipulácie?', 'American Hustle'),
('Filmy a seriály', 3, 'Kto režíroval film 1917?', 'Mendes'),
('Filmy a seriály', 3, 'Kto hral vo filme Goodfellas?', 'Liotta'),
('Filmy a seriály', 3, 'Kto režíroval film Pulp Fiction?', 'Tarantino'),
('Filmy a seriály', 3, 'Aký je názov filmu o nočnej mori?', 'Inception'),
('Filmy a seriály', 3, 'Kto hrá hlavnú postavu v snímke Mad Max?', 'Tom Hardy'),
('Filmy a seriály', 3, 'Kto je autorom knižnej predlohy pre film Duna?', 'Frank Herbert'),
('Filmy a seriály', 3, 'Aký je názov filmu o detektívovi s postavou Sherlocka Holmesa?', 'Sherlock'),
('Filmy a seriály', 3, 'Kto režíroval film Tvar vody?', 'Guillermo del Toro'),
('Filmy a seriály', 3, 'Aký je názov filmu o superhrdinovi menom Black Panther?', 'T''Challa'),
('Filmy a seriály', 3, 'Kto je hlavným protagonistom vo filme Fight Club?', 'Edward Norton'),
('Filmy a seriály', 3, 'Aký je názov kultového filmu o šiestej smene?', 'Donnie Darko'),
('Filmy a seriály', 3, 'Kto hral postavu Lisbeth Salander vo filme Dievča s drakom?', 'Rooney Mara'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde vystupuje postava Joker?', 'Joker'),
('Filmy a seriály', 3, 'Kto režíroval film Nespavost?', 'Christopher Nolan'),
('Filmy a seriály', 3, 'Aký je názov snímky s postavou V?', 'V for Vendetta'),
('Filmy a seriály', 3, 'Kto hral vo filme Tree of Life?', 'Brad Pitt'),
('Filmy a seriály', 3, 'Aký je názov filmu o osude vojakov vo Vietname?', 'Platoon'),
('Filmy a seriály', 3, 'Kto režíroval film Vykúpenie z väznice Shawshank?', 'Frank Darabont'),
('Filmy a seriály', 3, 'Aký je názov filmu o psychológii manipulácie?', 'Gone Girl'),
('Filmy a seriály', 3, 'Kto hral vo filme Nespavost?', 'Al Pacino'),
('Filmy a seriály', 3, 'Aký je názov filmu o skupine priateľov v Los Angeles?', 'Friends'),
('Filmy a seriály', 3, 'Kto režíroval film Zelená kniha?', 'Peter Farrelly'),
('Filmy a seriály', 3, 'Aký je názov filmu o vesmírnej lodi Nostromo?', 'Alien'),
('Filmy a seriály', 3, 'Kto hral rolu v snímke Blízko neznámeho?', 'Matt Damon'),
('Filmy a seriály', 3, 'Aký je názov filmu o podvode s identitou?', 'Catch Me If You Can'),
('Filmy a seriály', 3, 'Kto režíroval film Requiem za sen?', 'Darren Aronofsky'),
('Filmy a seriály', 3, 'Aký je názov snímky o hackerovi?', 'The Matrix'),
('Filmy a seriály', 3, 'Kto hral vo filme Pán prsteňov?', 'Elijah Wood'),
('Filmy a seriály', 3, 'Aký je názov filmu o záchrane vojakov?', 'Saving Private Ryan'),
('Filmy a seriály', 3, 'Kto je autorom knižnej predlohy pre film Zelená kniha?', 'D. J. Caruso'),
('Filmy a seriály', 3, 'Aký je názov filmu s postavou Tonyho Starka?', 'Iron Man'),
('Filmy a seriály', 3, 'Kto režíroval film A Star Is Born?', 'Bradley Cooper'),
('Filmy a seriály', 3, 'Aký je názov filmu o priateľstve a vojne?', 'Forrest Gump'),
('Filmy a seriály', 3, 'Kto hral vo filme Memento?', 'Guy Pearce'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde postava hľadá svojho syna?', 'Finding Nemo'),
('Filmy a seriály', 3, 'Kto režíroval film Birdman?', 'Alejandro González Iñárritu'),
('Filmy a seriály', 3, 'Aký je názov filmu o osude v budúcnosti?', 'Minority Report'),
('Filmy a seriály', 3, 'Kto hral vo filme Počiatok?', 'Leonardo DiCaprio'),
('Filmy a seriály', 3, 'Aký je názov filmu o vojnových reportéroch?', 'City of God'),
('Filmy a seriály', 3, 'Kto je autorom knižnej predlohy pre film Hladné hry?', 'Suzanne Collins'),
('Filmy a seriály', 3, 'Aký je názov filmu o vzostupe hitlera?', 'Downfall'),
('Filmy a seriály', 3, 'Kto režíroval film 12 rokov otrokom?', 'Steve McQueen'),
('Filmy a seriály', 3, 'Aký je názov filmu o rebelovi s postavou Katniss?', 'Hladné hry'),
('Filmy a seriály', 3, 'Kto hral vo filme The Social Network?', 'Jesse Eisenberg'),
('Filmy a seriály', 3, 'Aký je názov filmu o vzostupe a páde rockovej kapely?', 'Bohemian Rhapsody'),
('Filmy a seriály', 3, 'Kto režíroval film The King''s Speech?', 'Tom Hooper'),
('Filmy a seriály', 3, 'Aký je názov filmu, kde sa postava pokúša o samovraždu?', 'A Single Man'),
('Fyzika', 1, 'Ktorý zákon popisuje pohyb telesa v gravitačnom poli?', 'Gravitácia'),
('Fyzika', 1, 'Aký je symbol pre rýchlosť svetla?', 'c'),
('Fyzika', 1, 'Kto objavil zákon zachovania energie?', 'Joule'),
('Fyzika', 1, 'Aká je jednotka sily?', 'Newton'),
('Fyzika', 1, 'Ktorá častica má záporný náboj?', 'Elektrón'),
('Fyzika', 1, 'Čo je základnou jednotkou hmotnosti?', 'Kilogram'),
('Fyzika', 1, 'Akou jednotkou sa meria elektrický prúd?', 'Ampér'),
('Fyzika', 1, 'Aký je základný zákon termodynamiky?', 'Zachovanie energie'),
('Fyzika', 1, 'Kto formuloval Einsteinovu teóriu relativity?', 'Einstein'),
('Fyzika', 1, 'Aká je jednotka tlaku?', 'Pascal'),
('Fyzika', 1, 'Čo je to joule?', 'Jednotka energie'),
('Fyzika', 1, 'Aký je výskyt gravitačnej sily?', 'Všade'),
('Fyzika', 1, 'Ktorá častica má kladný náboj?', 'Proton'),
('Fyzika', 1, 'Aký je symbol pre hmotnosť?', 'm'),
('Fyzika', 1, 'Kto je považovaný za otca modernej fyziky?', 'Newton'),
('Fyzika', 1, 'Aká je maximálna rýchlosť vesmírneho letu?', 'Svetlo'),
('Fyzika', 1, 'Ktorá sila pôsobí na teleso pri páde?', 'Gravitácia'),
('Fyzika', 1, 'Aká je jednotka elektrického napätia?', 'Volt'),
('Fyzika', 1, 'Kto objavil zákony pohybu?', 'Newton'),
('Fyzika', 1, 'Aký je vzorec pre kinetickú energiu?', '1/2mv²'),
('Fyzika', 1, 'Čo je to akcelerácia?', 'Zrýchlenie'),
('Fyzika', 1, 'Ktorá veličina meria teplotu?', 'Kelvin'),
('Fyzika', 1, 'Aká je jednotka objemu?', 'Liter'),
('Fyzika', 1, 'Aký je symbol pre hustotu?', 'ρ'),
('Fyzika', 1, 'Kto objavil elektromagnetizmus?', 'Faraday'),
('Fyzika', 1, 'Aký je základný zákon optiky?', 'Lom'),
('Fyzika', 1, 'Aká je jednotka frekvencie?', 'Hertz'),
('Fyzika', 1, 'Kto objavil radioaktivitu?', 'Curie'),
('Fyzika', 1, 'Aký je vzorec pre obvod kruhu?', '2πr'),
('Fyzika', 1, 'Aký je symbol pre prácu?', 'W'),
('Fyzika', 1, 'Kto vymyslel teóriu relativity?', 'Einstein'),
('Fyzika', 1, 'Aká je jednotka energie?', 'Joule'),
('Fyzika', 1, 'Ktorý zákon opisuje pohyb planét?', 'Gravitácia'),
('Fyzika', 1, 'Aká je jednotka elektrického odporu?', 'Ohm'),
('Fyzika', 1, 'Kto je autor zákonov termodynamiky?', 'Carnot'),
('Fyzika', 1, 'Aký je symbol pre elektrický náboj?', 'Q'),
('Fyzika', 1, 'Aká je základná jednotka dĺžky?', 'Meter'),
('Fyzika', 1, 'Kto objavil zákon akcie a reakcie?', 'Newton'),
('Fyzika', 1, 'Čo meria gyroskop?', 'Rotáciu'),
('Fyzika', 1, 'Aký je symbol pre prietok?', 'Φ'),
('Fyzika', 1, 'Kto objavil zákon zachovania impulzu?', 'Newton'),
('Fyzika', 1, 'Aký je základný zákon mechaniky?', 'Zákon pohybu'),
('Fyzika', 1, 'Čo je to entropia?', 'Miera neusporiadanosti'),
('Fyzika', 1, 'Aký je symbol pre prácu?', 'W'),
('Fyzika', 1, 'Ktorá veličina určuje silu magnetického poľa?', 'Magnetická indukcia'),
('Fyzika', 1, 'Aká je jednotka magnetického toku?', 'Weber'),
('Fyzika', 1, 'Kto formuloval zákon o zachovaní hmotnosti?', 'Lavoisier'),
('Fyzika', 1, 'Aký je symbol pre elektromagnetickú indukciu?', 'ε'),
('Fyzika', 1, 'Čo je to gravitačné pole?', 'Sila ťahania'),
('Fyzika', 1, 'Aká je jednotka pre prúd?', 'Ampér'),
('Fyzika', 1, 'Ktorý zákon opisuje pohyb telesa vo vode?', 'Archimedov zákon'),
('Fyzika', 1, 'Aká je jednotka práce?', 'Joule'),
('Fyzika', 1, 'Kto je známy pre kvantovú mechaniku?', 'Planck'),
('Fyzika', 1, 'Aká je jednotka elektrického výkonu?', 'Watt'),
('Fyzika', 1, 'Ktorý zákon popisuje tepelnú expanziu?', 'Zákon expanzie'),
('Fyzika', 1, 'Kto je známy pre gravitáciu?', 'Newton'),
('Fyzika', 1, 'Aká je jednotka tepla?', 'Joule'),
('Fyzika', 1, 'Aký je symbol pre vodu?', 'H2O'),
('Fyzika', 1, 'Čo meria barometer?', 'Tlak'),
('Fyzika', 1, 'Aký je najmenší základný prvok?', 'Vodík'),
('Fyzika', 1, 'Aká je jednotka magnetizmu?', 'Tesla'),
('Fyzika', 1, 'Ktorý zákon hovorí o zotrvačnosti?', 'Newtonov'),
('Fyzika', 1, 'Aký je symbol pre zlato?', 'Au'),
('Fyzika', 1, 'Kto je známy pre kvantovú fyziku?', 'Planck'),
('Fyzika', 1, 'Aký je základný zákon akustiky?', 'Rovnica'),
('Fyzika', 1, 'Aká je jednotka intenzity svetla?', 'Lumen'),
('Fyzika', 1, 'Kto objavil zákon vzduchoprázdna?', 'Torricelli'),
('Fyzika', 1, 'Čo je základná jednotka elektriny?', 'Coulomb'),
('Fyzika', 1, 'Aká je jednotka pre prácu?', 'Joule'),
('Fyzika', 1, 'Aký je symbol pre rýchlosť?', 'v'),
('Fyzika', 1, 'Kto formuloval zákon gravitácie?', 'Newton'),
('Fyzika', 1, 'Aká je jednotka pre hustotu?', 'kg/m3'),
('Fyzika', 1, 'Čo meria voltmeter?', 'Napätie'),
('Fyzika', 1, 'Aká je základná jednotka teploty?', 'Kelvin'),
('Fyzika', 1, 'Aký je symbol pre akceleráciu?', 'a'),
('Fyzika', 1, 'Kto je známy pre polarizáciu svetla?', 'Malus'),
('Fyzika', 1, 'Čo je to kyvadlo?', 'Otočné'),
('Fyzika', 1, 'Aký je symbol pre frekvenciu?', 'f'),
('Fyzika', 1, 'Kto objavil zákon o zachovaní energie?', 'Meyer'),
('Fyzika', 1, 'Aká je jednotka elektrického výkonu?', 'Watt'),
('Fyzika', 1, 'Aký je základný zákon chemickej kinetiky?', 'Rýchlosť'),
('Fyzika', 1, 'Kto objavil zákon o pohybe telies?', 'Galileo'),
('Fyzika', 1, 'Aký je symbol pre elektrický odpor?', 'R'),
('Fyzika', 1, 'Aká je jednotka pre tlak?', 'Pascal'),
('Fyzika', 1, 'Kto je známy pre objav elektrónu?', 'Thomson'),
('Fyzika', 1, 'Čo určuje rýchlosť svetla?', 'Vákuum'),
('Fyzika', 1, 'Aký je symbol pre hustotu?', 'ρ'),
('Fyzika', 1, 'Kto formuloval zákony ohmov?', 'Ohm'),
('Fyzika', 1, 'Aká je jednotka pre magnetické pole?', 'Tesla'),
('Fyzika', 1, 'Čo je to vlna?', 'Oscilácia'),
('Fyzika', 1, 'Aký je symbol pre prácu?', 'W'),
('Fyzika', 1, 'Kto objavil zákon zachovania hybnosti?', 'Newton'),
('Fyzika', 1, 'Aká je jednotka pre energiu?', 'Joule'),
('Fyzika', 1, 'Aký je základný zákon optiky?', 'Zlom'),
('Fyzika', 1, 'Kto je známy pre objav fotoelektrického javu?', 'Einstein'),
('Fyzika', 1, 'Aký je symbol pre elektrický náboj?', 'Q'),
('Fyzika', 1, 'Čo meria termometer?', 'Teplotu'),
('Fyzika', 1, 'Aká je jednotka pre objem?', 'Liter'),
('Fyzika', 1, 'Aký je symbol pre čas?', 't'),
('Fyzika', 1, 'Kto objavil zákon o tepelnom žiarení?', 'Stefan'),
('Fyzika', 1, 'Aká je jednotka pre kinetickú energiu?', 'Joule'),
('Fyzika', 1, 'Čo je to gravitačná sila?', 'Príťažlivosť'),
('Fyzika', 1, 'Aký je základný zákon mechaniky?', 'Newtonov'),
('Fyzika', 2, 'Aký je základný zákon elektromagnetizmu?', 'Maxwellove rovnice'),
('Fyzika', 2, 'Čo meria newtonmeter?', 'Moment sily'),
('Fyzika', 2, 'Kto objavil zákon o pohybe telesa?', 'Newton'),
('Fyzika', 2, 'Aký je symbol pre tlak?', 'P'),
('Fyzika', 2, 'Čo je to ohm?', 'Jednotka odporu'),
('Fyzika', 2, 'Aká je základná jednotka elektrického výkonu?', 'Watt'),
('Fyzika', 2, 'Kto formuloval prvý zákon termodynamiky?', 'Zeroth'),
('Fyzika', 2, 'Aká je jednotka magnetického poľa?', 'Tesla'),
('Fyzika', 2, 'Kto navrhol teóriu kvantovania?', 'Planck'),
('Fyzika', 2, 'Čo je to entalpia?', 'Energia'),
('Fyzika', 2, 'Aký je vzorec pre potenciálnu energiu?', 'mgh'),
('Fyzika', 2, 'Aká je základná jednotka teploty?', 'Kelvin'),
('Fyzika', 2, 'Kto je autor zákonov pohybu?', 'Newton'),
('Fyzika', 2, 'Čo určuje hybnosť?', 'Hmotnosť rýchlosť'),
('Fyzika', 2, 'Aký je symbol pre hmotnosť?', 'm'),
('Fyzika', 2, 'Kto sa zaoberal studenou fúziou?', 'Pons'),
('Fyzika', 2, 'Čo meria akcelerometer?', 'Zrýchlenie'),
('Fyzika', 2, 'Aký je základný zákon hydrodynamiky?', 'Bernoulli'),
('Fyzika', 2, 'Kto objavil fotoelektrický jav?', 'Einstein'),
('Fyzika', 2, 'Aký je symbol pre teplotu?', 'T'),
('Fyzika', 2, 'Čo je to hmotnosť?', 'Množstvo hmoty'),
('Fyzika', 2, 'Aká je jednotka intenzity zvuku?', 'Decibel'),
('Fyzika', 2, 'Kto formuloval zákon o gravitácii?', 'Newton'),
('Fyzika', 2, 'Aký je symbol pre energiu?', 'E'),
('Fyzika', 2, 'Čo opisuje zákon zachovania hmotnosti?', 'Hmotnosť'),
('Fyzika', 2, 'Aká je základná jednotka elektrického náboja?', 'Coulomb'),
('Fyzika', 2, 'Kto je známy pre objav neutrína?', 'Reines'),
('Fyzika', 2, 'Aký je základný zákon optiky?', 'Huygens'),
('Fyzika', 2, 'Čo meria spektrometer?', 'Spektrum'),
('Fyzika', 2, 'Aký je základný zákon akustiky?', 'Huygens'),
('Fyzika', 2, 'Kto formuloval zákon o tepelnom žiarení?', 'Planck'),
('Fyzika', 2, 'Aká je jednotka pre elektrické napätie?', 'Volt'),
('Fyzika', 2, 'Kto je známy pre kvantovú mechaniku?', 'Bohr'),
('Fyzika', 2, 'Čo je to mechanická energia?', 'Kinetická potenciálna'),
('Fyzika', 2, 'Aký je symbol pre čas?', 't'),
('Fyzika', 2, 'Kto objavil zákon o akcii a reakcii?', 'Newton'),
('Fyzika', 2, 'Aký je základný zákon pružnosti?', 'Hooke'),
('Fyzika', 2, 'Čo meria manometer?', 'Tlak'),
('Fyzika', 2, 'Aká je jednotka pre elektrický prúd?', 'Ampér'),
('Fyzika', 2, 'Kto objavil zákon o tepelnom pohybe?', 'Brown'),
('Fyzika', 2, 'Aký je symbol pre magnetický tok?', 'Φ'),
('Fyzika', 2, 'Čo je to elektrická energia?', 'Práca prúd'),
('Fyzika', 2, 'Aká je základná jednotka svetelného toku?', 'Lumen'),
('Fyzika', 2, 'Kto je známy pre objav gravitácie?', 'Newton'),
('Fyzika', 2, 'Aký je symbol pre prietok?', 'Q'),
('Fyzika', 2, 'Čo opisuje zákon zachovania energie?', 'Energie'),
('Fyzika', 2, 'Aká je jednotka pre objem?', 'Liter'),
('Fyzika', 2, 'Kto je známy pre objav ultrazvuku?', 'Lavoisier'),
('Fyzika', 2, 'Aký je základný zákon termodynamiky?', 'Zeroth'),
('Fyzika', 2, 'Čo meria kalorimeter?', 'Teplo'),
('Fyzika', 2, 'Aký je symbol pre intenzitu svetla?', 'I'),
('Fyzika', 2, 'Kto formuloval zákon o optickej mriežke?', 'Grimaldi'),
('Fyzika', 2, 'Aká je jednotka pre elektrickú kapacitu?', 'Farad'),
('Fyzika', 2, 'Čo je to gravitačné zrýchlenie?', '9.81 m/s²'),
('Fyzika', 2, 'Aký je symbol pre tlak?', 'p'),
('Fyzika', 2, 'Aká je základná jednotka elektrického napätia?', 'Volt'),
('Fyzika', 2, 'Kto je známy pre objav relativity?', 'Einstein'),
('Fyzika', 2, 'Aký je vzorec pre prácu?', 'W=F·s'),
('Fyzika', 2, 'Čo určuje rozptyl svetla?', 'Refrakcia'),
('Fyzika', 2, 'Kto je známy pre objav magnetizmu?', 'Faraday'),
('Fyzika', 2, 'Aký je vzorec pre potenciálnu energiu?', 'PE=mgh'),
('Fyzika', 2, 'Čo meria barometer?', 'Tlak'),
('Fyzika', 2, 'Aký je symbol pre teplotu?', 'T'),
('Fyzika', 2, 'Čo je to mechanická práca?', 'F·s'),
('Fyzika', 2, 'Kto objavil zákon pohybu?', 'Newton'),
('Fyzika', 2, 'Aký je základný zákon akustiky?', 'Hybnosť'),
('Fyzika', 2, 'Aký je symbol pre elektrickú energiu?', 'E'),
('Fyzika', 2, 'Kto formuloval zákon o elektrodynamike?', 'Maxwell'),
('Fyzika', 2, 'Aká je jednotka pre magnetický tok?', 'Weber'),
('Fyzika', 2, 'Čo meria seismometer?', 'Zemetrasenia'),
('Fyzika', 2, 'Aký je základný zákon hydrodynamiky?', 'Bernoulli'),
('Fyzika', 2, 'Kto objavil zákon o akcii a reakcii?', 'Newton'),
('Fyzika', 2, 'Aká je jednotka pre svetelný výkon?', 'Lumen'),
('Fyzika', 2, 'Čo je to elektromagnetická vlna?', 'Rádiové vlny'),
('Fyzika', 2, 'Aký je základný zákon optiky?', 'Snellov zákon'),
('Fyzika', 2, 'Kto formuloval zákon o tepelnom pohybe?', 'Boltzmann'),
('Fyzika', 2, 'Aký je symbol pre elektrický prúd?', 'I'),
('Fyzika', 2, 'Aká je jednotka pre elektrický náboj?', 'Coulomb'),
('Fyzika', 2, 'Kto objavil zákon o magnetickej indukcii?', 'Faraday'),
('Fyzika', 2, 'Čo je to elektrická kapacita?', 'C=Q/V'),
('Fyzika', 2, 'Aká je jednotka pre svetelný tok?', 'Lumen'),
('Fyzika', 2, 'Kto je známy pre objav neutrína?', 'Reines'),
('Fyzika', 2, 'Aký je symbol pre magnetické pole?', 'B'),
('Fyzika', 2, 'Aká je základná jednotka hmotnosti?', 'Kilogram'),
('Fyzika', 2, 'Čo meria spektroskóp?', 'Spektrum'),
('Fyzika', 2, 'Aký je základný zákon dynamiky?', 'F=m·a'),
('Fyzika', 2, 'Kto objavil zákon o termodynamike?', 'Carnot'),
('Fyzika', 2, 'Aký je symbol pre výkon?', 'P'),
('Fyzika', 2, 'Čo je to oscilácia?', 'Periodické pohyby'),
('Fyzika', 2, 'Aká je jednotka pre tepelnú kapacitu?', 'Joule'),
('Fyzika', 2, 'Kto je známy pre objav fotónu?', 'Einstein'),
('Fyzika', 2, 'Aký je základný zákon optickej mriežky?', 'Braggov zákon'),
('Fyzika', 2, 'Čo je to gravitácia?', 'Pôsobenie hmoty'),
('Fyzika', 2, 'Aký je symbol pre hustotu?', 'ρ'),
('Fyzika', 2, 'Kto objavil zákon o zachovaní hybnosti?', 'Newton'),
('Fyzika', 2, 'Aká je jednotka pre prúd?', 'Ampér'),
('Fyzika', 2, 'Čo meria voltmeter?', 'Napätie'),
('Fyzika', 2, 'Aký je základný zákon akcelerácie?', 'F=m·a'),
('Fyzika', 2, 'Kto je známy pre objav radioaktivity?', 'Curie'),
('Fyzika', 2, 'Aký je symbol pre elektrický odpor?', 'R'),
('Fyzika', 2, 'Čo meria dynamometer?', 'Silu'),
('Fyzika', 2, 'Kto objavil zákon o tepelných výmenách?', 'Newton'),
('Fyzika', 2, 'Aká je jednotka pre intenzitu svetla?', 'Candela'),
('Fyzika', 2, 'Aký je základný zákon pohybu?', 'Zotrvačnosť'),
('Fyzika', 2, 'Čo je to kolízia?', 'Srážka telies'),
('Fyzika', 2, 'Aký je symbol pre frekvenciu?', 'f'),
('Fyzika', 2, 'Kto formuloval zákon o pohybe telies?', 'Newton'),
('Fyzika', 2, 'Aká je jednotka elektrickej kapacity?', 'Farad'),
('Fyzika', 2, 'Čo určuje teplota?', 'Energia častíc'),
('Fyzika', 2, 'Aký je základný zákon elektromagnetizmu?', 'Faradayov zákon'),
('Fyzika', 2, 'Kto je známy pre objav tepla?', 'Calorimetry'),
('Fyzika', 2, 'Aký je symbol pre magnetický tok?', 'Φ'),
('Fyzika', 2, 'Čo je to mechanická energia?', 'Kinetická+potenciálna'),
('Fyzika', 3, 'Aký je vzorec pre zákon zachovania energie?', 'E=mc²'),
('Fyzika', 3, 'Kto formuloval Schrödingerovu rovnicu?', 'Schrödinger'),
('Fyzika', 3, 'Aký je vzorec pre kinetickú energiu?', 'KE=½mv²'),
('Fyzika', 3, 'Čo je to kvantová mechanika?', 'Kvantová teória'),
('Fyzika', 3, 'Kto je autor teórie relativity?', 'Einstein'),
('Fyzika', 3, 'Aká je základná jednotka magnetického poľa?', 'Tesla'),
('Fyzika', 3, 'Kto objavil Bohrov model atómu?', 'Bohrova teória'),
('Fyzika', 3, 'Aký je základný zákon elektromagnetizmu?', 'Maxwellove rovnice'),
('Fyzika', 3, 'Čo je to superpozícia?', 'Superpozícia'),
('Fyzika', 3, 'Aká je jednotka elektrického náboja?', 'Coulomb'),
('Fyzika', 3, 'Kto formuloval zákon o pružnosti?', 'Hooke'),
('Fyzika', 3, 'Aký je vzorec pre prácu?', 'W=F·d'),
('Fyzika', 3, 'Čo je to kvantovanie?', 'Kvantový skok'),
('Fyzika', 3, 'Aká je jednotka pre elektrickú kapacitu?', 'Farad'),
('Fyzika', 3, 'Čo meria gravimeter?', 'Gravitácia'),
('Fyzika', 3, 'Kto je známy pre objav fotónu?', 'Einstein'),
('Fyzika', 3, 'Aký je symbol pre elektrický výkon?', 'W'),
('Fyzika', 3, 'Kto formuloval zákon o optike?', 'Huygens'),
('Fyzika', 3, 'Aký je základný zákon akustiky?', 'Bernoulli'),
('Fyzika', 3, 'Čo je to teplota?', 'Stavová veličina'),
('Fyzika', 3, 'Kto objavil súvislosť medzi teplom a prácou?', 'Carnot'),
('Fyzika', 3, 'Aký je základný zákon hydrodynamiky?', 'Bernoulliho'),
('Fyzika', 3, 'Čo je to entropia?', 'Miera neusporiadanosti'),
('Fyzika', 3, 'Aký je symbol pre hustotu?', 'ρ'),
('Fyzika', 3, 'Kto objavil zákon o tepelných výmenách?', 'Fourier'),
('Fyzika', 3, 'Aká je jednotka pre svetelný tok?', 'Lumen'),
('Fyzika', 3, 'Čo meria optický spektrometer?', 'Spektrum'),
('Fyzika', 3, 'Kto formuloval zákon o elektrickom poli?', 'Gauss'),
('Fyzika', 3, 'Aký je základný zákon tepelnej dynamiky?', 'Zákon zachovania'),
('Fyzika', 3, 'Čo je to mechanická práca?', 'Práca sily'),
('Fyzika', 3, 'Aká je základná jednotka tepelnej kapacity?', 'Joule'),
('Fyzika', 3, 'Kto je známy pre objav gravitačných vĺn?', 'Einstein'),
('Fyzika', 3, 'Aký je symbol pre elektrický prúd?', 'I'),
('Fyzika', 3, 'Čo je to relatívna vlhkosť?', 'Vlhkosť vzduchu'),
('Fyzika', 3, 'Aká je jednotka pre intenzitu zvuku?', 'Decibel'),
('Fyzika', 3, 'Kto formuloval zákon o osciláciách?', 'Hooke'),
('Fyzika', 3, 'Aký je základný zákon magnetizmu?', 'Ampèrov'),
('Fyzika', 3, 'Čo meria seismometer?', 'Zemetrasenie'),
('Fyzika', 3, 'Aká je jednotka pre elektrický náboj?', 'Coulomb'),
('Fyzika', 3, 'Kto objavil zákon o tepelnom žiarení?', 'Planck'),
('Fyzika', 3, 'Aký je symbol pre hybnosť?', 'p'),
('Fyzika', 3, 'Čo je to elektrická energia?', 'Energia náboja'),
('Fyzika', 3, 'Aká je základná jednotka pre prácu?', 'Joule'),
('Fyzika', 3, 'Kto je známy pre teóriu relativity?', 'Einstein'),
('Fyzika', 3, 'Aký je vzorec pre potenciálnu energiu?', 'PE=mgh'),
('Fyzika', 3, 'Čo je to harmonická oscilácia?', 'Pravidelný pohyb'),
('Fyzika', 3, 'Aká je jednotka pre elektrický výkon?', 'Watt'),
('Fyzika', 3, 'Kto objavil zákon o elektrickej indukcii?', 'Faraday'),
('Fyzika', 3, 'Aký je základný zákon akcelerácie?', 'Newtonov'),
('Fyzika', 3, 'Čo meria dynamometer?', 'Silu'),
('Fyzika', 3, 'Aký je symbol pre teplotu?', 'T'),
('Fyzika', 3, 'Kto formuloval zákon o odporu?', 'Ohm'),
('Fyzika', 3, 'Aká je jednotka pre magnetický tok?', 'Weber'),
('Fyzika', 3, 'Čo je to Coulombov zákon?', 'Interakcia nábojov'),
('Fyzika', 3, 'Aký je základný zákon optiky?', 'Snellov zákon');