INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Literatúra', 2, 'Kto je autorom "Sophie’s World"?', 'Jostein Gaarder'),
('Literatúra', 2, 'Aký je názov diela od Agathy Christie?', 'Desať malých černoškov'),
('Literatúra', 2, 'Kto napísal "Kvetinová vojna"?', 'V. Nabokov'),
('Literatúra', 2, 'Aký je názov románu od Ray Bradbury?', '451 stupňov Fahrenheita'),
('Literatúra', 2, 'Kto je autorom "Rukopis nájdený v Saragose"?', 'Jan Potocký'),
('Literatúra', 2, 'Aký je názov diela od H. G. Wellsa?', 'Stroj času'),
('Literatúra', 2, 'Kto napísal "Farebný prameň"?', 'Herman Hesse'),
('Literatúra', 2, 'Aký je názov románu od Italo Calvina?', 'Neviditeľné mestá'),
('Literatúra', 2, 'Kto je autorom "O myšiach a ľuďoch"?', 'Steinbeck'),
('Literatúra', 2, 'Aký je názov diela od S. Kingsleyho?', 'Waterland'),
('Literatúra', 2, 'Kto napísal "Päťdesiat odtieňov sivej"?', 'E. L. James'),
('Literatúra', 2, 'Aký je názov románu od J. K. Rowling?', 'Harry Potter'),
('Literatúra', 2, 'Kto je autorom "Trójske vojny"?', 'Homer'),
('Literatúra', 2, 'Aký je názov diela od Ch. Dickens?', 'Oliver Twist'),
('Literatúra', 2, 'Kto napísal "Cikán a generál"?', 'Milan Kunder'),
('Literatúra', 2, 'Aký je názov románu od F. Kafka?', 'Premena'),
('Literatúra', 2, 'Kto je autorom "Majster a Margaríta"?', 'Bulgakov'),
('Literatúra', 2, 'Aký je názov diela od J. Fowlesa?', 'Francúzska milenka'),
('Literatúra', 2, 'Kto napísal "Malý princ"?', 'Antoine de Saint-Exupéry'),
('Literatúra', 2, 'Aký je názov románu od H. Melvilla?', 'Moby Dick'),
('Literatúra', 2, 'Kto je autorom "Pani Dallowayová"?', 'Woolf'),
('Literatúra', 2, 'Aký je názov diela od E. A. Poea?', 'Havran'),
('Literatúra', 2, 'Kto napísal "Dobrý vojak Švejk"?', 'Jaroslav Hašek'),
('Literatúra', 2, 'Aký je názov románu od R. Rollanda?', 'Jean-Christophe'),
('Literatúra', 2, 'Kto je autorom "Hlava XXII"?', 'Joseph Heller'),
('Literatúra', 2, 'Aký je názov diela od D. H. Lawrence?', 'Láska a iné demonštrácie'),
('Literatúra', 2, 'Kto napísal "Vojna a mier"?', 'Lev Tolstoj'),
('Literatúra', 2, 'Aký je názov románu od K. Vonneguta?', 'Jatka č. 5'),
('Literatúra', 2, 'Kto je autorom "Svetlo, ktoré nevidíme"?', 'Anthony Doerr'),
('Literatúra', 2, 'Aký je názov diela od J. Orwell?', 'Farma zvierat'),
('Literatúra', 2, 'Kto napísal "Zločin a trest"?', 'Dostoevskij'),
('Literatúra', 2, 'Aký je názov románu od A. Christie?', 'Vražda v Orient exprese'),
('Literatúra', 2, 'Kto je autorom "Pýcha a predsudok"?', 'Jane Austen'),
('Literatúra', 3, 'Kto napísal "Cestovanie v čase"?', 'H. G. Wells'),
('Literatúra', 3, 'Aký je názov románu od Marcel Prousta?', 'Hľadanie strateného času'),
('Literatúra', 3, 'Kto je autorom "Sofiin svet"?', 'Jostein Gaarder'),
('Literatúra', 3, 'Aký je názov diela od Virginia Woolfovej?', 'Pani Dallowayová'),
('Literatúra', 3, 'Kto napísal "Mistr a Markétka"?', 'M. Bulgakov'),
('Literatúra', 3, 'Aký je názov románu od Michaila Bulgakova?', 'Majster a Margaríta'),
('Literatúra', 3, 'Kto je autorom "Neznesiteľná ľahkosť bytia"?', 'Milan Kundera'),
('Literatúra', 3, 'Aký je názov diela od Ray Bradburyho?', 'Fahrenheit 451'),
('Literatúra', 3, 'Kto napísal "Pani Bovaryová"?', 'Gustave Flaubert'),
('Literatúra', 3, 'Aký je názov románu od Thomasa Manna?', 'Buddenbrookovci'),
('Literatúra', 3, 'Kto je autorom "Zabudnutá záhrada"?', 'Kate Morton'),
('Literatúra', 3, 'Aký je názov diela od Haruki Murakamiho?', 'Kafka na pobreží'),
('Literatúra', 3, 'Kto napísal "Pýcha a predsudok"?', 'Jane Austen'),
('Literatúra', 3, 'Aký je názov románu od Georgea Orwella?', '1984'),
('Literatúra', 3, 'Kto je autorom "Svetlo, ktoré nevidíme"?', 'Anthony Doerr'),
('Literatúra', 3, 'Aký je názov diela od Ericha Marii Remarquea?', 'Na západe nič nového'),
('Literatúra', 3, 'Kto napísal "Alchymista"?', 'Paulo Coelho'),
('Literatúra', 3, 'Aký je názov románu od Gustava Flauberta?', 'Pani Bovaryová'),
('Literatúra', 3, 'Kto je autorom "Čarodejník z krajiny Oz"?', 'L. Frank Baum'),
('Literatúra', 3, 'Aký je názov diela od J. D. Salingera?', 'Kto chytá v žite'),
('Literatúra', 3, 'Kto napísal "Krajina pôvodu"?', 'John Steinbeck'),
('Literatúra', 3, 'Aký je názov románu od Aldouse Huxleyho?', 'Krásny nový svet'),
('Literatúra', 3, 'Kto je autorom "Hlava XXII"?', 'Joseph Heller'),
('Literatúra', 3, 'Aký je názov diela od Hermana Melvilla?', 'Moby Dick'),
('Literatúra', 3, 'Kto napísal "Cikán a generál"?', 'K. K. K.'),
('Literatúra', 3, 'Aký je názov románu od Eugena O''Neilla?', 'Mourning Becomes Electra'),
('Literatúra', 3, 'Kto je autorom "Súmrak"?', 'S. Meyer'),
('Literatúra', 3, 'Aký je názov diela od F. M. Dostojevského?', 'Zločin a trest'),
('Literatúra', 3, 'Kto napísal "Hrdinov našich čias"?', 'Mikhail Lermontov'),
('Literatúra', 3, 'Aký je názov románu od D. H. Lawrence?', 'Milenci v noci'),
('Literatúra', 3, 'Kto je autorom "Trójske vojny"?', 'Homer'),
('Literatúra', 3, 'Aký je názov diela od J. R. R. Tolkiena?', 'Hobit'),
('Literatúra', 3, 'Kto napísal "Veľký Gatsby"?', 'F. Scott Fitzgerald'),
('Literatúra', 3, 'Aký je názov románu od Charlotte Brontë?', 'Jana Eyrová'),
('Literatúra', 3, 'Kto je autorom "Farebný prameň"?', 'M. Proust'),
('Literatúra', 3, 'Aký je názov diela od D. H. Lawrence?', 'Žena, ktorá milovala muža'),
('Literatúra', 3, 'Kto napísal "Džin a jeho priateľ"?', 'E. J. K.'),
('Literatúra', 3, 'Aký je názov románu od Kafku?', 'Premet'),
('Literatúra', 3, 'Kto je autorom "Majster a Margaríta"?', 'M. Bulgakov'),
('Literatúra', 3, 'Aký je názov diela od Thomas Hardy?', 'Tess z d''Urbervillovcov'),
('Literatúra', 3, 'Kto napísal "Malý princ"?', 'Antoine de Saint-Exupéry'),
('Literatúra', 3, 'Aký je názov románu od Albert Camus?', 'Cudzinec'),
('Literatúra', 3, 'Kto je autorom "Dobrý vojak Švejk"?', 'Jaroslav Hašek'),
('Literatúra', 3, 'Aký je názov diela od Italo Calvina?', 'Neviditeľné mestá'),
('Literatúra', 3, 'Kto napísal "Neznesiteľná ľahkosť bytia"?', 'Milan Kundera'),
('Literatúra', 3, 'Aký je názov románu od Bram Stokera?', 'Dracula'),
('Literatúra', 3, 'Kto je autorom "Páni a otroci"?', 'J. M. Coetzee'),
('Literatúra', 3, 'Aký je názov diela od C. S. Lewisa?', 'Narnia'),
('Literatúra', 3, 'Kto napísal "O myšiach a ľuďoch"?', 'John Steinbeck'),
('Literatúra', 3, 'Kto napísal "Na ceste"?', 'Kerouac'),
('Literatúra', 3, 'Aký je názov románu od D. H. Lawrence?', 'Ženská'),
('Literatúra', 3, 'Kto je autorom "Majster a Margaríta"?', 'Bulgakov'),
('Literatúra', 3, 'Aký je názov diela od F. M. Dostojevského?', 'Zločin'),
('Literatúra', 3, 'Kto napísal "Storočný starček, ktorý vylezol z okna"?', 'Jonasson'),
('Literatúra', 3, 'Aký je názov románu od Michaila Bulgakova?', 'Margarita'),
('Literatúra', 3, 'Kto je autorom "Sofiin svet"?', 'Gaarder'),
('Literatúra', 3, 'Aký je názov diela od Haruki Murakami?', 'Norwegian'),
('Literatúra', 3, 'Kto napísal "Cikán a generál"?', 'Milan'),
('Literatúra', 3, 'Aký je názov románu od Thomasa Manna?', 'Kúzelník'),
('Literatúra', 3, 'Kto je autorom "Zabudnutá záhrada"?', 'Kate'),
('Literatúra', 3, 'Aký je názov diela od Gustava Flauberta?', 'Madam'),
('Literatúra', 3, 'Kto napísal "Kvetinová vojna"?', 'Sartre'),
('Literatúra', 3, 'Aký je názov románu od Georgea Orwella o totalitarizme?', '1984'),
('Literatúra', 3, 'Kto je autorom "Pán prsteňov"?', 'Tolkien'),
('Literatúra', 3, 'Aký je názov diela od Virginii Woolfovej?', 'Búrlivé'),
('Literatúra', 3, 'Kto napísal "Dobrý vojak Švejk"?', 'Hašek'),
('Literatúra', 3, 'Aký je názov románu od Aldouse Huxleyho?', 'Koniec'),
('Literatúra', 3, 'Kto je autorom "Čarodejník z krajiny Oz"?', 'Baum'),
('Literatúra', 3, 'Aký je názov diela od E. A. Poea?', 'Havran'),
('Literatúra', 3, 'Kto napísal "O myšiach a ľuďoch"?', 'Steinbeck'),
('Literatúra', 3, 'Aký je názov románu od F. Kafka?', 'Premet'),
('Literatúra', 3, 'Kto je autorom "Pýcha a predsudok"?', 'Austen'),
('Literatúra', 3, 'Aký je názov diela od J. D. Salingera?', 'Kto'),
('Literatúra', 3, 'Kto napísal "Veľkého Gatsbyho"?', 'Fitzgerald'),
('Literatúra', 3, 'Aký je názov románu od Ray Bradbury?', 'Fahrenheit'),
('Literatúra', 3, 'Kto je autorom "Alchymista"?', 'Coelho'),
('Literatúra', 3, 'Aký je názov diela od Mary Shelley?', 'Frankenstein'),
('Literatúra', 3, 'Kto napísal "Hrdinov našich čias"?', 'Lermontov'),
('Literatúra', 3, 'Aký je názov románu od Kafku o procese?', 'Proces'),
('Literatúra', 3, 'Kto je autorom "Dámy s kaméliami"?', 'Dumas'),
('Literatúra', 3, 'Aký je názov diela od E. Hemingwaya?', 'Starec'),
('Literatúra', 3, 'Kto napísal "Svetlo, ktoré nevidíme"?', 'Doerr'),
('Literatúra', 3, 'Aký je názov románu od Kunderu?', 'Nesnesiteľná'),
('Literatúra', 3, 'Kto je autorom "Kto chytá v žite"?', 'Salinger'),
('Literatúra', 3, 'Aký je názov diela od S. Kingsleyho?', 'Waterland'),
('Literatúra', 3, 'Kto napísal "Farebný prameň"?', 'Miller'),
('Literatúra', 3, 'Aký je názov románu od Italo Calvina?', 'Neviditeľné'),
('Literatúra', 3, 'Kto je autorom "Pán much"?', 'Golding'),
('Literatúra', 3, 'Aký je názov diela od C. S. Lewisa?', 'Narnia'),
('Literatúra', 3, 'Kto napísal "Päťdesiat odtieňov sivej"?', 'James'),
('Literatúra', 3, 'Aký je názov románu od G. Márqueza?', 'Láska'),
('Literatúra', 3, 'Kto je autorom "Neznesiteľná ľahkosť bytia"?', 'Kundera'),
('Literatúra', 3, 'Aký je názov diela od H. G. Wellsa?', 'Stroj'),
('Literatúra', 3, 'Kto napísal "Bratři Karamazovi"?', 'Dostojevský'),
('Literatúra', 3, 'Aký je názov románu od D. H. Lawrence?', 'Žena'),
('Literatúra', 3, 'Kto je autorom "Rukopis nájdený v Saragose"?', 'Potocki'),
('Literatúra', 3, 'Aký je názov diela od J. Steinbecka?', 'Hrozny'),
('Literatúra', 3, 'Kto napísal "Zločin a trest"?', 'Dostojevský'),
('Literatúra', 3, 'Aký je názov románu od Lev Tolstého?', 'Anna'),
('Literatúra', 3, 'Kto napísal "Pána prsteňov"?', 'Tolkien'),
('Literatúra', 3, 'Aký je názov románu "Tisíc a jedna noc"?', 'Arabské rozprávky'),
('Literatúra', 3, 'Kto je autorom "Starec a more"?', 'Hemingway'),
('Literatúra', 3, 'Aký je názov diela od T. Manna?', 'Buddenbrooks'),
('Literatúra', 3, 'Kto napísal "Tajomná záhrada"?', 'Burnett'),
('Literatúra', 3, 'Aký je názov románu od V. Nabokova?', 'Lolita'),
('Literatúra', 3, 'Kto je autorom "Básne o láske"?', 'Neruda'),
('Literatúra', 3, 'Aký je názov diela od D. H. Lawrence?', 'Nebezpečné vzťahy'),
('Literatúra', 3, 'Kto napísal "Vojna a mier"?', 'Tolstoj'),
('Literatúra', 3, 'Aký je názov románu od G. Flauberta?', 'Madame Bovary'),
('Literatúra', 3, 'Kto je autorom "Cudzie slová"?', 'Kundera'),
('Literatúra', 3, 'Aký je názov diela od H. Melvilla?', 'Moby Dick'),
('Literatúra', 3, 'Kto napísal "Zločin a trest"?', 'Dostojevskij'),
('Literatúra', 3, 'Aký je názov románu od A. Camus?', 'Cudzinec'),
('Literatúra', 3, 'Kto je autorom "Pani Bovaryová"?', 'Flaubert'),
('Literatúra', 3, 'Aký je názov diela od I. B. Singera?', 'Šesť postáv'),
('Literatúra', 3, 'Kto napísal "Kto chytá v žite"?', 'Salinger'),
('Literatúra', 3, 'Aký je názov románu od T. Wolfea?', 'Fleischman'),
('Literatúra', 3, 'Kto je autorom "Pán much"?', 'Golding'),
('Literatúra', 3, 'Aký je názov diela od H. G. Wellsa?', 'Stroj času'),
('Literatúra', 3, 'Kto napísal "O myšiach a ľuďoch"?', 'Steinbeck'),
('Literatúra', 3, 'Aký je názov románu od R. Rollanda?', 'Jean-Christophe'),
('Literatúra', 3, 'Kto je autorom "Vyhnanec"?', 'Kundera'),
('Literatúra', 3, 'Aký je názov diela od J. Fowlesa?', 'Zberateľ'),
('Literatúra', 3, 'Kto napísal "Láska v čase cholery"?', 'Márquez'),
('Literatúra', 3, 'Aký je názov románu od J. Steinbecka?', 'Hrozny hnevu'),
('Literatúra', 3, 'Kto je autorom "Pani Dallowayová"?', 'Woolf'),
('Literatúra', 3, 'Aký je názov diela od Kafku?', 'Premena'),
('Literatúra', 3, 'Kto napísal "Svetlo, ktoré nevidíme"?', 'Doerr'),
('Literatúra', 3, 'Aký je názov románu od A. Camus?', 'Cudzinec'),
('Literatúra', 3, 'Kto je autorom "Malý princ"?', 'Saint-Exupéry'),
('Literatúra', 3, 'Aký je názov diela od S. Kingsleyho?', 'Waterland'),
('Literatúra', 3, 'Kto napísal "Bratři Karamazovi"?', 'Dostojevskij'),
('Literatúra', 3, 'Aký je názov románu od E. Hemingwaya?', 'Slnko vychádza'),
('Literatúra', 3, 'Kto je autorom "Farebný prameň"?', 'Larkin'),
('Literatúra', 3, 'Aký je názov diela od G. Orwell?', '1984'),
('Literatúra', 3, 'Kto napísal "Na ceste"?', 'Kerouac'),
('Literatúra', 3, 'Aký je názov románu od H. Melvilla?', 'Biely tesák'),
('Literatúra', 3, 'Kto je autorom "Zlodejka kníh"?', 'Zusak'),
('Literatúra', 3, 'Aký je názov diela od Thoreaua?', 'Walden'),
('Literatúra', 3, 'Kto napísal "Kvetinová vojna"?', 'Neruda'),
('Literatúra', 3, 'Aký je názov románu od J. D. Salingera?', 'Kto chytá v žite'),
('Literatúra', 3, 'Kto je autorom "Starec a more"?', 'Hemingway'),
('Literatúra', 3, 'Aký je názov diela od Ray Bradbury?', 'Fahrenheit 451'),
('Literatúra', 3, 'Kto napísal "Trón zo skla"?', 'Maas'),
('Literatúra', 3, 'Aký je názov románu od H. G. Wellsa?', 'Nedokončený svet'),
('Literatúra', 3, 'Kto je autorom "Alchymista"?', 'Coelho'),
('Literatúra', 3, 'Aký je názov diela od A. Christie?', 'Vražda v Orient Expresse'),
('Literatúra', 3, 'Kto napísal "Dobrý vojak Švejk"?', 'Hašek'),
('Literatúra', 3, 'Aký je názov románu od Kafku?', 'Zámok'),
('Logika a hádanky', 1, 'Aký tvar má štvoruholník so všetkými stranami rovnakými?', 'Štvorček'),
('Logika a hádanky', 1, 'Koľko mesiacov má rok?', 'Dvanásť'),
('Logika a hádanky', 1, 'Aká farba vznikne zmiešaním modrej a žltej?', 'Zelená'),
('Logika a hádanky', 1, 'Aký tvar má kruh?', 'Kruh'),
('Logika a hádanky', 1, 'Čo je to, čo má štyri nohy, ale nechodí?', 'Stôl'),
('Logika a hádanky', 1, 'Koľko prstov má človek na jednej ruke?', 'Päť'),
('Logika a hádanky', 1, 'Aká je farba neba za jasného dňa?', 'Modrá'),
('Logika a hádanky', 1, 'Koľko dní má týždeň?', 'Sedem'),
('Logika a hádanky', 1, 'Čo je to, čo padajúce z neba, ale nie je to dážď?', 'Sneh'),
('Logika a hádanky', 1, 'Aký je opak dňa?', 'Noc'),
('Logika a hádanky', 1, 'Ktoré zviera je známe ako najlepší priateľ človeka?', 'Pes'),
('Logika a hádanky', 1, 'Koľko rokov má dospelý človek?', 'Dvadsať'),
('Logika a hádanky', 1, 'Aký je hlavný mestom Slovenska?', 'Bratislava'),
('Logika a hádanky', 1, 'Akú farbu má slnko?', 'Žltá'),
('Logika a hádanky', 1, 'Čo je to, čo má klobúk a nechodí?', 'Huba'),
('Logika a hádanky', 1, 'Aký je najväčší oceán na svete?', 'Tichý'),
('Logika a hádanky', 1, 'Koľko je 2+2?', 'Štyri'),
('Logika a hádanky', 1, 'Aký je najvyšší vrch sveta?', 'Everest'),
('Logika a hádanky', 1, 'Koľko mesiacov má február v priestore?', 'Dva'),
('Logika a hádanky', 1, 'Čo je to, čo sa vždy pohybuje, ale nikdy sa nezmení?', 'Hodiny'),
('Logika a hádanky', 1, 'Aké zviera je kráľom džungle?', 'Lev'),
('Logika a hádanky', 1, 'Aký je opak svetla?', 'Tma'),
('Logika a hádanky', 1, 'Aký je najmenší kontinent?', 'Austrália'),
('Logika a hádanky', 1, 'Koľko zubov má dospelý človek?', 'Tridsaťdva'),
('Logika a hádanky', 1, 'Ktoré ovocie je známe ako „kráľovná ovocia“?', 'Mango'),
('Logika a hádanky', 1, 'Aká je farba čerešní?', 'Červená'),
('Logika a hádanky', 1, 'Čo je to, čo má jedno oko, ale nemôže vidieť?', 'Ihlica'),
('Logika a hádanky', 1, 'Aká je základná jednotka dĺžky?', 'Meter'),
('Logika a hádanky', 1, 'Koľko hodín má deň?', 'Dvadsaťštyri'),
('Logika a hádanky', 1, 'Aký je najmenší štát na svete?', 'Vatikán'),
('Logika a hádanky', 1, 'Aký je opak tepla?', 'Chlad'),
('Logika a hádanky', 1, 'Čo je to, čo letí, ale nemá krídla?', 'Rok'),
('Logika a hádanky', 1, 'Aká je najznámejšia pyramída v Egypte?', 'Cheops'),
('Logika a hádanky', 1, 'Ktorý mesiac je najchladnejší?', 'Január'),
('Logika a hádanky', 1, 'Aký je najväčší cicavec?', 'Modrá veľryba'),
('Logika a hádanky', 1, 'Koľko štátov je v USA?', 'Päťdesiat'),
('Logika a hádanky', 1, 'Čo je to, čo sa dá zlomiť bez dotyku?', 'Sľub'),
('Logika a hádanky', 1, 'Aké je hlavné mesto Francúzska?', 'Paríž'),
('Logika a hádanky', 1, 'Aký je najhlbší oceán na svete?', 'Tichý'),
('Logika a hádanky', 1, 'Čo je to, čo má štyri rohy a nie je to zviera?', 'Stôl'),
('Logika a hádanky', 1, 'Aký je najpopulárnejší šport na svete?', 'Futbal'),
('Logika a hádanky', 1, 'Koľko strán má trojuholník?', 'Tri'),
('Logika a hádanky', 1, 'Čo je to, čo sa nikdy nevráti?', 'Čas'),
('Logika a hádanky', 1, 'Aká je farba hrachu?', 'Zelená'),
('Logika a hádanky', 1, 'Aký je opak slnka?', 'Mesiac'),
('Logika a hádanky', 1, 'Ktoré zviera je známe svojou pomalosťou?', 'Želva'),
('Logika a hádanky', 1, 'Aké je hlavné mesto Talianska?', 'Rím'),
('Logika a hádanky', 1, 'Koľko písmen má abeceda?', 'Dvadsťšesť'),
('Logika a hádanky', 1, 'Aký je najbežnejší jazyk na svete?', 'Mandarínčina'),
('Logika a hádanky', 1, 'Koľko farieb má dúha?', 'Sedem'),
('Logika a hádanky', 1, 'Čo je to, čo je v noci a nie je to deň?', 'Tma'),
('Logika a hádanky', 1, 'Aký je opak hmoty?', 'Prázdnota'),
('Logika a hádanky', 1, 'Aké číslo je nula plus nula?', 'Nula'),
('Logika a hádanky', 1, 'Koľko mesiacov má február v normálnom roku?', 'Dva'),
('Logika a hádanky', 1, 'Aký tvar má veľký štvoruholník?', 'Obdĺžnik'),
('Logika a hádanky', 1, 'Aké zviera sa považuje za najrýchlejšie na súši?', 'Gepard'),
('Logika a hádanky', 1, 'Čo sa vždy pohybuje, ale nikdy sa nezastaví?', 'Čas'),
('Logika a hádanky', 1, 'Koľko prstov má človek na oboch rukách?', 'Desať'),
('Logika a hádanky', 1, 'Aké zviera je známe svojím hlasným krikom?', 'Sova'),
('Logika a hádanky', 1, 'Koľko dní má apríl?', 'Tridsať'),
('Logika a hádanky', 1, 'Aký tvar má guľa?', 'Kruh'),
('Logika a hádanky', 1, 'Čo je to, čo je čierne a biele a je to zviera?', 'Panda'),
('Logika a hádanky', 1, 'Koľko mesiacov má rok v letnom období?', 'Tri'),
('Logika a hádanky', 1, 'Akú farbu má zmrzlina z jahôd?', 'Ružová'),
('Logika a hádanky', 1, 'Koľko žiaroviek je v bežnej lampe?', 'Jedna'),
('Logika a hádanky', 1, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'Myšlienka'),
('Logika a hádanky', 1, 'Aký je opak tepla?', 'Chlad'),
('Logika a hádanky', 1, 'Koľko strán má štvorec?', 'Štyri'),
('Logika a hádanky', 1, 'Čo má štyri nohy a spí na zemi?', 'Stôl'),
('Logika a hádanky', 1, 'Koľko farieb je v základnej palete?', 'Štyri'),
('Logika a hádanky', 1, 'Aké je opak šťastia?', 'Smútenie'),
('Logika a hádanky', 1, 'Čo je to, čo si oblečieš, ale nikdy to nevidíš?', 'Pokožka'),
('Logika a hádanky', 1, 'Koľko očí má človek?', 'Dve'),
('Logika a hádanky', 1, 'Aký je opak hory?', 'Dolina'),
('Logika a hádanky', 1, 'Čo je to, čo má štyri rohy a nie je to dom?', 'Stôl'),
('Logika a hádanky', 1, 'Aké zviera je najnižšie na svete?', 'Jelen'),
('Logika a hádanky', 1, 'Koľko prstov má človek na nohách?', 'Dvadsať'),
('Logika a hádanky', 1, 'Aký je opak dať?', 'Zobrať'),
('Logika a hádanky', 1, 'Čo je to, čo vidíš, ale nedotýkaš sa?', 'Svetlo'),
('Logika a hádanky', 1, 'Koľko mesiacov má rok v zime?', 'Štyri'),
('Logika a hádanky', 1, 'Aké je opak pravdy?', 'Lož'),
('Logika a hádanky', 1, 'Čo je to, čo sa nikdy nesníva?', 'Skutočnosť'),
('Logika a hádanky', 1, 'Aký je najmenší kontinent?', 'Austrália'),
('Logika a hádanky', 1, 'Koľko zubov má dieťa?', 'Dvadsať'),
('Logika a hádanky', 1, 'Aké je opak ticha?', 'Hlas'),
('Logika a hádanky', 1, 'Čo je to, čo je vo vzduchu, ale nie je to vták?', 'Vietor'),
('Logika a hádanky', 1, 'Koľko očí má mačka?', 'Dve'),
('Logika a hádanky', 1, 'Aký je opak hmoty?', 'Prázdnota'),
('Logika a hádanky', 1, 'Čo je to, čo je vždy s tebou, ale nie je to viditeľné?', 'Duša'),
('Logika a hádanky', 1, 'Koľko mesiacov má jún?', 'Jeden'),
('Logika a hádanky', 1, 'Aký je opak šedého?', 'Farebný'),
('Logika a hádanky', 1, 'Čo je to, čo prekoná každú prekážku?', 'Vôľa'),
('Logika a hádanky', 1, 'Koľko strán má šesťuholník?', 'Šesť'),
('Logika a hádanky', 1, 'Aký je opak pobrežia?', 'Hlbina'),
('Logika a hádanky', 1, 'Čo je to, čo má jazyk, ale nič nehovorí?', 'Okenná roleta'),
('Logika a hádanky', 1, 'Koľko písmen má slovo "auto"?', 'Štyri'),
('Logika a hádanky', 1, 'Aký je opak zima?', 'Leto'),
('Logika a hádanky', 1, 'Čo je to, čo sa nedá zjesť na raňajky?', 'Hory'),
('Logika a hádanky', 1, 'Koľko mesiacov má september?', 'Jeden'),
('Logika a hádanky', 1, 'Aký je opak pod?', 'Nad'),
('Logika a hádanky', 1, 'Čo je to, čo sa nedá vidieť, ale cítiť?', 'Vôňa'),
('Logika a hádanky', 1, 'Koľko farieb má základná paleta?', 'Štyri'),
('Logika a hádanky', 1, 'Aký je opak dažďa?', 'Slnečno'),
('Logika a hádanky', 1, 'Čo je to, čo má jedno krídlo, ale nelieta?', 'Dvere'),
('Logika a hádanky', 1, 'Koľko prstov má človek na nohách?', 'Dvadsať'),
('Logika a hádanky', 2, 'Aký je opak pravdy?', 'Lož'),
('Logika a hádanky', 2, 'Čo je to, čo sa stále pohybuje, ale nikdy neodíde?', 'Hodiny'),
('Logika a hádanky', 2, 'Koľko mesiacov má apríl?', 'Jeden'),
('Logika a hádanky', 2, 'Aký tvar má koláč?', 'Kruhový'),
('Logika a hádanky', 2, 'Čo je to, čo sa dá zlomiť, ale nie je to fyzické?', 'Sľub'),
('Logika a hádanky', 2, 'Koľko hviezd je na vlajke USA?', 'Pätnásť'),
('Logika a hádanky', 2, 'Aký je opak dňa?', 'Noc'),
('Logika a hádanky', 2, 'Kto je známy ako kráľ zvierat?', 'Lev'),
('Logika a hádanky', 2, 'Čo je to, čo je vždy pred tebou, ale nikdy to nevidíš?', 'Budúcnosť'),
('Logika a hádanky', 2, 'Aké je opak tepla?', 'Zima'),
('Logika a hádanky', 2, 'Koľko strán má päťuholník?', 'Päť'),
('Logika a hádanky', 2, 'Čo je to, čo má klobúk, ale nie je to hlava?', 'Huba'),
('Logika a hádanky', 2, 'Aký je opak lásky?', 'Nenávisť'),
('Logika a hádanky', 2, 'Koľko mesiacov má rok?', 'Dvanásť'),
('Logika a hádanky', 2, 'Aké zviera je známe svojou pomalosťou?', 'Želva'),
('Logika a hádanky', 2, 'Aký je opak slnka?', 'Mesiac'),
('Logika a hádanky', 2, 'Čo je to, čo má chvost, ale nie je to zviera?', 'Kométa'),
('Logika a hádanky', 2, 'Čo je to, čo je vo vnútri, ale von to nevidíš?', 'Srdce'),
('Logika a hádanky', 2, 'Ktoré ovocie je známe ako "kráľovná ovocia"?', 'Mango'),
('Logika a hádanky', 2, 'Čo je to, čo je hmotné, ale nie je to viditeľné?', 'Vzduch'),
('Logika a hádanky', 2, 'Aký je opak pravej?', 'Ľavá'),
('Logika a hádanky', 2, 'Čo je to, čo ti patrí, ale ostatní to používajú častejšie?', 'Meno'),
('Logika a hádanky', 2, 'Aké číslo je 2 plus 2?', 'Štyri'),
('Logika a hádanky', 2, 'Koľko prstov má človek na oboch rukách?', 'Desať'),
('Logika a hádanky', 2, 'Aké zviera je známe svojou pomalosťou?', 'Slon'),
('Logika a hádanky', 2, 'Kto je najznámejší detektív v literatúre?', 'Holmes'),
('Logika a hádanky', 2, 'Čo je to, čo má jazyk, ale nehovorí?', 'Topánka'),
('Logika a hádanky', 2, 'Koľko rokov má dospelý človek?', 'Dvadsať'),
('Logika a hádanky', 2, 'Aké je opak šťastia?', 'Nešťastie'),
('Logika a hádanky', 2, 'Čo je to, čo má štyri rohy a nie je to zviera?', 'Stôl'),
('Logika a hádanky', 2, 'Aký je opak bielej?', 'Čierna'),
('Logika a hádanky', 2, 'Čo je to, čo sa dá zjesť, ale nie je to jedlo?', 'Slovo'),
('Logika a hádanky', 2, 'Aký je opak neba?', 'Pôda'),
('Logika a hádanky', 2, 'Čo je to, čo má štyri nohy a spí na zemi?', 'Pes'),
('Logika a hádanky', 2, 'Ktoré zviera je známe svojim štekaním?', 'Pes'),
('Logika a hádanky', 2, 'Aký je opak šťastia?', 'Smutok'),
('Logika a hádanky', 2, 'Čo je to, čo sa nedá zjesť na raňajky?', 'Kameň'),
('Logika a hádanky', 2, 'Koľko strán má štvorec?', 'Štyri'),
('Logika a hádanky', 2, 'Aký je opak šedého?', 'Farebný'),
('Logika a hádanky', 2, 'Čo je to, čo sa ti páči, ale nie je to hmotné?', 'Myšlienka'),
('Logika a hádanky', 2, 'Koľko mesiacov má rok v zime?', 'Tri'),
('Logika a hádanky', 2, 'Aký je opak ticha?', 'Hlas'),
('Logika a hádanky', 2, 'Čo je to, čo má oči, ale nevidí?', 'Búran'),
('Logika a hádanky', 2, 'Koľko prstov má človek na nohách?', 'Dvadsať'),
('Logika a hádanky', 2, 'Aký je opak chudoby?', 'Bohatstvo'),
('Logika a hádanky', 2, 'Čo je to, čo sa nikdy nevráti?', 'Čas'),
('Logika a hádanky', 2, 'Koľko dní má február?', 'Dvadsaťosem'),
('Logika a hádanky', 2, 'Aký je opak zima?', 'Leto'),
('Logika a hádanky', 2, 'Čo je to, čo má jazyk, ale nič nehovorí?', 'Mapa'),
('Logika a hádanky', 2, 'Koľko mesiacov má rok v lete?', 'Štyri'),
('Logika a hádanky', 2, 'Aký je opak pravdy?', 'Lož'),
('Logika a hádanky', 2, 'Aký je najznámejší symbol lásky?', 'srdce'),
('Logika a hádanky', 2, 'Ktoré zviera je známe pre svoju múdrosť?', 'sova'),
('Logika a hádanky', 2, 'Aký je opak dlhého?', 'krátky'),
('Logika a hádanky', 2, 'Čo sa vždy pohybuje, ale nikdy sa nezastaví?', 'čas'),
('Logika a hádanky', 2, 'Koľko mesiacov má rok v normálnom roku?', 'dvanásť'),
('Logika a hádanky', 2, 'Aký je najčastejší tvar v architektúre?', 'štvorec'),
('Logika a hádanky', 2, 'Čo je to, čo sa nedá vidieť, ale cítiť?', 'vzduch'),
('Logika a hádanky', 2, 'Ktoré číslo je nula plus jeden?', 'jeden'),
('Logika a hádanky', 2, 'Aká je farba pečeného chleba?', 'hnedá'),
('Logika a hádanky', 2, 'Čo je to, čo sa môže zlomiť, ale nie je to fyzické?', 'sľub'),
('Logika a hádanky', 2, 'Aká je farba ľadu?', 'biela'),
('Logika a hádanky', 2, 'Čo je to, čo je vždy s tebou, ale nie je to viditeľné?', 'myšlienky'),
('Logika a hádanky', 2, 'Aký je opak lásky?', 'nenávisť'),
('Logika a hádanky', 2, 'Koľko farieb má dúha?', 'sedem'),
('Logika a hádanky', 2, 'Čo je to, čo je vo vnútri, ale von to nevidíš?', 'tajomstvo'),
('Logika a hádanky', 2, 'Aký tvar má čtverec?', 'štvorec'),
('Logika a hádanky', 2, 'Ktoré ovocie je známe svojou kyslosťou?', 'citrón'),
('Logika a hádanky', 2, 'Čo je to, čo má jazyk, ale nehovorí?', 'hodiny'),
('Logika a hádanky', 2, 'Aký je opak klidného?', 'hlučný'),
('Logika a hádanky', 2, 'Koľko mesiacov má rok v lete?', 'tri'),
('Logika a hádanky', 2, 'Aký je najmenší kontinent?', 'Austrália'),
('Logika a hádanky', 2, 'Čo je to, čo je vo vode, ale nie je to ryba?', 'lode'),
('Logika a hádanky', 2, 'Aké je opak nového?', 'starý'),
('Logika a hádanky', 2, 'Čo je to, čo sa dá spáliť, ale nie je to jedlo?', 'papier'),
('Logika a hádanky', 2, 'Ktoré zviera je známe svojím spevom?', 'vták'),
('Logika a hádanky', 2, 'Aký je opak tmy?', 'svetlo'),
('Logika a hádanky', 2, 'Koľko prstov má človek na jednej ruke?', 'päť'),
('Logika a hádanky', 2, 'Čo je to, čo je vždy pred tebou, ale nikdy to nevidíš?', 'budúcnosť'),
('Logika a hádanky', 2, 'Aký je opak pravej?', 'ľavá'),
('Logika a hádanky', 2, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'myšlienka'),
('Logika a hádanky', 2, 'Koľko strán má osemuholník?', 'osem'),
('Logika a hádanky', 2, 'Aký je opak dňa?', 'noc'),
('Logika a hádanky', 2, 'Čo je to, čo má nohy, ale nechodí?', 'stôl'),
('Logika a hádanky', 2, 'Aká je farba mlieka?', 'biela'),
('Logika a hádanky', 2, 'Koľko strán má päťuholník?', 'päť'),
('Logika a hádanky', 2, 'Čo je to, čo je vo vzduchu, ale nie je to vták?', 'prach'),
('Logika a hádanky', 2, 'Aký je opak úspechu?', 'neúspech'),
('Logika a hádanky', 2, 'Ktoré zviera je známe svojou rýchlosťou?', 'kôň'),
('Logika a hádanky', 2, 'Čo je to, čo nemá hmotnosť, ale môže ťa ťažiť?', 'starosti'),
('Logika a hádanky', 2, 'Aká farba je spojená s láskou?', 'červená'),
('Logika a hádanky', 2, 'Koľko písmen je v slove "dom"?', 'tri'),
('Logika a hádanky', 2, 'Čo je to, čo sa nedá vidieť, ale cítiť?', 'emócie'),
('Logika a hádanky', 2, 'Aký je opak slnka?', 'mesiac'),
('Logika a hádanky', 2, 'Čo je to, čo sa nedá zjesť na obed?', 'snívanie'),
('Logika a hádanky', 2, 'Koľko mesiacov má rok v zime?', 'tri'),
('Logika a hádanky', 2, 'Čo je to, čo má oči, ale nevidí?', 'zrkadlo'),
('Logika a hádanky', 2, 'Aký je najčastejší tvar v prírode?', 'kruh'),
('Logika a hádanky', 2, 'Čo je to, čo môžeš získať, ale nikdy to nevidíš?', 'vedomosti'),
('Logika a hádanky', 2, 'Aký je opak svetla?', 'tma'),
('Logika a hádanky', 2, 'Čo je to, čo sa stále pohybuje, ale nikdy neodíde?', 'čas'),
('Logika a hádanky', 2, 'Koľko strán má trojuholník?', 'tri'),
('Logika a hádanky', 2, 'Čo je to, čo je čierne a biele?', 'panda'),
('Logika a hádanky', 2, 'Aký je opak mŕtveho?', 'živý'),
('Logika a hádanky', 3, 'Čo je to, čo je vždy s tebou, ale nie je to viditeľné?', 'Duša'),
('Logika a hádanky', 3, 'Čo je to, čo sa nikdy nevráti?', 'Minulosť'),
('Logika a hádanky', 3, 'Aký je opak šťastia?', 'Smútenie'),
('Logika a hádanky', 3, 'Kto je najznámejší detektív v literatúre?', 'Sherlock Holmes'),
('Logika a hádanky', 3, 'Čo je to, čo sa nedá zjesť na raňajky?', 'Noc'),
('Logika a hádanky', 3, 'Kde sa nachádza najhlbšie miesto na Zemi?', 'Mariánsky priekop'),
('Logika a hádanky', 3, 'Čo je to, čo má jazyk, ale nehovorí?', 'Topánka'),
('Logika a hádanky', 3, 'Ktoré číslo je nula plus jeden?', 'Jedna'),
('Logika a hádanky', 3, 'Kto je známy ako kráľ zvierat?', 'Lev'),
('Logika a hádanky', 3, 'Čo je to, čo vidíš, ale nedotýkaš sa?', 'Vzduch'),
('Logika a hádanky', 3, 'Aké číslo je nula plus nula?', 'Nula'),
('Logika a hádanky', 3, 'Čo je to, čo nemá hmotnosť, ale môže ťa ťažiť?', 'Pocit'),
('Logika a hádanky', 3, 'Kto je známy svojou múdrosťou?', 'Sova'),
('Logika a hádanky', 3, 'Čo je to, čo prekoná každú prekážku?', 'Vôľa'),
('Logika a hádanky', 3, 'Aký je opak lásky?', 'Nenávisť'),
('Logika a hádanky', 3, 'Aký je najčastejší tvar v architektúre?', 'Kvádr'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'Myšlienka'),
('Logika a hádanky', 3, 'Čo sa vždy pohybuje, ale nikdy sa nezastaví?', 'Čas'),
('Logika a hádanky', 3, 'Čo je to, čo je vo vnútri, ale von to nevidíš?', 'Srdce'),
('Logika a hádanky', 3, 'Aký je opak klidného?', 'Búrlivý'),
('Logika a hádanky', 3, 'Čo je to, čo má nohy, ale nechodí?', 'Stôl'),
('Logika a hádanky', 3, 'Ktoré zviera je známe svojou rýchlosťou?', 'Gepard'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá zlomiť, ale nie je to fyzické?', 'Sľub'),
('Logika a hádanky', 3, 'Aký je opak úspechu?', 'Zlyhanie'),
('Logika a hádanky', 3, 'Čo je to, čo má štyri nohy a nie je to zviera?', 'Stôl'),
('Logika a hádanky', 3, 'Aký je opak dňa?', 'Noc'),
('Logika a hádanky', 3, 'Čo je to, čo nemôžeš chytiť, ale môžeš to cítiť?', 'Vzduch'),
('Logika a hádanky', 3, 'Kto je známy pre svoju múdrosť?', 'Sova'),
('Logika a hádanky', 3, 'Čo je to, čo má oči, ale nevidí?', 'Zrno'),
('Logika a hádanky', 3, 'Čo je to, čo je vo vode, ale nie je to ryba?', 'Lodný'),
('Logika a hádanky', 3, 'Ktoré ovocie je známe svojou kyslosťou?', 'Citrón'),
('Logika a hádanky', 3, 'Čo je to, čo sa nedá vidieť, ale cítiť?', 'Láska'),
('Logika a hádanky', 3, 'Aký je opak tmy?', 'Svetlo'),
('Logika a hádanky', 3, 'Čo je to, čo sa nedá zjesť na obed?', 'Noc'),
('Logika a hádanky', 3, 'Aký je opak bielej?', 'Čierna'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá zlomiť, ale nie je to fyzické?', 'Sľub'),
('Logika a hádanky', 3, 'Kto je známy pre svoj spev?', 'Slávik'),
('Logika a hádanky', 3, 'Čo je to, čo je vo vzduchu, ale nie je to vták?', 'Prach'),
('Logika a hádanky', 3, 'Kde sa nachádza najväčší vodopád?', 'Angel'),
('Logika a hádanky', 3, 'Čo je to, čo je vždy pred tebou, ale nikdy to nevidíš?', 'Budúcnosť'),
('Logika a hádanky', 3, 'Aký je opak tepla?', 'Chlad'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'Myšlienka'),
('Logika a hádanky', 3, 'Čo je to, čo má štyri rohy a nie je to dom?', 'Stôl'),
('Logika a hádanky', 3, 'Ktoré zviera je známe svojim štekaním?', 'Pes'),
('Logika a hádanky', 3, 'Čo je to, čo sa nikdy nesníva?', 'Realita'),
('Logika a hádanky', 3, 'Aký je opak pravdy?', 'Lož'),
('Logika a hádanky', 3, 'Čo je to, čo je vždy s tebou, ale nie je to viditeľné?', 'Tajomstvo'),
('Logika a hádanky', 3, 'Čo je to, čo nemôžeš chytiť, ale môžeš to cítiť?', 'Vzduch'),
('Logika a hádanky', 3, 'Aká je farba zeme počas dažďa?', 'Hnedá'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'Myšlienka'),
('Logika a hádanky', 3, 'Kto je známy svojou múdrosťou?', 'Sofokles'),
('Logika a hádanky', 3, 'Čo je to, čo má jazyk, ale nič nehovorí?', 'Mapa'),
('Logika a hádanky', 3, 'Kde sa nachádza najväčší vodopád?', 'Venezuela'),
('Logika a hádanky', 3, 'Čo je to, čo má štyri nohy a nie je to zviera?', 'Stôl'),
('Logika a hádanky', 3, 'Aký je opak pravdy?', 'Lož'),
('Logika a hádanky', 3, 'Čo je to, čo sa nedá vidieť, ale môžeš to cítiť?', 'Láska'),
('Logika a hádanky', 3, 'Kto je známy pre svoj spev?', 'Pavarotti'),
('Logika a hádanky', 3, 'Čo je to, čo nemá hmotnosť, ale môže ťa ťažiť?', 'Svedomie'),
('Logika a hádanky', 3, 'Aké je opak klidného?', 'Rozrušený'),
('Logika a hádanky', 3, 'Čo je to, čo prekoná každú prekážku?', 'Odvaha'),
('Logika a hádanky', 3, 'Kde sa nachádza najväčší oceán?', 'Tichý'),
('Logika a hádanky', 3, 'Čo je to, čo je vo vzduchu, ale nie je to vták?', 'Prach'),
('Logika a hádanky', 3, 'Aké číslo je nula plus dva?', 'Dva'),
('Logika a hádanky', 3, 'Čo je to, čo má oči, ale nevidí?', 'Hrnček'),
('Logika a hádanky', 3, 'Kto je známy ako kráľ zvierat?', 'Lev'),
('Logika a hádanky', 3, 'Čo je to, čo je vo vode, ale nie je to ryba?', 'Sneh'),
('Logika a hádanky', 3, 'Aké je opak mŕtveho?', 'Živý'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá zlomiť, ale nie je to fyzické?', 'Srdce'),
('Logika a hádanky', 3, 'Aký je opak šťastia?', 'Smútenie'),
('Logika a hádanky', 3, 'Čo je to, čo je vždy pred tebou, ale nikdy to nevidíš?', 'Budúcnosť'),
('Logika a hádanky', 3, 'Kde sa nachádza najhlbšie miesto na Zemi?', 'Mariánska priekopa'),
('Logika a hádanky', 3, 'Čo je to, čo má štyri rohy a nie je to dom?', 'Stôl'),
('Logika a hádanky', 3, 'Čo je to, čo je čierne a biele?', 'Panda'),
('Logika a hádanky', 3, 'Aké je opak tmy?', 'Svetlo'),
('Logika a hádanky', 3, 'Čo je to, čo sa nedá zjesť na obed?', 'Slnko'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'Emócia'),
('Logika a hádanky', 3, 'Kedy je najlepší čas na spánok?', 'Noc'),
('Logika a hádanky', 3, 'Čo je to, čo má klobúk, ale nie je to hlava?', 'Huba'),
('Logika a hádanky', 3, 'Aké je opak šťastia?', 'Nešťastie'),
('Logika a hádanky', 3, 'Čo je to, čo je v noci a nie je to deň?', 'Tma'),
('Logika a hádanky', 3, 'Kto je známy pre svoj spev?', 'Madonna'),
('Logika a hádanky', 3, 'Čo je to, čo sa nedá vidieť, ale môžeš to cítiť?', 'Emócia'),
('Logika a hádanky', 3, 'Aký je opak dňa?', 'Noc'),
('Logika a hádanky', 3, 'Čo je to, čo má oči, ale nevidí?', 'Hrnček'),
('Logika a hádanky', 3, 'Čo je to, čo sa môže zlomiť, ale nie je to fyzické?', 'Srdce'),
('Logika a hádanky', 3, 'Kto je známy ako kráľ zvierat?', 'Lev'),
('Logika a hádanky', 3, 'Čo je to, čo je vo vzduchu, ale nie je to vták?', 'Prach'),
('Logika a hádanky', 3, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'Myšlienka'),
('Logika a hádanky', 3, 'Aké je opak klidného?', 'Rozrušený'),
('Logika a hádanky', 3, 'Čo je to, čo je vo vode, ale nie je to ryba?', 'Sneh'),
('Logika a hádanky', 3, 'Čo je to, čo nemôžeš chytiť, ale môžeš to cítiť?', 'Vzduch'),
('Logika a hádanky', 3, 'Čo je to, čo je vždy s tebou, ale nie je to viditeľné?', 'Tajomstvo'),
('Logika a hádanky', 3, 'Aké číslo je nula plus dva?', 'Dva'),
('Logika a hádanky', 3, 'Čo je to, čo prekoná každú prekážku?', 'Odvaha'),
('Logika a hádanky', 3, 'Čo je to, čo má klobúk, ale nie je to hlava?', 'Huba'),
('Logika', 3, 'Čo sa môže zlomiť, ale nie je to fyzické?', 'sľub'),
('Logika', 3, 'Čo je to, čo má jazyk, ale nič nehovorí?', 'topánka'),
('Logika', 3, 'Čo je to, čo je vo vnútri, ale von to nevidíš?', 'myseľ'),
('Logika', 3, 'Čo je to, čo sa dá preniesť, ale nie je to hmotné?', 'myšlienka'),
('Logika', 3, 'Čo je to, čo prekoná každú prekážku?', 'čas'),
('Logika', 3, 'Koľko mesiacov má rok v priestore?', 'dvanásť'),
('Logika', 3, 'Aký je opak pravdy?', 'loš'),
('Logika', 3, 'Čo je to, čo sa nikdy nevráti?', 'minulosť'),
('Logika', 3, 'Čo je to, čo sa vždy pohybuje, ale nikdy sa nezastaví?', 'čas'),
('Logika', 3, 'Čo je to, čo má štyri nohy a nie je to zviera?', 'stôl'),
('Logika', 3, 'Čo je to, čo letí, ale nemá krídla?', 'myšlienka'),
('Logika', 3, 'Aký je opak dňa?', 'noc'),
('Logika', 3, 'Čo je to, čo má klobúk a nechodí?', 'hubka'),
('Logika', 3, 'Aký je opak tepla?', 'chlad');