INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Politika', 3, 'Kto je predsedom strany Smer?', 'Fico'),
('Politika', 3, 'Kto je prezidentom Zeleného mysu?', 'Ramaphosa'),
('Politika', 3, 'Kto je predsedom strany PS?', 'Heger'),
('Politika', 3, 'Kto je prezidentom Bahrajnu?', 'Hamad'),
('Politika', 3, 'Kto je predsedom vlády Talianska?', 'Meloni'),
('Politika', 3, 'Kto je predsedom strany SPD v Nemecku?', 'Kahrs'),
('Politika', 3, 'Kto je prezidentom Fínska?', 'Niinistö'),
('Politika', 3, 'Kto je predsedom vlády Švajčiarska?', 'Berset'),
('Politika', 3, 'Kto je predsedom strany PIS v Poľsku?', 'Kaczyński'),
('Politika', 3, 'Kto je predsedom vlády Talianska?', 'Meloni'),
('Politika', 3, 'Kto je prezidentom Turecka?', 'Erdogan'),
('Politika', 3, 'Kto je predsedom strany ANO v Česku?', 'Babiš'),
('Politika', 3, 'Kto je prezidentom Mexika?', 'López'),
('Politika', 3, 'Kto je predsedom strany Rassemblement?', 'Le Pen'),
('Politika', 3, 'Kto je prezidentom Srbska?', 'Vučić'),
('Politika', 3, 'Kto je predsedom vlády Rakúska?', 'Nehammer'),
('Politika', 3, 'Kto je predsedom strany ODS v Česku?', 'Fiala'),
('Politika', 3, 'Kto je prezidentom Estónska?', 'Karise'),
('Politika', 3, 'Kto je predsedom strany Labour v Austrálii?', 'Albanese'),
('Politika', 3, 'Kto je prezidentom Slovinska?', 'Náci'),
('Politika', 3, 'Kto je predsedom strany FIDESZ v Maďarsku?', 'Orbán'),
('Politika', 3, 'Kto je predsedom strany CDU v Nemecku?', 'Merz'),
('Politika', 3, 'Kto je prezidentom Chorvátska?', 'Milanović'),
('Politika', 3, 'Kto je predsedom strany PS v Česku?', 'Bartoš'),
('Politika', 3, 'Kto je generálnym tajomníkom ÚN?', 'Guterres'),
('Politika', 3, 'Kto je predsedom strany Zelených v Nemecku?', 'Habeck'),
('Politika', 3, 'Kto je prezidentom Japonska?', 'Nakashima'),
('Politika', 3, 'Kto je predsedom strany Smer v Slovensku?', 'Fico'),
('Politika', 3, 'Kto je predsedom vlády Grécka?', 'Mitsotakis'),
('Politika', 3, 'Kto je predsedom strany Podemos v Španielsku?', 'Iglesias'),
('Politika', 3, 'Kto je prezidentom Kolumbie?', 'Petro'),
('Politika', 3, 'Kto je predsedom vlády Fínska?', 'Marin'),
('Politika', 3, 'Kto je prezidentom Litvy?', 'Nausėda'),
('Politika', 3, 'Kto je predsedom strany KDH na Slovensku?', 'Hrušovský'),
('Politika', 3, 'Kto je prezidentom Nigérie?', 'Tinubu'),
('Politika', 3, 'Kto je predsedom strany ANO v Slovensku?', 'Klein'),
('Politika', 3, 'Kto je predsedom vlády Švédska?', 'Kristersson'),
('Politika', 3, 'Kto je prezidentom Bahrajnu?', 'Hamad'),
('Politika', 3, 'Kto je predsedom strany FIDESZ v Maďarsku?', 'Orbán'),
('Politika', 3, 'Kto je predsedom strany Labour v UK?', 'Starmer'),
('Politika', 3, 'Kto je prezidentom Zimbabwe?', 'Mnangagwa'),
('Politika', 3, 'Kto je predsedom vlády Kanady?', 'Trudeau'),
('Politika', 3, 'Kto je prezidentom Malajzie?', 'Anwar'),
('Politika', 3, 'Kto je predsedom strany ČSSD v Česku?', 'Hamáček'),
('Politika', 3, 'Kto je prezidentom Gruzínska?', 'Zourabichvili'),
('Politika', 3, 'Kto je predsedom strany Rassemblement v Francúzsku?', 'Le Pen'),
('Politika', 3, 'Kto je prezidentom Ekvádoru?', 'Lasso'),
('Politika', 3, 'Kto je predsedom strany Smer v Slovensku?', 'Fico'),
('Politika', 3, 'Kto je predsedom vlády Talianska?', 'Meloni'),
('Politika', 3, 'Kto je prezidentom Kene?', 'Ruto'),
('Politika', 3, 'Kto je predsedom strany PZP v Slovensku?', 'Hirsch'),
('Politika', 3, 'Kto je prezidentom Moldavska?', 'Sandu'),
('Politika', 3, 'Kto je predsedom strany PS v Česku?', 'Bartoš'),
('Politika', 3, 'Kto je predsedom strany Zelených v Nemecku?', 'Habeck'),
('Politika', 3, 'Kto je prezidentom Južného Sudánu?', 'Kiir'),
('Politika', 3, 'Kto je predsedom vlády Turecka?', 'Erdogan'),
('Politika', 3, 'Kto je predsedom strany ANO v Česku?', 'Babiš'),
('Politika', 3, 'Kto je prezidentom Španielska?', 'Sánchez'),
('Politika', 3, 'Kto je predsedom strany PIS v Poľsku?', 'Kaczyński'),
('Politika', 3, 'Kto je predsedom strany CDU v Nemecku?', 'Merz'),
('Popkultúra', 1, 'Kto spieva hit "Shape of You"?', 'Ed Sheeran'),
('Popkultúra', 1, 'Ktorý film získal Oscara za najlepší film v roku 2020?', 'Parasite'),
('Popkultúra', 1, 'Kto je hlavnou postavou v seriáli "Friends"?', 'Rachel Green'),
('Popkultúra', 1, 'Ktorý spevák je známy ako "Král popu"?', 'Michael Jackson'),
('Popkultúra', 1, 'Kto hrá rolu Iron Mana vo filmoch Marvel?', 'Robert Downey'),
('Popkultúra', 1, 'Ktorý film je o dinosauroch a parku?', 'Jurassic Park'),
('Popkultúra', 1, 'Kto je autorom knihy "Harry Potter"?', 'J.K. Rowling'),
('Popkultúra', 1, 'Ktorá speváčka má hit "Bad Romance"?', 'Lady Gaga'),
('Popkultúra', 1, 'Kto režíroval film "Titanic"?', 'James Cameron'),
('Popkultúra', 1, 'Aký je názov populárneho reality show, kde sú "Súťažiaci"?', 'Survivor'),
('Popkultúra', 1, 'Ktorý spevák je známy ako "Beyoncé"?', 'Beyoncé'),
('Popkultúra', 1, 'Kto je postava vo filme "The Joker"?', 'Joaquin Phoenix'),
('Popkultúra', 1, 'Ktorá skupina spieva "Bohemian Rhapsody"?', 'Queen'),
('Popkultúra', 1, 'Kto je známy ako "Kardashianka"?', 'Kim Kardashian'),
('Popkultúra', 1, 'Ktorý film má postavu "Forrest Gump"?', 'Forrest Gump'),
('Popkultúra', 1, 'Kto hrá postavu "Hannibal Lecter"?', 'Anthony Hopkins'),
('Popkultúra', 1, 'Kto je autorom piesne "Someone Like You"?', 'Adele'),
('Popkultúra', 1, 'Ktorá herečka hrá "Wonder Woman"?', 'Gal Gadot'),
('Popkultúra', 1, 'Kto je speváčkou skupiny "No Doubt"?', 'Gwen Stefani'),
('Popkultúra', 1, 'Aký je názov populárneho sitcomu s rodinou Simpsonovcov?', 'The Simpsons'),
('Popkultúra', 1, 'Ktorý spevák má prezývku "The Weeknd"?', 'The Weeknd'),
('Popkultúra', 1, 'Kto je hlavnou postavou vo filme "Pirates of the Caribbean"?', 'Jack Sparrow'),
('Popkultúra', 1, 'Aký je názov populárneho tanečného filmu z 80-tych rokov?', 'Dirty Dancing'),
('Popkultúra', 1, 'Ktorý spevák je známy piesňou "Uptown Funk"?', 'Bruno Mars'),
('Popkultúra', 1, 'Kto hrá "Sherlock Holmes" vo filmových adaptáciách?', 'Robert Downey'),
('Popkultúra', 1, 'Ktorý film je o superhrdinoch z Marvelu?', 'Avengers'),
('Popkultúra', 1, 'Kto je hlavným protagonistom filmu "The Matrix"?', 'Neo'),
('Popkultúra', 1, 'Ktorá speváčka je známa ako "Pop Queen"?', 'Madonna'),
('Popkultúra', 1, 'Kto režíroval film "Inception"?', 'Christopher Nolan'),
('Popkultúra', 1, 'Ktorý spevák je známy ako "Prince of Pop"?', 'Justin Bieber'),
('Popkultúra', 1, 'Kto je známy ako "The Rock"?', 'Dwayne Johnson'),
('Popkultúra', 1, 'Ktorý film má postavu "Darth Vader"?', 'Star Wars'),
('Popkultúra', 1, 'Kto je autorom piesne "Rolling in the Deep"?', 'Adele'),
('Popkultúra', 1, 'Aký je názov populárneho seriálu o drakoch?', 'Game of Thrones'),
('Popkultúra', 1, 'Kto hrá postavu "Tony Stark"?', 'Robert Downey'),
('Popkultúra', 1, 'Ktorá speváčka je známa hitom "Shake It Off"?', 'Taylor Swift'),
('Popkultúra', 1, 'Kto je herec vo filme "Deadpool"?', 'Ryan Reynolds'),
('Popkultúra', 1, 'Ktorý spevák je známy ako "Mr. Worldwide"?', 'Pitbull'),
('Popkultúra', 1, 'Kto je známy ako "Queen of Soul"?', 'Aretha Franklin'),
('Popkultúra', 1, 'Ktorý film je o chlapcovi a jeho psovi?', 'Lassie'),
('Popkultúra', 1, 'Kto je hlavnou postavou v "The Crown"?', 'Queen Elizabeth'),
('Popkultúra', 1, 'Kto režíroval film "Pulp Fiction"?', 'Quentin Tarantino'),
('Popkultúra', 1, 'Ktorý spevák je známy ako "Hound Dog"?', 'Elvis Presley'),
('Popkultúra', 1, 'Kto je postava vo filme "Wonder Woman"?', 'Diana Prince'),
('Popkultúra', 1, 'Kto je autorom piesne "Like a Rolling Stone"?', 'Bob Dylan'),
('Popkultúra', 1, 'Kto hrá "Captain America"?', 'Chris Evans'),
('Popkultúra', 1, 'Ktorý film má postavu "Sherlock Holmes"?', 'Sherlock Holmes'),
('Popkultúra', 1, 'Kto je speváčkou skupiny "The Supremes"?', 'Diana Ross'),
('Popkultúra', 1, 'Ktorý film je o mágii a čarodejníkoch?', 'Fantastic Beasts'),
('Popkultúra', 1, 'Kto hrá postavu "Katniss Everdeen"?', 'Jennifer Lawrence'),
('Popkultúra', 1, 'Kto je kúzelník v "Harry Potter" sérii?', 'Harry Potter'),
('Popkultúra', 1, 'Ktorá skupina spieva "Rolling in the Deep"?', 'Adele'),
('Popkultúra', 1, 'Kto je známy ako "Queen B"?', 'Beyoncé'),
('Popkultúra', 1, 'Kto je autorom piesne "Thriller"?', 'Michael Jackson'),
('Popkultúra', 1, 'Ktorý film má postavu "James Bond"?', 'Skyfall'),
('Popkultúra', 1, 'Kto hrá "Black Widow" vo filmoch Marvel?', 'Scarlett Johansson'),
('Popkultúra', 1, 'Ktorý spevák je známy hitom "Firework"?', 'Katy Perry'),
('Popkultúra', 1, 'Kto je herec známy ako "Wolverine"?', 'Hugh Jackman'),
('Popkultúra', 1, 'Aký je názov populárneho sitcomu s "Frasier"?', 'Frasier'),
('Popkultúra', 1, 'Kto režíroval film "Avatar"?', 'James Cameron'),
('Popkultúra', 1, 'Ktorý spevák je známy ako "Mr. T"?', 'T-Pain'),
('Popkultúra', 1, 'Kto hrá postavu "Hermione Granger"?', 'Emma Watson'),
('Popkultúra', 1, 'Kto je spevákom skupiny "N''Sync"?', 'Justin Timberlake'),
('Popkultúra', 1, 'Ktorá herečka hrá postavu "Daenerys Targaryen"?', 'Emilia Clarke'),
('Popkultúra', 1, 'Kto je autorom piesne "I Will Always Love You"?', 'Whitney Houston'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Genie in a Bottle"?', 'Christina Aguilera'),
('Popkultúra', 1, 'Kto je režisér filmov "Star Wars"?', 'George Lucas'),
('Popkultúra', 1, 'Kto hrá "Bruce Wayne"?', 'Ben Affleck'),
('Popkultúra', 1, 'Kto je speváčkom skupiny "Green Day"?', 'Billie Joe'),
('Popkultúra', 1, 'Ktorý film má postavu "E.T."?', 'E.T.'),
('Popkultúra', 1, 'Kto je známy ako "The Boss"?', 'Bruce Springsteen'),
('Popkultúra', 1, 'Ktorá speváčka je známa ako "Material Girl"?', 'Madonna'),
('Popkultúra', 1, 'Kto hrá "Peter Parker"?', 'Tom Holland'),
('Popkultúra', 1, 'Kto je hlavnou postavou vo filme "The Lion King"?', 'Simba'),
('Popkultúra', 1, 'Kto je speváčkou známa ako "Diva"?', 'Mariah Carey'),
('Popkultúra', 1, 'Kto je herec vo filme "The Matrix"?', 'Keanu Reeves'),
('Popkultúra', 1, 'Kto je režisér filmu "Jurassic Park"?', 'Steven Spielberg'),
('Popkultúra', 1, 'Kto spieva "Just Dance"?', 'Lady Gaga'),
('Popkultúra', 1, 'Ktorý film má postavu "Rocky Balboa"?', 'Rocky'),
('Popkultúra', 1, 'Kto je speváčkou skupiny "The Cranberries"?', 'Dolores O''Riordan'),
('Popkultúra', 1, 'Kto hrá "Gandalf" vo filme "Pán prsteňov"?', 'Ian McKellen'),
('Popkultúra', 1, 'Kto je autorom piesne "Hey Jude"?', 'The Beatles'),
('Popkultúra', 1, 'Kto režíroval film "The Godfather"?', 'Francis Ford Coppola'),
('Popkultúra', 1, 'Kto je spevákom známy ako "The Kid"?', 'Kid Rock'),
('Popkultúra', 1, 'Kto hrá "Wonder Woman" vo filme?', 'Gal Gadot'),
('Popkultúra', 1, 'Kto je hlavnou postavou vo filme "Frozen"?', 'Elsa'),
('Popkultúra', 1, 'Kto je autorom piesne "Wonderwall"?', 'Oasis'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Royals"?', 'Lorde'),
('Popkultúra', 1, 'Kto je herec vo filme "The Pursuit of Happyness"?', 'Will Smith'),
('Popkultúra', 1, 'Kto je herečkou známa ako "The Bride"?', 'Uma Thurman'),
('Popkultúra', 1, 'Kto je spevákom známy ako "The Voice"?', 'Blake Shelton'),
('Popkultúra', 1, 'Kto je autorom piesne "Billie Jean"?', 'Michael Jackson'),
('Popkultúra', 1, 'Kto hrá "Thor" vo filmoch Marvel?', 'Chris Hemsworth'),
('Popkultúra', 1, 'Kto je režisér filmu "The Shining"?', 'Stanley Kubrick'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Bleeding Love"?', 'Leona Lewis'),
('Popkultúra', 1, 'Kto je autorom piesne "My Heart Will Go On"?', 'Celine Dion'),
('Popkultúra', 1, 'Kto je herec vo filme "Gladiator"?', 'Russell Crowe'),
('Popkultúra', 1, 'Kto je známy ako "Král rock and roll"?', 'Elvis Presley'),
('Popkultúra', 1, 'Kto je hviezdou filmu "Titanic"?', 'Leonardo DiCaprio'),
('Popkultúra', 1, 'Ktorý film je o superhrdinoch z DC?', 'Aquaman'),
('Popkultúra', 1, 'Kto je spevákom piesne "Hotline Bling"?', 'Drake'),
('Popkultúra', 1, 'Kto hrá "Peter Pan" v najnovšej adaptácii?', 'Hugh Jackman'),
('Popkultúra', 1, 'Kto je autorom hitu "Hello"?', 'Adele'),
('Popkultúra', 1, 'Kto je herečka známa ako "Scarlett O''Hara"?', 'Vivien Leigh'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Umbrella"?', 'Rihanna'),
('Popkultúra', 1, 'Kto režíroval film "Avatar"?', 'James Cameron'),
('Popkultúra', 1, 'Kto je spevákom piesne "Dancing with a Stranger"?', 'Sam Smith'),
('Popkultúra', 1, 'Kto je známy ako "The Material Girl"?', 'Madonna'),
('Popkultúra', 1, 'Kto hrá "Wolverine" vo filmových adaptáciách?', 'Hugh Jackman'),
('Popkultúra', 1, 'Kto je speváčka skupiny "The Pussycat Dolls"?', 'Nicole Scherzinger'),
('Popkultúra', 1, 'Kto je známy ako "Queen of Pop"?', 'Madonna'),
('Popkultúra', 1, 'Kto je herečka známa vo filme "Legally Blonde"?', 'Reese Witherspoon'),
('Popkultúra', 1, 'Kto je spevákom piesne "Senorita"?', 'Shawn Mendes'),
('Popkultúra', 1, 'Kto je hlavnou postavou v "The Office"?', 'Michael Scott'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Fight Song"?', 'Rachel Platten'),
('Popkultúra', 1, 'Kto je hlavnou postavou vo filme "The Hunger Games"?', 'Katniss Everdeen'),
('Popkultúra', 1, 'Kto je spevákom piesne "Stay"?', 'Rihanna'),
('Popkultúra', 1, 'Kto je herec známy ako "Iron Man"?', 'Robert Downey'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Shape of You"?', 'Ed Sheeran'),
('Popkultúra', 1, 'Kto je herec vo filme "The Matrix"?', 'Keanu Reeves'),
('Popkultúra', 1, 'Kto je spevákom piesne "Lose Yourself"?', 'Eminem'),
('Popkultúra', 1, 'Kto je speváčkou známa ako "Bey"?', 'Beyoncé'),
('Popkultúra', 1, 'Kto je herečka známa vo filme "The Devil Wears Prada"?', 'Anne Hathaway'),
('Popkultúra', 1, 'Kto je spevákom piesne "Viva La Vida"?', 'Coldplay'),
('Popkultúra', 1, 'Kto je herec známy ako "Batman"?', 'Christian Bale'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Chasing Cars"?', 'Snow Patrol'),
('Popkultúra', 1, 'Kto je herečka známa vo filme "Black Swan"?', 'Natalie Portman'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Toxic"?', 'Britney Spears'),
('Popkultúra', 1, 'Kto je herec známy ako "The Terminator"?', 'Arnold Schwarzenegger'),
('Popkultúra', 1, 'Kto je spevákom piesne "Rolling in the Deep"?', 'Adele'),
('Popkultúra', 1, 'Kto je herečka známa vo filme "A Star is Born"?', 'Lady Gaga'),
('Popkultúra', 1, 'Kto je spevákom hitu "All of Me"?', 'John Legend'),
('Popkultúra', 1, 'Kto je herec známy ako "Johnny Depp"?', 'Jack Sparrow'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "I Will Always Love You"?', 'Whitney Houston'),
('Popkultúra', 1, 'Kto je herečka známa vo filme "The Fault in Our Stars"?', 'Shailene Woodley'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Bad Guy"?', 'Billie Eilish'),
('Popkultúra', 1, 'Kto je herec známy ako "Indiana Jones"?', 'Harrison Ford'),
('Popkultúra', 1, 'Kto je spevákom piesne "Perfect"?', 'Ed Sheeran'),
('Popkultúra', 1, 'Kto je herec vo filme "Guardians of the Galaxy"?', 'Chris Pratt'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Halo"?', 'Beyoncé'),
('Popkultúra', 1, 'Kto je herec známy ako "Sherlock"?', 'Benedict Cumberbatch'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Firework"?', 'Katy Perry'),
('Popkultúra', 1, 'Kto je herec vo filme "The Imitation Game"?', 'Benedict Cumberbatch'),
('Popkultúra', 1, 'Kto je spevákom piesne "Take Me to Church"?', 'Hozier'),
('Popkultúra', 1, 'Kto je herečka známa vo filme "Wonder Woman"?', 'Gal Gadot'),
('Popkultúra', 1, 'Kto je speváčkou známa hitom "Let It Go"?', 'Idina Menzel'),
('Popkultúra', 2, 'Kto je spevákom piesne "Stay with Me"?', 'Sam Smith'),
('Popkultúra', 2, 'Ktorá herečka hrá postavu "Katniss Everdeen"?', 'Jennifer Lawrence'),
('Popkultúra', 2, 'Aký je názov populárneho seriálu o rodine Griffinovcov?', 'Family Guy'),
('Popkultúra', 2, 'Kto je režisér filmu "Django Unchained"?', 'Quentin Tarantino'),
('Popkultúra', 2, 'Ktorý spevák je známy ako "The Boss"?', 'Bruce Springsteen'),
('Popkultúra', 2, 'Kto hrá postavu "Jack Dawson" vo filme "Titanic"?', 'Leonardo DiCaprio'),
('Popkultúra', 2, 'Kto je autorom piesne "Umbrella"?', 'Rihanna'),
('Popkultúra', 2, 'Ktorý film má postavu "Hannibal Lecter"?', 'Silence of the Lambs'),
('Popkultúra', 2, 'Kto je spevákom piesne "Just the Way You Are"?', 'Bruno Mars'),
('Popkultúra', 2, 'Ktorá herečka hrá "Belle" vo filme "Beauty and the Beast"?', 'Emma Watson'),
('Popkultúra', 2, 'Kto je známy ako "Queen of Country"?', 'Dolly Parton'),
('Popkultúra', 2, 'Ktorý film je o superhrdinoch z Marvel Universe?', 'Avengers'),
('Popkultúra', 2, 'Kto je speváčkou piesne "Shake It Off"?', 'Taylor Swift'),
('Popkultúra', 2, 'Kto je herec známy ako "Hugh Jackman"?', 'Wolverine'),
('Popkultúra', 2, 'Ktorý spevák je známy hitom "Hello"?', 'Adele'),
('Popkultúra', 2, 'Kto je herečka známa vo filme "Lost in Translation"?', 'Scarlett Johansson'),
('Popkultúra', 2, 'Kto je režisér filmu "Inglourious Basterds"?', 'Quentin Tarantino'),
('Popkultúra', 2, 'Kto hrá "Aquaman" vo filmových adaptáciách?', 'Jason Momoa'),
('Popkultúra', 2, 'Kto je speváčkou známa hitom "Poker Face"?', 'Lady Gaga'),
('Popkultúra', 2, 'Ktorý film má postavu "Neo"?', 'The Matrix'),
('Popkultúra', 2, 'Kto je spevákom piesne "Blinding Lights"?', 'The Weeknd'),
('Popkultúra', 2, 'Kto je herečka vo filme "The Hunger Games"?', 'Jennifer Lawrence'),
('Popkultúra', 2, 'Kto je autorom piesne "Fight Song"?', 'Rachel Platten'),
('Popkultúra', 2, 'Ktorý film má postavu "Gollum"?', 'The Lord of the Rings'),
('Popkultúra', 2, 'Kto je herečka známa vo filme "The Notebook"?', 'Rachel McAdams'),
('Popkultúra', 2, 'Kto je spevákom piesne "Stay"?', 'Rihanna'),
('Popkultúra', 2, 'Ktorý film režíroval Christopher Nolan?', 'Inception'),
('Popkultúra', 2, 'Kto je spevákom hitu "Can''t Stop the Feeling"?', 'Justin Timberlake'),
('Popkultúra', 2, 'Kto hrá postavu "Darth Vader" v nových filmoch?', 'Hayden Christensen'),
('Popkultúra', 2, 'Ktorá herečka hrá "Mia" vo filme "La La Land"?', 'Emma Stone'),
('Popkultúra', 2, 'Kto je známy ako "King of Pop"?', 'Michael Jackson'),
('Popkultúra', 2, 'Kto je spevákom piesne "Rolling in the Deep"?', 'Adele'),
('Popkultúra', 2, 'Kto je herec z "The Shawshank Redemption"?', 'Tim Robbins'),
('Popkultúra', 2, 'Kto je speváčka známa hitom "Bad Romance"?', 'Lady Gaga'),
('Popkultúra', 2, 'Kto je autorom piesne "Smells Like Teen Spirit"?', 'Nirvana'),
('Popkultúra', 2, 'Ktorý film má postavu "Frodo"?', 'The Lord of the Rings'),
('Popkultúra', 2, 'Kto je herec známy ako "The Rock"?', 'Dwayne Johnson'),
('Popkultúra', 2, 'Kto je speváčkou známa hitom "Toxic"?', 'Britney Spears'),
('Popkultúra', 2, 'Kto hrá "Black Panther" vo filmoch Marvel?', 'Chadwick Boseman'),
('Popkultúra', 2, 'Kto je spevákom piesne "Shape of You"?', 'Ed Sheeran'),
('Popkultúra', 2, 'Kto je herečka vo filme "The Devil Wears Prada"?', 'Anne Hathaway'),
('Popkultúra', 2, 'Kto je spevákom hitu "Chasing Cars"?', 'Snow Patrol'),
('Popkultúra', 2, 'Kto je herec známy ako "The Joker"?', 'Joaquin Phoenix'),
('Popkultúra', 2, 'Kto je speváčkou známa hitom "Royals"?', 'Lorde'),
('Popkultúra', 2, 'Kto je režisér filmu "The Social Network"?', 'David Fincher'),
('Popkultúra', 2, 'Kto hrá "Wolverine" vo filme?', 'Hugh Jackman'),
('Popkultúra', 2, 'Kto je herec známy ako "Captain America"?', 'Chris Evans'),
('Popkultúra', 2, 'Kto je speváčka známa hitom "Sweet Child o'' Mine"?', 'Guns N'' Roses'),
('Popkultúra', 2, 'Kto je herec vo filme "The Revenant"?', 'Leonardo DiCaprio'),
('Popkultúra', 2, 'Kto je speváčkou známa hitom "Dancing Queen"?', 'ABBA'),
('Popkultúra', 2, 'Kto je speváčkou piesne "Thank U, Next"?', 'Ariana Grande'),
('Popkultúra', 2, 'Kto hrá "Deadpool" vo filmoch?', 'Ryan Reynolds'),
('Popkultúra', 2, 'Ktorý film je o skupine "Avengers"?', 'Avengers'),
('Popkultúra', 2, 'Kto je autorom piesne "Hello"?', 'Adele'),
('Popkultúra', 2, 'Ktorá herečka hrá "Harley Quinn"?', 'Margot Robbie'),
('Popkultúra', 2, 'Kto je spevákom piesne "Bleeding Love"?', 'Leona Lewis'),
('Popkultúra', 2, 'Kto režíroval film "Get Out"?', 'Jordan Peele'),
('Popkultúra', 2, 'Kto je speváčkou hitu "Rolling in the Deep"?', 'Adele'),
('Popkultúra', 2, 'Ktorý spevák je známy ako "Little Monster"?', 'Lady Gaga'),
('Popkultúra', 2, 'Kto hrá "Spider-Man" v najnovších filmoch?', 'Tom Holland'),
('Popkultúra', 2, 'Kto je režisér filmu "The Shape of Water"?', 'Guillermo del Toro'),
('Popkultúra', 2, 'Kto je speváčkou skupiny "Fifth Harmony"?', 'Camila Cabello'),
('Popkultúra', 2, 'Kto je autorom piesne "Shake It Off"?', 'Taylor Swift'),
('Popkultúra', 2, 'Kto hrá "Loki" vo filmoch Marvel?', 'Tom Hiddleston'),
('Popkultúra', 2, 'Kto je spevákom piesne "Bad Liar"?', 'Imagine Dragons'),
('Popkultúra', 2, 'Ktorý film má postavu "Joker"?', 'Joker'),
('Popkultúra', 2, 'Kto je herečka známa ako "Katniss"?', 'Jennifer Lawrence'),
('Popkultúra', 2, 'Kto je spevákom piesne "Perfect"?', 'Ed Sheeran'),
('Popkultúra', 2, 'Kto režíroval film "The Irishman"?', 'Martin Scorsese'),
('Popkultúra', 2, 'Kto je speváčkou známa hitom "Work"?', 'Rihanna'),
('Popkultúra', 2, 'Kto je autorom piesne "Take a Bow"?', 'Rihanna'),
('Popkultúra', 2, 'Kto hrá "Wonder Woman" v DC filmoch?', 'Gal Gadot'),
('Popkultúra', 2, 'Kto je spevákom piesne "Stay"?', 'The Kid LAROI'),
('Popkultúra', 2, 'Kto režíroval "La La Land"?', 'Damien Chazelle'),
('Popkultúra', 2, 'Kto je speváčkou piesne "Fight Song"?', 'Rachel Platten'),
('Popkultúra', 2, 'Kto je herečka známa ako "Black Widow"?', 'Scarlett Johansson'),
('Popkultúra', 2, 'Kto hrá "Doctor Strange" vo filmoch Marvel?', 'Benedict Cumberbatch'),
('Popkultúra', 2, 'Kto je speváčkou známa hitom "Halo"?', 'Beyoncé'),
('Popkultúra', 2, 'Ktorý film má postavu "Groot"?', 'Guardians'),
('Popkultúra', 2, 'Kto je spevákom piesne "Believer"?', 'Imagine Dragons'),
('Popkultúra', 2, 'Kto režíroval film "Once Upon a Time in Hollywood"?', 'Quentin Tarantino'),
('Popkultúra', 2, 'Kto je herec vo filme "The Great Gatsby"?', 'Leonardo DiCaprio'),
('Popkultúra', 2, 'Kto je speváčkou piesne "Hotline Bling"?', 'Drake'),
('Popkultúra', 2, 'Kto hrá "Aquaman" vo filmových adaptáciách?', 'Jason Momoa'),
('Popkultúra', 2, 'Kto je spevákom piesne "Havana"?', 'Camila Cabello'),
('Popkultúra', 2, 'Kto je herečka vo filme "The Princess Diaries"?', 'Anne Hathaway'),
('Popkultúra', 2, 'Kto je autorom piesne "All of Me"?', 'John Legend'),
('Popkultúra', 2, 'Kto je speváčkou piesne "My Immortal"?', 'Evanescence'),
('Popkultúra', 2, 'Kto režíroval film "Black Panther"?', 'Ryan Coogler'),
('Popkultúra', 2, 'Kto je spevákom piesne "Wake Me Up"?', 'Avicii'),
('Popkultúra', 2, 'Ktorý film má postavu "Wolverine"?', 'X-Men'),
('Popkultúra', 2, 'Kto je speváčkou hitu "Chasing Cars"?', 'Snow Patrol'),
('Popkultúra', 2, 'Kto hrá "Captain Marvel"?', 'Brie Larson'),
('Popkultúra', 2, 'Kto je spevákom piesne "Starboy"?', 'The Weeknd'),
('Popkultúra', 2, 'Kto je herečka známa ako "Harley Quinn"?', 'Margot Robbie'),
('Popkultúra', 2, 'Kto je speváčkou piesne "Complicated"?', 'Avril Lavigne'),
('Popkultúra', 2, 'Kto je autorom piesne "Somebody That I Used to Know"?', 'Gotye'),
('Popkultúra', 2, 'Kto režíroval "The Revenant"?', 'Alejandro Iñárritu'),
('Popkultúra', 2, 'Kto je herec známy ako "Maverick"?', 'Tom Cruise'),
('Popkultúra', 2, 'Kto hrá "Elsa" vo filme "Frozen"?', 'Idina Menzel'),
('Popkultúra', 2, 'Kto je spevákom piesne "Bad Guy"?', 'Billie Eilish'),
('Popkultúra', 2, 'Kto je herečka vo filme "A Star is Born"?', 'Lady Gaga'),
('Popkultúra', 2, 'Kto je spevákom piesne "Uptown Funk"?', 'Bruno Mars'),
('Popkultúra', 2, 'Kto je autorom piesne "Lose Yourself"?', 'Eminem'),
('Popkultúra', 2, 'Kto režíroval "The Dark Knight"?', 'Christopher Nolan'),
('Popkultúra', 2, 'Kto je herec známy ako "Rocket Raccoon"?', 'Bradley Cooper'),
('Popkultúra', 2, 'Kto je speváčka známa hitom "Sucker"?', 'Jonas Brothers'),
('Popkultúra', 3, 'Kto je režisér filmu "Blade Runner 2049"?', 'Villeneuve'),
('Popkultúra', 3, 'Ktorý spevák je známy ako "Mr. Brightside"?', 'Flowers'),
('Popkultúra', 3, 'Kto hrá "Wanda Maximoff" vo filmoch Marvel?', 'Elizabeth Olsen'),
('Popkultúra', 3, 'Kto je autorom piesne "All Star"?', 'Smash Mouth'),
('Popkultúra', 3, 'Kto je hlavnou postavou v "Stranger Things"?', 'Eleven'),
('Popkultúra', 3, 'Kto režíroval film "Birdman"?', 'Iñárritu'),
('Popkultúra', 3, 'Ktorý herec hrá "James T. Kirk" v nových Star Trek filmoch?', 'Pine'),
('Popkultúra', 3, 'Kto je spevákom piesne "Blinding Lights"?', 'The Weeknd'),
('Popkultúra', 3, 'Kto je hlavnou postavou vo filme "The Social Network"?', 'Mark Zuckerberg'),
('Popkultúra', 3, 'Kto je režisér filmu "Get Out"?', 'Peele'),
('Popkultúra', 3, 'Kto hrá "Drax" vo filme "Guardians of the Galaxy"?', 'Bautista'),
('Popkultúra', 3, 'Kto je speváčkou piesne "Truth Hurts"?', 'Lizzo'),
('Popkultúra', 3, 'Kto je autorom piesne "Someone You Loved"?', 'Lewis Capaldi'),
('Popkultúra', 3, 'Kto je herec známy ako "Jack Sparrow"?', 'Depp'),
('Popkultúra', 3, 'Kto režíroval film "The Shape of Water"?', 'Del Toro'),
('Popkultúra', 3, 'Kto hrá "Harley Quinn" vo filme "Birds of Prey"?', 'Robbie'),
('Popkultúra', 3, 'Kto je spevákom piesne "Shallow"?', 'Cooper'),
('Popkultúra', 3, 'Kto je autorom piesne "Rolling in the Deep"?', 'Adele'),
('Popkultúra', 3, 'Kto je hlavnou postavou v seriáli "Breaking Bad"?', 'Walter White'),
('Popkultúra', 3, 'Kto hrá "The Mandalorian" v rovnomennom seriáli?', 'Pascal'),
('Popkultúra', 3, 'Kto je speváčkou piesne "Bad Romance"?', 'Gaga'),
('Popkultúra', 3, 'Ktorý film je založený na knihe "The Great Gatsby"?', 'Gatsby'),
('Popkultúra', 3, 'Kto režíroval film "Dunkirk"?', 'Nolan'),
('Popkultúra', 3, 'Kto je spevákom piesne "Lose Yourself"?', 'Eminem'),
('Popkultúra', 3, 'Kto hrá "Cersei Lannister" v "Game of Thrones"?', 'Lena Headey'),
('Popkultúra', 3, 'Kto je autorom piesne "Chasing Cars"?', 'Snow Patrol'),
('Popkultúra', 3, 'Kto je herec známy ako "Hannibal Lecter"?', 'Hopkins'),
('Popkultúra', 3, 'Kto režíroval film "The Grand Budapest Hotel"?', 'Wes Anderson'),
('Popkultúra', 3, 'Kto je speváčkou piesne "All of Me"?', 'John Legend'),
('Popkultúra', 3, 'Kto hrá "Rocket Raccoon" v "Guardians of the Galaxy"?', 'Cooper'),
('Popkultúra', 3, 'Kto je autorom piesne "Royals"?', 'Lorde'),
('Popkultúra', 3, 'Kto je herec vo filme "The Revenant"?', 'DiCaprio'),
('Popkultúra', 3, 'Kto je režisér filmu "Inception"?', 'Nolan'),
('Popkultúra', 3, 'Kto je spevákom piesne "Hotline Bling"?', 'Drake'),
('Popkultúra', 3, 'Kto hrá "Sherlock Holmes" v najnovších filmových adaptáciách?', 'Cumberbatch'),
('Popkultúra', 3, 'Kto je speváčkou piesne "Wrecking Ball"?', 'Cyrus'),
('Popkultúra', 3, 'Kto je režisér filmu "The Irishman"?', 'Scorsese'),
('Popkultúra', 3, 'Kto je herec známy ako "Tony Stark"?', 'Downey'),
('Popkultúra', 3, 'Kto hrá "Katniss Everdeen" vo filme "Hunger Games"?', 'Lawrence'),
('Popkultúra', 3, 'Kto je spevákom piesne "Take Me to Church"?', 'Hozier'),
('Popkultúra', 3, 'Kto je režisér filmu "La La Land"?', 'Chazelle'),
('Popkultúra', 3, 'Kto je herečka známa ako "Wonder Woman"?', 'Gadot'),
('Popkultúra', 3, 'Kto je speváčkou piesne "Someone Like You"?', 'Adele'),
('Popkultúra', 3, 'Kto režíroval film "The Dark Knight"?', 'Nolan'),
('Popkultúra', 3, 'Kto je herec známy ako "Wolverine"?', 'Jackman'),
('Popkultúra', 3, 'Kto hrá "Thor" vo filmoch Marvel?', 'Hemsworth'),
('Popkultúra', 3, 'Kto je speváčkou piesne "Fight Song"?', 'Rachel Platten'),
('Popkultúra', 3, 'Kto je autorom piesne "Billie Jean"?', 'Michael Jackson'),
('Popkultúra', 3, 'Kto je režisér filmu "A Star is Born"?', 'Gaga'),
('Popkultúra', 3, 'Kto je herečka známa ako "Jessica Jones"?', 'Ritter'),
('Popkultúra', 3, 'Kto hrá "Aquaman" v najnovších filmových adaptáciách?', 'Momoa'),
('Popkultúra', 3, 'Kto je autorom piesne "Smells Like Teen Spirit"?', 'Kurt Cobain'),
('Popkultúra', 3, 'Kto hrá postavu "Loki" vo filmoch Marvel?', 'Tom Hiddleston'),
('Popkultúra', 3, 'Kto režíroval film "Fight Club"?', 'David Fincher'),
('Popkultúra', 3, 'Kto je spevákom piesne "Hotline Bling"?', 'Drake'),
('Popkultúra', 3, 'Kto je herec známy ako "Sherlock" v nových filmových adaptáciách?', 'Benedict Cumberbatch'),
('Popkultúra', 3, 'Kto je speváčkou známa hitom "Radioactive"?', 'Imagine Dragons'),
('Popkultúra', 3, 'Kto hrá "The Doctor" v seriáli "Doctor Who"?', 'Jodie Whittaker'),
('Popkultúra', 3, 'Kto je autorom piesne "Back to Black"?', 'Amy Winehouse'),
('Popkultúra', 3, 'Kto režíroval film "Memento"?', 'Christopher Nolan'),
('Popkultúra', 3, 'Kto je spevákom piesne "Somebody That I Used to Know"?', 'Gotye'),
('Popkultúra', 3, 'Kto hrá postavu "Daenerys Targaryen" v "Game of Thrones"?', 'Emilia Clarke'),
('Popkultúra', 3, 'Kto je režisér filmu "Parasite"?', 'Bong Joon-ho'),
('Popkultúra', 3, 'Kto je speváčkou známa hitom "Bad Guy"?', 'Billie Eilish'),
('Popkultúra', 3, 'Kto je herec známy ako "The Terminator"?', 'Arnold Schwarzenegger'),
('Popkultúra', 3, 'Kto je autorom piesne "Crazy in Love"?', 'Beyoncé'),
('Popkultúra', 3, 'Kto hrá "Wonder Woman" vo filme?', 'Gal Gadot'),
('Popkultúra', 3, 'Kto je spevákom piesne "Blinding Lights"?', 'The Weeknd'),
('Popkultúra', 3, 'Kto režíroval film "Blade Runner 2049"?', 'Denis Villeneuve'),
('Popkultúra', 3, 'Kto je herec známy ako "Magneto"?', 'Ian McKellen'),
('Popkultúra', 3, 'Kto je speváčkou známa hitom "Toxic"?', 'Britney Spears'),
('Popkultúra', 3, 'Kto hrá postavu "Rogue" vo filme "X-Men"?', 'Anna Paquin'),
('Popkultúra', 3, 'Kto je autorom piesne "Rolling in the Deep"?', 'Adele'),
('Popkultúra', 3, 'Kto je spevákom piesne "Uptown Funk"?', 'Bruno Mars'),
('Popkultúra', 3, 'Kto režíroval film "The Shape of Water"?', 'Guillermo del Toro'),
('Popkultúra', 3, 'Kto je herec známy ako "James Bond"?', 'Daniel Craig'),
('Popkultúra', 3, 'Kto je speváčkou známa hitom "Like a Prayer"?', 'Madonna'),
('Popkultúra', 3, 'Kto hrá "Catwoman" vo filme "The Dark Knight Rises"?', 'Anne Hathaway'),
('Popkultúra', 3, 'Kto je autorom piesne "Firework"?', 'Katy Perry'),
('Popkultúra', 3, 'Kto režíroval film "The Grand Budapest Hotel"?', 'Wes Anderson'),
('Popkultúra', 3, 'Kto je spevákom piesne "Shape of You"?', 'Ed Sheeran'),
('Popkultúra', 3, 'Kto je herečka známa ako "Jessica Jones"?', 'Krysten Ritter'),
('Popkultúra', 3, 'Kto hrá "Green Lantern" vo filme?', 'Ryan Reynolds'),
('Popkultúra', 3, 'Kto je autorom piesne "Someone Like You"?', 'Adele'),
('Popkultúra', 3, 'Kto je speváčkou známa hitom "All About That Bass"?', 'Meghan Trainor'),
('Popkultúra', 3, 'Kto režíroval film "The Social Network"?', 'David Fincher'),
('Popkultúra', 3, 'Kto je herec známy ako "Gandalf"?', 'Ian McKellen'),
('Popkultúra', 3, 'Kto je spevákom piesne "Take Me to Church"?', 'Hozier'),
('Popkultúra', 3, 'Kto je autorom piesne "Ain''t No Mountain High Enough"?', 'Marvin Gaye'),
('Popkultúra', 3, 'Kto hrá "The Witch" v "The Witch"?', 'Anya Taylor-Joy'),
('Popkultúra', 3, 'Kto je herečka známa ako "Harley Quinn"?', 'Margot Robbie'),
('Popkultúra', 3, 'Kto je speváčkou známa hitom "Hotline Bling"?', 'Drake'),
('Popkultúra', 3, 'Kto je autorom piesne "Sweet Child o'' Mine"?', 'Guns N'' Roses'),
('Popkultúra', 3, 'Kto režíroval film "Inception"?', 'Christopher Nolan'),
('Popkultúra', 3, 'Kto je hercom známy ako "Neo"?', 'Keanu Reeves'),
('Popkultúra', 3, 'Kto je spevákom piesne "Lose Yourself"?', 'Eminem'),
('Popkultúra', 3, 'Kto hrá "Black Widow" vo filmoch Marvel?', 'Scarlett Johansson'),
('Popkultúra', 3, 'Kto je autorom piesne "I Will Always Love You"?', 'Dolly Parton'),
('Popkultúra', 3, 'Kto je herec známy ako "Captain America"?', 'Chris Evans'),
('Popkultúra', 3, 'Kto je speváčka známa hitom "Just Dance"?', 'Lady Gaga'),
('Popkultúra', 3, 'Kto režíroval film "Django Unchained"?', 'Quentin Tarantino'),
('Popkultúra', 3, 'Kto je spevákom piesne "Hallelujah"?', 'Leonard Cohen'),
('Popkultúra', 3, 'Kto hrá "Thor" vo filmoch Marvel?', 'Chris Hemsworth'),
('Ríša zvierat', 1, 'Ktoré zviera je najväčšie na svete?', 'Modrý veľryba'),
('Ríša zvierat', 1, 'Ktoré zviera je známe ako "kráľ džungle"?', 'Lev'),
('Ríša zvierat', 1, 'Aké zviera je symbolom múdrosti?', 'Sova'),
('Ríša zvierat', 1, 'Ktoré zviera produkuje med?', 'Včela'),
('Ríša zvierat', 1, 'Aké zviera je najrýchlejšie na súši?', 'Gepard'),
('Ríša zvierat', 1, 'Ktoré zviera je najmenšie na svete?', 'Bumblebee bat'),
('Ríša zvierat', 1, 'Ktoré zviera má najdlhší krk?', 'Žirafa'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou schopnosťou skákať?', 'Králiček'),
('Ríša zvierat', 1, 'Ktoré zviera je najdlhšie žijúce?', 'Žralok'),
('Ríša zvierat', 1, 'Ktoré zviera je najbližší príbuzný človeka?', 'Šimpanz'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím červeným nosom?', 'Sob'),
('Ríša zvierat', 1, 'Aké zviera je známe ako "plazivý kráľ"?', 'Korytnačka'),
('Ríša zvierat', 1, 'Ktoré zviera má najväčšie oči?', 'Oko'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím pestrým perím?', 'Papagáj'),
('Ríša zvierat', 1, 'Ktoré zviera je hlavným zdrojom ovčej vlny?', 'Ovca'),
('Ríša zvierat', 1, 'Aké zviera je známe svojim skvelým čuchom?', 'Pes'),
('Ríša zvierat', 1, 'Ktoré zviera sa nazýva "kráľovná noci"?', 'Kocúr'),
('Ríša zvierat', 1, 'Ktoré zviera je súčasťou známeho zverinca?', 'Slon'),
('Ríša zvierat', 1, 'Aké zviera sa považuje za symbol lásky?', 'Holub'),
('Ríša zvierat', 1, 'Ktoré zviera má najväčšiu silu v pomere k veľkosti?', 'Chrobák'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou ostrohou?', 'Rybárik'),
('Ríša zvierat', 1, 'Ktoré zviera je považované za "pána hmyzu"?', 'Mravec'),
('Ríša zvierat', 1, 'Ktoré zviera má schopnosť meniť farbu?', 'Chameleón'),
('Ríša zvierat', 1, 'Kto sa považuje za najzraniteľnejšie zviera?', 'Nosorožec'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím hmyzom?', 'Motýľ'),
('Ríša zvierat', 1, 'Kto je najvyšší suchozemský cicavec?', 'Žirafa'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím dlhým chvostom?', 'Lemur'),
('Ríša zvierat', 1, 'Ktoré zviera je symbolom Austrálie?', 'Kangúr'),
('Ríša zvierat', 1, 'Ktoré zviera je najväčší predátor?', 'Ľadový medveď'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím spevom?', 'Slávik'),
('Ríša zvierat', 1, 'Ktoré zviera je považované za najinteligentnejšie?', 'Delfín'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou plávajúcou schopnosťou?', 'Korytnačka'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou lietať?', 'Vták'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím náhľadom?', 'Tigra'),
('Ríša zvierat', 1, 'Ktoré zviera je najväčšie suchozemské zviera?', 'Slon'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím silným hlasom?', 'Kohút'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím dlhým telom?', 'Had'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím zlatým sfarbením?', 'Zlatá rybka'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou tancovať?', 'Pavián'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou pomalou chôdzou?', 'Korytnačka'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím strážením?', 'Pes'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím skrytým životom?', 'Tajga'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou prežiť v extrémnych podmienkach?', 'Púšť'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou silou?', 'Lev'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím spievaním?', 'Slávik'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím skrytým životom vo vode?', 'Rybár'),
('Ríša zvierat', 1, 'Ktoré zviera je najobľúbenejším domácim zvieraťom?', 'Pes'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojimi dlhými ušami?', 'Zajac'),
('Ríša zvierat', 1, 'Ktoré zviera je najmenším cicavcom na svete?', 'Pipistrellus'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím čiernym sfarbením?', 'Uhlíkový chvost'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou rýchlosťou vo vode?', 'Delfín'),
('Ríša zvierat', 1, 'Aké zviera sa nazýva "pán hmyzu"?', 'Mravec'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím skvelým sluchom?', 'Sova'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou plávať?', 'Vydra'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou veľkou silou?', 'Slon'),
('Ríša zvierat', 1, 'Aké zviera je známe svojím pestrým sfarbením?', 'Papagáj'),
('Ríša zvierat', 1, 'Ktoré zviera je najobľúbenejším domácim miláčikom?', 'Pes'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím dlhým krkom?', 'Žirafa'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím ostrým zrakom?', 'Jastrab'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou dlhou životnosťou?', 'Žralok'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou skryť sa?', 'Chameleon'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou agresivitou?', 'Hroch'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou skákať?', 'Králiček'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím pomalým pohybom?', 'Slen'),
('Ríša zvierat', 1, 'Aké zviera je najmenšie v oceáne?', 'Krysa'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím spevom v noci?', 'Sova'),
('Ríša zvierat', 1, 'Ktoré zviera má najdlhší chvost?', 'Pavúk'),
('Ríša zvierat', 1, 'Aké zviera je najväčšie na pevnine?', 'Slon'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím rozkošným vzhľadom?', 'Koala'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou lietať?', 'Netopier'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou silou v mori?', 'Chobotnica'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím vynikajúcim čuchom?', 'Psy'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím spevom?', 'Slávik'),
('Ríša zvierat', 1, 'Aké zviera je známe svojou rýchlosťou?', 'Kôň'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím dlhým telom?', 'Had'),
('Ríša zvierat', 1, 'Ktoré zviera sa považuje za symbol moci?', 'Orol'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojimi dlhými nohami?', 'Žirafa'),
('Ríša zvierat', 1, 'Ktoré zviera má najväčšiu silu v pomere k veľkosti?', 'Mravec'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím štíhlym telom?', 'Gepard'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojou schopnosťou plávať?', 'Rybka'),
('Ríša zvierat', 1, 'Ktoré zviera sa považuje za symbol šťastia?', 'Sova'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím priateľským správaním?', 'Pes'),
('Ríša zvierat', 1, 'Ktoré zviera je známe svojím vynikajúcim zrakom?', 'Sova'),
('Ríša zvierat', 1, 'Aké zviera sa nazýva "kráľovná džungle"?', 'Leopard');