INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "dialogue"?', 'Dialóg'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "narration"?', 'Rozprávanie'),
('Slovenský jazyk', 2, 'Kto napísal "Kniha o piesni"?', 'M. K.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "translation"?', 'Preklad'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "phrase"?', 'Fráza'),
('Slovenský jazyk', 2, 'Kto napísal "Krajina pod hviezdami"?', 'M. M.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "sentence"?', 'Veta'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "meaning"?', 'Význam'),
('Slovenský jazyk', 2, 'Kto napísal "Pieseň pre národ"?', 'M. R.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "inspiration"?', 'Inšpirácia'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "language"?', 'Jazyk'),
('Slovenský jazyk', 2, 'Kto napísal "Život na dedine"?', 'J. B.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "theme"?', 'Téma'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "poetess"?', 'Básničkárka'),
('Slovenský jazyk', 2, 'Kto napísal "Pohádky"?', 'A. P.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "literature"?', 'Literatúra'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "dialogue"?', 'Dialóg'),
('Slovenský jazyk', 2, 'Kto napísal "Klasici"?', 'J. K.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "reality"?', 'Realita'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "story"?', 'Príbeh'),
('Slovenský jazyk', 2, 'Kto napísal "Kniha piesní"?', 'M. B.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "style"?', 'Štýl'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "fiction"?', 'Fikcia'),
('Slovenský jazyk', 2, 'Kto napísal "Rozprávky pre deti"?', 'P. M.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "paragraph"?', 'Odsek'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "editor"?', 'Redaktor'),
('Slovenský jazyk', 2, 'Kto napísal "Kniha snov a túžob"?', 'L. T.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "scene"?', 'Scéna'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "audience"?', 'Publikum'),
('Slovenský jazyk', 2, 'Kto napísal "Hrdinovia"?', 'M. K.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "plot"?', 'Dej'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "meaning"?', 'Zmysel'),
('Slovenský jazyk', 2, 'Kto napísal "Príbehy z lesa"?', 'J. K.'),
('Slovenský jazyk', 2, 'Aké je slovenské slovo pre "characterization"?', 'Charakterizácia'),
('Slovenský jazyk', 2, 'Aký je slovenský názov pre "language"?', 'Jazyk'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "dictionary"?', 'slovník'),
('Slovenský jazyk', 3, 'Kto napísal "Slovenské piesne"?', 'Ján Kollár'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "grammar"?', 'gramatika'),
('Slovenský jazyk', 3, 'Kto je autorom "Krajina snov"?', 'Milan Kňažko'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "prose"?', 'próza'),
('Slovenský jazyk', 3, 'Kto napísal "Zem spieva"?', 'Ján Levoslav Bella'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "metaphor"?', 'metafora'),
('Slovenský jazyk', 3, 'Kto napísal "Svetlo v tme"?', 'Milan Rúfus'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "epic"?', 'epika'),
('Slovenský jazyk', 3, 'Kto napísal "Vtáčik a kvet"?', 'Milan Kňažko'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "rhyme"?', 'rým'),
('Slovenský jazyk', 3, 'Kto napísal "Kvetinový román"?', 'Jozef Gregor Tajovský'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "critique"?', 'kritika'),
('Slovenský jazyk', 3, 'Čo je to "literárny žáner"?', 'žáner'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "audience"?', 'publikum'),
('Slovenský jazyk', 3, 'Kto napísal "Hlava XXII"?', 'Joseph Heller'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "translation"?', 'preklad'),
('Slovenský jazyk', 3, 'Kto napísal "Pohľady na svet"?', 'Milan Kňažko'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "character"?', 'postava'),
('Slovenský jazyk', 3, 'Kto napísal "Príbehy z lesa"?', 'Jozef Karika'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "dialogue"?', 'dialog'),
('Slovenský jazyk', 3, 'Kto napísal "Moje deti"?', 'Milan Rúfus'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "theme"?', 'téma'),
('Slovenský jazyk', 3, 'Kto napísal "Kniha piesní"?', 'Ján Smrek'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "phrase"?', 'fráza'),
('Slovenský jazyk', 3, 'Kto napísal "Svetlo v tme"?', 'Jozef Gregor Tajovský'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "context"?', 'kontext'),
('Slovenský jazyk', 3, 'Kto napísal "Rozprávky pre deti"?', 'Jakub Deml'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "narration"?', 'rozprávanie'),
('Slovenský jazyk', 3, 'Kto napísal "Pohádky"?', 'Karel Čapek'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "style"?', 'štýl'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "meaning"?', 'význam'),
('Slovenský jazyk', 3, 'Kto napísal "Kniha o piesni"?', 'Ján Smrek'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "scene"?', 'scéna'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "author"?', 'autor'),
('Slovenský jazyk', 3, 'Kto napísal "Klasici"?', 'Ján Kalinčiak'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "reality"?', 'realita'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "narrator"?', 'rozprávač'),
('Slovenský jazyk', 3, 'Kto napísal "Kniha snov a túžob"?', 'Milan Rúfus'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "interpretation"?', 'interpretácia'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "literary"?', 'literárny'),
('Slovenský jazyk', 3, 'Kto napísal "Návrat"?', 'Jozef Mihály'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "fiction"?', 'fikcia'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "paragraph"?', 'odsek'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "play"?', 'hra'),
('Slovenský jazyk', 3, 'Kto napísal "Hrdinovia"?', 'Jozef Gregor Tajovský'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "characterization"?', 'charakterizácia'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "history"?', 'história'),
('Slovenský jazyk', 3, 'Kto napísal "Krajina v srdci"?', 'Milan Kňažko'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "theater"?', 'divadlo'),
('Slovenský jazyk', 3, 'Kto napísal "Kniha o Slovensku"?', 'Milan Kňažko'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "grammar"?', 'Gramatika'),
('Slovenský jazyk', 3, 'Kto napísal "Hlava XXII"?', 'Heller'),
('Slovenský jazyk', 3, 'Čo znamená slovo "metafora"?', 'Obrázok'),
('Slovenský jazyk', 3, 'Kto napísal "Svetlo v tme"?', 'Kováč'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "prozaik"?', 'Prozaik'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "literárny žáner"?', 'Žáner'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "metóda"?', 'Metóda'),
('Slovenský jazyk', 3, 'Kto napísal "Pohádky"?', 'Andersen'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "recenzia"?', 'Recenzia'),
('Slovenský jazyk', 3, 'Kto napísal "Krajina snov"?', 'Brodský'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "dielo"?', 'Dielo'),
('Slovenský jazyk', 3, 'Aká je slovenská terminológia pre "poetika"?', 'Poetika'),
('Slovenský jazyk', 3, 'Kto napísal "Moje deti"?', 'Pavlovič'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "román"?', 'Román'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "interpretácia"?', 'Interpretácia'),
('Slovenský jazyk', 3, 'Kto napísal "Návrat"?', 'Král'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "prozaická" štruktúra?', 'Štruktúra'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "narratív"?', 'Narativ'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "kniha"?', 'Kniha'),
('Slovenský jazyk', 3, 'Kto napísal "Pohľady na svet"?', 'Milan'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "metafora"?', 'Metafora'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "epika"?', 'Epika'),
('Slovenský jazyk', 3, 'Kto napísal "Rozprávky pre deti"?', 'Pavol'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "audiovizuálna literatúra"?', 'Audiovizuálna'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "názov"?', 'Názov'),
('Slovenský jazyk', 3, 'Kto napísal "Piesne"?', 'Kukura'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "dialekt"?', 'Dialekt'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "poviedka"?', 'Poviedka'),
('Slovenský jazyk', 3, 'Kto napísal "Hrdinovia"?', 'Bútorová'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "kultúra"?', 'Kultúra'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "dokument"?', 'Dokument'),
('Slovenský jazyk', 3, 'Kto napísal "Príbehy z lesa"?', 'Kováčik'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "narrátor"?', 'Narátor'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "rým"?', 'Rým'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "poetka"?', 'Poetka'),
('Slovenský jazyk', 3, 'Kto napísal "Kvetinový román"?', 'Borec'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "príbeh"?', 'Príbeh'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "analýza"?', 'Analýza'),
('Slovenský jazyk', 3, 'Kto napísal "Svetlo v tme"?', 'Hlava'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "kontext"?', 'Kontext'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "typografia"?', 'Typografia'),
('Slovenský jazyk', 3, 'Kto napísal "Hlava XXII"?', 'Heller'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "spisovateľ"?', 'Spisovateľ'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "príbeh"?', 'Príbeh'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "názor"?', 'Názor'),
('Slovenský jazyk', 3, 'Kto napísal "Kniha o piesni"?', 'Rúfus'),
('Slovenský jazyk', 3, 'Aké je slovenské slovo pre "písanie"?', 'Písanie'),
('Slovenský jazyk', 3, 'Aký je slovenský názov pre "analýza"?', 'Analýza'),
('Slovenský jazyk', 3, 'Kto napísal "Pohádky"?', 'Andersen'),
('Technológie', 1, 'Ktorá spoločnosť vyvinula Android?', 'Google'),
('Technológie', 1, 'Aký je názov najpopulárnejšieho prehliadača od Microsoftu?', 'Edge'),
('Technológie', 1, 'Kto je zakladateľom spoločnosti Microsoft?', 'Gates'),
('Technológie', 1, 'Aký je názov najnovšieho modelu iPhone?', 'iPhone'),
('Technológie', 1, 'Ktorý jazyk je najpoužívanejší na webových stránkach?', 'JavaScript'),
('Technológie', 1, 'Čo je to Wi-Fi?', 'Bezdrôtová sieť'),
('Technológie', 1, 'Ktorý sociálny sieťový server vlastní Mark Zuckerberg?', 'Facebook'),
('Technológie', 1, 'Aký je názov cloudového úložiska od Google?', 'Drive'),
('Technológie', 1, 'Ktorý operačný systém je vyvinutý spoločnosťou Apple?', 'macOS'),
('Technológie', 1, 'Aké zariadenie slúži na snímanie fotografií?', 'Fotoaparát'),
('Technológie', 1, 'Aké je skratka pre internetový protokol?', 'IP'),
('Technológie', 1, 'Ktorá technológia sa používa na bezkontaktné platby?', 'NFC'),
('Technológie', 1, 'Ktorý typ pamäte sa často používa v mobilných zariadeniach?', 'RAM'),
('Technológie', 1, 'Aký je názov najznámejšej hernej konzoly od Sony?', 'PlayStation'),
('Technológie', 1, 'Kto vytvoril Linux?', 'Torvalds'),
('Technológie', 1, 'Aký je názov populárneho video portálu?', 'YouTube'),
('Technológie', 1, 'Aké zariadenie slúži na prepojenie s internetom?', 'Router'),
('Technológie', 1, 'Čo je to USB?', 'Univerzálny zbernica'),
('Technológie', 1, 'Ktorý jazyk je najpoužívanejší na programovanie?', 'Python'),
('Technológie', 1, 'Ktorý operačný systém je vyvinutý pre mobilné zariadenia od Apple?', 'iOS'),
('Technológie', 1, 'Aký je názov technológie pre rozpoznávanie tváre?', 'Biometria'),
('Technológie', 1, 'Ktorá značka vyrába Surface zariadenia?', 'Microsoft'),
('Technológie', 1, 'Aký je názov populárneho operačného systému pre servery?', 'Linux'),
('Technológie', 1, 'Ktorý typ siete je najčastejšie používaný v domácnostiach?', 'Wi-Fi'),
('Technológie', 1, 'Aký je názov technológie pre prenos dát na krátke vzdialenosti?', 'Bluetooth'),
('Technológie', 1, 'Čo je to HTML?', 'Značkovací jazyk'),
('Technológie', 1, 'Aká je skratka pre "základná doska"?', 'MB'),
('Technológie', 1, 'Aký je názov populárneho operačného systému od Googlu pre zariadenia?', 'Chrome'),
('Technológie', 1, 'Ktorý typ obrazovky je najbežnejší v smartfónoch?', 'LCD'),
('Technológie', 1, 'Aký je názov technológie pre prácu s virtuálnou realitou?', 'VR'),
('Technológie', 1, 'Ktorý internetový vyhľadávač je najpoužívanejší?', 'Google'),
('Technológie', 1, 'Aký je názov populárneho softvéru na úpravu videa?', 'Premiere'),
('Technológie', 1, 'Kto založil spoločnosť Apple?', 'Jobs'),
('Technológie', 1, 'Aký je skratka pre "grafická karta"?', 'GPU'),
('Technológie', 1, 'Aký je názov technológie pre kompresiu súborov?', 'ZIP'),
('Technológie', 1, 'Ktorý operačný systém je určený pre servery od Microsoftu?', 'Windows Server'),
('Technológie', 1, 'Aké je názov technológie pre bezdrôtové nabíjanie?', 'Qi'),
('Technológie', 1, 'Ktorý jazyk sa používa na tvorbu webových stránok?', 'HTML'),
('Technológie', 1, 'Čo je to malware?', 'Zlý softvér'),
('Technológie', 1, 'Ktorý typ pamäte je trvalý?', 'SSD'),
('Technológie', 1, 'Aký je názov technológie pre video konferencie?', 'Zoom'),
('Technológie', 1, 'Kto je zakladateľom spoločnosti Tesla?', 'Musk'),
('Technológie', 1, 'Aký je názov programovacieho jazyka od Microsoftu?', 'C#'),
('Technológie', 1, 'Ktorý typ databázy je najčastejšie používaný?', 'SQL'),
('Technológie', 1, 'Aký je názov technológie pre sledovanie polohy?', 'GPS'),
('Technológie', 1, 'Aký je názov najpopulárnejšej platformy na blogovanie?', 'WordPress'),
('Technológie', 1, 'Kto je zakladateľom spoločnosti Amazon?', 'Bezos'),
('Technológie', 1, 'Ktorý typ čipu je používaný v mobilných zariadeniach?', 'SoC'),
('Technológie', 1, 'Aký je názov najpopulárnejšieho operačného systému pre PC?', 'Windows'),
('Technológie', 1, 'Ktorý typ pamäte je používaný pre dočasné ukladanie dát?', 'RAM'),
('Technológie', 1, 'Aký je názov najznámejšieho vyhľadávača?', 'Google'),
('Technológie', 1, 'Kto vytvoril prvý počítač?', 'Babbage\nTechnológie'),
('Technológie', 1, 'Aký je názov najpoužívanejšieho internetového prehliadača?', 'Chrome'),
('Technológie', 1, 'Ktorý výrobca produkuje PlayStation?', 'Sony'),
('Technológie', 1, 'Aký typ pamäte je RAM?', 'Dočasná'),
('Technológie', 1, 'Kto je zakladateľom Facebooku?', 'Zuckerberg'),
('Technológie', 1, 'Aká je skratka pre umelú inteligenciu?', 'AI'),
('Technológie', 1, 'Čo označuje skratka Wi-Fi?', 'Bezdrôtová'),
('Technológie', 1, 'Ktorý operačný systém vyvinul Apple?', 'macOS'),
('Technológie', 1, 'Aký je názov najpopulárnejšej sociálnej siete?', 'Facebook'),
('Technológie', 1, 'Ktoré zariadenie sa používa na tlač dokumentov?', 'Tlačiareň'),
('Technológie', 1, 'Aký je názov najznámejšieho vyhľadávača?', 'Google'),
('Technológie', 1, 'Ktorá firma vytvorila Windows?', 'Microsoft'),
('Technológie', 1, 'Aká je skratka pre textový procesor Microsoftu?', 'Word'),
('Technológie', 1, 'Ktorý produkt je známy ako smartphone od Samsungu?', 'Galaxy'),
('Technológie', 1, 'Aké zariadenie slúži na pripojenie k internetu?', 'Router'),
('Technológie', 1, 'Čo je to QR kód?', 'Kód'),
('Technológie', 1, 'Ktorá spoločnosť vyvinula iOS?', 'Apple'),
('Technológie', 1, 'Aký je názov najznámejšej videohry od Nintendo?', 'Mario'),
('Technológie', 1, 'Aký je názov najpoužívanejšieho klientskeho programu na e-mail?', 'Outlook'),
('Technológie', 1, 'Ktoré zariadenie je známe ako tablet od Apple?', 'iPad'),
('Technológie', 1, 'Aký je názov operačného systému pre Linux?', 'Ubuntu'),
('Technológie', 1, 'Ktorá technológia sa používa na bezdrôtové nabíjanie?', 'Qi'),
('Technológie', 1, 'Aký je názov cloudovej služby od Google?', 'Drive'),
('Technológie', 1, 'Kto je zakladateľom Tesly?', 'Musk'),
('Technológie', 1, 'Aký je názov najznámejšieho softvéru pre strih videa?', 'Premiere'),
('Technológie', 1, 'Kto vyvinul procesory Intel?', 'Intel'),
('Technológie', 1, 'Aký je názov najpoužívanejšieho operačného systému pre servery?', 'Linux'),
('Technológie', 1, 'Čo je to URL?', 'Adresa'),
('Technológie', 1, 'Ktorá spoločnosť vyrába Xbox?', 'Microsoft'),
('Technológie', 1, 'Aká je skratka pre počítačovú sieť?', 'LAN'),
('Technológie', 1, 'Ktorý produkt je známy ako smartwatch od Apple?', 'Apple Watch'),
('Technológie', 1, 'Aký je názov najznámejšieho softvéru pre grafiku?', 'Photoshop'),
('Technológie', 1, 'Ktorá technológia sa používa na virtuálnu realitu?', 'VR'),
('Technológie', 1, 'Kto je zakladateľom Googlu?', 'Page'),
('Technológie', 1, 'Aký je názov bezpečnostného protokolu na internete?', 'HTTPS'),
('Technológie', 1, 'Ktorý typ pamäte sa používa v počítačoch?', 'SSD'),
('Technológie', 1, 'Aký je názov programovacieho jazyka od Sun Microsystems?', 'Java'),
('Technológie', 1, 'Ktorá spoločnosť vyrába grafické karty GeForce?', 'NVIDIA'),
('Technológie', 1, 'Aká je skratka pre rozšírenú realitu?', 'AR'),
('Technológie', 1, 'Ktorý mobilný operačný systém je založený na Linuxe?', 'Android'),
('Technológie', 1, 'Aký je názov najznámejšieho webového hostingu?', 'GoDaddy'),
('Technológie', 1, 'Ktorý jazyk sa používa na tvorbu webstránok?', 'HTML'),
('Technológie', 1, 'Aká je skratka pre slovo "aplikácia"?', 'App'),
('Technológie', 1, 'Ktorý produkt je známy ako osobný počítač od Dellu?', 'XPS'),
('Technológie', 1, 'Aký je názov najznámejšieho antimalwarového softvéru?', 'Norton'),
('Technológie', 1, 'Kto vyvinul programovací jazyk Python?', 'Van Rossum'),
('Technológie', 1, 'Aký je názov najpoužívanejšieho operačného systému pre mobilné zariadenia?', 'Android'),
('Technológie', 1, 'Ktoré zariadenie sa používa na videohovory?', 'Webkamera'),
('Technológie', 1, 'Aká je skratka pre prenos údajov cez mobilnú sieť?', 'GPRS'),
('Technológie', 1, 'Ktorý program sa používa na úpravu zvuku?', 'Audacity\nTechnológie'),
('Technológie', 2, 'Aký je názov známej databázy od Oracle?', 'Oracle DB'),
('Technológie', 2, 'Ktorý protokol sa používa na zabezpečenú komunikáciu?', 'HTTPS'),
('Technológie', 2, 'Aký je názov populárneho cloudového úložiska od Google?', 'Google Drive'),
('Technológie', 2, 'Aký je názov operačného systému pre Apple zariadenia?', 'macOS'),
('Technológie', 2, 'Čo znamená skratka AI?', 'Umelá inteligencia'),
('Technológie', 2, 'Ktorý jazyk je známy pre webový vývoj?', 'JavaScript'),
('Technológie', 2, 'Aký je názov najpopulárnejšej sociálnej siete?', 'Facebook'),
('Technológie', 2, 'Ktorá firma vyrába konzolu PlayStation?', 'Sony'),
('Technológie', 2, 'Aký je názov technológie pre bezdrôtové pripojenie?', 'Wi-Fi'),
('Technológie', 2, 'Ktorý program je určený na úpravu fotografií?', 'Photoshop'),
('Technológie', 2, 'Aký je názov systémového softvéru pre servery?', 'Linux'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Tesla?', 'Elon Musk'),
('Technológie', 2, 'Čo znamená skratka IoT?', 'Internet vecí'),
('Technológie', 2, 'Aký je názov rozhrania pre bezdrôtové pripojenie?', 'Bluetooth'),
('Technológie', 2, 'Ktorý operačný systém je určený pre mobilné zariadenia?', 'Android'),
('Technológie', 2, 'Aký je názov najväčšieho vyhľadávača?', 'Google'),
('Technológie', 2, 'Kto vyvinul jazyk Java?', 'James Gosling'),
('Technológie', 2, 'Ktorý softvér sa používa na správu databáz?', 'MySQL'),
('Technológie', 2, 'Aký je názov šifrovacieho protokolu pre e-maily?', 'PGP'),
('Technológie', 2, 'Ktorá firma vyrába procesory Ryzen?', 'AMD'),
('Technológie', 2, 'Čo znamená skratka CPU?', 'Centrálny procesor'),
('Technológie', 2, 'Aký je názov populárneho prehliadača od Mozilla?', 'Firefox'),
('Technológie', 2, 'Ktorý jazyk sa používa na vývoj aplikácií pre iOS?', 'Swift'),
('Technológie', 2, 'Aký je názov technológie pre virtuálnu realitu?', 'VR'),
('Technológie', 2, 'Kto je zakladateľom Amazonu?', 'Jeff Bezos'),
('Technológie', 2, 'Aký je názov spoločnosti, ktorá vyrába Linux?', 'Red Hat'),
('Technológie', 2, 'Ktorý formát súborov je populárny pre obrázky?', 'JPEG'),
('Technológie', 2, 'Aký je názov technológie pre videokonferencie?', 'Zoom'),
('Technológie', 2, 'Ktorá firma vyrába operačný systém Windows?', 'Microsoft'),
('Technológie', 2, 'Aký je názov populárneho programovacieho jazyka pre web?', 'PHP'),
('Technológie', 2, 'Kto vyvinul jazyk C++?', 'Bjarne Stroustrup'),
('Technológie', 2, 'Aký je názov technológie pre digitálne platby?', 'Blockchain'),
('Technológie', 2, 'Ktorá firma vyrába grafické karty GeForce?', 'NVIDIA'),
('Technológie', 2, 'Aký je názov systému pre riadenie verzií?', 'Git'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Facebook?', 'Mark Zuckerberg'),
('Technológie', 2, 'Aký je názov najpopulárnejšieho mobilného operačného systému?', 'Android'),
('Technológie', 2, 'Ktorý jazyk je najpoužívanejší pre analýzu dát?', 'R'),
('Technológie', 2, 'Aký je názov súborového systému pre Windows?', 'NTFS'),
('Technológie', 2, 'Ktorý jazyk je známy pre vývoj hier?', 'C#'),
('Technológie', 2, 'Aký je názov najpopulárnejšej platformy pre blogy?', 'WordPress'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Google?', 'Larry Page'),
('Technológie', 2, 'Aký je názov technológie pre cloudové služby?', 'AWS'),
('Technológie', 2, 'Ktorý jazyk sa používa na analýzu veľkých dát?', 'Python'),
('Technológie', 2, 'Aký je názov technológie pre zdieľanie súborov?', 'FTP'),
('Technológie', 2, 'Kto vyvinul jazyk Ruby?', 'Yukihiro Matsumoto'),
('Technológie', 2, 'Ktorý protokol je základom internetu?', 'TCP/IP'),
('Technológie', 2, 'Aký je názov technológie pre mobilnú platbu?', 'NFC'),
('Technológie', 2, 'Ktorá spoločnosť vyrába procesory Intel?', 'Intel'),
('Technológie', 2, 'Aký je názov technológie pre rozpoznávanie tváre?', 'Face ID'),
('Technológie', 2, 'Ktorý jazyk je populárny na server-side?', 'Node.js'),
('Technológie', 2, 'Aký je názov najznámejšieho antivírusového softvéru?', 'Norton\nTechnológie'),
('Technológie', 2, 'Aký jazyk sa používa na webové programovanie?', 'JavaScript'),
('Technológie', 2, 'Ktorý procesor je známy pod značkou Intel?', 'Core i7'),
('Technológie', 2, 'Aký je názov najpopulárnejšieho vyhľadávača?', 'Google'),
('Technológie', 2, 'Ktorá technológia umožňuje bezdrôtové pripojenie?', 'Bluetooth'),
('Technológie', 2, 'Aký je názov operačného systému od Apple?', 'macOS'),
('Technológie', 2, 'Kto vyvinul programovací jazyk Java?', 'James Gosling'),
('Technológie', 2, 'Aký je názov technológie pre virtuálnu realitu od Facebooku?', 'Oculus'),
('Technológie', 2, 'Ktorý protokol sa používa na prenos webových stránok?', 'HTTP'),
('Technológie', 2, 'Aký je názov populárneho softvéru na úpravu fotografií?', 'Photoshop'),
('Technológie', 2, 'Ktorý mobilný operačný systém je určený pre zariadenia Apple?', 'iOS'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Amazon?', 'Jeff Bezos'),
('Technológie', 2, 'Aký je názov populárneho cloudového úložiska od Google?', 'Drive'),
('Technológie', 2, 'Ktorá technológia slúži na zabezpečenie siete?', 'Firewall'),
('Technológie', 2, 'Aký je názov najpoužívanejšieho operačného systému na svete?', 'Windows'),
('Technológie', 2, 'Ktorý jazyk sa používa na tvorbu webových stránok?', 'HTML'),
('Technológie', 2, 'Aký je názov technológie pre bezkontaktné platby?', 'NFC'),
('Technológie', 2, 'Ktorý produkt je známy ako "inteligentný reproduktor"?', 'Echo'),
('Technológie', 2, 'Aký je názov štandardu pre bezdrôtové siete?', 'Wi-Fi'),
('Technológie', 2, 'Kto vyvinul hernú konzolu PlayStation?', 'Sony'),
('Technológie', 2, 'Aký je názov technológie pre videokonferencie od Zoomu?', 'Zoom'),
('Technológie', 2, 'Ktorý jazyk je známy pre vývoj hier?', 'C++'),
('Technológie', 2, 'Aký je názov programovacieho prostredia od Microsoftu?', 'Visual Studio'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Oracle?', 'Larry Ellison'),
('Technológie', 2, 'Aký je názov mobilného operačného systému od Google?', 'Android'),
('Technológie', 2, 'Ktorá technológia sa používa na streamovanie videa?', 'HTTP'),
('Technológie', 2, 'Aký je názov obľúbeného herného enginu?', 'Unity'),
('Technológie', 2, 'Ktorý jazyk sa používa na analýzu dát?', 'R'),
('Technológie', 2, 'Aký je názov systému správy databáz od Microsoftu?', 'SQL Server'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Facebook?', 'Mark Zuckerberg'),
('Technológie', 2, 'Aký je názov technológie pre rozšírenú realitu?', 'AR'),
('Technológie', 2, 'Ktorý jazyk je používaný na vývoj mobilných aplikácií pre iOS?', 'Swift'),
('Technológie', 2, 'Aký je názov technológie pre blockchain?', 'Ethereum'),
('Technológie', 2, 'Ktorá spoločnosť vyrába procesory Ryzen?', 'AMD'),
('Technológie', 2, 'Aký je názov protokolu pre e-mail?', 'SMTP'),
('Technológie', 2, 'Ktorý jazyk je považovaný za jazyk pre webové aplikácie?', 'PHP'),
('Technológie', 2, 'Aký je názov technológie pre online platby?', 'PayPal'),
('Technológie', 2, 'Kto vyvinul operačný systém Linux?', 'Linus Torvalds'),
('Technológie', 2, 'Aký je názov technológie pre digitálne podpisy?', 'PKI'),
('Technológie', 2, 'Ktorá technológia je základom pre smartfóny?', 'Touchscreen'),
('Technológie', 2, 'Aký je názov technológie pre internet vecí?', 'IoT'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Adobe?', 'John Warnock'),
('Technológie', 2, 'Aký je názov technológie pre analýzu big data?', 'Hadoop'),
('Technológie', 2, 'Ktorý jazyk sa používa na automatizáciu testovania?', 'Selenium'),
('Technológie', 2, 'Aký je názov technológie pre cloud computing?', 'AWS'),
('Technológie', 2, 'Ktorý jazyk je často používaný na serverovej strane?', 'Node.js'),
('Technológie', 2, 'Aký je názov platformy pre online vzdelávanie?', 'Coursera\nTechnológie'),
('Technológie', 3, 'Kto vytvoril protokol TCP/IP?', 'Vint Cerf'),
('Technológie', 3, 'Aká je skratka pre umelú inteligenciu?', 'AI'),
('Technológie', 3, 'Ktorý jazyk sa používa pri vývoji webových stránok?', 'JavaScript'),
('Technológie', 3, 'Kto je autorom teórie relativity?', 'Einstein'),
('Technológie', 3, 'Aký typ pamäte je RAM?', 'Volatilná'),
('Technológie', 3, 'Kto vyvinul jazyk C++?', 'Bjarne Stroustrup'),
('Technológie', 3, 'Akú technológiu používa Bitcoin?', 'Blockchain'),
('Technológie', 3, 'Kto je známy ako "otec internetu"?', 'Vint Cerf'),
('Technológie', 3, 'Aký je názov najpopulárnejšieho webového prehliadača?', 'Chrome'),
('Technológie', 3, 'Ktorý jazyk je známy pre svoj syntaktický cukor?', 'Ruby'),
('Technológie', 3, 'Aký je názov prvého počítača?', 'ENIAC'),
('Technológie', 3, 'Kto založil spoločnosť Apple?', 'Steve Jobs'),
('Technológie', 3, 'Čo označuje skratka IoT?', 'Internet vecí'),
('Technológie', 3, 'Aký typ sieťového protokolu je HTTP?', 'Aplikačný'),
('Technológie', 3, 'Kto je autorom jazykov Ada a Pascal?', 'Niklaus Wirth'),
('Technológie', 3, 'Aký je názov najrozšírenejšieho operačného systému pre servery?', 'Linux'),
('Technológie', 3, 'Kto vyvinul jazyk Java?', 'James Gosling'),
('Technológie', 3, 'Akou technológiou je zabezpečený HTTPS?', 'SSL/TLS'),
('Technológie', 3, 'Kto je známy za jeho prácu na teórii algoritmov?', 'Donald Knuth'),
('Technológie', 3, 'Aká je skratka pre virtuálnu realitu?', 'VR'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti Oracle?', 'Larry Ellison'),
('Technológie', 3, 'Aký je názov najväčšej sociálnej siete?', 'Facebook'),
('Technológie', 3, 'Kto vynalezl prvý osobný počítač?', 'IBM'),
('Technológie', 3, 'Ktorý jazyk je základom pre Android aplikácie?', 'Java'),
('Technológie', 3, 'Aký je názov systému pre správu databáz?', 'MySQL'),
('Technológie', 3, 'Kto je autorom Linuxu?', 'Linus Torvalds'),
('Technológie', 3, 'Aký je názov najpoužívanejšieho cloudového úložiska?', 'Google Drive'),
('Technológie', 3, 'Ktorý jazyk sa používa na vývoj iOS aplikácií?', 'Swift'),
('Technológie', 3, 'Aký je názov protokolu pre prenos e-mailov?', 'SMTP'),
('Technológie', 3, 'Kto je známy za svoj prínos v oblasti strojového učenia?', 'Geoff Hinton'),
('Technológie', 3, 'Aká je skratka pre rozšírenú realitu?', 'AR'),
('Technológie', 3, 'Ktorá technológia sa používa na prenos dát cez optické vlákna?', 'TOSLINK'),
('Technológie', 3, 'Aký je názov najpoužívanejšieho operačného systému pre mobilné telefóny?', 'Android'),
('Technológie', 3, 'Kto je autorom teórie grafov?', 'Leonhard Euler'),
('Technológie', 3, 'Aké je skratkové označenie pre systém správy verzií?', 'VCS'),
('Technológie', 3, 'Ktorý jazyk je známy pre svoju funkcionálnu paradigmu?', 'Haskell'),
('Technológie', 3, 'Aká je skratka pre rozpoznávanie obrazov?', 'CV'),
('Technológie', 3, 'Kto vyvinul jazyk Kotlin?', 'JetBrains'),
('Technológie', 3, 'Aký je názov technológie pre hlasové ovládanie?', 'ASR'),
('Technológie', 3, 'Kto je autorom teórie informačnej teórie?', 'Claude Shannon'),
('Technológie', 3, 'Aký je názov technológie pre bezdrôtovú komunikáciu na krátke vzdialenosti?', 'Bluetooth'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti IBM?', 'Charles Ranlett Flint'),
('Technológie', 3, 'Aký je názov najpopulárnejšej databázy pre NoSQL?', 'MongoDB'),
('Technológie', 3, 'Ktorý jazyk je známy pre svoju syntax podobnú jazyku C?', 'C#'),
('Technológie', 3, 'Kto vynalezl prvý mobilný telefón?', 'Martin Cooper\nTechnológie'),
('Technológie', 3, 'Kto vyvinul jazyk C++?', 'Bjarne Stroustrup'),
('Technológie', 3, 'Aký typ architektúry je používaný v procesoroch ARM?', 'RISC'),
('Technológie', 3, 'Kto je autorom konceptu blockchain?', 'Satoshi Nakamoto'),
('Technológie', 3, 'Čo je názov pre programovací jazyk vyvinutý na MIT pre umelú inteligenciu?', 'Lisp'),
('Technológie', 3, 'Aký je názov prvého komerčne úspešného osobného počítača?', 'Apple II'),
('Technológie', 3, 'Ktorý jazyk je základom pre vývoj webových stránok?', 'JavaScript'),
('Technológie', 3, 'Aký je názov technológie pre virtuálnu realitu vyvinutej spoločnosťou Oculus?', 'Rift'),
('Technológie', 3, 'Aký typ algoritmu sa používa na rozpoznávanie obrazov?', 'CNN'),
('Technológie', 3, 'Kto je známy ako "otec internetu"?', 'Vint Cerf'),
('Technológie', 3, 'Ktorý operačný systém je srdcom serverov Linux?', 'Ubuntu'),
('Technológie', 3, 'Aký je názov technológie, ktorá umožňuje prenos dát bezdrôtovo na krátke vzdialenosti?', 'Bluetooth'),
('Technológie', 3, 'Čo je názov prvej verzie operačného systému Windows?', 'Windows 1.0'),
('Technológie', 3, 'Ktorá technológia umožňuje zdieľanie zdrojov v rámci počítačovej siete?', 'Cloud'),
('Technológie', 3, 'Aký jazyk bol vyvinutý pre systém Windows a nielen preň?', 'C#'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti Facebook?', 'Mark Zuckerberg'),
('Technológie', 3, 'Aký je názov technológie pre rozšírenú realitu vyvinutej spoločnosťou Microsoft?', 'HoloLens'),
('Technológie', 3, 'Ktorý protokol sa používa pre prenos e-mailov?', 'SMTP'),
('Technológie', 3, 'Aký je skratka pre technológiu pre analýzu veľkých dát?', 'Hadoop'),
('Technológie', 3, 'Ktorý jazyk je známy pre svoje aplikácie v oblasti strojového učenia?', 'R'),
('Technológie', 3, 'Kto je známy ako "otec GPS"?', 'Roger L. Easton'),
('Technológie', 3, 'Aký typ pamäte je známy pre svoju vysokú rýchlosť?', 'RAM'),
('Technológie', 3, 'Ktorá technológia je základom pre bezdrôtové nabíjanie?', 'Qi'),
('Technológie', 3, 'Aká je skratka pre technológiu rozpoznávania hlasu?', 'ASR'),
('Technológie', 3, 'Kto je známy ako zakladateľ spoločnosti Oracle?', 'Larry Ellison'),
('Technológie', 3, 'Aký je názov najpopulárnejšieho prehliadača na svete?', 'Chrome'),
('Technológie', 3, 'Ktorá technológia je známa ako "internet vecí"?', 'IoT'),
('Technológie', 3, 'Aká je skratka pre technológiu na spracovanie textu?', 'XML'),
('Technológie', 3, 'Kto je autorom teórie automatov?', 'Alan Turing'),
('Technológie', 3, 'Aký je názov technológie pre analýzu dát v reálnom čase?', 'Streaming'),
('Technológie', 3, 'Ktorý jazyk je považovaný za jazyk pre vývoj hier?', 'C++'),
('Technológie', 3, 'Aký je názov technológie pre spracovanie obrazov v počítačoch?', 'GPU'),
('Technológie', 3, 'Ktorá technológia sa používa na ochranu údajov?', 'Šifrovanie'),
('Technológie', 3, 'Aký je názov pre systém správy obsahu?', 'CMS'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti Amazon?', 'Jeff Bezos'),
('Technológie', 3, 'Ktorý softvér sa používa na virtuálne stretnutia?', 'Zoom'),
('Technológie', 3, 'Aký jazyk je základom pre Android aplikácie?', 'Java'),
('Technológie', 3, 'Ktorý typ databázy je známy ako relačná?', 'SQL'),
('Technológie', 3, 'Aký je názov pre systém ovládania verzií?', 'Git'),
('Technológie', 3, 'Ktorý jazyk je známy pre vývoj aplikácií pre iOS?', 'Swift'),
('Technológie', 3, 'Aký je názov pre technológiu na analýzu dát pomocou umelých neurónových sietí?', 'Deep Learning'),
('Technológie', 3, 'Kto je známy ako zakladateľ spoločnosti Intel?', 'Robert Noyce'),
('Technológie', 3, 'Aký je názov pre technológiu na prenos videa cez internet?', 'Streaming'),
('Technológie', 3, 'Ktorý typ pamäte sa používa pre trvalé uloženie dát?', 'ROM'),
('Technológie', 3, 'Aká je skratka pre technológiu bezdrôtovej komunikácie?', 'Wi-Fi'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti IBM?', 'Charles Ranlett Flint'),
('Technológie', 3, 'Aký je názov pre jazyk na tvorbu webových stránok?', 'HTML'),
('Technológie', 3, 'Ktorý jazyk bol vyvinutý pre analýzu dát?', 'Python'),
('Technológie', 3, 'Aký je názov pre systém riadenia obsahu na webových stránkach?', 'WordPress'),
('Technológie', 3, 'Kto je známy ako zakladateľ spoločnosti Adobe?', 'John Warnock'),
('Technológie', 3, 'Ktorý typ programovania sa využíva na vývoj mobilných aplikácií?', 'Objektové'),
('Technológie', 3, 'Aký je názov pre technológiu, ktorá zaisťuje bezpečnosť pripojenia?', 'VPN\nTechnológie'),
('Technológie', 2, 'Čo je to DNS?', 'Doménový systém'),
('Technológie', 2, 'Aký je názov programovacieho jazyka používaného na webovú analýzu?', 'R'),
('Technológie', 2, 'Kto vytvoril jazyk PHP?', 'Rasmus Lerdorf'),
('Technológie', 2, 'Aká je skratka pre "zabezpečený prenos"?', 'HTTPS'),
('Technológie', 2, 'Aký je názov technológie pre digitálne platby?', 'PayPal'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Twitter?', 'Jack Dorsey'),
('Technológie', 2, 'Aký je názov pre protokol pre prenos videa?', 'RTSP'),
('Technológie', 2, 'Aká je skratka pre "súborový systém"?', 'FS'),
('Technológie', 2, 'Aký jazyk sa používa na server-side scripting?', 'PHP'),
('Technológie', 2, 'Aký je názov technológie pre spracovanie prirodzeného jazyka?', 'NLP'),
('Technológie', 2, 'Čo je to VPN?', 'Virtuálna privátna sieť'),
('Technológie', 2, 'Kto je autorom jazyka JavaScript?', 'Brendan Eich'),
('Technológie', 2, 'Aký je názov platformy pre správu projektov?', 'Jira'),
('Technológie', 2, 'Čo je to API?', 'Programovacie rozhranie'),
('Technológie', 2, 'Aký je názov technológie pre analýzu sentimentu?', 'Sentiment analýza'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti LinkedIn?', 'Reid Hoffman'),
('Technológie', 2, 'Aký je názov technológie pre digitálne podpisy?', 'PKI'),
('Technológie', 2, 'Aký je názov pre technológiu blockchain?', 'Distribuovaná kniha'),
('Technológie', 2, 'Aká je skratka pre "zabezpečené pripojenie"?', 'SSL'),
('Technológie', 2, 'Kto je autorom jazyka Swift?', 'Apple'),
('Technológie', 2, 'Aký je názov pre technológiu na analýzu veľkých dát?', 'Big Data'),
('Technológie', 2, 'Ktorý jazyk je známy pre strojové učenie?', 'Python'),
('Technológie', 2, 'Aký je názov pre nástroj na správu kódu?', 'Git'),
('Technológie', 2, 'Čo je to CI/CD?', 'Kontinuálna integrácia'),
('Technológie', 2, 'Kto je autorom technológie Docker?', 'Solomon Hykes'),
('Technológie', 2, 'Aký je názov pre technológiu na zdieľanie súborov?', 'BitTorrent'),
('Technológie', 2, 'Aká je skratka pre "okrajové spracovanie"?', 'Edge'),
('Technológie', 2, 'Aký je názov pre technológiu na rozpoznávanie reči?', 'ASR'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Spotify?', 'Daniel Ek'),
('Technológie', 2, 'Aký je názov pre technológiu pre cloudové úložisko?', 'Dropbox'),
('Technológie', 2, 'Aký je názov technológie pre analýzu dát?', 'Data Mining'),
('Technológie', 2, 'Čo je to IoT?', 'Internet vecí'),
('Technológie', 2, 'Aký je názov pre technológiu na správu obsahu?', 'CMS'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Slack?', 'Stewart Butterfield'),
('Technológie', 2, 'Aký jazyk je známy pre vývoj webových aplikácií?', 'Ruby'),
('Technológie', 2, 'Aký je názov pre technológiu na prediktívne modelovanie?', 'Prediktívna analýza'),
('Technológie', 2, 'Kto je autorom technológie Kubernetes?', 'Google'),
('Technológie', 2, 'Čo je to SaaS?', 'Softvér ako služba'),
('Technológie', 2, 'Aký je názov pre technológiu pre mobilné platby?', 'Apple Pay'),
('Technológie', 2, 'Aký je názov pre technológiu na automatizáciu testovania?', 'Selenium'),
('Technológie', 2, 'Kto je zakladateľom spoločnosti Zoom?', 'Eric Yuan'),
('Technológie', 2, 'Aký jazyk je známy pre vývoj hier?', 'C#'),
('Technológie', 2, 'Aký je názov pre technológiu pre analýzu dát v reálnom čase?', 'Stream Processing'),
('Technológie', 2, 'Kto je autorom technológie TensorFlow?', 'Google'),
('Technológie', 2, 'Aký je názov pre protokol pre prenos súborov?', 'FTP'),
('Technológie', 3, 'Aká je skratka pre "zabezpečený prenos" na internete?', 'HTTPS'),
('Technológie', 3, 'Ktorá technológia sa používa na decentralizované uchovávanie dát?', 'Blockchain'),
('Technológie', 3, 'Aký jazyk je známy pre vývoj aplikácií strojového učenia?', 'Python'),
('Technológie', 3, 'Kto je autorom jazyka Swift?', 'Apple'),
('Technológie', 3, 'Aký je názov pre technológiu správy kontajnerov?', 'Docker'),
('Technológie', 3, 'Čo je to API?', 'Rozhranie'),
('Technológie', 3, 'Kto je známy za vývoj jazykov Ada a Pascal?', 'Niklaus Wirth'),
('Technológie', 3, 'Aký je názov pre technológiu na spracovanie prirodzeného jazyka?', 'NLP'),
('Technológie', 3, 'Ktorý protokol sa používa pre prenos videa na YouTube?', 'RTMP'),
('Technológie', 3, 'Aký je názov technológie pre analýzu sentimentu?', 'Sentiment'),
('Technológie', 3, 'Kto je zakladateľom spoločnosti Spotify?', 'Daniel Ek'),
('Technológie', 3, 'Aký je názov pre technológiu na prediktívne modelovanie?', 'Machine Learning'),
('Technológie', 3, 'Ktorý jazyk je považovaný za jazyk pre webové aplikácie?', 'JavaScript'),
('Technológie', 3, 'Aký je názov technológie pre cloudové úložisko od Amazonu?', 'S3'),
('Technológie', 3, 'Kto je autorom technológie Kubernetes?', 'Google'),
('Technológie', 3, 'Aký je názov pre technológiu na automatizáciu testovania?', 'Selenium'),
('Technológie', 3, 'Aký je názov pre jazyk na analýzu veľkých dát?', 'R'),
('Technológie', 3, 'Ktorý jazyk je známy pre vývoj hier?', 'C++'),
('Technológie', 3, 'Aký je názov pre systém správy databáz od Microsoftu?', 'SQL Server'),
('Technológie', 3, 'Kto je známy za vývoj jazykov Ruby a Perl?', 'Larry Wall'),
('Technológie', 3, 'Aká je skratka pre "zabezpečené pripojenie"?', 'VPN'),
('Technológie', 3, 'Ktorý jazyk sa používa na server-side scripting?', 'PHP'),
('Technológie', 3, 'Aký je názov pre technológiu, ktorá zaisťuje bezpečnosť pripojenia?', 'SSL'),
('Technológie', 3, 'Kto je autorom teórie informačnej teórie?', 'Claude Shannon'),
('Technológie', 3, 'Aký jazyk je známy pre analýzu veľkých dát?', 'Scala'),
('Technológie', 3, 'Aký je názov pre technológiu na zdieľanie súborov?', 'P2P');