INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Geografia', 2, 'Kde sa nachádza mesto Curych?', 'Švajčiarsko'),
('Geografia', 2, 'Kde sa nachádza mesto Praha?', 'Česko'),
('Geografia', 2, 'Kde sa nachádza mesto Mníchov?', 'Nemecko'),
('Geografia', 2, 'Kde sa nachádza mesto Kapské Mesto?', 'Južná Afrika'),
('Geografia', 2, 'Aké je hlavné mesto Holandska?', 'Amsterdam'),
('Geografia', 2, 'Kde sa nachádza Veľký bariérový útes?', 'Austrália'),
('Geografia', 2, 'Ktoré mesto je známe ako Mesto svetiel?', 'Paríž'),
('Geografia', 2, 'Kde sa nachádza mesto Budapešť?', 'Maďarsko'),
('Geografia', 2, 'Ktorý oceán je najmenší?', 'Severný'),
('Geografia', 2, 'Kde sa nachádza mesto Porto?', 'Portugalsko'),
('Geografia', 2, 'Kde leží mesto Tokio?', 'Japonsko'),
('Geografia', 2, 'Kde sa nachádza mesto Hongkong?', 'Čína'),
('Geografia', 2, 'Kde sa nachádza mesto Sydney?', 'Austrália'),
('Geografia', 2, 'Kde sa nachádza mesto Bratislava?', 'Slovensko'),
('Geografia', 2, 'Kde sa nachádzajú Galapágy?', 'Ekvádor'),
('Geografia', 2, 'Kde sa nachádza mesto Catania?', 'Taliansko'),
('Geografia', 2, 'Kde sa nachádza mesto Helsinki?', 'Fínsko'),
('Geografia', 2, 'Kde sa nachádza mesto Amsterodam?', 'Holandsko'),
('Geografia', 2, 'Kde sa nachádza mesto Quito?', 'Ekvádor'),
('Geografia', 2, 'Kde sa nachádza mesto La Paz?', 'Bolívia'),
('Geografia', 2, 'Kde sa nachádza mesto Antananarivo?', 'Madagaskar'),
('Geografia', 2, 'Ktorá krajina je známa svojimi fjordmi?', 'Nórsko'),
('Geografia', 2, 'Kde sa nachádza mesto Stockholm?', 'Švédsko'),
('Geografia', 2, 'Kde sa nachádza mesto Vilnius?', 'Litva'),
('Geografia', 2, 'Kde sa nachádza mesto Tallinn?', 'Estónia'),
('Geografia', 2, 'Kde sa nachádza mesto Dubrovník?', 'Chorvátsko'),
('Geografia', 2, 'Kde sa nachádza mesto Bratislava?', 'Slovensko'),
('Geografia', 2, 'Kde sa nachádza mesto Tbilisi?', 'Gruzínsko'),
('Geografia', 2, 'Kde sa nachádza mesto Baku?', 'Azerbajdžan'),
('Geografia', 2, 'Kde sa nachádza mesto Sofia?', 'Bulharsko'),
('Geografia', 2, 'Kde sa nachádza mesto Sarajevo?', 'Bosna a Hercegovina'),
('Geografia', 2, 'Kde sa nachádza mesto Vilnius?', 'Litva'),
('Geografia', 2, 'Kde sa nachádza mesto PeKING?', 'Čína'),
('Geografia', 2, 'Kde sa nachádza mesto Nicosia?', 'Cyprus'),
('Geografia', 2, 'Ktoré mesto je známe ako "Mesto kanálov"?', 'Benátky'),
('Geografia', 2, 'Kde sa nachádza najväčšia socha Budhu?', 'Kambodža'),
('Geografia', 2, 'Ktorý kontinent je domovom najväčšieho počtu krajín?', 'Afrika'),
('Geografia', 2, 'Kde sa nachádza mesto Petra?', 'Jordánsko'),
('Geografia', 2, 'Kde sa nachádza najvyšší vodopád na svete?', 'Venezuela'),
('Geografia', 2, 'Kde sa nachádza najväčší ostrov v Tichom oceáne?', 'Grónsko'),
('Geografia', 2, 'Kto je autor mapy sveta z 16. storočia?', 'Mercator'),
('Geografia', 2, 'Kde sa nachádza mesto Káhira?', 'Egypt'),
('Geografia', 2, 'Ktorá krajina má najdlhšiu rieku na svete?', 'Brazília'),
('Geografia', 2, 'Kde sa nachádza mesto Buenos Aires?', 'Argentína'),
('Geografia', 2, 'Kde sa nachádza najstaršia univerzita na svete?', 'Bologna'),
('Geografia', 2, 'Ktorá krajina leží na najviac ostrovoch?', 'Švédsko'),
('Geografia', 2, 'Kde sa nachádza mesto Reykjavik?', 'Island'),
('Geografia', 2, 'Ktorá krajina je známa svojimi fjordmi?', 'Nórsko'),
('Geografia', 2, 'Kde sa nachádza socha Krista Spasiteľa?', 'Brazília'),
('Geografia', 2, 'Ktoré mesto je známe ako "Mesto lásky"?', 'Paríž'),
('Geografia', 2, 'Kde sa nachádza púšť Atakama?', 'Čile'),
('Geografia', 2, 'Kde sa nachádza mesto Lima?', 'Peru'),
('Geografia', 2, 'Kde sa nachádza mesto Nairobi?', 'Keňa'),
('Geografia', 2, 'Kde sa nachádza mesto Oslo?', 'Nórsko'),
('Geografia', 2, 'Kde sa nachádza najhlbšie jazero v Afrike?', 'Tanganika'),
('Geografia', 2, 'Ktorý štát je známy ako "Zlatý štát"?', 'Kalifornia'),
('Geografia', 2, 'Kde sa nachádza mesto Santiago?', 'Čile'),
('Geografia', 2, 'Kde sa nachádza známa pyramída v Gíze?', 'Egypt'),
('Geografia', 2, 'Kde sa nachádza mesto Antananarivo?', 'Madagaskar'),
('Geografia', 2, 'Kde sa nachádza najväčšia púšť v Ázii?', 'Gobi'),
('Geografia', 2, 'Ktoré mesto je známe ako hlavné mesto módy?', 'Miláno'),
('Geografia', 2, 'Kde sa nachádza známa pláž Copacabana?', 'Brazília'),
('Geografia', 2, 'Kde sa nachádza mesto Hočiminovo Mesto?', 'Vietnam'),
('Geografia', 2, 'Kde sa nachádza jazero Baikal?', 'Rusko'),
('Geografia', 2, 'Ktoré mesto je známe ako "Mesto zázrakov"?', 'Machu Picchu'),
('Geografia', 2, 'Kde sa nachádza mesto Montevideo?', 'Uruguaj'),
('Geografia', 2, 'Kde sa nachádza mesto Oslo?', 'Nórsko'),
('Geografia', 2, 'Kde sa nachádza známa pláž Bondi?', 'Austrália'),
('Geografia', 2, 'Kde sa nachádza mesto Kuala Lumpur?', 'Malajzia'),
('Geografia', 2, 'Kde sa nachádza mesto Helsinki?', 'Fínsko'),
('Geografia', 2, 'Kde sa nachádza mesto Varšava?', 'Poľsko'),
('Geografia', 2, 'Kde sa nachádza mesto Algiers?', 'Alžírsko'),
('Geografia', 2, 'Kde sa nachádza mesto Kapské Mesto?', 'Južná Afrika'),
('Geografia', 2, 'Kde sa nachádza mesto Male?', 'Maldivy'),
('Geografia', 2, 'Kde sa nachádza mesto Tbilisi?', 'Gruzínsko'),
('Geografia', 2, 'Kde sa nachádza mesto Bratislava?', 'Slovensko'),
('Geografia', 2, 'Kde sa nachádza mesto Hanoj?', 'Vietnam'),
('Geografia', 2, 'Kde sa nachádza mesto Dubrovník?', 'Chorvátsko'),
('Geografia', 2, 'Kde sa nachádza mesto Glasgow?', 'Škótsko'),
('Geografia', 2, 'Kde sa nachádza mesto Nicosia?', 'Cyprus'),
('Geografia', 2, 'Kde sa nachádza mesto Tallinn?', 'Estónia'),
('Geografia', 2, 'Kde sa nachádza mesto Vilnius?', 'Litva'),
('Geografia', 2, 'Kde sa nachádza mesto Sofia?', 'Bulharsko'),
('Geografia', 2, 'Kde sa nachádza mesto Sarajevo?', 'Bosna a Hercegovina'),
('Geografia', 2, 'Kde sa nachádza mesto Baku?', 'Azerbajdžan'),
('Geografia', 2, 'Kde sa nachádza mesto Catania?', 'Taliansko'),
('Geografia', 2, 'Kde sa nachádza mesto Quito?', 'Ekvádor'),
('Geografia', 2, 'Kde sa nachádza mesto La Paz?', 'Bolívia'),
('Geografia', 2, 'Kde sa nachádza mesto Amsterodam?', 'Holandsko'),
('Geografia', 2, 'Kde sa nachádza mesto Stockholm?', 'Švédsko'),
('Geografia', 2, 'Kde sa nachádza mesto Bratislava?', 'Slovensko'),
('Geografia', 3, 'Aké je hlavné mesto Bahrajnu?', 'Manáma'),
('Geografia', 3, 'Kde sa nachádza najhlbšia priepasť na svete?', 'Mariánska priekopa'),
('Geografia', 3, 'Ktorá krajina má najviac jazier na svete?', 'Kanada'),
('Geografia', 3, 'Kde sa nachádza najväčší ostrov na svete?', 'Grónsko'),
('Geografia', 3, 'Kde sa nachádza gejzír Old Faithful?', 'Yellowstone'),
('Geografia', 3, 'Ktoré mesto je známe ako „Mesto riek“?', 'Bologna'),
('Geografia', 3, 'Kde sa nachádza najväčšia jaskyňa na svete?', 'Son Doong'),
('Geografia', 3, 'Ktoré mesto je známe ako „Mesto mostov“?', 'Pittsburgh'),
('Geografia', 3, 'Kde sa nachádza najväčší vodopád v USA?', 'Niagara'),
('Geografia', 3, 'Kde sa nachádza najvyšší vodopád na svete?', 'Angel'),
('Geografia', 3, 'Kde sa nachádza najstaršia univerzita v Európe?', 'Bologna'),
('Geografia', 3, 'Kde leží mesto Timbuktu?', 'Mali'),
('Geografia', 3, 'Ktoré mesto je známe svojou sochou „Cristo Redentor“?', 'Rio'),
('Geografia', 3, 'Kde sa nachádza najväčšia púšť na svete?', 'Antarktída'),
('Geografia', 3, 'Ktorý štát je známy ako „Zem vychádzajúceho slnka“?', 'Japonsko'),
('Geografia', 3, 'Kde sa nachádza najvyšší vrchol Ázie?', 'K2'),
('Geografia', 3, 'Kde sa nachádza mesto Petra?', 'Jordánsko'),
('Geografia', 3, 'Kde sa nachádza vulkán Mauna Kea?', 'Havaj'),
('Geografia', 3, 'Kde sa nachádza najhlbšie jazero v Európe?', 'Baikal'),
('Geografia', 3, 'Kde sa nachádza mesto Nuuk?', 'Grónsko'),
('Geografia', 3, 'Kde sa nachádzajú Galapágy?', 'Ekvádor'),
('Geografia', 3, 'Kde sa nachádza historické mesto Machu Picchu?', 'Peru'),
('Geografia', 3, 'Kde sa nachádza najväčší ostrov v Indickom oceáne?', 'Madagaskar'),
('Geografia', 3, 'Kde sa nachádza najväčšia socha Budhu?', 'Bodh Gaya'),
('Geografia', 3, 'Kde sa nachádza najväčšia tropická dažďová zrážka?', 'Mawsynram'),
('Geografia', 3, 'Kde sa nachádza mesto Oslofjord?', 'Nórsko'),
('Geografia', 3, 'Kde sa nachádza najdlhšia rieka v Afrike?', 'Níl'),
('Geografia', 3, 'Kde sa nachádza mesto Dubrovník?', 'Chorvátsko'),
('Geografia', 3, 'Kde sa nachádza najsevernejšie mesto na svete?', 'Longyearbyen'),
('Geografia', 3, 'Ktoré mesto je známe ako „Mesto snov“?', 'Las Vegas'),
('Geografia', 3, 'Kde sa nachádza púšť Sahara?', 'Afrika'),
('Geografia', 3, 'Kde sa nachádza mesto Reykjavik?', 'Island'),
('Geografia', 3, 'Kde sa nachádza mesto Antananarivo?', 'Madagaskar'),
('Geografia', 3, 'Kde sa nachádza mesto Suez?', 'Egypt'),
('Geografia', 3, 'Kde sa nachádza mesto Buenos Aires?', 'Argentína'),
('Geografia', 3, 'Kde sa nachádza mesto Luanda?', 'Angola'),
('Geografia', 3, 'Kde sa nachádza najväčší ostrov v Tichom oceáne?', 'Nová Guinea'),
('Geografia', 3, 'Kde sa nachádza mesto Lhasa?', 'Tibet'),
('Geografia', 3, 'Kde sa nachádza mesto Ulaanbaatar?', 'Mongolsko'),
('Geografia', 3, 'Kde sa nachádza mesto Hanoj?', 'Vietnam'),
('Geografia', 3, 'Kde sa nachádza mesto Wellington?', 'Nový Zéland'),
('Geografia', 3, 'Kde sa nachádza mesto Kapské Mesto?', 'Južná Afrika'),
('Geografia', 3, 'Kde sa nachádza mesto Nuuk?', 'Grónsko'),
('Geografia', 3, 'Kde sa nachádza mesto Viedenský les?', 'Rakúsko'),
('Geografia', 3, 'Kde sa nachádza mesto Tbilisi?', 'Gruzínsko'),
('Geografia', 3, 'Kde sa nachádza mesto Santiago?', 'Chile'),
('Geografia', 3, 'Kde sa nachádza mesto Tiranë?', 'Albánsko'),
('Geografia', 3, 'Kde sa nachádza mesto Chisinau?', 'Moldavsko'),
('Geografia', 3, 'Kde sa nachádza mesto Mombasa?', 'Keňa'),
('Geografia', 3, 'Kde sa nachádza mesto Gdaňsk?', 'Poľsko'),
('Geografia', 3, 'Kde sa nachádza mesto Vilnius?', 'Litva'),
('Geografia', 3, 'Kde sa nachádza mesto Bratislava?', 'Slovensko'),
('Geografia', 3, 'Kde sa nachádza mesto Praga?', 'Česko'),
('Geografia', 3, 'Kde sa nachádza mesto Oslo?', 'Nórsko'),
('Geografia', 3, 'Kde sa nachádza mesto Štokholm?', 'Švédsko'),
('Geografia', 3, 'Kde sa nachádza mesto Varšava?', 'Poľsko'),
('Geografia', 3, 'Kde sa nachádza mesto Solún?', 'Grécko'),
('Geografia', 3, 'Kde sa nachádza mesto Tirana?', 'Albánsko'),
('Geografia', 3, 'Kde sa nachádza mesto Quito?', 'Ekvádor'),
('Geografia', 3, 'Kde sa nachádza mesto Luanda?', 'Angola'),
('Geografia', 3, 'Kde sa nachádza mesto Bangkok?', 'Thajsko'),
('Geografia', 3, 'Kde sa nachádza mesto Nairobi?', 'Keňa'),
('Geografia', 3, 'Kde sa nachádza najhlbšie miesto na Zemi?', 'Marianská priekopa'),
('Geografia', 3, 'Aké je najväčšie jazero na svete?', 'Kaspické'),
('Geografia', 3, 'Ktorá krajina má najviac jazier?', 'Kanada'),
('Geografia', 3, 'Kde leží najvyšší vodopád na svete?', 'Angel'),
('Geografia', 3, 'Ktorý kontinent má najviac krajín?', 'Afrika'),
('Geografia', 3, 'Kde sa nachádza mesto Timbuktu?', 'Mali'),
('Geografia', 3, 'Kde sa nachádza najväčší ostrov na svete?', 'Grónsko'),
('Geografia', 3, 'Kde sa nachádza historické mesto Petra?', 'Jordánsko'),
('Geografia', 3, 'Kde sa nachádza najsevernejšie mesto na svete?', 'Ny-Ålesund'),
('Geografia', 3, 'Aké je hlavné mesto Nepálu?', 'Káthmandu'),
('Geografia', 3, 'Kde sa nachádza najstaršia univerzita na svete?', 'Bologna'),
('Geografia', 3, 'Ktoré mesto je známe ako „Mesto svetiel“?', 'Paríž'),
('Geografia', 3, 'Kde leží púšť Atakama?', 'Chile'),
('Geografia', 3, 'Kde sa nachádza najvyšší vrchol Ázie?', 'Mount Everest'),
('Geografia', 3, 'Ktorá krajina má najdlhšiu rieku na svete?', 'Brazília'),
('Geografia', 3, 'Kde sa nachádzajú Galapágy?', 'Ekvádor'),
('Geografia', 3, 'Kde sa nachádza mesto Machu Picchu?', 'Peru'),
('Geografia', 3, 'Kde sa nachádza najhustejší les na svete?', 'Amazonka'),
('Geografia', 3, 'Kde sa nachádza mesto Lhasa?', 'Tibet'),
('Geografia', 3, 'Kde sa nachádza mesto Ulaanbaatar?', 'Mongolsko'),
('Geografia', 3, 'Kde sa nachádza mesto Nuuk?', 'Grónsko'),
('Geografia', 3, 'Kde sa nachádza najhlbšie jazero na svete?', 'Baikal'),
('Geografia', 3, 'Kde sa nachádza najväčšia socha Budhu?', 'Bodhgaya'),
('Geografia', 3, 'Kde sa nachádza najväčšia tropická dažďová zrážka?', 'Mesoamerika'),
('Geografia', 3, 'Kde sa nachádza mesto Reykjavik?', 'Island'),
('Geografia', 3, 'Kde sa nachádza púšť Gobi?', 'Čína'),
('Geografia', 3, 'Kde sa nachádza najdlhšia rieka v Ázii?', 'Chang Jiang'),
('Geografia', 3, 'Kde sa nachádza najsevernejší bod Európy?', 'Nordkapp'),
('Geografia', 3, 'Kde sa nachádza socha Krista Spasiteľa?', 'Rio de Janeiro'),
('Geografia', 3, 'Kde sa nachádza najvyšší vodopád na svete?', 'Angel'),
('Geografia', 3, 'Kde sa nachádza najväčší ostrov v Indickom oceáne?', 'Madagaskar'),
('Geografia', 3, 'Kde sa nachádza známy gejzír Strokkur?', 'Island'),
('Geografia', 3, 'Kde sa nachádza najhlbšia priepasť na svete?', 'Marianská'),
('Geografia', 3, 'Kde sa nachádza najväčší vodopád v USA?', 'Niagara'),
('Geografia', 3, 'Kde sa nachádza najväčšia púšť na svete?', 'Sahara'),
('Geografia', 3, 'Kde sa nachádza najmenší kontinent?', 'Austrália'),
('Geografia', 3, 'Kde sa nachádza známa pláž Copacabana?', 'Brazília'),
('Geografia', 3, 'Kde sa nachádza mesto Algiers?', 'Alžírsko'),
('Geografia', 3, 'Kde sa nachádza mesto Buenos Aires?', 'Argentína'),
('Geografia', 3, 'Kde sa nachádza mesto Santiago?', 'Čile'),
('Geografia', 3, 'Kde sa nachádza mesto Tirana?', 'Albánsko'),
('Geografia', 3, 'Kde sa nachádza mesto Štokholm?', 'Švédsko'),
('Geografia', 3, 'Kde sa nachádza mesto Oslofjord?', 'Nórsko'),
('Geografia', 3, 'Kde sa nachádza mesto Varšava?', 'Poľsko'),
('Geografia', 3, 'Kde sa nachádza mesto Sarajevo?', 'Bosna'),
('Geografia', 3, 'Kde sa nachádza mesto Gdaňsk?', 'Poľsko'),
('Geografia', 3, 'Kde sa nachádza mesto Tallinn?', 'Estónia'),
('Geografia', 3, 'Kde sa nachádza mesto Sofie?', 'Bulharsko'),
('Geografia', 3, 'Kde sa nachádza mesto Baku?', 'Azerbajdžan'),
('Geografia', 3, 'Kde sa nachádza mesto Catania?', 'Taliansko'),
('Geografia', 3, 'Kde sa nachádza mesto Quito?', 'Ekvádor'),
('Geografia', 3, 'Kde sa nachádza mesto La Paz?', 'Bolívia'),
('Geografia', 3, 'Kde sa nachádza mesto Hanoj?', 'Vietnam'),
('Geografia', 3, 'Kde sa nachádza mesto Kapské Mesto?', 'Južná Afrika'),
('Geografia', 3, 'Kde sa nachádza mesto Lima?', 'Peru'),
('Hry a hračky', 1, 'Aká hra kombinuje slová a body?', 'Scrabble'),
('Hry a hračky', 1, 'Ktorý z týchto hier je známy ako "človeče, nehnevaj sa"?', 'Dame'),
('Hry a hračky', 1, 'Aká je najpredávanejšia hračka na svete?', 'Barbie'),
('Hry a hračky', 1, 'Akú hru hráme s kockami?', 'Hracích'),
('Hry a hračky', 1, 'Aká hra je známa ako "Tetris"?', 'Puzzle'),
('Hry a hračky', 1, 'Ktorá hra sa hrá s kartami a má 52 kariet?', 'Poker'),
('Hry a hračky', 1, 'Aké sú malé figúrky v hre Monopoly?', 'Pena'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená medzi deťmi a má kolieska?', 'Bicykel'),
('Hry a hračky', 1, 'Ktorá hra sa hrá na počítači s postavami v boji?', 'Dota'),
('Hry a hračky', 1, 'Aká je najobľúbenejšia stolná hra na svete?', 'Monopoly'),
('Hry a hračky', 1, 'Ktorá hra je známa ako "hra s otázkami"?', 'Kvíz'),
('Hry a hračky', 1, 'Aká hračka sa skladá z farebných kociek?', 'LEGO'),
('Hry a hračky', 1, 'Ktorá hra sa hrá na ploche s figúrkami a šachovnicou?', 'Šach'),
('Hry a hračky', 1, 'Aká hračka sa používa na kreslenie a maľovanie?', 'Farby'),
('Hry a hračky', 1, 'Ktorá hra sa hrá s balónmi a je populárna na párty?', 'Hádzanie'),
('Hry a hračky', 1, 'Ktorá hračka má zvyčajne zvuk a svetlá?', 'Hračky'),
('Hry a hračky', 1, 'Aká hra sa hrá na počítači a vyžaduje tímovú prácu?', 'FPS'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou skákať?', 'Gulička'),
('Hry a hračky', 1, 'Aká hračka sa používa na súťaženie v rýchlosti?', 'Autíčko'),
('Hry a hračky', 1, 'Ktorá hra má figúrky, ktoré sa pohybujú po doske?', 'Dame'),
('Hry a hračky', 1, 'Aký je názov populárneho kartového pokru?', 'Texas'),
('Hry a hračky', 1, 'Ktorá hračka sa používa na stavanie a hranie?', 'Kocky'),
('Hry a hračky', 1, 'Aká hračka je známa svojou schopnosťou lietať?', 'Dron'),
('Hry a hračky', 1, 'Aká kartová hra je známa svojou stratégiou?', 'Rummy'),
('Hry a hračky', 1, 'Ktorá hračka má vo svojej zloženia plyšové zvieratá?', 'Medveď'),
('Hry a hračky', 1, 'Aká hra je známa ako "hra s číslami"?', 'Sudoku'),
('Hry a hračky', 1, 'Ktorá hračka sa používa na skákanie a zábavu?', 'Trampolína'),
('Hry a hračky', 1, 'Ktorá hra je zameraná na preteky s autami?', 'Racing'),
('Hry a hračky', 1, 'Aká hračka je obľúbená pre deti a umožňuje im tvoriť?', 'Hliny'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou plávať?', 'Lodička'),
('Hry a hračky', 1, 'Aká hra sa hrá s figúrkami a vyžaduje stratégiu?', 'Risk'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou jednoduchou konštrukciou?', 'Skladačka'),
('Hry a hračky', 1, 'Aká hra sa hrá s kockami a má cieľ dosiahnuť 21?', 'Blackjack'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou svietiť?', 'Lampička'),
('Hry a hračky', 1, 'Aká hračka je populárna medzi bábätkami a má zvuky?', 'Hrkálka'),
('Hry a hračky', 1, 'Ktorá hračka sa používa na učenie farieb?', 'Kocky'),
('Hry a hračky', 1, 'Aká hračka je známa svojou interaktívnosťou?', 'Tablet'),
('Hry a hračky', 1, 'Ktorá hračka je zameraná na zábavu a pohyb?', 'Loptu'),
('Hry a hračky', 1, 'Aká hra je známa ako "klasická hra s kockami"?', 'Kocky'),
('Hry a hračky', 1, 'Ktorá hra sa hrá na pláži a vyžaduje tímovú prácu?', 'Lopta'),
('Hry a hračky', 1, 'Aké sú malé hračky s postavičkami?', 'Figúrky'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou variabilitou?', 'Puzzle'),
('Hry a hračky', 1, 'Aká hračka je obľúbená pre deti a má pohyb?', 'Autíčko'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou chápať príkazy?', 'Robot'),
('Hry a hračky', 1, 'Akú hru hráme s kartami a má 4 farby?', 'Bingo'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená na výlety a má kolieska?', 'Kufor'),
('Hry a hračky', 1, 'Aká hračka sa používa na hranie vonku a má tvar lopty?', 'Futbal'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou farbou a má tvar zvieraťa?', 'Plyšák'),
('Hry a hračky', 1, 'Aká hračka sa používa na učenie a má rôzne zvuky?', 'Hračky'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená na pieskovisku?', 'Lopta'),
('Hry a hračky', 1, 'Aká hračka sa dá ťahať za sebou?', 'Káčatko'),
('Hry a hračky', 1, 'Ktorá hra sa hrá s figúrkami a má šachovnicu?', 'Šach'),
('Hry a hračky', 1, 'Aká hračka má kolesá a jazdí?', 'Autíčko'),
('Hry a hračky', 1, 'Aká hračka je často vyrobená z plyšu?', 'Medveď'),
('Hry a hračky', 1, 'Ktorá hra sa hrá s kartami a má 21?', 'Blackjack'),
('Hry a hračky', 1, 'Ktorá hračka sa používa na skákanie?', 'Skákacie'),
('Hry a hračky', 1, 'Aká hra je známa svojím logickým myslením?', 'Sudoku'),
('Hry a hračky', 1, 'Aká hračka je určená na maľovanie?', 'Pastelky'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou interaktívnosťou?', 'Tablet'),
('Hry a hračky', 1, 'Ktorá hra sa hrá na doske s bodmi?', 'Dáma'),
('Hry a hračky', 1, 'Aká hračka je určená na skladanie?', 'Puzzle'),
('Hry a hračky', 1, 'Ktorá hračka sa používa na učenie písmen?', 'Písmenká'),
('Hry a hračky', 1, 'Aká hračka je určená pre bábätká a vydáva zvuky?', 'Hračky'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou odolnosťou?', 'Kocky'),
('Hry a hračky', 1, 'Aká hračka je populárna na narodeninových oslavách?', 'Balón'),
('Hry a hračky', 1, 'Ktorá hra je známa svojou rýchlosťou?', 'Bleskovka'),
('Hry a hračky', 1, 'Aká hračka je určená na hranie vo vode?', 'Lodná'),
('Hry a hračky', 1, 'Ktorá hračka má tvar zvieratka a je obľúbená?', 'Plyšák'),
('Hry a hračky', 1, 'Aká hračka je známa svojou schopnosťou skákať?', 'Skočec'),
('Hry a hračky', 1, 'Ktorá hračka je zvyčajne na kolieskach a jazdí?', 'Bicykel'),
('Hry a hračky', 1, 'Ktorá hračka sa dá stavať z kociek?', 'LEGO'),
('Hry a hračky', 1, 'Aká hračka je určená na učenie tvarov?', 'Tvary'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou variabilitou?', 'Stavebnica'),
('Hry a hračky', 1, 'Aká hračka je obľúbená pre deti a má zvuky?', 'Hračka'),
('Hry a hračky', 1, 'Ktorá hračka je zvyčajne vyrobená z plastu?', 'Figúrka'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou farbou a tvarom?', 'Okrúhla'),
('Hry a hračky', 1, 'Aká hračka je často používaná v škôlkach?', 'Kocky'),
('Hry a hračky', 1, 'Ktorá hra sa hrá s kartami a je obľúbená?', 'Poker'),
('Hry a hračky', 1, 'Aká hračka je známa svojou schopnosťou lietať?', 'Dron'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená medzi chlapcami?', 'Autíčko'),
('Hry a hračky', 1, 'Aká hračka je určená na zábavu a pohyb?', 'Skákadlo'),
('Hry a hračky', 1, 'Ktorá hračka má zvuk a je interaktívna?', 'Hlasová'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou jednoduchou konštrukciou?', 'Stolná'),
('Hry a hračky', 1, 'Aká hračka je obľúbená na pláži?', 'Lopta'),
('Hry a hračky', 1, 'Ktorá hračka je určená pre najmenších?', 'Hrkálka'),
('Hry a hračky', 1, 'Aká hra je známa ako "hra na preteky"?', 'Preteky'),
('Hry a hračky', 1, 'Ktorá hračka je určená na hranie vonku?', 'Lopta'),
('Hry a hračky', 1, 'Aká hračka je známa svojou schopnosťou skákať?', 'Skákačka'),
('Hry a hračky', 1, 'Ktorá hra je určená na učenie čísel?', 'Čísla'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená pre deti a je plyšová?', 'Zvieratko'),
('Hry a hračky', 1, 'Aká hračka je známa svojou variabilitou?', 'Stavebnica'),
('Hry a hračky', 1, 'Ktorá hračka je určená na učenie farieb?', 'Farby'),
('Hry a hračky', 1, 'Aká hračka je populárna na narodeninových oslavách?', 'Pohárik'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou svetla?', 'Svietiaca'),
('Hry a hračky', 1, 'Aká hračka je obľúbená na výlety?', 'Batožtek'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou skákať?', 'Skákací míč'),
('Hry a hračky', 1, 'Aká hračka je určená na maľovanie?', 'Farbičky'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená medzi deťmi a má kolieska?', 'Bicykel'),
('Hry a hračky', 1, 'Aká hračka sa používa na učenie tvarov?', 'Stavebnica'),
('Hry a hračky', 1, 'Ktorá hračka je určená pre bábätká a vydáva zvuky?', 'Hrajúca hračka'),
('Hry a hračky', 1, 'Aká hračka je známa svojou variabilitou?', 'Lego'),
('Hry a hračky', 1, 'Ktorá hračka je populárna na narodeninových oslavách?', 'Balón'),
('Hry a hračky', 1, 'Aká hračka je známa svojou farbou a tvarom?', 'Plyšový medveď'),
('Hry a hračky', 1, 'Ktorá hračka je určená na hranie vo vode?', 'Lodná hračka'),
('Hry a hračky', 1, 'Aká hračka je často používaná v škôlkach?', 'Kocky'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená medzi dievčatami?', 'Bábika'),
('Hry a hračky', 1, 'Aká hračka je známa svojou schopnosťou lietať?', 'Dron'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou svietiť?', 'Svietiaca tyč'),
('Hry a hračky', 1, 'Aká hračka je obľúbená na pieskovisku?', 'Lopatka'),
('Hry a hračky', 1, 'Ktorá hračka má tvar zvieratka a je obľúbená?', 'Plyšový pes'),
('Hry a hračky', 1, 'Aká hračka sa dá ťahať za sebou?', 'Ťahací medveď'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou odolnosťou?', 'Gumená lopta'),
('Hry a hračky', 1, 'Aká hračka je určená na učenie farieb?', 'Farebné kocky'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená pre deti a má pohyb?', 'Autíčko'),
('Hry a hračky', 1, 'Akú hru hráme s kockami a má cieľ dosiahnuť 21?', 'Blackjack'),
('Hry a hračky', 1, 'Ktorá hra sa hrá s figúrkami a má šachovnicu?', 'Šach'),
('Hry a hračky', 1, 'Aká hračka sa používa na skákanie?', 'Skákací hračky'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou chápať príkazy?', 'Interaktívny robot'),
('Hry a hračky', 1, 'Aká hračka je obľúbená na výlety a má kolieska?', 'Detský vozík'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená medzi chlapcami?', 'Autíčko'),
('Hry a hračky', 1, 'Aká hra je známa ako "hra na preteky"?', 'Preteky'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou jednoduchou konštrukciou?', 'Puzzle'),
('Hry a hračky', 1, 'Aká hračka je určená na zábavu a pohyb?', 'Skákacie lano'),
('Hry a hračky', 1, 'Ktorá hračka má kolesá a jazdí?', 'Autobus'),
('Hry a hračky', 1, 'Aká hračka je známa svojou schopnosťou plávať?', 'Gumová kačka'),
('Hry a hračky', 1, 'Ktorá hračka je zvyčajne vyrobená z plastu?', 'Figúrka'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou variabilitou?', 'Stavebnica'),
('Hry a hračky', 1, 'Aká hračka je určená na učebné aktivity?', 'Vzdelávacia hračka'),
('Hry a hračky', 1, 'Ktorá hra sa hrá s kartami a má 4 farby?', 'Hra s kartami'),
('Hry a hračky', 1, 'Aká hračka je známa svojou schopnosťou svietiť?', 'Nočná lampa'),
('Hry a hračky', 1, 'Ktorá hračka je určená na učenie písmen?', 'Písmenková hračka'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou odolnosťou?', 'Plyšový hračky'),
('Hry a hračky', 1, 'Aká hračka je populárna na narodeninových oslavách?', 'Hračkársky balón'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou schopnosťou lietať?', 'Detský dron'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou farbou a tvarom?', 'Kocky'),
('Hry a hračky', 1, 'Aká hračka je obľúbená pre deti a je plyšová?', 'Plyšový medveď'),
('Hry a hračky', 1, 'Ktorá hračka je často používaná v škôlkach?', 'Interaktívny stôl'),
('Hry a hračky', 1, 'Aká hračka je určená na maľovanie?', 'Kriedy'),
('Hry a hračky', 1, 'Ktorá hračka sa dá stavať z kociek?', 'Stavebnica'),
('Hry a hračky', 1, 'Aká hračka je určená na učenie a má rôzne zvuky?', 'Zvuková hračka'),
('Hry a hračky', 1, 'Ktorá hračka je obľúbená na hranie vonku?', 'Lopta'),
('Hry a hračky', 1, 'Ktorá hračka je určená pre najmenších?', 'Plyšový králik'),
('Hry a hračky', 1, 'Aká hračka je známa svojou variabilitou?', 'Kreatívna súprava'),
('Hry a hračky', 1, 'Ktorá hračka je populárna na výlet?', 'Detský batoh'),
('Hry a hračky', 1, 'Ktorá hračka je známa svojou farbou a má tvar zvieraťa?', 'Plyšový slon'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou skákať?', 'Skákajúca lopta'),
('Hry a hračky', 2, 'Ktorá hra sa hrá s figúrkami a má šachovnicu?', 'Šach'),
('Hry a hračky', 2, 'Aká hračka je určená na maľovanie a kreslenie?', 'Farbičky'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie farieb?', 'Stolná hra'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou variabilitou a modulárnosťou?', 'Kocky LEGO'),
('Hry a hračky', 2, 'Aká hračka je určená pre bábätká a vydáva zvuky?', 'Interaktívna kniha'),
('Hry a hračky', 2, 'Ktorá hračka má tvar zvieratka a je obľúbená?', 'Plyšový medveď'),
('Hry a hračky', 2, 'Aká hra je známa ako "hra s číslami"?', 'Sudoku'),
('Hry a hračky', 2, 'Ktorá hračka je zvyčajne vyrobená z plastu a má kolieska?', 'Autíčko'),
('Hry a hračky', 2, 'Aká hračka je určená na učenie tvarov?', 'Skladacie tvary'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená pre deti a má pohyb?', 'Bábika s pohybom'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou lietať?', 'Dron'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie písmen?', 'Písmenková skládačka'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou svietiť?', 'Svietiaca lopta'),
('Hry a hračky', 2, 'Ktorá hra je zameraná na preteky s autami?', 'Formule'),
('Hry a hračky', 2, 'Aká hračka je obľúbená na pláži?', 'Lopta'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou odolnosťou?', 'Plyšový lev'),
('Hry a hračky', 2, 'Aká hračka je určená na učenie a má rôzne zvuky?', 'Interaktívna hračka'),
('Hry a hračky', 2, 'Ktorá hračka je určená na stavanie a hranie?', 'Kocky'),
('Hry a hračky', 2, 'Aká hračka je populárna medzi deťmi a má kolieska?', 'Kolobežka'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená na pieskovisku?', 'Lopatka'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou chápať príkazy?', 'Robot'),
('Hry a hračky', 2, 'Ktorá hračka má zvuk a je interaktívna?', 'Interaktívny medveď'),
('Hry a hračky', 2, 'Aká hračka je známa svojou variabilitou a zložitosťou?', 'Puzzle'),
('Hry a hračky', 2, 'Ktorá hračka je určená na zábavu a pohyb?', 'Hojdacia sieť'),
('Hry a hračky', 2, 'Aká hračka je známa svojou jednoduchosťou?', 'Hračkárske autíčko'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou farbou a tvarom?', 'Lopta'),
('Hry a hračky', 2, 'Aká hračka je obľúbená na narodeninových oslavách?', 'Bublifuk'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi dievčatami?', 'Bábika'),
('Hry a hračky', 2, 'Aká hračka je určená na učenie čísel?', 'Karty s číslami'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou schopnosťou plávať?', 'Plávajúca kačička'),
('Hry a hračky', 2, 'Aká hračka je známa svojou farbou a tvarom?', 'Hračkárske zviera'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie a má zvuky?', 'Hudobná hračka'),
('Hry a hračky', 2, 'Aká hračka je známa svojou jednoduchou konštrukciou?', 'Skladačka'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená pre deti a má pohyb?', 'Autíčko na diaľkové ovládanie'),
('Hry a hračky', 2, 'Aká hračka je populárna na narodeninových oslavách?', 'Balón'),
('Hry a hračky', 2, 'Ktorá hračka sa dá ťahať za sebou?', 'Hračkárske auto'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou svietiť?', 'Svietiaci drak'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou variabilitou?', 'Stavebnica'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou skákať?', 'Skákajúca guma'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi chlapcami?', 'Autíčko'),
('Hry a hračky', 2, 'Aká hračka je určená na maľovanie?', 'Kreatívny set'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou schopnosťou plávať?', 'Lodička'),
('Hry a hračky', 2, 'Ktorá hra sa hrá s figúrkami a má strategický charakter?', 'Dáma'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou schopnosťou stavania?', 'Kocky'),
('Hry a hračky', 2, 'Aká hra je zameraná na zábavu a tímovú prácu?', 'Mafia'),
('Hry a hračky', 2, 'Aká je populárna spoločenská hra s otázkami a odpoveďami?', 'Trivial Pursuit'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou odolnosťou a trvácnosťou?', 'Duplo'),
('Hry a hračky', 2, 'Aká kartová hra je založená na bluffovaní?', 'Poker'),
('Hry a hračky', 2, 'Ktorá hračka má zvyčajne štyri kolieska a jazdí?', 'Autíčko'),
('Hry a hračky', 2, 'Aká je najobľúbenejšia stolná hra na svete po Monopoly?', 'Scrabble'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou interaktívnosťou a zvukmi?', 'Robot'),
('Hry a hračky', 2, 'Ktorá hra je založená na hľadaní skrytých predmetov?', 'Hádanky'),
('Hry a hračky', 2, 'Aká hra sa hrá na doske a má cieľ získať všetky figúrky?', 'Parchisi'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi deťmi a má rozprávkové postavy?', 'Plyšová'),
('Hry a hračky', 2, 'Aká hra sa hrá s kockami a má cieľ získať najvyššie skóre?', 'Yahtzee'),
('Hry a hračky', 2, 'Ktorá hračka je určená na zábavu a pohyb?', 'Lopta'),
('Hry a hračky', 2, 'Ktorá kartová hra je známa svojou stratégiou a taktizovaním?', 'Magic'),
('Hry a hračky', 2, 'Aká hračka sa používa na učenie písmen a číslic?', 'Písmenková hra'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená na hranie v skupinách?', 'Spoločenská hra'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou variabilitou a flexibilitou?', 'Stavebnice'),
('Hry a hračky', 2, 'Aká hračka je určená na učenie tvarov a farieb?', 'Vzdelávacia hračka'),
('Hry a hračky', 2, 'Ktorá hračka má tvar zvieratka a je obľúbená medzi deťmi?', 'Plyšový medveď'),
('Hry a hračky', 2, 'Aká hra je známa ako "hra na preteky" s autami?', 'Formule'),
('Hry a hračky', 2, 'Ktorá hračka je určená na hranie vo vode?', 'Hračkárske lode'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojim zvukom a hrou na hudobný nástroj?', 'Klavír'),
('Hry a hračky', 2, 'Aká hračka je populárna medzi bábätkami a má rôzne textúry?', 'Plyšová kniha'),
('Hry a hračky', 2, 'Ktorá hra sa hrá s figúrkami na hexagonálnej doske?', 'Hex'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou skákať a pohybovať sa?', 'Skákacia lopta'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou jednoduchosťou a zábavnosťou?', 'Puzzle'),
('Hry a hračky', 2, 'Ktorá hra je zameraná na zábavu a rozvoj logického myslenia?', 'Kreatívne hry'),
('Hry a hračky', 2, 'Aká hračka je obľúbená na narodeninových oslavách a má svetlá?', 'Balóniky'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou flexibilitou a možnosťou variácií?', 'Stavebnica'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie a je interaktívna?', 'Tablet pre deti'),
('Hry a hračky', 2, 'Aká hračka je populárna pre deti a má zvuky?', 'Interaktívny dinosaur'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou schopnosťou byť "inteligentná"?', 'Robotická hračka'),
('Hry a hračky', 2, 'Ktorá hra sa hrá s figúrkami a má špeciálne pravidlá?', 'Karetní hry'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi deťmi a má pohyb?', 'Hračkárske auto'),
('Hry a hračky', 2, 'Aká hračka je určená na učenie a zahŕňa farby?', 'Vzdelávacia hračka'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou variabilitou a rôznymi použitím?', 'Multifunkčná hračka'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená na pieskovisku a má tvar zvieraťa?', 'Pieskový formička'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou odolnosťou a je vyrobená z gumy?', 'Skákacia guma'),
('Hry a hračky', 2, 'Aká hračka je známa svojou farbou a je plyšová?', 'Plyšová hračka'),
('Hry a hračky', 2, 'Ktorá hračka je určená na hranie vonku?', 'Skateboard'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená na výlety a má kolieska?', 'Cestovný kočík'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou variabilitou a modifikovateľnosťou?', 'Kreatívne stavebnice'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie a má rôzne zvuky?', 'Interaktívna kniha'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou schopnosťou plávať?', 'Lodný model'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi dievčatami a je plyšová?', 'Plyšová bábika'),
('Hry a hračky', 2, 'Ktorá hračka je zvyčajne vyrobená z plastu a je variabilná?', 'Stavebnica'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie a rozvoj schopností?', 'Vzdelávacia stavebnica'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou skákať?', 'Skákací pes'),
('Hry a hračky', 2, 'Aká hračka sa skladá z farebných blokov?', 'Duplo'),
('Hry a hračky', 2, 'Ktorá hračka je určená na montovanie a demontovanie?', 'Kreatívny set'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou farbou a tvarom?', 'Plyšový medveď'),
('Hry a hračky', 2, 'Aká hračka je určená na učenie farieb?', 'Farbičky'),
('Hry a hračky', 2, 'Ktorá hračka má tvar lode a pláva?', 'Lodná hračka'),
('Hry a hračky', 2, 'Aká hračka sa používa na učenie číslic?', 'Číselné kocky'),
('Hry a hračky', 2, 'Ktorá hračka má zvuk a je interaktívna?', 'Interaktívny robot'),
('Hry a hračky', 2, 'Ktorá hra je známa ako "hra na preteky" s autami?', 'Pretekárske autíčka'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou variabilitou?', 'Stavebnica'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou lietať?', 'Dron'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie tvarov?', 'Tvarové kocky'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená pre deti a má svetlá?', 'Svetelný robot'),
('Hry a hračky', 2, 'Aká hra je známa svojím logickým myslením?', 'Logická hra'),
('Hry a hračky', 2, 'Ktorá hračka má kolieska a jazdí?', 'Autíčko'),
('Hry a hračky', 2, 'Ktorá hračka sa používa na hranie vo vode?', 'Plávajúca kačka'),
('Hry a hračky', 2, 'Aká hračka je populárna na narodeninových oslavách?', 'Balóniky'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie písmen?', 'Písmenkový set'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou odolnosťou?', 'Gumená hračka'),
('Hry a hračky', 2, 'Aká hračka je známa svojou jednoduchosťou?', 'Drevené kocky'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi bábätkami?', 'Plyšový zajac'),
('Hry a hračky', 2, 'Ktorá hra sa hrá s figúrkami na doske?', 'Šach'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou plávať?', 'Lodný model'),
('Hry a hračky', 2, 'Ktorá hračka je určená na zábavu a pohyb?', 'Skákajúca lopta'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená pre deti a má zvuky?', 'Zvuková kniha'),
('Hry a hračky', 2, 'Aká hračka je známa svojou variabilitou?', 'Kreatívna stavebnica'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie a má rôzne zvuky?', 'Hudobný nástroj'),
('Hry a hračky', 2, 'Ktorá hra je známa svojou strategickou hrou?', 'Risk'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi chlapcami?', 'Autíčko'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou chápať príkazy?', 'Inteligentný robot'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou farbou a tvarom?', 'Kocka'),
('Hry a hračky', 2, 'Aká hračka je populárna na výlety a má kolieska?', 'Cestovný kočík'),
('Hry a hračky', 2, 'Ktorá hračka je určená na hranie v piesku?', 'Piesková forma'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou schopnosťou skákať?', 'Skákací balón'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi dievčatami?', 'Barbie'),
('Hry a hračky', 2, 'Aká hračka je známa svojou odolnosťou?', 'Gumový medvedík'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie a je interaktívna?', 'Interaktívny tablet'),
('Hry a hračky', 2, 'Aká hračka je známa svojou variabilitou a flexibilitou?', 'Stavebnica LEGO'),
('Hry a hračky', 2, 'Ktorá hračka je určená na zábavu a pohyb?', 'Skákanie na trampolíne'),
('Hry a hračky', 2, 'Ktorá hračka má tvar zvieratka a je obľúbená?', 'Plyšový slon'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou skákať?', 'Skákací hrad'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie farieb?', 'Farbičky'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená na narodeninových oslavách?', 'Torta'),
('Hry a hračky', 2, 'Ktorá hračka má zvuk a je interaktívna?', 'Hračkársky telefón'),
('Hry a hračky', 2, 'Ktorá hračka je známa svojou variabilitou?', 'Puzzle'),
('Hry a hračky', 2, 'Aká hračka je známa svojou schopnosťou plávať?', 'Plávajúci robot'),
('Hry a hračky', 2, 'Ktorá hračka je obľúbená medzi bábätkami a má zvuky?', 'Hračkárska kniha'),
('Hry a hračky', 2, 'Aká hračka je známa svojou jednoduchosťou?', 'Drevené autíčko'),
('Hry a hračky', 2, 'Ktorá hračka je určená na učenie a má rôzne textúry?', 'Textúrne kocky'),
('Hry a hračky', 3, 'Ktorá stolná hra sa hrá na doske so 64 políčkami?', 'Šach'),
('Hry a hračky', 3, 'Aká je názov populárneho detského bábkového divadla?', 'Marioneta'),
('Hry a hračky', 3, 'Ktorá hračka sa používa na učenie a má písmená?', 'Písmenková hra'),
('Hry a hračky', 3, 'Ktorá hra sa hrá na ploche s 9 políčkami?', 'Tic-tac-toe'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou skákať a pohybovať sa?', 'Skákajúca lopta'),
('Hry a hračky', 3, 'Ktorý z týchto hier je známy ako "hra s číslami"?', 'Sudoku'),
('Hry a hračky', 3, 'Ktorá hračka je známa z filmu Toy Story?', 'Buzz Lightyear');