INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Aktuálne dianie', 2, 'Ktorá krajina vyhrala MS v hádzanej 2023?', 'Dánsko'),
('Aktuálne dianie', 2, 'Kto je prezidentom Argentíny?', 'Javier Milei'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Španielska?', 'Pedro Sánchez'),
('Aktuálne dianie', 2, 'Ktorá krajina vyhrala majstrovstvá sveta v rugby?', 'Južná Afrika'),
('Aktuálne dianie', 2, 'Kto je prezidentom Srbska?', 'Aleksandar Vučić'),
('Aktuálne dianie', 2, 'Kto je hlavný vyjednávač USA pre klimatickú dohodu?', 'John Kerry'),
('Aktuálne dianie', 2, 'Ktorá krajina prišla o kráľovnú v 2022?', 'Veľká Británia'),
('Aktuálne dianie', 2, 'Kto je prezidentom Južnej Kórey?', 'Yoon Suk-yeol'),
('Aktuálne dianie', 2, 'Kto je predsedom Európskej rady?', 'Charles Michel'),
('Aktuálne dianie', 2, 'Ktorá krajina prijala zákony proti dezinformáciám?', 'Nemecko'),
('Aktuálne dianie', 2, 'Kto je generálnym tajomníkom OSN?', 'António Guterres'),
('Aktuálne dianie', 2, 'Kto je prezidentom Maďarska?', 'Katalin Novák'),
('Aktuálne dianie', 2, 'Kto je prezidentom Nemecka?', 'Frank-Walter Steinmeier'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Českej republiky?', 'Petr Fiala'),
('Aktuálne dianie', 2, 'Kto je prezidentom Grécka?', 'Katerina Sakellaropoulou'),
('Aktuálne dianie', 2, 'Kto je prezidentom Rumunska?', 'Marcel Ciolacu'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Slovenska?', 'Robert Fico'),
('Aktuálne dianie', 2, 'Kto je prezidentom Portugalska?', 'Marcelo Rebelo'),
('Aktuálne dianie', 2, 'Kto je prezidentom Litvy?', 'Gitanas Nausėda'),
('Aktuálne dianie', 2, 'Kto je predsedníčkou Európskej komisie?', 'Ursula von der Leyen'),
('Aktuálne dianie', 2, 'Kto je prezidentom Egypta?', 'Abdel Fattah el-Sisi'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Talianska?', 'Giorgia Meloni'),
('Aktuálne dianie', 2, 'Kto je prezidentom Slovinska?', 'Nataša Pirc Musar'),
('Aktuálne dianie', 2, 'Kto je prezidentom Mali?', 'Assimi Goïta'),
('Aktuálne dianie', 2, 'Kto je prezidentom Cypru?', 'Nicos Christodoulides'),
('Aktuálne dianie', 2, 'Kto je prezidentom Kene?', 'William Ruto'),
('Aktuálne dianie', 2, 'Kto je prezidentom Sýrie?', 'Bashar al-Assad'),
('Aktuálne dianie', 2, 'Kto je predsedom vlády Belgicka?', 'Alexander De Croo'),
('Aktuálne dianie', 2, 'Kto je prezidentom Malajzie?', 'Anwar Ibrahim'),
('Aktuálne dianie', 2, 'Kto je prezidentom Libanonu?', 'Michel Aoun'),
('Aktuálne dianie', 2, 'Kto je prezidentom Zeleného mysu?', 'José Maria Neves'),
('Aktuálne dianie', 2, 'Kto je prezidentom Dominikánskej republiky?', 'Luis Abinader'),
('Aktuálne dianie', 2, 'Kto je prezidentom Súdánu?', 'Abdel Fattah al-Burhan'),
('Aktuálne dianie', 2, 'Kto je prezidentom Zambie?', 'Hakainde Hichilema'),
('Aktuálne dianie', 2, 'Kto je prezidentom Toga?', 'Faure Gnassingbé'),
('Aktuálne dianie', 2, 'Kto je prezidentom Pobrežia Slonoviny?', 'Alassane Ouattara'),
('Aktuálne dianie', 2, 'Kto je prezidentom Barmy?', 'Min Aung Hlaing'),
('Aktuálne dianie', 2, 'Kto je prezidentom Gabonu?', 'Ali Bongo'),
('Aktuálne dianie', 2, 'Kto je prezidentom Mali?', 'Assimi Goïta'),
('Aktuálne dianie', 2, 'Kto je prezidentom Bahrajnu?', 'Hamad bin Isa Al Khalifa'),
('Aktuálne dianie', 2, 'Kto je prezidentom Qataru?', 'Tamim bin Hamad Al Thani'),
('Aktuálne dianie', 2, 'Kto je prezidentom Saint Kitts a Nevis?', 'Terrance Drew'),
('Aktuálne dianie', 3, 'Kto vyhral voľby v Taliansku v roku 2022?', 'Meloni'),
('Aktuálne dianie', 3, 'Kto je hlavným vyjednávačom USA na klimatických konferenciách?', 'Kerry'),
('Aktuálne dianie', 3, 'Kto je prezidentom Srbska v roku 2023?', 'Vučić'),
('Aktuálne dianie', 3, 'Kto je generálnym tajomníkom EÚ?', 'Ursula von der Leyen'),
('Aktuálne dianie', 3, 'Ktorá krajina zorganizovala COP27?', 'Egypt'),
('Aktuálne dianie', 3, 'Kto je prezidentom Brazílie od roku 2023?', 'Lula'),
('Aktuálne dianie', 3, 'Kto je víťazom Nobelovej ceny za literatúru 2023?', 'Kjell Askildsen'),
('Aktuálne dianie', 3, 'Kto je premiérom Kanady v roku 2023?', 'Trudeau'),
('Aktuálne dianie', 3, 'Kto je prezidentom Ukrajiny od začiatku vojny?', 'Zelenskyj'),
('Aktuálne dianie', 3, 'Ktorá krajina ukončila vojenskú službu pre ženy?', 'Švédsko'),
('Aktuálne dianie', 3, 'Kto je predsedníčkou Európskej komisie v roku 2023?', 'Ursula'),
('Aktuálne dianie', 3, 'Kto je prezidentom Indonézie?', 'Joko Widodo'),
('Aktuálne dianie', 3, 'Kto je víťazom prezidentských volieb vo Francúzsku 2022?', 'Macron'),
('Aktuálne dianie', 3, 'Kto je prezidentom Južnej Kórey od 2022?', 'Yoon Suk-yeol'),
('Aktuálne dianie', 3, 'Ktorá krajina zrušila núdzový stav kvôli COVID-19?', 'Nový Zéland'),
('Aktuálne dianie', 3, 'Kto je generálnym tajomníkom NATO v roku 2023?', 'Stoltenberg'),
('Aktuálne dianie', 3, 'Kto je predsedom vlády Japonska v roku 2023?', 'Kishida'),
('Aktuálne dianie', 3, 'Kto je prezidentom Kolumbie v roku 2023?', 'Gustavo Petro'),
('Aktuálne dianie', 3, 'Kto je premiérom Talianska od 2022?', 'Meloni'),
('Aktuálne dianie', 3, 'Kto je prezidentom Fínska?', 'Niinistö'),
('Aktuálne dianie', 3, 'Kto je prezidentom Argentíny v roku 2023?', 'Milei'),
('Aktuálne dianie', 3, 'Ktorá krajina vyhrala majstrovstvá sveta vo futbale 2022?', 'Argentína'),
('Aktuálne dianie', 3, 'Kto je prezidentom Maďarska v roku 2023?', 'Áder'),
('Aktuálne dianie', 3, 'Kto je predsedom vlády Španielska v roku 2023?', 'Sánchez'),
('Aktuálne dianie', 3, 'Kto je prezidentom Moldavska?', 'Sandu'),
('Aktuálne dianie', 3, 'Kto je víťazom majstrovstiev sveta v hokeji 2023?', 'Kanada'),
('Aktuálne dianie', 3, 'Kto je prezidentom Mexika od 2018?', 'López Obrador'),
('Aktuálne dianie', 3, 'Kto je prezidentom Turecka v roku 2023?', 'Erdogan'),
('Aktuálne dianie', 3, 'Kto je prezidentom Českej republiky od 2023?', 'Pavel'),
('Aktuálne dianie', 3, 'Kto je premiérom Veľkej Británie v roku 2023?', 'Sunak'),
('Aktuálne dianie', 3, 'Kto je prezidentom Nemecka v roku 2023?', 'Steinmeier'),
('Aktuálne dianie', 3, 'Kto je generálnym tajomníkom OSN v roku 2023?', 'Guterres'),
('Aktuálne dianie', 3, 'Kto je prezidentom Litvy?', 'Nausėda'),
('Aktuálne dianie', 3, 'Kto je predsedom vlády Slovenska od 2023?', 'Heger'),
('Aktuálne dianie', 3, 'Kto je prezidentom Grécka?', 'Sakellaropoulou'),
('Aktuálne dianie', 3, 'Kto je prezidentom Rumunska v roku 2023?', 'Iohannis'),
('Aktuálne dianie', 3, 'Kto je prezidentom Zeleného mysu?', 'Ramaphosa'),
('Aktuálne dianie', 3, 'Kto je prezidentom Toga?', 'Gnassingbé'),
('Aktuálne dianie', 3, 'Kto je prezidentom Pobrežia Slonoviny?', 'Ouattara'),
('Aktuálne dianie', 3, 'Kto je predsedníkom vlády Veľkej Británie v roku 2023?', 'Sunak'),
('Aktuálne dianie', 3, 'Kto je prezidentom Egypta?', 'Sisi'),
('Aktuálne dianie', 3, 'Kto je prezidentom Malajzie?', 'Anwar'),
('Aktuálne dianie', 3, 'Kto je prezidentom Cypru?', 'Christodoulides'),
('Aktuálne dianie', 3, 'Kto je prezidentom Sýrie?', 'Asad'),
('Aktuálne dianie', 3, 'Kto je prezidentom Bahrajnu?', 'Khalifa'),
('Aktuálne dianie', 3, 'Kto je prezidentom Saint Kitts?', 'Terrance Drew'),
('Aktuálne dianie', 3, 'Kto je prezidentom Brazílie od roku 2023?', 'Lula da Silva'),
('Aktuálne dianie', 3, 'Ktorá krajina zorganizovala COP27?', 'Egypt'),
('Aktuálne dianie', 3, 'Kto je generálnym tajomníkom NATO v roku 2023?', 'Jens Stoltenberg'),
('Aktuálne dianie', 3, 'Kto je víťazom Nobelovej ceny za literatúru 2023?', 'Jon Fosse'),
('Aktuálne dianie', 3, 'Kto je predsedom vlády Japonska v roku 2023?', 'Fumio Kishida'),
('Aktuálne dianie', 3, 'Kto je prezidentom Kolumbie v roku 2023?', 'Gustavo Petro'),
('Aktuálne dianie', 3, 'Kto je prezidentom Fínska?', 'Sauli Niinistö'),
('Aktuálne dianie', 3, 'Kto je prezidentom Indonézie?', 'Joko Widodo'),
('Aktuálne dianie', 3, 'Kto je predsedom vlády Talianska od 2022?', 'Giorgia Meloni'),
('Aktuálne dianie', 3, 'Kto je prezidentom Malajzie?', 'Anwar Ibrahim'),
('Aktuálne dianie', 3, 'Kto je prezidentom Ukrajiny od začiatku vojny?', 'Volodymyr Zelenskyj'),
('Aktuálne dianie', 3, 'Kto je prezidentom Maďarska v roku 2023?', 'Katalin Novák'),
('Aktuálne dianie', 3, 'Kto je prezidentom Srbska v roku 2023?', 'Aleksandar Vučić'),
('Aktuálne dianie', 3, 'Kto je prezidentom Turecka v roku 2023?', 'Recep Tayyip Erdoğan'),
('Aktuálne dianie', 3, 'Kto je prezidentom Českej republiky od 2023?', 'Petr Pavel'),
('Aktuálne dianie', 3, 'Kto je prezidentom Grécka?', 'Katerina Sakellaropoulou'),
('Aktuálne dianie', 3, 'Kto je prezidentom Zeleného mysu?', 'José Maria Neves'),
('Aktuálne dianie', 3, 'Kto je prezidentom Pobrežia Slonoviny?', 'Alassane Ouattara'),
('Aktuálne dianie', 3, 'Kto je predsedom vlády Veľkej Británie v roku 2023?', 'Rishi Sunak'),
('Aktuálne dianie', 3, 'Kto je prezidentom Egypta?', 'Abdel Fattah el-Sisi'),
('Aktuálne dianie', 3, 'Kto je prezidentom Sýrie?', 'Bashar al-Assad'),
('Aktuálne dianie', 3, 'Kto je prezidentom Bahrajnu?', 'Hamad bin Isa Al Khalifa'),
('Aktuálne dianie', 3, 'Kto je prezidentom Saint Kitts?', 'Terrance Drew'),
('Aktuálne dianie', 3, 'Kto je prezidentom Libanonu?', 'Nabih Berri'),
('Aktuálne dianie', 3, 'Kto je prezidentom Mali?', 'Assimi Goita'),
('Aktuálne dianie', 3, 'Kto je prezidentom Dominikánskej republiky?', 'Luis Abinader'),
('Aktuálne dianie', 3, 'Kto je prezidentom Qataru?', 'Tamim bin Hamad Al Thani'),
('Aktuálne dianie', 3, 'Kto je prezidentom Zambie?', 'Hakainde Hichilema'),
('Aktuálne dianie', 3, 'Kto je prezidentom Toga?', 'Faure Gnassingbé'),
('Aktuálne dianie', 3, 'Kto je prezidentom Barmy?', 'Min Aung Hlaing'),
('Aktuálne dianie', 3, 'Kto je prezidentom Gabonu?', 'Ali Bongo Ondimba'),
('Aktuálne dianie', 3, 'Kto je prezidentom Austrálie?', 'Anthony Albanese'),
('Aktuálne dianie', 3, 'Kto je prezidentom Nového Zélandu?', 'Chris Hipkins'),
('Aktuálne dianie', 3, 'Kto je prezidentom Kanady?', 'Justin Trudeau'),
('Aktuálne dianie', 3, 'Kto je prezidentom Thajska?', 'Prayut Chan-o-cha'),
('Aktuálne dianie', 3, 'Kto je prezidentom Súdánu?', 'Abdel Fattah al-Burhan'),
('Aktuálne dianie', 3, 'Kto je prezidentom Japonska?', 'Fumio Kishida'),
('Aktuálne dianie', 3, 'Kto je prezidentom Nigeru?', 'Mohamed Bazoum'),
('Aktuálne dianie', 3, 'Kto je prezidentom Salvadoru?', 'Nayib Bukele'),
('Aktuálne dianie', 3, 'Kto je prezidentom Haiti?', 'Ariel Henry'),
('Aktuálne dianie', 3, 'Kto je prezidentom Rwandy?', 'Paul Kagame'),
('Aktuálne dianie', 3, 'Kto je prezidentom Zeleného mysu?', 'José Maria Neves'),
('Aktuálne dianie', 3, 'Kto je prezidentom Alžírska?', 'Abdelmadjid Tebboune'),
('Aktuálne dianie', 3, 'Kto je prezidentom Kambodže?', 'Hun Sen'),
('Aktuálne dianie', 3, 'Kto je prezidentom Sýrie?', 'Bashar al-Assad'),
('Aktuálne dianie', 3, 'Kto je prezidentom Malajzie?', 'Anwar Ibrahim'),
('Aktuálne dianie', 3, 'Kto je prezidentom Surinamu?', 'Chandrikapersad Santokhi'),
('Aktuálne dianie', 3, 'Kto je prezidentom Gany?', 'Nana Akufo-Addo'),
('Aktuálne dianie', 3, 'Kto je prezidentom Nemecka?', 'Frank-Walter Steinmeier'),
('Aktuálne dianie', 3, 'Kto je prezidentom Francúzska?', 'Emmanuel Macron'),
('Aktuálne dianie', 3, 'Kto je prezidentom Portugalska?', 'Marcelo Rebelo de Sousa'),
('Aktuálne dianie', 3, 'Kto je premiérom Kanady v roku 2023?', 'Trudeau'),
('Aktuálne dianie', 3, 'Kto je prezidentom Turecka od 2023?', 'Erdogan'),
('Aktuálne dianie', 3, 'Kto je generálnym tajomníkom NATO v roku 2023?', 'Stoltenberg'),
('Aktuálne dianie', 3, 'Kto je prezidentom Južnej Kórey od 2022?', 'Yoon'),
('Aktuálne dianie', 3, 'Kto je premiérom Veľkej Británie v roku 2023?', 'Sunak'),
('Aktuálne dianie', 3, 'Kto je prezidentom Fínska v roku 2023?', 'Niinistö'),
('Aktuálne dianie', 3, 'Kto je prezidentom Litvy v roku 2023?', 'Nausėda'),
('Aktuálne dianie', 3, 'Kto je prezidentom Brazílie od 2023?', 'Lula'),
('Aktuálne dianie', 3, 'Kto je prezidentom Indonézie v roku 2023?', 'Widodo'),
('Aktuálne dianie', 3, 'Kto je prezidentom Srbska v roku 2023?', 'Vučić'),
('Aktuálne dianie', 3, 'Kto je prezidentom Kolumbie v roku 2023?', 'Petro'),
('Aktuálne dianie', 3, 'Kto je prezidentom Maďarska v roku 2023?', 'Orbán'),
('Aktuálne dianie', 3, 'Kto je prezidentom Moldavska v roku 2023?', 'Sandu'),
('Aktuálne dianie', 3, 'Kto je prezidentom Egypta v roku 2023?', 'El-Sisi'),
('Aktuálne dianie', 3, 'Kto je prezidentom Rumunska v roku 2023?', 'Iohannis'),
('Aktuálne dianie', 3, 'Kto je prezidentom Thajska v roku 2023?', 'Prayuth'),
('Aktuálne dianie', 3, 'Kto je prezidentom Sýrie v roku 2023?', 'Assad'),
('Aktuálne dianie', 3, 'Kto je prezidentom Japonska v roku 2023?', 'Kishida'),
('Aktuálne dianie', 3, 'Kto je prezidentom Zeleného mysu v roku 2023?', 'Moussa'),
('Aktuálne dianie', 3, 'Kto je generálnym tajomníkom EÚ v roku 2023?', 'Von der Leyen'),
('Aktuálne dianie', 3, 'Kto je predsedom vlády Japonska v roku 2023?', 'Kishida'),
('Aktuálne dianie', 3, 'Kto je prezidentom Dominikánskej republiky v roku 2023?', 'Abinader'),
('Aktuálne dianie', 3, 'Kto je prezidentom Malajzie v roku 2023?', 'Anwar'),
('Aktuálne dianie', 3, 'Kto je prezidentom Pobrežia Slonoviny v roku 2023?', 'Ouattara'),
('Aktuálne dianie', 3, 'Kto je prezidentom Austrálie v roku 2023?', 'Albanese'),
('Aktuálne dianie', 3, 'Kto je prezidentom Haiti v roku 2023?', 'Ariel'),
('Aktuálne dianie', 3, 'Kto je prezidentom Nigeru v roku 2023?', 'Bazoum'),
('Aktuálne dianie', 3, 'Kto je prezidentom Kambodže v roku 2023?', 'Hun Sen'),
('Aktuálne dianie', 3, 'Kto je prezidentom Gany v roku 2023?', 'Akufo-Addo'),
('Aktuálne dianie', 3, 'Kto je prezidentom Súdánu v roku 2023?', 'Burhan'),
('Aktuálne dianie', 3, 'Kto je víťazom Nobelovej ceny za mier v roku 2023?', 'Guterres'),
('Aktuálne dianie', 3, 'Kto je prezidentom Zambie v roku 2023?', 'Hichilema'),
('Aktuálne dianie', 3, 'Kto je prezidentom Bahrajnu v roku 2023?', 'Hamad'),
('Aktuálne dianie', 3, 'Kto je prezidentom Maldiv?', 'Solih'),
('Aktuálne dianie', 3, 'Kto je prezidentom Kene v roku 2023?', 'Ruto'),
('Aktuálne dianie', 3, 'Kto je prezidentom Gabonu v roku 2023?', 'Bongo'),
('Aktuálne dianie', 3, 'Kto je prezidentom Sýrie v roku 2023?', 'Assad'),
('Aktuálne dianie', 3, 'Kto je prezidentom Toga v roku 2023?', 'Gnassingbé'),
('Aktuálne dianie', 3, 'Kto je prezidentom Alžírska v roku 2023?', 'Tebboune'),
('Aktuálne dianie', 3, 'Kto je prezidentom Surinamu v roku 2023?', 'Santokhi'),
('Aktuálne dianie', 3, 'Kto je prezidentom Rwandy v roku 2023?', 'Kagame'),
('Aktuálne dianie', 3, 'Kto je prezidentom Barmy v roku 2023?', 'Min Aung'),
('Aktuálne dianie', 3, 'Kto je prezidentom Saint Kitts v roku 2023?', 'Terrence'),
('Aktuálne dianie', 3, 'Kto je prezidentom Zeleného mysu v roku 2023?', 'Moussa'),
('Aktuálne dianie', 3, 'Kto je prezidentom Libanonu v roku 2023?', 'Aoun'),
('Aktuálne dianie', 3, 'Kto je prezidentom Súdánu v roku 2023?', 'Burhan'),
('Aktuálne dianie', 3, 'Kto je prezidentom Dominikánskej republiky v roku 2023?', 'Abinader'),
('Aktuálne dianie', 3, 'Kto je prezidentom Bahrajnu v roku 2023?', 'Hamad'),
('Anatómia', 1, 'Aký orgán pumpuje krv?', 'srdce'),
('Anatómia', 1, 'Kde sa nachádza pečeň?', 'brucho'),
('Anatómia', 1, 'Aký je najväčší orgán v tele?', 'koža'),
('Anatómia', 1, 'Ktorá kost sa nachádza v predlaktí?', 'rádius'),
('Anatómia', 1, 'Aký je hlavný orgán dýchacieho systému?', 'pľúca'),
('Anatómia', 1, 'Aký je názov kostí v hlave?', 'lebka'),
('Anatómia', 1, 'Ktorý sval je zodpovedný za pohyb paží?', 'biceps'),
('Anatómia', 1, 'Aký orgán filtruje krv?', 'obličky'),
('Anatómia', 1, 'Aký je najmenší kost v tele?', 'stapedus'),
('Anatómia', 1, 'Ktorý orgán produkuje inzulín?', 'pankreas'),
('Anatómia', 1, 'Kde sa nachádza slezina?', 'brucho'),
('Anatómia', 1, 'Aký je názov svalov v nohách?', 'stehná'),
('Anatómia', 1, 'Ktorý systém riadi telo?', 'nervový'),
('Anatómia', 1, 'Aký je názov svalov na chrbte?', 'dorsálne'),
('Anatómia', 1, 'Aký orgán je zodpovedný za zmysel chuti?', 'jazyk'),
('Anatómia', 1, 'Ktorý orgán je spojený so sluchom?', 'ucho'),
('Anatómia', 1, 'Aký je názov kĺbu v kolene?', 'meniskus'),
('Anatómia', 1, 'Kde sa nachádza močový mechúr?', 'brucho'),
('Anatómia', 1, 'Aký je názov svalov v hrudníku?', 'pectoralis'),
('Anatómia', 1, 'Ktorý orgán produkuje žlč?', 'pečeň'),
('Anatómia', 1, 'Aký je názov kosti v stehne?', 'femur'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za videnie?', 'oko'),
('Anatómia', 1, 'Kde sa nachádzajú pľúca?', 'hrudník'),
('Anatómia', 1, 'Aký je názov malého prsta na ruke?', 'prst'),
('Anatómia', 1, 'Aký je názov kosti v predlaktí?', 'ulna'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za hormonálnu reguláciu?', 'žľazy'),
('Anatómia', 1, 'Aký je názov časti mozgu?', 'cerebellum'),
('Anatómia', 1, 'Ktorý sval je zodpovedný za dýchanie?', 'bránica'),
('Anatómia', 1, 'Aký je názov časti chrbtice?', 'priečne'),
('Anatómia', 1, 'Kde sa nachádza mozog?', 'hlava'),
('Anatómia', 1, 'Aký je názov žily v tele?', 'vena'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za metabolizmus?', 'pečeň'),
('Anatómia', 1, 'Aký je názov kostí v nohe?', 'kosti'),
('Anatómia', 1, 'Ktorý orgán je spojený s trávením?', 'žalúdok'),
('Anatómia', 1, 'Aký je názov tkaniva, ktoré obklopuje orgány?', 'peritoneum'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za imunitu?', 'slezina'),
('Anatómia', 1, 'Kde sa nachádzajú obličky?', 'brucho'),
('Anatómia', 1, 'Aký je názov nosných kostí?', 'nasálne'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za rovnováhu?', 'ucho'),
('Anatómia', 1, 'Aký je názov svalov v bruchu?', 'abdominálne'),
('Anatómia', 1, 'Ktorý systém chráni telo pred infekciou?', 'imunitný'),
('Anatómia', 1, 'Aký je názov časti zubov?', 'korunka'),
('Anatómia', 1, 'Kde sa nachádza srdce?', 'hrudník'),
('Anatómia', 1, 'Aký je názov ciev, ktoré vedú krv k srdcu?', 'žíly'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za reprodukciu?', 'vaječníky'),
('Anatómia', 1, 'Aký je názov kostí v ruke?', 'zápästie'),
('Anatómia', 1, 'Ktorý sval je zodpovedný za chôdzu?', 'quadriceps'),
('Anatómia', 1, 'Aký je názov malého kostného úseku?', 'kostička'),
('Anatómia', 1, 'Kde sa nachádzajú cievy?', 'telo'),
('Anatómia', 1, 'Aký je názov kĺbu v ramene?', 'glenohumerálny'),
('Anatómia', 1, 'Ktorý orgán zodpovedá za trávenie?', 'žalúdok'),
('Anatómia', 1, 'Aký je názov tkaniva, ktoré spája svaly s kosťami?', 'šľacha'),
('Anatómia', 1, 'Aký je názov časti srdca?', 'predsieň'),
('Anatómia', 1, 'Ktorý orgán produkuje hormóny?', 'štítna žľaza'),
('Anatómia', 1, 'Aký je názov najväčšieho svalstva?', 'gluteus maximus'),
('Anatómia', 1, 'Kde sa nachádzajú uši?', 'hlava'),
('Anatómia', 1, 'Aký je názov kostí v tvári?', 'čeľusť'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za vylučovanie?', 'obličky'),
('Anatómia', 1, 'Aký je názov svalov v predlaktí?', 'flexory'),
('Anatómia', 1, 'Kde sa nachádza pupok?', 'brucho'),
('Anatómia', 1, 'Aký je názov kostí v ruke?', 'zápästie'),
('Anatómia', 1, 'Aký je názov svalov na tvári?', 'mimické svaly'),
('Anatómia', 1, 'Ktorý orgán sa podieľa na dýchaní?', 'priedušnice'),
('Anatómia', 1, 'Aký je názov kĺbu v lakti?', 'ohyb'),
('Anatómia', 1, 'Kde sa nachádzajú pľúca?', 'hrudník'),
('Anatómia', 1, 'Aký je názov kostí v krku?', 'krčné stavce'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za zmysel čuchu?', 'nos'),
('Anatómia', 1, 'Aký je názov tkaniva, ktoré obklopuje svaly?', 'svalovina'),
('Anatómia', 1, 'Kde sa nachádza jazyk?', 'ústa'),
('Anatómia', 1, 'Aký je názov časti chrbtice?', 'bedrová'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za sluch?', 'ucho'),
('Anatómia', 1, 'Aký je názov ciev, ktoré vedú krv od srdca?', 'artérie'),
('Anatómia', 1, 'Kde sa nachádza bránica?', 'hrudná dutina'),
('Anatómia', 1, 'Aký je názov kostí v oblasti hrudníka?', 'rebrá'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za trávenie?', 'žalúdok'),
('Anatómia', 1, 'Aký je názov tkaniva, ktoré spája orgány?', 'väzivo'),
('Anatómia', 1, 'Kde sa nachádzajú obličky?', 'chrbát'),
('Anatómia', 1, 'Aký je názov svalov v bokoch?', 'abduktory'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za imunitu?', 'lymfa'),
('Anatómia', 1, 'Aký je názov najmenšej kosti?', 'sluchová'),
('Anatómia', 1, 'Kde sa nachádza konečník?', 'brucho'),
('Anatómia', 1, 'Aký je názov svalov v oblasti krku?', 'sternocleidomastoid'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za metabolizmus?', 'pečeň'),
('Anatómia', 1, 'Aký je názov kostí v nohe?', 'stehenná'),
('Anatómia', 1, 'Kde sa nachádza srdcová chlopňa?', 'srdce'),
('Anatómia', 1, 'Aký je názov žíl v tele?', 'vena'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za produkciu krvného objemu?', 'kostná dreň'),
('Anatómia', 1, 'Aký je názov najdôležitejších zmyslov?', 'zrak'),
('Anatómia', 1, 'Kde sa nachádza žlčník?', 'brucho'),
('Anatómia', 1, 'Aký je názov tkaniva, ktoré obklopuje pľúca?', 'pleura'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za rozklad potravy?', 'tenké črevo'),
('Anatómia', 1, 'Aký je názov tkaniva, ktoré spája svaly?', 'šľachy'),
('Anatómia', 1, 'Kde sa nachádza nosová dutina?', 'hlava'),
('Anatómia', 1, 'Aký je názov kostí v ruke?', 'falangy'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za hormonálnu reguláciu?', 'pankreas'),
('Anatómia', 1, 'Aký je názov svalov na nohách?', 'kvadricepsy'),
('Anatómia', 1, 'Kde sa nachádza srdce?', 'hrudník'),
('Anatómia', 1, 'Aký je názov kĺbu v bedre?', 'bedrový'),
('Anatómia', 1, 'Ktorý orgán je zodpovedný za produkciu žlče?', 'pečeň'),
('Anatómia', 1, 'Aký je názov tkaniva, ktoré obklopuje srdce?', 'perikard'),
('Anatómia', 1, 'Kde sa nachádzajú sleziny?', 'brucho'),
('Anatómia', 1, 'Aký je názov časti tráviaceho traktu?', 'pažerák'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za reguláciu telesnej teploty?', 'Koža'),
('Anatómia', 2, 'Kde sa nachádzajú predné zuby?', 'Ústa'),
('Anatómia', 2, 'Aký je názov najväčšej žľazy v tele?', 'Pečeň'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za rovnováhu?', 'Mozgový labyrint'),
('Anatómia', 2, 'Kde sa nachádza štítna žľaza?', 'Krk'),
('Anatómia', 2, 'Aký je názov kosti v dolnej časti nohy?', 'Lýtková'),
('Anatómia', 2, 'Ktorý sval je zodpovedný za zdvíhanie ramien?', 'Trapéz'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré spája kosti?', 'Chrupavka'),
('Anatómia', 2, 'Kde sa nachádzajú semenníky?', 'Šourok'),
('Anatómia', 2, 'Aký je názov časti srdca, ktorá pumpuje krv?', 'Komora'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za filtráciu moču?', 'Obličky'),
('Anatómia', 2, 'Kde sa nachádza pankreas?', 'Hrudná dutina'),
('Anatómia', 2, 'Aký je názov svalov v oblasti hrudníka?', 'Pectoralis'),
('Anatómia', 2, 'Ktorý orgán sa podieľa na trávení tukov?', 'Pečeň'),
('Anatómia', 2, 'Aký je názov žľazy, ktorá reguluje metabolizmus?', 'Štítna'),
('Anatómia', 2, 'Kde sa nachádzajú pľúcne alveoly?', 'Pľúca'),
('Anatómia', 2, 'Aký je názov kosti v oblasti zápästia?', 'Zápästné'),
('Anatómia', 2, 'Ktorý orgán produkuje krvné doštičky?', 'Kosť'),
('Anatómia', 2, 'Kde sa nachádza močová trubica?', 'Panva'),
('Anatómia', 2, 'Aký je názov svalov na bruchu?', 'Abdomen'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za pocit hladu?', 'Hypotalamus'),
('Anatómia', 2, 'Aký je názov najväčšej kosti v tele?', 'Stehenná'),
('Anatómia', 2, 'Kde sa nachádzajú zubné korunky?', 'Ústa'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré obklopuje nervy?', 'Neuróny'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za zmysel dotyku?', 'Koža'),
('Anatómia', 2, 'Aký je názov svalov v oblasti chrbta?', 'Erector'),
('Anatómia', 2, 'Kde sa nachádza hypofýza?', 'Mozog'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré vytvára krv?', 'Krvotvorba'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za čuch?', 'Nos'),
('Anatómia', 2, 'Aký je názov časti ucha?', 'Bubienok'),
('Anatómia', 2, 'Kde sa nachádza hrudná kosť?', 'Hrudník'),
('Anatómia', 2, 'Aký je názov svalov v oblasti nôh?', 'Quadriceps'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za vylučovanie potu?', 'Potné žľazy'),
('Anatómia', 2, 'Aký je názov kosti v oblasti panvy?', 'Panvová'),
('Anatómia', 2, 'Kde sa nachádza slinivka brušná?', 'Brucho'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré prenáša impulzy?', 'Nervové'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za zmysel zraku?', 'Oko'),
('Anatómia', 2, 'Aký je názov šľachy, ktorá spája svaly?', 'Šľacha'),
('Anatómia', 2, 'Kde sa nachádzajú črevá?', 'Brucho'),
('Anatómia', 2, 'Aký je názov orgánu, ktorý produkuje spermie?', 'Semenník'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za spracovanie výživy?', 'Črevo'),
('Anatómia', 2, 'Aký je názov cievy, ktorá vedie krv od pľúc?', 'Pľúcna'),
('Anatómia', 2, 'Kde sa nachádza slezina?', 'Brucho'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré chráni orgány?', 'Peritoneum'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za vnímanie zvuku?', 'Ucho'),
('Anatómia', 2, 'Aký je názov kosti v ruke?', 'Zápästie'),
('Anatómia', 2, 'Kde sa nachádzajú svaly v predlaktí?', 'Predlaktie'),
('Anatómia', 2, 'Aký je názov orgánu, ktorý kontroluje hladinu cukru?', 'Pankreas'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za vylučovanie moču?', 'Obličky'),
('Anatómia', 2, 'Aký je názov kosti v oblasti hlavy?', 'Lebka'),
('Anatómia', 2, 'Ktorý orgán reguluje krvný tlak?', 'Obličky'),
('Anatómia', 2, 'Aký je názov hlavného svalstva dolných končatín?', 'Stehná'),
('Anatómia', 2, 'Kde sa nachádzajú pľúcne väzivá?', 'Pľúca'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré obklopuje srdce?', 'Perikard'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za produkciu inzulínu?', 'Pankreas'),
('Anatómia', 2, 'Aký je názov hlavných kostí v chrbtici?', 'Obratle'),
('Anatómia', 2, 'Kde sa nachádzajú očné bulvy?', 'Hlava'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré prenáša kyslík?', 'Krv'),
('Anatómia', 2, 'Ktorý orgán zabezpečuje rovnováhu?', 'Ucho'),
('Anatómia', 2, 'Kde sa nachádza bránica?', 'Hrudník'),
('Anatómia', 2, 'Aký je názov kostí v zápästí?', 'Zápästné'),
('Anatómia', 2, 'Kde sa nachádza temporálna kosť?', 'Hlava'),
('Anatómia', 2, 'Aký je názov žľazy v krku?', 'Štítna'),
('Anatómia', 2, 'Ktorý orgán filtruje odpadové látky?', 'Obličky'),
('Anatómia', 2, 'Aký je názov svalstva v oblasti brucha?', 'Brucho'),
('Anatómia', 2, 'Kde sa nachádza pupok?', 'Brucho'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré prenáša nervové impulzy?', 'Nervy'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za zmysel chuti?', 'Jazyk'),
('Anatómia', 2, 'Kde sa nachádzajú lymfatické uzliny?', 'Telo'),
('Anatómia', 2, 'Aký je názov najväčšieho svalstva?', 'Gluteus'),
('Anatómia', 2, 'Ktorý orgán sa podieľa na trávení bielkovín?', 'Žalúdok'),
('Anatómia', 2, 'Kde sa nachádzajú slinné žľazy?', 'Ústa'),
('Anatómia', 2, 'Aký je názov kĺbu v bedrovej oblasti?', 'Bedrový'),
('Anatómia', 2, 'Kde sa nachádza jazyk?', 'Ústa'),
('Anatómia', 2, 'Aký je názov žľazy, ktorá produkuje adrenalín?', 'Nadobličky'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za zmysel dotyku?', 'Koža'),
('Anatómia', 2, 'Kde sa nachádzajú semenníky?', 'Šourok'),
('Anatómia', 2, 'Aký je názov kosti v oblasti krku?', 'Krčný'),
('Anatómia', 2, 'Ktorý orgán sa podieľa na regulácii teploty?', 'Hypotalamus'),
('Anatómia', 2, 'Kde sa nachádzajú hrudné kosti?', 'Hrudník'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré spája svaly a kosti?', 'Šľachy'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za produkciu žlče?', 'Pečeň'),
('Anatómia', 2, 'Kde sa nachádzajú pľúca?', 'Hrudník'),
('Anatómia', 2, 'Aký je názov tkaniva, ktoré obklopuje obličky?', 'Tukové'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za metabolizmus?', 'Pečeň'),
('Anatómia', 2, 'Aký je názov svalstva v oblasti ramien?', 'Deltový'),
('Anatómia', 2, 'Kde sa nachádza hrtan?', 'Krk'),
('Anatómia', 2, 'Aký je názov kosti v dolnej časti nohy?', 'Päta'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za imunitu?', 'Slezina'),
('Anatómia', 2, 'Kde sa nachádzajú žlčové cesty?', 'Pečeň'),
('Anatómia', 2, 'Aký je názov svalov v oblasti nôh?', 'Stehná'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za vylučovanie potu?', 'Koža'),
('Anatómia', 2, 'Kde sa nachádzajú cievy?', 'Telo'),
('Anatómia', 2, 'Aký je názov žľazy, ktorá produkuje hormóny?', 'Endokrinné'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za absorpciu živín?', 'Črevo'),
('Anatómia', 2, 'Kde sa nachádzajú nervy?', 'Telo'),
('Anatómia', 2, 'Aký je názov kostí v oblasti panvy?', 'Panvové'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za spracovanie potravy?', 'Žalúdok'),
('Anatómia', 2, 'Kde sa nachádzajú cievy vedúce krv?', 'Telo'),
('Anatómia', 2, 'Aký je názov svalov na nohách?', 'Svaly'),
('Anatómia', 2, 'Ktorý orgán je zodpovedný za spracovanie vitamínov?', 'Pečeň'),
('Anatómia', 2, 'Kde sa nachádzajú zuby?', 'Ústa'),
('Anatómia', 3, 'Aký je názov časti srdca, ktorá prijíma krv?', 'atrium'),
('Anatómia', 3, 'Aký je názov najväčšieho nervu v tele?', 'ischiadicus'),
('Anatómia', 3, 'Kde sa nachádza hypotalamus?', 'mozog'),
('Anatómia', 3, 'Aký je názov sluchovej kosti?', 'stapedus'),
('Anatómia', 3, 'Ktorý orgán reguluje pH v krvi?', 'obličky'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré obklopuje svaly?', 'fascia'),
('Anatómia', 3, 'Kde sa nachádzajú lymfatické cievy?', 'telo'),
('Anatómia', 3, 'Ktorý orgán produkuje estradiol?', 'vaječníky'),
('Anatómia', 3, 'Aký je názov žľazy, ktorá produkuje inzulín?', 'pankreas'),
('Anatómia', 3, 'Ktorý sval je zodpovedný za ohyb kolena?', 'hamstring'),
('Anatómia', 3, 'Aký je názov časti kosti, ktorá spája kosti?', 'kĺb'),
('Anatómia', 3, 'Kde sa nachádza štítna žľaza?', 'krk'),
('Anatómia', 3, 'Aký je názov nervového tkaniva, ktoré prenáša signály?', 'neurón'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za produkciu žlče?', 'pečeň'),
('Anatómia', 3, 'Aký je názov kostnej štruktúry v uchu?', 'labyrint'),
('Anatómia', 3, 'Kde sa nachádzajú fibroblasty?', 'tkanivo'),
('Anatómia', 3, 'Aký je názov nervu, ktorý ovláda pohyb očí?', 'oculomotorius'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za zmysel rovnováhy?', 'vnútorné ucho'),
('Anatómia', 3, 'Aký je názov svalovej vrstvy čreva?', 'muscularis'),
('Anatómia', 3, 'Kde sa nachádzajú alveoly?', 'pľúca'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré obklopuje srdce?', 'perikard'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za absorpciu vody?', 'hrubé črevo'),
('Anatómia', 3, 'Aký je názov časti mozgu zodpovednej za rovnováhu?', 'cerebellum'),
('Anatómia', 3, 'Kde sa nachádza hypofýza?', 'pod mozgom'),
('Anatómia', 3, 'Aký je názov šľachy, ktorá spája svaly s kosťami?', 'tendón'),
('Anatómia', 3, 'Ktorý orgán produkuje trávicí enzýmy?', 'pankreas'),
('Anatómia', 3, 'Aký je názov najmenšieho svalu v tele?', 'stapes'),
('Anatómia', 3, 'Kde sa nachádzajú pľúcne alveoly?', 'pľúca'),
('Anatómia', 3, 'Aký je názov časti mozgu zodpovednej za dýchanie?', 'medulla'),
('Anatómia', 3, 'Ktorý orgán sa podieľa na detoxikácii?', 'pečeň'),
('Anatómia', 3, 'Aký je názov svalov, ktoré tvoria bránicu?', 'diaphragma'),
('Anatómia', 3, 'Kde sa nachádzajú črevné klky?', 'tenké črevo'),
('Anatómia', 3, 'Aký je názov žľazy v oblasti krku?', 'štítna'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za reguláciu teploty?', 'hypotalamus'),
('Anatómia', 3, 'Aký je názov kostí v oblasti zápästia?', 'karpály'),
('Anatómia', 3, 'Kde sa nachádza bránica?', 'hrudník'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré prenáša kyslík?', 'krv'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za produkciu progesterónu?', 'vaječníky'),
('Anatómia', 3, 'Aký je názov svalov, ktoré dvíhajú rameno?', 'trapez'),
('Anatómia', 3, 'Kde sa nachádzajú črevné mikroorganizmy?', 'črevá'),
('Anatómia', 3, 'Aký je názov nervu, ktorý ovláda ruku?', 'radialis'),
('Anatómia', 3, 'Ktorý orgán sa podieľa na metabolizme lipidov?', 'pečeň'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré spája svaly?', 'šľachy'),
('Anatómia', 3, 'Kde sa nachádzajú epitelové bunky?', 'koža'),
('Anatómia', 3, 'Aký je názov kostí, ktoré tvoria lebku?', 'kosti'),
('Anatómia', 3, 'Ktorý orgán reguluje hladinu cukru?', 'pankreas'),
('Anatómia', 3, 'Aký je názov svalstva zodpovedného za dýchanie?', 'intercostales'),
('Anatómia', 3, 'Kde sa nachádza močový mechúr?', 'panva'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré prenáša impulzy?', 'nervové'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za produkciu adrenalínu?', 'nadobličky'),
('Anatómia', 3, 'Aký je názov najväčšej žľazy?', 'pečeň'),
('Anatómia', 3, 'Kde sa nachádzajú pľúca?', 'hrudník'),
('Anatómia', 3, 'Aký je názov žľazy, ktorá produkuje hormóny?', 'endokrinné'),
('Anatómia', 3, 'Aký je názov časti mozgu zodpovednej za pamäť?', 'hipokampus'),
('Anatómia', 3, 'Ktorý orgán produkuje erytropoetín?', 'obličky'),
('Anatómia', 3, 'Aký je názov štruktúry, ktorá spája svaly s kosťami?', 'šľacha'),
('Anatómia', 3, 'Ktorý sval umožňuje ohyb kolena?', 'biceps'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré obklopuje nervy?', 'endoneurium'),
('Anatómia', 3, 'Kde sa nachádza epifýza?', 'mozog'),
('Anatómia', 3, 'Aký je názov najväčšieho svalstva v tele?', 'gluteus'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za reguláciu kalcia?', 'pankreas'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré tvoria pľúca?', 'alveolárne'),
('Anatómia', 3, 'Ktorý orgán sa podieľa na detoxikácii krvi?', 'pečeň'),
('Anatómia', 3, 'Kde sa nachádza arachnoidálna membrána?', 'mozog'),
('Anatómia', 3, 'Aký je názov bunky, ktorá produkuje protilátky?', 'plazmatická'),
('Anatómia', 3, 'Ktorý orgán má funkciu regulácie metabolizmu?', 'štítna'),
('Anatómia', 3, 'Aký je názov štruktúry, ktorá chráni miechu?', 'chrbtica'),
('Anatómia', 3, 'Kde sa nachádzajú lymfatické uzliny?', 'lymfatický'),
('Anatómia', 3, 'Ktorý sval je zodpovedný za dýchanie?', 'bránica'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré spája kosti?', 'periosteum'),
('Anatómia', 3, 'Kde sa nachádza sluchová kosť?', 'ucho'),
('Anatómia', 3, 'Aký je názov časti pľúc, kde prebieha výmena plynov?', 'alveoly'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za produkciu inzulínu?', 'pankreas'),
('Anatómia', 3, 'Aký je názov cievy, ktorá vedie krv od srdca?', 'aorta'),
('Anatómia', 3, 'Kde sa nachádza medulla oblongata?', 'mozog'),
('Anatómia', 3, 'Aký je názov svalstva, ktoré dvíha hlavu?', 'sternocleidomastoid'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za spracovanie tukov?', 'pečeň'),
('Anatómia', 3, 'Aký je názov nervu, ktorý ovláda bránicu?', 'frenický'),
('Anatómia', 3, 'Kde sa nachádzajú synapsie?', 'nervový systém'),
('Anatómia', 3, 'Aký je názov štruktúry, ktorá umožňuje pohyb kĺbu?', 'chrupavka'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za reguláciu pH?', 'pečeň'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré prenáša kyslík?', 'hemoglobín'),
('Anatómia', 3, 'Kde sa nachádzajú bazálne gangliá?', 'mozog'),
('Anatómia', 3, 'Aký je názov štruktúry, ktorá spája obličky s močovým mechúrom?', 'močovod'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za filtráciu krvi?', 'obličky'),
('Anatómia', 3, 'Aký je názov časti ucha, ktorá zachytáva zvuk?', 'uši'),
('Anatómia', 3, 'Kde sa nachádza tymus?', 'hrudná dutina'),
('Anatómia', 3, 'Aký je názov štruktúry, ktorá chráni srdce?', 'perikardium'),
('Anatómia', 3, 'Ktorý orgán kontroluje hladinu hormónov?', 'hypofýza'),
('Anatómia', 3, 'Aký je názov žily, ktorá odvádza krv z hlavy?', 'jugulárna'),
('Anatómia', 3, 'Kde sa nachádzajú pľúcne sklíčka?', 'pľúca'),
('Anatómia', 3, 'Aký je názov časti miechy?', 'kanál'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za absorpciu živín?', 'tenké črevo'),
('Anatómia', 3, 'Aký je názov nervu, ktorý ovláda srdce?', 'vagus'),
('Anatómia', 3, 'Kde sa nachádza epifýza?', 'mozog'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré obklopuje svaly?', 'fascia'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za reguláciu cukru?', 'pankreas'),
('Anatómia', 3, 'Aký je názov časti hrudníka?', 'sternum'),
('Anatómia', 3, 'Kde sa nachádzajú bunky zodpovedné za imunitu?', 'lymfatické tkanivo'),
('Anatómia', 3, 'Aký je názov nervového tkaniva v mieche?', 'šedá hmota'),
('Anatómia', 3, 'Ktorý orgán je zodpovedný za rovnováhu?', 'vnútorné ucho'),
('Anatómia', 3, 'Aký je názov žľazy, ktorá produkuje progesterón?', 'vaječník'),
('Anatómia', 3, 'Kde sa nachádzajú obličkové tubuly?', 'obličky'),
('Anatómia', 3, 'Aký je názov svalov, ktoré ovládajú mimiku?', 'tvárové svaly'),
('Anatómia', 3, 'Ktorý orgán sa podieľa na spracovaní vitamínov?', 'pečeň'),
('Anatómia', 3, 'Aký je názov tkaniva, ktoré obklopuje cievy?', 'adventícia'),
('Biológia', 1, 'Aký je najväčší cicavec na svete?', 'Modrý veľryba'),
('Biológia', 1, 'Aký orgán pumpuje krv v tele?', 'Srdce'),
('Biológia', 1, 'Ktorý proces zabezpečuje výrobu energie v bunkách?', 'Fotosyntéza');