INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Náboženstvo', 2, 'Kto je zakladateľom hnutia Hare Krišna?', 'A. C. Bhaktivedanta'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Náboženstvo', 2, 'Kto je autorom "Knihy židovských zákonov"?', 'Maimonides'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod nového roka v judaizme?', 'Roš hašana'),
('Náboženstvo', 2, 'Kto je považovaný za zakladateľa protestantizmu?', 'Martin Luther'),
('Náboženstvo', 2, 'Kto je bohom múdrosti v severskej mytológii?', 'Odín'),
('Náboženstvo', 2, 'Aký je názov svätého textu v sikhizme?', 'Guru Granth'),
('Náboženstvo', 2, 'Kto je duchovným vodcom v sikhizme?', 'Guru'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod jari v judaizme?', 'Pesach'),
('Náboženstvo', 2, 'Kto je považovaný za posledného proroka v judaizme?', 'Malachiáš'),
('Náboženstvo', 2, 'Aký je názov moslimskej svätyne v Medine?', 'Masjid'),
('Náboženstvo', 2, 'Kto je bohom plodnosti v rímskej mytológii?', 'Ceres'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje úrodu v katolicizme?', 'Žatva'),
('Náboženstvo', 2, 'Kto je zakladateľom rehole benediktínov?', 'Benedikt'),
('Náboženstvo', 2, 'Aký je názov modlitby, ktorú recitujú moslimovia pred jedlom?', 'Bismillah'),
('Náboženstvo', 2, 'Kto je hlavným bohom v hinduizme?', 'Brahma'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Náboženstvo', 2, 'Kto je patrónom katolíckej cirkvi?', 'Panna Mária'),
('Náboženstvo', 2, 'Kto je bohom slnka v aztéckej mytológii?', 'Huitzilopochtli'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje oslavu svetla v hinduizme?', 'Diwali'),
('Náboženstvo', 2, 'Kto je bohom obchodu v gréckej mytológii?', 'Hermes'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje pamiatku zosnulých v katolicizme?', 'Dušičky'),
('Náboženstvo', 2, 'Kto je zakladateľom hnutia Bahá''í?', 'Bahá''u''lláh'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Íd al-Fitr'),
('Náboženstvo', 2, 'Kto je bohom smrti v hinduizme?', 'Šiva'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje víťazstvo dobra nad zlom v hinduizme?', 'Dussehra'),
('Náboženstvo', 2, 'Kto je zakladateľom taoizmu?', 'Lao-c'''),
('Náboženstvo', 2, 'Aký je názov modlitby pred jedlom v katolicizme?', 'Molitva'),
('Náboženstvo', 2, 'Kto je považovaný za prvého pápeža?', 'Peter'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje slávnosť v katolicizme?', 'Sviatok'),
('Náboženstvo', 2, 'Kto je bohom múdrosti v gréckej mytológii?', 'Athéna'),
('Náboženstvo', 2, 'Aký je názov svätého textu v hinduizme?', 'Védy'),
('Náboženstvo', 2, 'Kto je bohom chaosu v gréckej mytológii?', 'Erebus'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod nového roka v katolicizme?', 'Nový rok'),
('Náboženstvo', 2, 'Kto je duchovným vodcom v budhizme?', 'Lama'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje radosť?', 'Vianoce'),
('Náboženstvo', 2, 'Kto je bohom hromu v gréckej mytológii?', 'Zeus'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje zber úrody?', 'Sviatok úrody'),
('Náboženstvo', 2, 'Kto je bohom víťazstva v hinduizme?', 'Ganéša'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje pamiatku zosnulých?', 'Día de Muertos'),
('Náboženstvo', 2, 'Kto je zakladateľom scientológie?', 'Ron Hubbard'),
('Náboženstvo', 2, 'Aký je názov modlitby v budhizme?', 'Metta'),
('Náboženstvo', 2, 'Kto je bohom lásky v hinduizme?', 'Káma'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje náboženský pôst?', 'Ramadán'),
('Náboženstvo', 2, 'Kto je bohom vína v gréckej mytológii?', 'Dionýsos'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje narodenie Ježiša?', 'Vianoce'),
('Náboženstvo', 2, 'Kto je patrónom lekárov v katolicizme?', 'Sv. Lukáš'),
('Náboženstvo', 2, 'Aký je názov modlitby v islame?', 'Salah'),
('Náboženstvo', 2, 'Kto je zakladateľom rehole františkánov?', 'František'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod Ducha Svätého?', 'Turíce'),
('Náboženstvo', 2, 'Kto je bohom slnka v hinduizme?', 'Súrja'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje víťazstvo svetla?', 'Diwali'),
('Náboženstvo', 2, 'Kto je bohom vojny v hinduizme?', 'Kálí'),
('Náboženstvo', 2, 'Kto je považovaný za zakladateľa taoizmu?', 'Lao-c'''),
('Náboženstvo', 2, 'Aký je názov svätého textu v sikhizme?', 'Guru Granth'),
('Náboženstvo', 2, 'Kto napísal "Knihu mŕtvych"?', 'Tibetskí mnísi'),
('Náboženstvo', 2, 'Kto je bohom plodnosti v gréckej mytológii?', 'Deméter'),
('Náboženstvo', 2, 'Ktorý deň je zasvätený v islame?', 'Piatok'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Náboženstvo', 2, 'Kto je považovaný za proroka v judaizme?', 'Eliáš'),
('Náboženstvo', 2, 'Kto je zakladateľom Bahá''í?', 'Bahá''u''lláh'),
('Náboženstvo', 2, 'Aký je názov modlitby pred jedlom v judaizme?', 'Birkat Hamazon'),
('Náboženstvo', 2, 'Kto je bohom lásky v rímskej mytológii?', 'Venuša'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje slávnosť v katolicizme?', 'Sviatok Krista Kráľa'),
('Náboženstvo', 2, 'Kto je bohom múdrosti v azteckej mytológii?', 'Tezcatlipoca'),
('Náboženstvo', 2, 'Kto je duchovným vodcom v budhizme?', 'Dalajláma'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod jari v judaizme?', 'Pesach'),
('Náboženstvo', 2, 'Kto je bohom vína v gréckej mytológii?', 'Dionýsos'),
('Náboženstvo', 2, 'Kto je považovaný za posledného proroka v judaizme?', 'Ezechiel'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid al-Fitr'),
('Náboženstvo', 2, 'Kto je zakladateľom scientológie?', 'L. Ron Hubbard'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje zber úrody v judaizme?', 'Sukkot'),
('Náboženstvo', 2, 'Kto je patrónom umelcov v katolicizme?', 'Svätý Lukáš'),
('Náboženstvo', 2, 'Kto je bohom chaosu v gréckej mytológii?', 'Khaos'),
('Náboženstvo', 2, 'Aký je názov festivalu, ktorý oslavuje víťazstvo svetla?', 'Diwali'),
('Náboženstvo', 2, 'Kto je považovaný za zakladateľa protestantizmu?', 'Martin Luther'),
('Náboženstvo', 2, 'Kto je bohom múdrosti v egyptskom náboženstve?', 'Thovt'),
('Náboženstvo', 2, 'Aký je názov modlitby, ktorú recitujú katolíci?', 'Otče náš'),
('Náboženstvo', 2, 'Kto je bohom smrti v hinduizme?', 'Šiva'),
('Náboženstvo', 2, 'Kto je zakladateľom rehole benediktínov?', 'Benedikt z Nursie'),
('Náboženstvo', 2, 'Ktorý sviatok oslavujú kresťania na Pamiatku všetkých svätých?', 'Dušičky'),
('Náboženstvo', 2, 'Aký je názov svätého textu v budhizme?', 'Tripitaka'),
('Náboženstvo', 2, 'Kto je bohom hromu v gréckej mytológii?', 'Zeus'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje pamiatku zosnulých?', 'Dušičky'),
('Náboženstvo', 2, 'Kto je duchovným vodcom v sikhizme?', 'Guru'),
('Náboženstvo', 2, 'Kto je bohom slnka v egyptskom náboženstve?', 'Ra'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje narodenie Ježiša?', 'Vianoce'),
('Náboženstvo', 2, 'Kto je hlavným bohom v hinduizme?', 'Brahma'),
('Náboženstvo', 2, 'Kto je bohom vojny v rímskej mytológii?', 'Mars'),
('Náboženstvo', 2, 'Ktorý sviatok oslavujú kresťania na Veľký piatok?', 'Ukrižovanie'),
('Náboženstvo', 2, 'Kto je zakladateľom rehole františkánov?', 'František z Assisi'),
('Náboženstvo', 2, 'Kto je bohom lásky v hinduizme?', 'Káma'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje príchod jari?', 'Holi'),
('Náboženstvo', 2, 'Kto je bohom víťazstva v hinduizme?', 'Durga'),
('Náboženstvo', 2, 'Aký je názov sviatku, ktorý oslavuje náboženský pôst?', 'Ramadán'),
('Náboženstvo', 2, 'Kto je autorom "Knihy židovských zákonov"?', 'Maimonides'),
('Náboženstvo', 2, 'Kto je zakladateľom šintoizmu?', 'Jinmu'),
('Náboženstvo', 2, 'Kto je bohom obchodu v hinduizme?', 'Ganesha'),
('Náboženstvo', 2, 'Kto je patrónom lekárov v katolicizme?', 'Svätý Lukáš'),
('Náboženstvo', 2, 'Aký je názov modlitby, ktorú recitujú moslimovia pred jedlom?', 'Bismillah'),
('Náboženstvo', 3, 'Aký je názov najstaršieho známeho písma?', 'Klinové písmo'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa zoroastriánstva?', 'Zoroaster'),
('Náboženstvo', 3, 'Aký je názov náboženstva založeného na učení Lao-c''?', 'Taoizmus'),
('Náboženstvo', 3, 'Kto je autorom "Knihy mŕtvych" v egyptskom náboženstve?', 'Anonym'),
('Náboženstvo', 3, 'Ktorý náboženský text je známy ako "Kniha mŕtvych"?', 'Egyptský text'),
('Náboženstvo', 3, 'Kto je považovaný za proroka v sikhizme?', 'Guru Nanak'),
('Náboženstvo', 3, 'Kto napísal "Bhagavad-gítu"?', 'Vyasa'),
('Náboženstvo', 3, 'Aký je názov posvätnej knihy sikhizmu?', 'Guru Granth'),
('Náboženstvo', 3, 'Ktorý deň sa považuje za svätý v judaizme?', 'Sabat'),
('Náboženstvo', 3, 'Kto je bohom múdrosti v gréckej mytológii?', 'Athéna'),
('Náboženstvo', 3, 'Kto je bohom víťazstva v hinduizme?', 'Vishnu'),
('Náboženstvo', 3, 'Aký je názov svätého textu v zoroastriánstve?', 'Avesta'),
('Náboženstvo', 3, 'Kto je bohom plodnosti v egyptskom náboženstve?', 'Hathor'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod nového roka v islame?', 'Ramadán'),
('Náboženstvo', 3, 'Kto je považovaný za prvého rímskeho pápeža?', 'Peter'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod jari v katolicizme?', 'Veľká noc'),
('Náboženstvo', 3, 'Kto je bohom vojny v gréckej mytológii?', 'Ares'),
('Náboženstvo', 3, 'Aký je názov posvätnej knihy budhizmu?', 'Tipitaka'),
('Náboženstvo', 3, 'Kto je bohom lásky v azteckej mytológii?', 'Xochiquetzal'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa šintoizmu?', 'Anonym'),
('Náboženstvo', 3, 'Kto je zakladateľom Bahá''í?', 'Bahá''u''lláh'),
('Náboženstvo', 3, 'Ktorý sviatok je oslavou úrody v hinduizme?', 'Pongal'),
('Náboženstvo', 3, 'Kto je patrónom umelcov v hinduizme?', 'Sarasvatí'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje pamiatku zosnulých v katolicizme?', 'Dušičky'),
('Náboženstvo', 3, 'Kto je bohom slnka v gréckej mytológii?', 'Helios'),
('Náboženstvo', 3, 'Aký je názov náboženského textu v sikhizme?', 'Guru Granth'),
('Náboženstvo', 3, 'Kto je bohom liečenia v grécko-rímskej mytológii?', 'Asklepios'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje víťazstvo svetla nad tmou v hinduizme?', 'Diwali'),
('Náboženstvo', 3, 'Kto je bohom vojny v hinduizme?', 'Kálí'),
('Náboženstvo', 3, 'Aký je názov posvätnej knihy v zoroastriánstve?', 'Avesta'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa taoizmu?', 'Lao-c'''),
('Náboženstvo', 3, 'Ktorý sviatok oslavujú kresťania na pamiatku ukrižovania?', 'Veľký piatok'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa islamu?', 'Muhammad'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod Ducha Svätého?', 'Letnice'),
('Náboženstvo', 3, 'Kto je bohom múdrosti v egyptskom náboženstve?', 'Thovt'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Náboženstvo', 3, 'Kto je bohom smrti v hinduizme?', 'Yama'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje úrodu v judaizme?', 'Sukot'),
('Náboženstvo', 3, 'Kto je bohom chaosu v egyptskom náboženstve?', 'Set'),
('Náboženstvo', 3, 'Kto je autorom "Knihy mŕtvych" v budhizme?', 'Anonym'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje víťazstvo dobra nad zlom v hinduizme?', 'Diwali'),
('Náboženstvo', 3, 'Kto je bohom vánku v gréckej mytológii?', 'Eurus'),
('Náboženstvo', 3, 'Kto je zakladateľom scientológie?', 'Hubbard'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid'),
('Náboženstvo', 3, 'Kto je bohom vína v gréckej mytológii?', 'Dionýsos'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje narodenie Ježiša?', 'Vianoce'),
('Náboženstvo', 3, 'Kto je autorom "Knihy Genesis"?', 'Mojžiš'),
('Náboženstvo', 3, 'Aký je názov svätého textu zoroastriánstva?', 'Avesta'),
('Náboženstvo', 3, 'Ktorý rímsky boh je známy ako "Jupiter"?', 'Dzeus'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa sikhizmu?', 'Guru Nanak'),
('Náboženstvo', 3, 'Ktorý náboženský text sa zaoberá učením Lao-c''?', 'Tao Te ťing'),
('Náboženstvo', 3, 'Aký je názov svätého mesta pre budhistov?', 'Lumbiní'),
('Náboženstvo', 3, 'Kto je hlavným bohom v severskej mytológii?', 'Odin'),
('Náboženstvo', 3, 'Aké je posolstvo "Desatora" v judaizme?', 'Prikázania'),
('Náboženstvo', 3, 'Kto je považovaný za najstaršieho boha v Egypte?', 'Ra'),
('Náboženstvo', 3, 'Kto napísal "Knihu mŕtvych" v Egyptskom náboženstve?', 'Anubis'),
('Náboženstvo', 3, 'Kto je patrónom umelcov v hinduizme?', 'Saraswati'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje zber úrody v Indii?', 'Pongal'),
('Náboženstvo', 3, 'Kto je zakladateľom hnutia Hare Krišna?', 'Prabhupáda'),
('Náboženstvo', 3, 'Ktorý deň sa považuje za svätý v hinduizme?', 'Diwali'),
('Náboženstvo', 3, 'Kto je bohom vojny v severskej mytológii?', 'Týr'),
('Náboženstvo', 3, 'Aký je názov posvätnej knihy v taoizme?', 'Tao Te ťing'),
('Náboženstvo', 3, 'Kto je bohom lásky v hinduizme?', 'Káma'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid'),
('Náboženstvo', 3, 'Kto je bohom múdrosti v gréckej mytológii?', 'Athéna'),
('Náboženstvo', 3, 'Kto je zakladateľom judaizmu?', 'Abrahám'),
('Náboženstvo', 3, 'Aký je názov posvätnej knihy sikhizmu?', 'Guru Granth'),
('Náboženstvo', 3, 'Kto je bohom vojny v hinduizme?', 'Krišna'),
('Náboženstvo', 3, 'Kto je bohom lásky v azteckej mytológii?', 'Xochiquetzal'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod Ducha Svätého?', 'Letnice'),
('Náboženstvo', 3, 'Kto je považovaný za prvého rímskeho pápeža?', 'Peter'),
('Náboženstvo', 3, 'Ktorý náboženský text obsahuje učenia Budhu?', 'Tripitaka'),
('Náboženstvo', 3, 'Kto je zakladateľom Bahá''í?', 'Bahá''u''lláh'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod jari v judaizme?', 'Pesach'),
('Náboženstvo', 3, 'Kto je bohom smrti v hinduizme?', 'Yama'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje víťazstvo dobra nad zlom?', 'Dussehra'),
('Náboženstvo', 3, 'Kto je bohom múdrosti v azteckej mytológii?', 'Tezcatlipoca'),
('Náboženstvo', 3, 'Ktorý sviatok oslavujú kresťania na Pamiatku všetkých svätých?', 'Dušičky'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa sikhizmu?', 'Nanak'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid al-Fitr'),
('Náboženstvo', 3, 'Kto je bohom plodnosti v hinduizme?', 'Parvati'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje náboženský pôst v islame?', 'Ramadán'),
('Náboženstvo', 3, 'Kto je bohom obchodu v hinduizme?', 'Ganesha'),
('Náboženstvo', 3, 'Ktorý deň je zasvätený v katolicizme?', 'Nedeľa'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje lásku a vzájomnosť?', 'Valentín'),
('Náboženstvo', 3, 'Kto je bohom slnka v majskej mytológii?', 'Kinich Ahau'),
('Náboženstvo', 3, 'Kto je považovaný za proroka v islame?', 'Muhammad'),
('Náboženstvo', 3, 'Aký je názov modlitby, ktorú recitujú moslimovia?', 'Salah'),
('Náboženstvo', 3, 'Kto je bohom vojny v egyptskom náboženstve?', 'Horus'),
('Náboženstvo', 3, 'Kto je považovaný za matku Ježiša?', 'Mária'),
('Náboženstvo', 3, 'Aký je názov najposvätnejšej knihy islamu?', 'Korán'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa hinduizmu?', 'Maharishi'),
('Náboženstvo', 3, 'Kto je bohom múdrosti v severskej mytológii?', 'Ódin'),
('Náboženstvo', 3, 'Ktorá kniha je základom židovskej viery?', 'Tóra'),
('Náboženstvo', 3, 'Aký je názov svätého textu v budhizme?', 'Tripitaka'),
('Náboženstvo', 3, 'Kto je autorom "Knihy mŕtvych" v hinduizme?', 'Múdry'),
('Náboženstvo', 3, 'Kto je bohom vojny v hinduizme?', 'Kálí'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa protestantizmu?', 'Luther'),
('Náboženstvo', 3, 'Aký je názov hlavného chrámu v Jeruzaleme?', 'Svätý'),
('Náboženstvo', 3, 'Kto je bohom plodnosti v gréckej mytológii?', 'Demetra'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa taoizmu?', 'Lao-c'''),
('Náboženstvo', 3, 'Aký je názov modlitby, ktorú recitujú moslimovia?', 'Salah'),
('Náboženstvo', 3, 'Kto je bohom smrti v hinduizme?', 'Šiva'),
('Náboženstvo', 3, 'Ktorý sviatok oslavujú Židia na jeseň?', 'Sukot'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje koniec ramadánu?', 'Eid'),
('Náboženstvo', 3, 'Kto je bohom vojny v rímskej mytológii?', 'Mars'),
('Náboženstvo', 3, 'Aký je názov najstaršej známej civilizácie?', 'Sumerská'),
('Náboženstvo', 3, 'Kto je bohom ticha v gréckej mytológii?', 'Hades'),
('Náboženstvo', 3, 'Aký je názov posvätnej knihy zoroastriánstva?', 'Avesta'),
('Náboženstvo', 3, 'Kto je bohom múdrosti v hinduizme?', 'Sarasvatí'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Náboženstvo', 3, 'Kto je považovaný za posledného proroka v judaizme?', 'Eliáš'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod jari v hinduizme?', 'Holi'),
('Náboženstvo', 3, 'Kto je autorom "Bhagavad Gíty"?', 'Krišna'),
('Náboženstvo', 3, 'Kto je hlavným bohom gréckej mytológie?', 'Zeus'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje pamiatku zosnulých?', 'Día de los Muertos'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa Bahá''í?', 'Bahá''u''lláh'),
('Náboženstvo', 3, 'Kto je bohom obchodu v hinduizme?', 'Ganesha'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje zber úrody v Indii?', 'Pongal'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa islamu?', 'Muhammad'),
('Náboženstvo', 3, 'Aký je názov modlitby pred jedlom v judaizme?', 'Hamotzi'),
('Náboženstvo', 3, 'Kto je bohom múdrosti v severskej mytológii?', 'Ódin'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod nového roka v judaizme?', 'Rosh Hashaná'),
('Náboženstvo', 3, 'Ktorý sviatok oslavujú kresťania na Božie narodenie?', 'Vianoce'),
('Náboženstvo', 3, 'Kto je bohom smrti v gréckej mytológii?', 'Thanatos'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje príchod jari v katolicizme?', 'Veľká noc'),
('Náboženstvo', 3, 'Kto je považovaný za zakladateľa buddhizmu?', 'Siddhárta'),
('Náboženstvo', 3, 'Aký je názov svätého textu v sikhizme?', 'Guru Granth'),
('Náboženstvo', 3, 'Kto je bohom lásky v rímskej mytológii?', 'Venus'),
('Náboženstvo', 3, 'Ktorý sviatok oslavujú kresťania na Pamiatku všetkých svätých?', 'Halloween'),
('Náboženstvo', 3, 'Kto je bohom hromu v gréckej mytológii?', 'Zeus'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje pôst v katolicizme?', 'Veľký pôst'),
('Náboženstvo', 3, 'Kto je zakladateľom rehole dominikánov?', 'Dominik'),
('Náboženstvo', 3, 'Kto je bohom vojny v hinduizme?', 'Kálí'),
('Náboženstvo', 3, 'Ktorý deň je zasvätený v judaizme?', 'Sabat'),
('Náboženstvo', 3, 'Aký je názov sviatku, ktorý oslavuje narodenie Budhu?', 'Vesak'),
('Politika', 1, 'Kto je prezidentom USA?', 'Biden'),
('Politika', 1, 'Ktorá strana je v Slovensku vládnou?', 'Smer'),
('Politika', 1, 'Kto je predsedom vlády Slovenska?', 'Heger'),
('Politika', 1, 'Aké je hlavné mesto Francúzska?', 'Paríž'),
('Politika', 1, 'Kto je lídrom KDH?', 'Hrušovský'),
('Politika', 1, 'Čo je názov parlamentu v UK?', 'Westminster'),
('Politika', 1, 'Kto bol prvý prezident Slovenska?', 'Kováč'),
('Politika', 1, 'Kto je zakladateľom OĽaNO?', 'Matovič'),
('Politika', 1, 'Aká je farba vlajky USA?', 'Červená'),
('Politika', 1, 'Kto je premiérom Veľkej Británie?', 'Sunak'),
('Politika', 1, 'Aké je hlavné mesto Nemecka?', 'Berlín'),
('Politika', 1, 'Kto je lídrom PS?', 'Hlinčík'),
('Politika', 1, 'Ktorá krajina má najväčší počet štátov?', 'USA'),
('Politika', 1, 'Aká je farba vlajky Slovenska?', 'Modrá'),
('Politika', 1, 'Kto je predsedom Európskej komisie?', 'Ursula'),
('Politika', 1, 'Čo je názov parlamentu v SR?', 'Národná rada'),
('Politika', 1, 'Kto je najdlhšie slúžiacim prezidentom USA?', 'Franklin'),
('Politika', 1, 'Kde sídli OSN?', 'New York'),
('Politika', 1, 'Kto je prezidentom Ruska?', 'Putin'),
('Politika', 1, 'Aká je hlavná úloha vlády?', 'Správa'),
('Politika', 1, 'Kto je predsedom SNS?', 'Danko'),
('Politika', 1, 'Ktorá krajina je známa ako "Zem vychádzajúceho slnka"?', 'Japonsko'),
('Politika', 1, 'Čo je názov najvyššieho súdu v USA?', 'Supremný'),
('Politika', 1, 'Kto je lídrom KDH?', 'Mikloško'),
('Politika', 1, 'Aké je hlavné mesto Talianska?', 'Rím'),
('Politika', 1, 'Kto je prezidentom Francúzska?', 'Macron'),
('Politika', 1, 'Kto je ministerkou spravodlivosti SR?', 'Žitňanská'),
('Politika', 1, 'Kto je predsedom Smeru?', 'Fico'),
('Politika', 1, 'Aká je farba vlajky Nemecka?', 'Čierna'),
('Politika', 1, 'Kde sídli NATO?', 'Brusel'),
('Politika', 1, 'Kto je zakladateľom strany SaS?', 'Sulík'),
('Politika', 1, 'Kto je ministrom zahraničných vecí SR?', 'Káčer'),
('Politika', 1, 'Kto je šéfom Maďarskej vlády?', 'Orbán'),
('Politika', 1, 'Aké je hlavné mesto Španielska?', 'Madrid'),
('Politika', 1, 'Kto je predsedom čínskej vlády?', 'Li'),
('Politika', 1, 'Kto je prvou dámou USA?', 'Jill'),
('Politika', 1, 'Kto je lídrom strany Zelených?', 'Grüne'),
('Politika', 1, 'Aké je hlavné mesto Česka?', 'Praha'),
('Politika', 1, 'Kto je prezidentom Ukrajiny?', 'Zelenskyj'),
('Politika', 1, 'Kto je predsedom vlády Talianska?', 'Meloni'),
('Politika', 1, 'Kto je generálnym tajomníkom OSN?', 'Guterres'),
('Politika', 1, 'Kto je predsedom Európskeho parlamentu?', 'Metsola'),
('Politika', 1, 'Kto je prezidentom Indie?', 'Murmu'),
('Politika', 1, 'Aká je farba vlajky Japonska?', 'Biela'),
('Politika', 1, 'Kto je predsedom vlády Kanady?', 'Trudeau'),
('Politika', 1, 'Ktorá strana je v Česku vládnou?', 'Piráti'),
('Politika', 1, 'Kto je premiérom Austrálie?', 'Albanese'),
('Politika', 1, 'Kto je prezidentom Brazílie?', 'Lula'),
('Politika', 1, 'Kto je predsedníčkou vlády Nového Zélandu?', 'Ardern'),
('Politika', 1, 'Kto je predsedom strany FIDESZ?', 'Orbán'),
('Politika', 1, 'Aké je hlavné mesto Švédska?', 'Štokholm'),
('Politika', 1, 'Kto je prezidentom Číny?', 'Si Ťin-pching'),
('Politika', 1, 'Kto je premiérkou Spojeného kráľovstva?', 'Rishi Sunak'),
('Politika', 1, 'Kto je predsedom strany ĽSNS?', 'Marián Kotleba'),
('Politika', 1, 'Kto je predsedom vlády Nemecka?', 'Olaf Scholz'),
('Politika', 1, 'Kto je prezidentom Talianska?', 'Sergio Mattarella'),
('Politika', 1, 'Kto je prezidentom Južnej Kórey?', 'Yoon Suk-yeol'),
('Politika', 1, 'Kto je premiérom Indie?', 'Narendra Modi'),
('Politika', 1, 'Aké je hlavné mesto Belgicka?', 'Brusel'),
('Politika', 1, 'Ktorá strana je v Nemecku vládnou?', 'SPD'),
('Politika', 1, 'Kto je prezidentom Argentíny?', 'Javier Milei'),
('Politika', 1, 'Kto je predsedom strany OĽaNO?', 'Igor Matovič'),
('Politika', 1, 'Aké je hlavné mesto Holandska?', 'Amsterdam'),
('Politika', 1, 'Kto je prezidentom Srbska?', 'Aleksandar Vučić'),
('Politika', 1, 'Kto je predsedom vlády Japonska?', 'Fumio Kishida'),
('Politika', 1, 'Kto je prezidentom Egypta?', 'Abdel Fattah'),
('Politika', 1, 'Kto je predsedom strany Smer?', 'Robert Fico'),
('Politika', 1, 'Kto je premiérkou Nového Zélandu?', 'Chris Hipkins'),
('Politika', 1, 'Aké je hlavné mesto Turecka?', 'Ankara'),
('Politika', 1, 'Kto je prezidentom Mexika?', 'Andrés Manuel'),
('Politika', 1, 'Kto je predsedom strany SNS?', 'Andrej Danko'),
('Politika', 1, 'Ktorá strana je v Rakúsku vládnou?', 'ÖVP'),
('Politika', 1, 'Kto je prezidentom Filipín?', 'Ferdinand Marcos'),
('Politika', 1, 'Kto je predsedom vlády Španielska?', 'Pedro Sánchez'),
('Politika', 1, 'Kto je predsedom strany FIDESZ?', 'Viktor Orbán'),
('Politika', 1, 'Aké je hlavné mesto Dánska?', 'Kodaň'),
('Politika', 1, 'Kto je prezidentom Ukrajiny?', 'Volodymyr Zelenskyj'),
('Politika', 1, 'Kto je predsedom strany PS?', 'Michal Šimečka'),
('Politika', 1, 'Kto je premiérom Kanady?', 'Justin Trudeau'),
('Politika', 1, 'Kto je prezidentom Írska?', 'Michael D. Higgins'),
('Politika', 1, 'Kto je predsedom vlády Austrálie?', 'Anthony Albanese'),
('Politika', 1, 'Ktorá strana je v Taliansku vládnou?', 'Lega'),
('Politika', 1, 'Kto je prezidentom Portugalska?', 'Marcelo Rebelo'),
('Politika', 1, 'Aké je hlavné mesto Nemecka?', 'Berlín'),
('Politika', 1, 'Kto je predsedom vlády Rakúska?', 'Karl Nehammer'),
('Politika', 1, 'Kto je prezidentom Južnej Afriky?', 'Cyril Ramaphosa'),
('Politika', 1, 'Kto je premiérom Švédska?', 'Ulf Kristersson'),
('Politika', 1, 'Kto je predsedom strany Zelených?', 'Jozef Mihál'),
('Politika', 1, 'Aké je hlavné mesto Fínska?', 'Helsinki'),
('Politika', 1, 'Kto je prezidentom Rumunska?', 'Klaus Iohannis'),
('Politika', 1, 'Kto je predsedom vlády Grécka?', 'Kyriakos Mitsotakis'),
('Politika', 1, 'Kto je premiérom Malajzie?', 'Anwar Ibrahim'),
('Politika', 1, 'Kto je prezidentom Kolumbie?', 'Gustavo Petro'),
('Politika', 1, 'Kto je predsedom strany SaS?', 'Richard Sulík'),
('Politika', 1, 'Aké je hlavné mesto Austrálie?', 'Canberra'),
('Politika', 1, 'Kto je prezidentom Španielska?', 'Pedro Sánchez'),
('Politika', 1, 'Kto je predsedom strany KDH?', 'Alojz Hlina'),
('Politika', 1, 'Kto je prezidentom Bieloruska?', 'Alexander Lukašenko'),
('Politika', 1, 'Kto je predsedom vlády Islandu?', 'Katrín Jakobsdóttir'),
('Politika', 1, 'Kto je prezidentom Malajzie?', 'Anwar Ibrahim'),
('Politika', 2, 'Kto je predsedom strany ODS?', 'Fiala'),
('Politika', 2, 'Kde sídli Európsky parlament?', 'Štrasburg'),
('Politika', 2, 'Kto je prezidentom Talianska?', 'Mattarella'),
('Politika', 2, 'Kto je premiérom Španielska?', 'Sánchez'),
('Politika', 2, 'Aká je farba vlajky Holandska?', 'Červená'),
('Politika', 2, 'Kto je minister financií SR?', 'Krajniak'),
('Politika', 2, 'Kto je prezidentom Nemecka?', 'Steinmeier'),
('Politika', 2, 'Kto je predsedom strany KDH?', 'Heger'),
('Politika', 2, 'Kde sídli vláda Kanady?', 'Ottawa'),
('Politika', 2, 'Kto je premiérom Bulharska?', 'Petkov'),
('Politika', 2, 'Kto je prezidentom Argentíny?', 'Fernández'),
('Politika', 2, 'Kto je predsedom vlády Švédska?', 'Kristersson'),
('Politika', 2, 'Aká je farba vlajky Francúzska?', 'Modrá'),
('Politika', 2, 'Kto je predsedom strany FIDESZ?', 'Orbán'),
('Politika', 2, 'Kto je generálnym tajomníkom NATO?', 'Stoltenberg'),
('Politika', 2, 'Kto je predsedom strany Smer?', 'Fico'),
('Politika', 2, 'Kto je prezidentom Nórska?', 'Støre'),
('Politika', 2, 'Kto je predsedníčkou vlády Dánska?', 'Frederiksen'),
('Politika', 2, 'Kto je prezidentom Južnej Kórey?', 'Yoon'),
('Politika', 2, 'Kto je predsedom vlády Grécka?', 'Mitsotakis'),
('Politika', 2, 'Kde sídli Európska komisia?', 'Brusel'),
('Politika', 2, 'Kto je premiérom Nemecka?', 'Scholz'),
('Politika', 2, 'Kto je predsedom strany PS?', 'Matovič'),
('Politika', 2, 'Kto je prezidentom Českej republiky?', 'Pavel'),
('Politika', 2, 'Aká je farba vlajky Talianska?', 'Zelená'),
('Politika', 2, 'Kto je predsedom vlády Maďarska?', 'Orbán'),
('Politika', 2, 'Kto je prezidentom Srbska?', 'Vučić'),
('Politika', 2, 'Kto je predsedom vlády Fínska?', 'Marin'),
('Politika', 2, 'Kto je prezidentom Slovenska?', 'Heger'),
('Politika', 2, 'Kto je predsedom strany SaS?', 'Sulík'),
('Politika', 2, 'Kde sídli Ústavný súd SR?', 'Košice'),
('Politika', 2, 'Kto je predsedom vlády Slovinska?', 'Golob'),
('Politika', 2, 'Kto je prezidentom Holandska?', 'Rutte'),
('Politika', 2, 'Kto je predsedom strany Zelených?', 'Krajčír'),
('Politika', 2, 'Kto je premiérom Rakúska?', 'Nehammer'),
('Politika', 2, 'Kto je prezidentom Rumunska?', 'Iohannis'),
('Politika', 2, 'Kto je predsedom strany ĽSNS?', 'Kotleba'),
('Politika', 2, 'Kto je prezidentom Ekvádoru?', 'Lasso'),
('Politika', 2, 'Kto je predsedom vlády Turecka?', 'Erdogan'),
('Politika', 2, 'Kto je prezidentom Švajčiarska?', 'Berset'),
('Politika', 2, 'Kto je predsedníčkou vlády Nového Zélandu?', 'Ardern'),
('Politika', 2, 'Kto je predsedníčkou vlády Islandu?', 'Jakobsdóttir'),
('Politika', 2, 'Kto je prezidentom Austrálie?', 'Albanese'),
('Politika', 2, 'Kto je predsedom vlády Malajzie?', 'Anwar'),
('Politika', 2, 'Kto je prezidentom Južného Sudánu?', 'Kiir'),
('Politika', 2, 'Kto je predsedom strany PS?', 'Matovič'),
('Politika', 2, 'Kto je prezidentom Zeleného mysu?', 'Weyman'),
('Politika', 2, 'Kto je predsedom vlády Kanady?', 'Trudeau'),
('Politika', 2, 'Kto je prezidentom Bahrajnu?', 'Hamad'),
('Politika', 2, 'Kto je predsedom vlády Japonska?', 'Kishida'),
('Politika', 2, 'Kto je prezidentom Malawii?', 'Chakwera'),
('Politika', 2, 'Kto je predsedom strany Smer?', 'Fico'),
('Politika', 2, 'Kto je premiérom Talianska?', 'Meloni'),
('Politika', 2, 'Kto je prezidentom Kene?', 'Ruto'),
('Politika', 2, 'Kto je predsedom strany FIDESZ?', 'Orbán'),
('Politika', 2, 'Kto je prezidentom Zambie?', 'Hakainde'),
('Politika', 2, 'Kto je predsedom Európskej rady?', 'Charles Michel'),
('Politika', 2, 'Aké je hlavné mesto Kanady?', 'Ottawa'),
('Politika', 2, 'Kto je guvernérom Kalifornie?', 'Gavin Newsom'),
('Politika', 2, 'Aká je najstaršia politická strana na Slovensku?', 'HZDS'),
('Politika', 2, 'Kto je predsedom komunistickej strany Číny?', 'Xi Jinping'),
('Politika', 2, 'Kto je premiérom Fínska?', 'Sanna Marin'),
('Politika', 2, 'Ktorá krajina je známa svojím systémom parlamentnej monarchie?', 'Veľká Británia'),
('Politika', 2, 'Kto je predsedom strany Labour v UK?', 'Keir Starmer'),
('Politika', 2, 'Kto je prezidentom Srbska?', 'Aleksandar Vučić'),
('Politika', 2, 'Kto je ministrom obrany USA?', 'Lloyd Austin'),
('Politika', 2, 'Kto je prezidentom Chile?', 'Gabriel Boric'),
('Politika', 2, 'Aká je farba vlajky Talianska?', 'Zelená, biela, červená'),
('Politika', 2, 'Kto je predsedom vlády Holandska?', 'Mark Rutte'),
('Politika', 2, 'Kto je prezidentom Južnej Afriky?', 'Cyril Ramaphosa'),
('Politika', 2, 'Kto je predsedom vlády Belgie?', 'Alexander De Croo'),
('Politika', 2, 'Kto je prezidentom Zeleného mysu?', 'Ursula Gomes'),
('Politika', 2, 'Kto je predsedom strany KDH?', 'Alojz Hlina'),
('Politika', 2, 'Kto je premiérom Talianska?', 'Giorgia Meloni'),
('Politika', 2, 'Aká je hlavná úloha súdnej moci?', 'Rozhodovanie'),
('Politika', 2, 'Kto je predsedom vlády Fínska?', 'Petteri Orpo'),
('Politika', 2, 'Kto je prezidentom Estónska?', 'Alar Karis'),
('Politika', 2, 'Kto je predsedom Európskej komisie?', 'Ursula von der Leyen'),
('Politika', 2, 'Kto je predsedom strany Smer?', 'Robert Fico'),
('Politika', 2, 'Kto je prezidentom Bulharska?', 'Rumen Radev'),
('Politika', 2, 'Kto je predsedom strany ODS?', 'Petr Fiala'),
('Politika', 2, 'Kto je prezidentom Mexika?', 'Andrés Manuel López Obrador'),
('Politika', 2, 'Kto je predsedom vlády Grécka?', 'Kyriakos Mitsotakis'),
('Politika', 2, 'Kto je prezidentom Litvy?', 'Gitanas Nausėda'),
('Politika', 2, 'Kto je predsedom strany SaS?', 'Richard Sulík'),
('Politika', 2, 'Kto je prezidentom Turecka?', 'Recep Tayyip Erdoğan'),
('Politika', 2, 'Kto je predsedom strany FIDESZ?', 'Viktor Orbán'),
('Politika', 2, 'Kto je premiérom Dánska?', 'Mette Frederiksen'),
('Politika', 2, 'Kde sídli vláda Slovenska?', 'Bratislava'),
('Politika', 2, 'Kto je predsedom vlády Nórska?', 'Jonas Gahr Støre'),
('Politika', 2, 'Aké je hlavné mesto Maďarska?', 'Budapešť'),
('Politika', 2, 'Kto je prezidentom Rakúska?', 'Alexander Van der Bellen'),
('Politika', 2, 'Kto je predsedom vlády Španielska?', 'Pedro Sánchez'),
('Politika', 2, 'Kto je predsedom strany Zelených?', 'Annalena Baerbock'),
('Politika', 2, 'Kto je prezidentom Portugalska?', 'Marcelo Rebelo de Sousa'),
('Politika', 2, 'Kto je premiérom Švédska?', 'Ulf Kristersson'),
('Politika', 2, 'Kto je prezidentom Indie?', 'Droupadi Murmu'),
('Politika', 2, 'Kto je predsedom vlády Japonska?', 'Fumio Kishida'),
('Politika', 2, 'Kto je predsedom strany PS?', 'Michal Šimečka'),
('Politika', 2, 'Kto je prezidentom Rakúska?', 'Alexander Van der Bellen'),
('Politika', 2, 'Kto je predsedom vlády Česka?', 'Petr Fiala'),
('Politika', 2, 'Kto je prezidentom Slovinska?', 'Nataša Pirc Musar'),
('Politika', 2, 'Kto je predsedom vlády Malajzie?', 'Anwar Ibrahim'),
('Politika', 2, 'Kto je prezidentom Talianska?', 'Sergio Mattarella'),
('Politika', 2, 'Aké je hlavné mesto Nemecka?', 'Berlín'),
('Politika', 2, 'Kto je predsedom Európskej rady?', 'Charles Michel'),
('Politika', 2, 'Kto je prezidentom Rwandy?', 'Paul Kagame'),
('Politika', 2, 'Kto je predsedom vlády Španielska?', 'Pedro Sánchez'),
('Politika', 2, 'Kde sídli parlament v Taliansku?', 'Rím'),
('Politika', 2, 'Kto je prezidentom Zambie?', 'Hakainde Hichilema'),
('Politika', 2, 'Kto je predsedom vlády Talianska?', 'Giorgia Meloni'),
('Politika', 2, 'Kto je prezidentom Libérie?', 'George Weah'),
('Politika', 2, 'Kto je predsedom strany KDH?', 'Alojz Hlina'),
('Politika', 3, 'Kto je autorom myšlienky laissez-faire?', 'Smith'),
('Politika', 3, 'Kto bol prvým britským premiérom?', 'Walpole'),
('Politika', 3, 'Kde sídli Medzinárodný trestný súd?', 'Haag'),
('Politika', 3, 'Kto je predsedom strany ANO v Česku?', 'Babiš'),
('Politika', 3, 'Kto formuloval teóriu rozdelenia mocí?', 'Montesquieu'),
('Politika', 3, 'Kto je autorom knihy "O štáte"?', 'Platón'),
('Politika', 3, 'Kto bol posledným prezidentom ZSSR?', 'Gorbačov'),
('Politika', 3, 'Kto je hlavným predstaviteľom OSN?', 'Guterres'),
('Politika', 3, 'Kto je zakladateľom strany Podemos?', 'Iglesias'),
('Politika', 3, 'Kto je autorom "Dohody o ochrane ľudských práv"?', 'Európsky súd'),
('Politika', 3, 'Aké je sídlo OSN v New Yorku?', 'Manhattan'),
('Politika', 3, 'Kto bol predsedníkom vlády Ruska v 90. rokoch?', 'Černomyrdin'),
('Politika', 3, 'Kto je autorom "Všeobecnej deklarácie práv človeka"?', 'OSN'),
('Politika', 3, 'Kto bol prvým prezidentom Afriky?', 'Nkrumah'),
('Politika', 3, 'Kto je predsedom strany CDU v Nemecku?', 'Merkel'),
('Politika', 3, 'Kto je autorom knihy "Kapital"?', 'Marx'),
('Politika', 3, 'Kto je predsedom vlády Škótska?', 'Sturgeon'),
('Politika', 3, 'Kto je generálnym tajomníkom NATO?', 'Stoltenberg'),
('Politika', 3, 'Kto je autorom "Pravidiel politickej ekonomie"?', 'Ricardo'),
('Politika', 3, 'Kto je predsedom strany FIDESZ?', 'Orbán'),
('Politika', 3, 'Kto je prezidentom Libérie?', 'Weah'),
('Politika', 3, 'Kto je predsedom vlády Južnej Kórey?', 'Yoon'),
('Politika', 3, 'Kto je zakladateľom strany Smer?', 'Fico'),
('Politika', 3, 'Kto je autorom "Dohody o vojne"?', 'Kissinger'),
('Politika', 3, 'Kto je predsedom strany PIS v Poľsku?', 'Kaczyński'),
('Politika', 3, 'Kto je prezidentom Francúzskej republiky?', 'Macron'),
('Politika', 3, 'Kto je predsedom Európskej rady?', 'Michel'),
('Politika', 3, 'Kto je autorom "Teórie demokratického socializmu"?', 'Rosenberg'),
('Politika', 3, 'Kto je predsedom vlády Talianska?', 'Meloni'),
('Politika', 3, 'Kto je prezidentom Českej republiky?', 'Pavel'),
('Politika', 3, 'Kto je predsedom vlády Malajzie?', 'Anwar'),
('Politika', 3, 'Kto je predsedom strany Labour v UK?', 'Starmer'),
('Politika', 3, 'Kto je prezidentom Argentíny?', 'Massa'),
('Politika', 3, 'Kto je premiérom Grécka?', 'Mitsotakis'),
('Politika', 3, 'Kto je predsedom strany Zelených v Nemecku?', 'Habeck'),
('Politika', 3, 'Kto je predsedom vlády Japonska?', 'Kishida'),
('Politika', 3, 'Kto je prezidentom Juhoafrickej republiky?', 'Ramaphosa'),
('Politika', 3, 'Kto je predsedom strany ANO?', 'Babiš'),
('Politika', 3, 'Kto je predsedom vlády Holandska?', 'Mark Rutte'),
('Politika', 3, 'Kto je prezidentom Egypta?', 'Sisi'),
('Politika', 3, 'Kto je predsedom strany Smer?', 'Fico'),
('Politika', 3, 'Kto je prezidentom Turkmenistanu?', 'Berdimuhamedov'),
('Politika', 3, 'Kto je predsedom strany ODS?', 'Fiala'),
('Politika', 3, 'Kto je prezidentom Fínska?', 'Niinistö'),
('Politika', 3, 'Kto je predsedom strany PZP?', 'Kováč'),
('Politika', 3, 'Kto je prezidentom Ukrajiny?', 'Zelenskyj'),
('Politika', 3, 'Kto je predsedom vlády Rakúska?', 'Nehammer'),
('Politika', 3, 'Kto je prezidentom Nórska?', 'Støre'),
('Politika', 3, 'Kto je predsedom strany FIDESZ?', 'Orbán'),
('Politika', 3, 'Kto je prezidentom Litvy?', 'Nausėda'),
('Politika', 3, 'Kto je predsedom vlády Estónska?', 'Kallas');