INSERT INTO public.questions (category, difficulty, question_text, answer) VALUES 
('Hry a hračky', 3, 'Aká hračka je známa svojou schopnosťou skákať a otáčať sa?', 'Skákajúca guma'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na školských dvoroch a má tvar zvieraťa?', 'Plyšový medveď'),
('Hry a hračky', 3, 'Ktorá hra sa hrá s figurkami a vyžaduje stratégiu?', 'Risk'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou v stavbe?', 'LEGO'),
('Hry a hračky', 3, 'Aká hračka je známa svojou schopnosťou plávať v bazéne?', 'Plávajúca kačička'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie čísel?', 'Číselné kocky'),
('Hry a hračky', 3, 'Ktorá hračka je zvyčajne určená pre staršie deti a obsahuje strategické prvky?', 'Taktické doskové hry'),
('Hry a hračky', 3, 'Ktorá hra sa hrá na doske a zahŕňa obchodovanie?', 'Monopoly'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou vytvárať zvuky?', 'Interaktívna hračka'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená a používa sa na rozvoj motorických zručností?', 'Stavebnica'),
('Hry a hračky', 3, 'Aká hračka je určená na učenie a predstavuje geometrické tvary?', 'Geometrické bloky'),
('Hry a hračky', 3, 'Ktorá hra sa hrá s figúrkami a má cieľ získať väčšinu územia?', 'Risk'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou odolnosťou a je určená pre vonkajšie hry?', 'Lopta'),
('Hry a hračky', 3, 'Aká je názov populárnej kartovej hry s tromi kartami?', 'Bluff'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou svietiť?', 'Svietiaca lopta'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie farieb a tvarov?', 'Tvarové bloky'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na narodeninových oslavách a má tvar zvieraťa?', 'Plyšová hračka'),
('Hry a hračky', 3, 'Ktorá hra sa hrá s figúrkami a vyžaduje logické myslenie?', 'Dáma'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou a modifikovateľnosťou?', 'Stavebnica'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie a má rôzne zvuky?', 'Interaktívna kniha'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená medzi deťmi a je známa svojou zložitou konštrukciou?', 'Robotická hračka'),
('Hry a hračky', 3, 'Aká je populárna hra s figúrkami a má cieľ získať čo najviac bodov?', 'Dominó'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou skákať a pohybovať sa?', 'Skákajúca lopta'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená medzi deťmi a používa sa na hranie vo vode?', 'Vodná hračka'),
('Hry a hračky', 3, 'Ktorá hračka je určená na zábavu a pohyb?', 'Skákací hrad'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou byť "inteligentná"?', 'Interaktívny robot'),
('Hry a hračky', 3, 'Ktorá hračka sa používa na učenie a má rôzne textúry?', 'Textúrované bloky'),
('Hry a hračky', 3, 'Ktorá hra sa hrá s figúrkami a má strategický charakter?', 'Catan'),
('Hry a hračky', 3, 'Ktorá hračka má zvuky a je známa svojou interaktívnosťou?', 'Interaktívna bábika'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená medzi deťmi a má pohyb?', 'Autíčko'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie a má zvuky?', 'Hračkársky telefón'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou a flexibilitou?', 'Modelovacia hmota'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na pieskovisku a má tvar zvieraťa?', 'Pieskový hrad'),
('Hry a hračky', 3, 'Ktorá hra je známa svojím logickým myslením a strategickým plánovaním?', 'Šach'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie a má rôzne geometrické tvary?', 'Geometrické puzzle'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou rozvíjať motoriku?', 'Hračkárske náradie'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na narodeninových oslavách a vydáva zvuky?', 'Hračkárske gitarové nástroje'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou transformácie?', 'Transformers'),
('Hry a hračky', 3, 'Aká hra sa hrá s figúrkami na hexagonálnej doske?', 'Hive'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená v detských súťažiach?', 'Lego'),
('Hry a hračky', 3, 'Aká je populárna strategická hra s civilizáciami?', 'Civilization'),
('Hry a hračky', 3, 'Ktorá hračka je používaná na učenie programovania?', 'RoboBlockly'),
('Hry a hračky', 3, 'Aká hra je známa ako "strategická vojenská hra"?', 'Risk'),
('Hry a hračky', 3, 'Ktorá hračka je založená na zložitom skladaní?', 'Rubikova kocka'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou kooperatívnou hrou proti zombie?', 'Left 4 Dead'),
('Hry a hračky', 3, 'Aká hračka je zameraná na zloženie rôznych tvarov?', 'Geomag'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou prepojiť zvuky a svetlá?', 'Sphero'),
('Hry a hračky', 3, 'Aká hra je známa svojou tematikou prežitia?', 'Ark: Survival'),
('Hry a hračky', 3, 'Ktorá hračka je určená na logické súťaženie?', 'ThinkFun'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou modulárnosťou?', 'Nanoblock'),
('Hry a hračky', 3, 'Aká hra je známa svojou jedinečnou mechanikou presúvania figúriek?', 'Tikal'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená medzi programátormi?', 'LEGO Mindstorms'),
('Hry a hračky', 3, 'Aká hračka je známa svojou interaktívnosťou a učením?', 'Osmo'),
('Hry a hračky', 3, 'Ktorá hra je zameraná na budovanie a obranu?', 'Castle Crashers'),
('Hry a hračky', 3, 'Ktorá hračka má základňu a umožňuje montáž?', 'K''NEX'),
('Hry a hračky', 3, 'Aká hra je známa svojou strategickou výstavbou?', '7 Wonders'),
('Hry a hračky', 3, 'Ktorá hračka je zvyčajne používaná na učenie logiky?', 'Logic Puzzles'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená pri rozvoji kognitívnych schopností?', 'BrainBox'),
('Hry a hračky', 3, 'Aká hra je známa pre tímovú spoluprácu?', 'Overcooked'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou rozvíjať kreativitu?', 'Play-Doh'),
('Hry a hračky', 3, 'Ktorá hračka je zameraná na učenie a má robotické prvky?', 'Botley'),
('Hry a hračky', 3, 'Aká hra je založená na strategickom obchodovaní?', 'Catan'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou interaktívnosťou a programovateľnosťou?', 'Dash'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou tematikou o prežití a stavbe?', 'Minecraft'),
('Hry a hračky', 3, 'Aká hračka je určená na učenie a rozvoj logiky?', 'SmartGames'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou a výnimočnosťou?', 'Tinkercad'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na rozvoj motorických schopností?', 'Perler Beads'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou tematikou hádania a dedukcie?', 'Clue'),
('Hry a hračky', 3, 'Aká hračka je určená na experimentovanie a učenie?', 'Snap Circuits'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou jednoduchosťou a kreatívnosťou?', 'Origami'),
('Hry a hračky', 3, 'Ktorá hračka je určená na strategické plánovanie a obchodovanie?', 'Power Grid'),
('Hry a hračky', 3, 'Aká hra je známa pre budovanie a rozvoj miest?', 'SimCity'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na výučbu matematiky?', 'Math Dice'),
('Hry a hračky', 3, 'Ktorá hračka je zameraná na logické myslenie a stratégie?', 'Hannabi'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou tvoriť zvuky a melódie?', 'Tonies'),
('Hry a hračky', 3, 'Aká hračka je určená na učenie a rozvoj technických zručností?', 'Lego Robotics'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou tematikou prežitia a prepravy?', 'Don''t Starve'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená pre skupinové hranie a interakciu?', 'Werewolf'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou a možnosťou experimentovania?', 'Brio'),
('Hry a hračky', 3, 'Ktorá hra je známa pre kombinovanie logiky a zručnosti?', 'Portal'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie a má rôzne výzvy?', 'Cubetto'),
('Hry a hračky', 3, 'Ktorá hra je pre deti a kombinuje pohyb a zábavu?', 'Just Dance'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou interaktívnosťou a súťaživosťou?', 'Gartic Phone'),
('Hry a hračky', 3, 'Aká hračka je známa svojou schopnosťou skákať a pohybovať sa?', 'Skákajúca lopta'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou a modifikovateľnosťou?', 'Kocky'),
('Hry a hračky', 3, 'Ktorá kartová hra je známa svojou stratégiou a taktizovaním?', 'Pokér'),
('Hry a hračky', 3, 'Aká hračka je založená na zložitom skladaní?', 'Origami'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená medzi programátormi?', 'Robot'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou transformácie?', 'Transformátor'),
('Hry a hračky', 3, 'Ktorá hra je zameraná na budovanie a obranu?', 'Hra o tróny'),
('Hry a hračky', 3, 'Aká hračka je známa svojou schopnosťou rozvíjať kreativitu?', 'Kreatívne kocky'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie a rozvoj technických zručností?', 'Stavebnica'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená pre skupinové hranie a interakciu?', 'Spoločenská hra'),
('Hry a hračky', 3, 'Aká hračka je známa svojou schopnosťou vytvárať zvuky?', 'Zvuková hračka'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou tematikou prežitia a prepravy?', 'Survivor'),
('Hry a hračky', 3, 'Ktorá hračka je určená na logické súťaženie?', 'Logická hra'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou jednoduchosťou a kreatívnosťou?', 'Kreatívny blok'),
('Hry a hračky', 3, 'Ktorá hra je známa pre kombinovanie logiky a zručnosti?', 'Šach'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na výučbu matematiky?', 'Matematické kocky'),
('Hry a hračky', 3, 'Ktorá hračka je zameraná na logické myslenie a stratégie?', 'Strategická hra'),
('Hry a hračky', 3, 'Aká hračka je určená na učenie a má rôzne výzvy?', 'Vzdelávacia hračka'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou a výnimočnosťou?', 'Modulárna hračka'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená pre deti a má pohyb?', 'Pohybujúca sa hračka'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou tematikou hádania a dedukcie?', 'Detektívna hra'),
('Hry a hračky', 3, 'Aká hračka je zvyčajne používaná na učenie logiky?', 'Logické hlavolamy'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou plávať?', 'Plávajúci robot'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou byť "inteligentná"?', 'Inteligentná hračka'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na narodeninových oslavách a má tvar zvieraťa?', 'Plyšová hračka'),
('Hry a hračky', 3, 'Aká hračka je určená na učenie a zahŕňa farby?', 'Farebná hračka'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou svietiť?', 'Svietiaca hračka'),
('Hry a hračky', 3, 'Ktorá hra je zameraná na zábavu a tímovú prácu?', 'Kooperatívna hra'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená na pieskovisku a má tvar zvieraťa?', 'Pieskovisková hračka'),
('Hry a hračky', 3, 'Ktorá hračka je určená na učenie a má rôzne textúry?', 'Textúrovaná hračka'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou odolnosťou?', 'Odolná hračka'),
('Hry a hračky', 3, 'Ktorá hračka je určená na zábavu a pohyb?', 'Pohybová hračka'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou variabilitou a flexibilitou?', 'Flexibilná stavebnica'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou schopnosťou rozvíjať motoriku?', 'Motorická hračka'),
('Hry a hračky', 3, 'Ktorá hra je známa svojou interaktívnosťou a súťaživosťou?', 'Interaktívna hra'),
('Hry a hračky', 3, 'Ktorá hračka je známa svojou zložitou konštrukciou?', 'Složitá stavebnica'),
('Hry a hračky', 3, 'Ktorá hračka je obľúbená medzi deťmi a je známa svojou zábavnosťou?', 'Zábavná hračka'),
('Hry a hračky', 3, 'Ktorá hračka je určená na experimentovanie a učenie?', 'Experimentálna hračka'),
('Hry a hračky', 3, 'Ktorá hračka je zameraná na učenie čísel?', 'Číselná hračka'),
('Hry a hračky', 3, 'Ktorá hra je známa pre tímovú spoluprácu?', 'Tímová hra'),
('Hudba', 1, 'Kto je známy ako "kráľ popu"?', 'Jackson'),
('Hudba', 1, 'Ktorý nástroj má struny a klávesy?', 'Piano'),
('Hudba', 1, 'Aký žáner reprezentuje skupina Beatles?', 'Rock'),
('Hudba', 1, 'Kto zložil pieseň "Imagine"?', 'Lennon'),
('Hudba', 1, 'Ktorý spevák je známy pieseňou "Like a Rolling Stone"?', 'Dylan'),
('Hudba', 1, 'Kto je speváčkou piesne "Rolling in the Deep"?', 'Adele'),
('Hudba', 1, 'Aký nástroj hrá Jimi Hendrix?', 'Gitara'),
('Hudba', 1, 'Ktorá skupina má hit "Hotel California"?', 'Eagles'),
('Hudba', 1, 'Kto je známy ako "Lady Gaga"?', 'Gaga'),
('Hudba', 1, 'Kto zložil "Symfóniu č. 9"?', 'Beethoven'),
('Hudba', 1, 'Aký je pôvodný názov piesne "Yesterday"?', 'Scrambled'),
('Hudba', 1, 'Kto spieva pieseň "Shape of You"?', 'Sheeran'),
('Hudba', 1, 'Aký žáner reprezentuje Beyoncé?', 'Pop'),
('Hudba', 1, 'Ktorý skladateľ je známy svojimi operami?', 'Mozart'),
('Hudba', 1, 'Kto je frontmanom skupiny Coldplay?', 'Martin'),
('Hudba', 1, 'Ktorý nástroj má klávesy a je elektronický?', 'Syntetizátor'),
('Hudba', 1, 'Kto spieval "I Will Always Love You"?', 'Houston'),
('Hudba', 1, 'Kto je spevákom piesne "Uptown Funk"?', 'Mars'),
('Hudba', 1, 'Ktorá kapela má hit "Sweet Child o'' Mine"?', 'Guns N'' Roses'),
('Hudba', 1, 'Kto zložil "Toccata a fuga d moll"?', 'Bach'),
('Hudba', 1, 'Kto má hit "Bad Guy"?', 'Eilish'),
('Hudba', 1, 'Kto spieva pieseň "Viva La Vida"?', 'Coldplay'),
('Hudba', 1, 'Ktorá speváčka má pseudonym "Rihanna"?', 'Fenty'),
('Hudba', 1, 'Kto je autorom piesne "Bohemian Rhapsody"?', 'Queen'),
('Hudba', 1, 'Kto je spevák piesne "Born to Run"?', 'Springsteen'),
('Hudba', 1, 'Ktorá pieseň je známa ako hymna USA?', 'Star-Spangled'),
('Hudba', 1, 'Kto je známy ako "Kráľ rock and rollu"?', 'Elvis'),
('Hudba', 1, 'Aký nástroj sa často používa v jazze?', 'Saxofón'),
('Hudba', 1, 'Kto je autorkou piesne "I Will Survive"?', 'Gaynor'),
('Hudba', 1, 'Ktorý spevák je známy piesňou "Can''t Help Falling in Love"?', 'Presley'),
('Hudba', 1, 'Kto je autorom "Clair de Lune"?', 'Debussy'),
('Hudba', 1, 'Ktorý žáner je spojený s Bobom Marleyom?', 'Reggae'),
('Hudba', 1, 'Kto zložil "Eine kleine Nachtmusik"?', 'Mozart'),
('Hudba', 1, 'Ktorá skupina má hit "Wonderwall"?', 'Oasis'),
('Hudba', 1, 'Kto je speváčkou piesne "Single Ladies"?', 'Beyoncé'),
('Hudba', 1, 'Kto je autorom piesne "My Heart Will Go On"?', 'Dion'),
('Hudba', 1, 'Kto spieva "Shake It Off"?', 'Swift'),
('Hudba', 1, 'Aký nástroj má klávesy a pedály?', 'Organ'),
('Hudba', 1, 'Kto je spevákom piesne "Just the Way You Are"?', 'Mars'),
('Hudba', 1, 'Kto je autorkou piesne "Firework"?', 'Perry'),
('Hudba', 1, 'Ktorá kapela má hit "Smells Like Teen Spirit"?', 'Nirvana'),
('Hudba', 1, 'Kto je autorom piesne "Hallelujah"?', 'Cohen'),
('Hudba', 1, 'Kto je speváčkou piesne "Someone Like You"?', 'Adele'),
('Hudba', 1, 'Kto je známy ako "Kráľ country"?', 'Williams'),
('Hudba', 1, 'Ktorý spevák má hit "In the End"?', 'Linkin Park'),
('Hudba', 1, 'Kto je autorkou piesne "Bad Romance"?', 'Gaga'),
('Hudba', 1, 'Kto je spevák piesne "Let It Be"?', 'McCartney'),
('Hudba', 1, 'Kto je známy ako "Queen of Soul"?', 'Franklin'),
('Hudba', 1, 'Kto je autorom "Satisfaction"?', 'Jagger'),
('Hudba', 1, 'Kto je speváčkou piesne "Chasing Cars"?', 'Snow Patrol'),
('Hudba', 1, 'Ktorá pieseň je známa ako hymna LGBTQ+?', 'Born This Way'),
('Hudba', 1, 'Kto je spevák piesne "Thinking Out Loud"?', 'Sheeran'),
('Hudba', 1, 'Kto je známy ako "Kráľ popu"?', 'Jackson'),
('Hudba', 1, 'Ktorý nástroj je v orchestri najvyšší?', 'Hlas'),
('Hudba', 1, 'Kto je spevákom piesne "Hello"?', 'Adele'),
('Hudba', 1, 'Aký žáner reprezentuje Elvis Presley?', 'Rock'),
('Hudba', 1, 'Kto zložil "Čajkovského balet"?', 'Čajkovskij'),
('Hudba', 1, 'Kto spieva pieseň "Shake It Off"?', 'Swift'),
('Hudba', 1, 'Kto je autorom piesne "The Sound of Silence"?', 'Simon'),
('Hudba', 1, 'Ktorá speváčka má hit "Umbrella"?', 'Rihanna'),
('Hudba', 1, 'Kto je frontmanom skupiny Queen?', 'Mercury'),
('Hudba', 1, 'Kto spieva pieseň "Someone You Loved"?', 'Lewis'),
('Hudba', 1, 'Kto zložil "Nutcracker Suite"?', 'Čajkovskij'),
('Hudba', 1, 'Kto je autorom piesne "Stairway to Heaven"?', 'Page'),
('Hudba', 1, 'Kto má hit "Rolling in the Deep"?', 'Adele'),
('Hudba', 1, 'Kto zložil "Eine kleine Nachtmusik"?', 'Mozart'),
('Hudba', 1, 'Kto spieva pieseň "Tears Dry on Their Own"?', 'Winehouse'),
('Hudba', 1, 'Aký nástroj je klávesový a má struny?', 'Hammond'),
('Hudba', 1, 'Kto je spevákom piesne "Chasing Cars"?', 'Snow Patrol'),
('Hudba', 1, 'Kto je známy ako "Král reggae"?', 'Marley'),
('Hudba', 1, 'Kto zložil pieseň "In the Hall of the Mountain King"?', 'Grieg'),
('Hudba', 1, 'Kto je spevákom piesne "Royals"?', 'Lorde'),
('Hudba', 1, 'Kto zložil "Fur Elise"?', 'Beethoven'),
('Hudba', 1, 'Kto je autorom piesne "Hey Jude"?', 'Lennon'),
('Hudba', 1, 'Kto je speváčkou piesne "Born This Way"?', 'Gaga'),
('Hudba', 1, 'Kto má hit "Counting Stars"?', 'OneRepublic'),
('Hudba', 1, 'Kto je spevákom piesne "Rude"?', 'Magic!'),
('Hudba', 1, 'Kto je autorkou piesne "Stronger"?', 'Kanye'),
('Hudba', 1, 'Kto spieva pieseň "Lose Yourself"?', 'Eminem'),
('Hudba', 1, 'Kto je autorom piesne "My Heart Will Go On"?', 'Horner'),
('Hudba', 1, 'Kto je spevákom piesne "Despacito"?', 'Fonsi'),
('Hudba', 1, 'Kto je spevákom piesne "Say You Won''t Let Go"?', 'James'),
('Hudba', 1, 'Kto zložil pieseň "Clair de Lune"?', 'Debussy'),
('Hudba', 1, 'Kto je autorom piesne "I Want to Hold Your Hand"?', 'Lennon'),
('Hudba', 1, 'Kto je speváčkou piesne "Just a Girl"?', 'Stefani'),
('Hudba', 1, 'Kto má hit "I Gotta Feeling"?', 'Black Eyed Peas'),
('Hudba', 1, 'Kto je známy ako "Kráľ hip-hopu"?', 'Jay-Z'),
('Hudba', 1, 'Kto spieva pieseň "Let It Go"?', 'Idina'),
('Hudba', 1, 'Kto je spevákom piesne "Wake Me Up"?', 'AVICII'),
('Hudba', 1, 'Kto je autorkou piesne "Fight Song"?', 'Rachel'),
('Hudba', 1, 'Kto zložil pieseň "Carmen"?', 'Bizet'),
('Hudba', 1, 'Kto je spevákom piesne "Blinding Lights"?', 'The Weeknd'),
('Hudba', 1, 'Kto je známy ako "Kráľ R&B"?', 'Usher'),
('Hudba', 1, 'Kto zložil "Symfóniu č. 5"?', 'Beethoven'),
('Hudba', 1, 'Kto spieva pieseň "Don''t Start Now"?', 'Dua'),
('Hudba', 1, 'Kto je speváčkou piesne "Bubbly"?', 'Colbie'),
('Hudba', 1, 'Kto je spevákom piesne "All of Me"?', 'Legend'),
('Hudba', 1, 'Kto je autorom piesne "Back to Black"?', 'Winehouse'),
('Hudba', 1, 'Kto má hit "Fight Song"?', 'Rachel'),
('Hudba', 1, 'Kto je spevákom piesne "Firework"?', 'Katy'),
('Hudba', 1, 'Kto je autorkou piesne "Hello"?', 'Adele'),
('Hudba', 1, 'Kto je spevákom piesne "Can''t Stop the Feeling"?', 'Timberlake'),
('Hudba', 2, 'Kto je spevákom piesne "Wonderwall"?', 'Oasis'),
('Hudba', 2, 'Ktorý spevák je známy ako "Kráľ popu"?', 'Michael Jackson'),
('Hudba', 2, 'Kto zložil pieseň "Fur Elise"?', 'Beethoven'),
('Hudba', 2, 'Kto je autorom piesne "Lose Yourself"?', 'Eminem'),
('Hudba', 2, 'Kto je spevákom piesne "Thinking Out Loud"?', 'Ed Sheeran'),
('Hudba', 2, 'Ktorá speváčka má hit "Toxic"?', 'Britney Spears'),
('Hudba', 2, 'Kto zložil "Ravel''s Boléro"?', 'Ravel'),
('Hudba', 2, 'Kto je frontmanom skupiny Oasis?', 'Liam Gallagher'),
('Hudba', 2, 'Kto zložil "Symfóniu č. 40"?', 'Mozart'),
('Hudba', 2, 'Kto je spevákom piesne "Stay"?', 'The Kid LAROI'),
('Hudba', 2, 'Kto je známy ako "Kráľ country"?', 'George Strait'),
('Hudba', 2, 'Kto je speváčkou piesne "Hips Don''t Lie"?', 'Shakira'),
('Hudba', 2, 'Kto je autorom piesne "Summer of ''69"?', 'Bryan Adams'),
('Hudba', 2, 'Kto spieva pieseň "Rolling in the Deep"?', 'Adele'),
('Hudba', 2, 'Kto je spevákom piesne "Radioactive"?', 'Imagine Dragons'),
('Hudba', 2, 'Kto je autorom "The Four Seasons"?', 'Vivaldi'),
('Hudba', 2, 'Kto spieva pieseň "Shake It Off"?', 'Taylor Swift'),
('Hudba', 2, 'Kto je spevákom piesne "Sweet Home Alabama"?', 'Lynyrd Skynyrd'),
('Hudba', 2, 'Kto je speváčkou piesne "Chandelier"?', 'Sia'),
('Hudba', 2, 'Kto zložil "Peer Gynt Suite"?', 'Grieg'),
('Hudba', 2, 'Kto je autorom piesne "I Will Always Love You"?', 'Dolly Parton'),
('Hudba', 2, 'Kto je spevákom piesne "Bad Blood"?', 'Taylor Swift'),
('Hudba', 2, 'Kto je známy ako "Kráľ blues"?', 'B.B. King'),
('Hudba', 2, 'Kto je speváčkou piesne "Genie in a Bottle"?', 'Christina Aguilera'),
('Hudba', 2, 'Kto zložil "Piano Concerto No. 1"?', 'Tchaikovsky'),
('Hudba', 2, 'Kto je spevákom piesne "Born to Run"?', 'Bruce Springsteen'),
('Hudba', 2, 'Kto je autorom piesne "Take Me to Church"?', 'Hozier'),
('Hudba', 2, 'Kto je speváčkou piesne "Halo"?', 'Beyoncé'),
('Hudba', 2, 'Kto zložil "Swan Lake"?', 'Tchaikovsky'),
('Hudba', 2, 'Kto je spevákom piesne "Rolling in the Deep"?', 'Adele'),
('Hudba', 2, 'Kto je speváčkou piesne "Fight Song"?', 'Rachel Platten'),
('Hudba', 2, 'Kto je autorom piesne "Imagine"?', 'John Lennon'),
('Hudba', 2, 'Kto je spevákom piesne "Shallow"?', 'Bradley Cooper'),
('Hudba', 2, 'Kto je známy ako "Queen of Pop"?', 'Madonna'),
('Hudba', 2, 'Kto je spevákom piesne "Wake Me Up"?', 'Avicii'),
('Hudba', 2, 'Kto je autorkou piesne "Back to Black"?', 'Amy Winehouse'),
('Hudba', 2, 'Kto zložil "Carmen"?', 'Bizet'),
('Hudba', 2, 'Kto je speváčkou piesne "Run the World"?', 'Beyoncé'),
('Hudba', 2, 'Kto je spevákom piesne "Dance Monkey"?', 'Tones and I'),
('Hudba', 2, 'Kto je autorom piesne "Somebody to Love"?', 'Queen'),
('Hudba', 2, 'Kto spieva pieseň "Let It Go"?', 'Idina Menzel'),
('Hudba', 2, 'Kto je spevákom piesne "Uptown Funk"?', 'Bruno Mars'),
('Hudba', 2, 'Kto je speváčkou piesne "Bleeding Love"?', 'Leona Lewis'),
('Hudba', 2, 'Kto je autorom piesne "Every Breath You Take"?', 'The Police'),
('Hudba', 2, 'Kto je spevákom piesne "Hey Jude"?', 'The Beatles'),
('Hudba', 2, 'Kto je speváčkou piesne "Ain''t Nobody"?', 'Chaka Khan'),
('Hudba', 2, 'Kto je spevákom piesne "All of Me"?', 'John Legend'),
('Hudba', 2, 'Kto zložil "Rhapsody in Blue"?', 'Gershwin'),
('Hudba', 2, 'Kto je speváčkou piesne "Love Me Like You Do"?', 'Ellie Goulding'),
('Hudba', 2, 'Kto je spevákom piesne "Despacito"?', 'Luis Fonsi'),
('Hudba', 2, 'Kto je autorom piesne "Jolene"?', 'Dolly Parton'),
('Hudba', 2, 'Kto je spevákom piesne "Take Me Home"?', 'Phil Collins'),
('Hudba', 2, 'Kto je speváčkou piesne "My Immortal"?', 'Evanescence'),
('Hudba', 2, 'Kto je spevákom piesne "Fight Song"?', 'Rachel Platten'),
('Hudba', 2, 'Kto je speváčkou piesne "Perfect"?', 'Ed Sheeran'),
('Hudba', 2, 'Kto zložil "The Planets"?', 'Holst'),
('Hudba', 2, 'Aký nástroj má klávesy a struny?', 'Klávesový nástroj'),
('Hudba', 2, 'Kto je známy ako "Kráľ reggae"?', 'Bob Marley'),
('Hudba', 2, 'Kto zložil "Symfóniu č. 6"?', 'Beethoven'),
('Hudba', 2, 'Kto je autorom piesne "Wonderwall"?', 'Oasis'),
('Hudba', 2, 'Kto je spevákom piesne "Thinking Out Loud"?', 'Ed Sheeran'),
('Hudba', 2, 'Kto je speváčkou piesne "Love on Top"?', 'Beyoncé'),
('Hudba', 2, 'Ktorá skupina má hit "Black Dog"?', 'Led Zeppelin'),
('Hudba', 2, 'Kto je spevákom piesne "Chasing Cars"?', 'Snow Patrol'),
('Hudba', 2, 'Kto zložil "Symfóniu č. 40"?', 'Mozart'),
('Hudba', 2, 'Ktorá speváčka má hit "Tears Dry on Their Own"?', 'Amy Winehouse'),
('Hudba', 2, 'Kto je spevákom piesne "Hotline Bling"?', 'Drake'),
('Hudba', 2, 'Kto je známy ako "Kráľ rocku"?', 'Elvis Presley'),
('Hudba', 2, 'Kto zložil pieseň "Ave Maria"?', 'Schubert'),
('Hudba', 2, 'Ktorý spevák je známy piesňou "Hurt"?', 'Johnny Cash'),
('Hudba', 2, 'Kto je speváčkou piesne "Stay"?', 'Rihanna'),
('Hudba', 2, 'Kto je autorom piesne "Shape of My Heart"?', 'Sting'),
('Hudba', 2, 'Kto zložil "Peer Gynt"?', 'Grieg'),
('Hudba', 2, 'Kto je spevákom piesne "Karma Police"?', 'Radiohead'),
('Hudba', 2, 'Kto je autorkou piesne "Take a Bow"?', 'Rihanna'),
('Hudba', 2, 'Ktorá skupina má hit "Boulevard of Broken Dreams"?', 'Green Day'),
('Hudba', 2, 'Kto je spevákom piesne "I Want It That Way"?', 'Backstreet Boys'),
('Hudba', 2, 'Kto je autorom piesne "Sweet Caroline"?', 'Neil Diamond'),
('Hudba', 2, 'Kto je známy ako "Kráľ hip-hopu"?', 'Tupac'),
('Hudba', 2, 'Kto zložil pieseň "Pavane"?', 'Faure'),
('Hudba', 2, 'Kto je spevákom piesne "Dance Monkey"?', 'Tones and I'),
('Hudba', 2, 'Kto je speváčkou piesne "Fight Song"?', 'Rachel Platten'),
('Hudba', 2, 'Kto je spevákom piesne "Somebody That I Used to Know"?', 'Gotye'),
('Hudba', 2, 'Kto je speváčkou piesne "Bleeding Love"?', 'Leona Lewis'),
('Hudba', 2, 'Kto je autorom piesne "Watermelon Sugar"?', 'Harry Styles'),
('Hudba', 2, 'Kto je spevákom piesne "I Don''t Care"?', 'Ed Sheeran'),
('Hudba', 2, 'Kto zložil "Carmen"?', 'Bizet'),
('Hudba', 2, 'Kto je spevákom piesne "Rolling in the Deep"?', 'Adele'),
('Hudba', 2, 'Kto zložil "The Four Seasons"?', 'Vivaldi'),
('Hudba', 2, 'Kto je spevákom piesne "Uptown Funk"?', 'Bruno Mars'),
('Hudba', 2, 'Kto je autorom piesne "Ain''t No Mountain High Enough"?', 'Marvin Gaye'),
('Hudba', 2, 'Kto je speváčkou piesne "Don''t Speak"?', 'No Doubt'),
('Hudba', 2, 'Kto je spevákom piesne "Summer of ''69"?', 'Bryan Adams'),
('Hudba', 2, 'Kto je speváčkou piesne "Say So"?', 'Doja Cat'),
('Hudba', 2, 'Kto zložil pieseň "Fur Elise"?', 'Beethoven'),
('Hudba', 2, 'Kto je spevákom piesne "What a Wonderful World"?', 'Louis Armstrong'),
('Hudba', 2, 'Kto je autorom piesne "Shake It Off"?', 'Taylor Swift'),
('Hudba', 2, 'Kto je spevákom piesne "My Immortal"?', 'Evanescence'),
('Hudba', 2, 'Kto zložil "The Rite of Spring"?', 'Stravinsky'),
('Hudba', 2, 'Kto je speváčkou piesne "Halo"?', 'Beyoncé'),
('Hudba', 2, 'Kto je spevákom piesne "Mr. Brightside"?', 'The Killers'),
('Hudba', 2, 'Kto zložil "Boléro"?', 'Ravel'),
('Hudba', 2, 'Kto je spevákom piesne "The A Team"?', 'Ed Sheeran'),
('Hudba', 2, 'Kto je speváčkou piesne "Bad Liar"?', 'Imagine Dragons'),
('Hudba', 2, 'Kto je spevákom piesne "Take Me to Church"?', 'Hozier'),
('Hudba', 2, 'Kto je spevákom piesne "When We Were Young"?', 'Adele'),
('Hudba', 3, 'Kto je autorom piesne "Satisfaction"?', 'Jagger Richards'),
('Hudba', 3, 'Kto zložil "Rhapsody in Blue"?', 'Gershwin'),
('Hudba', 3, 'Kto je známy ako "Kráľ blues"?', 'B.B. King'),
('Hudba', 3, 'Kto je spevákom piesne "Black" od Pearl Jam?', 'Vedder'),
('Hudba', 3, 'Kto zložil "Symfóniu č. 40"?', 'Mozart'),
('Hudba', 3, 'Kto je spevákom piesne "Creep"?', 'Yorke'),
('Hudba', 3, 'Kto zložil "Symfóniu č. 9"?', 'Beethoven'),
('Hudba', 3, 'Kto je autorom piesne "Take a Chance on Me"?', 'ABBA'),
('Hudba', 3, 'Kto je spevákom piesne "Candle in the Wind"?', 'Elton John'),
('Hudba', 3, 'Kto zložil pieseň "Boléro"?', 'Ravel'),
('Hudba', 3, 'Kto je spevákom piesne "Kashmir"?', 'Plant'),
('Hudba', 3, 'Kto je autorom piesne "Every Breath You Take"?', 'Sting'),
('Hudba', 3, 'Kto je spevákom piesne "Black Dog"?', 'Plant'),
('Hudba', 3, 'Kto zložil "Peer Gynt Suite"?', 'Grieg'),
('Hudba', 3, 'Kto je známy ako "Kráľ country"?', 'Hank Williams'),
('Hudba', 3, 'Kto je autorom piesne "Chasing Cars"?', 'Snow Patrol'),
('Hudba', 3, 'Kto spieva pieseň "Under Pressure"?', 'Queen Bowie'),
('Hudba', 3, 'Kto je spevákom piesne "No Woman No Cry"?', 'Marley'),
('Hudba', 3, 'Kto je autorom piesne "Somebody to Love"?', 'Queen'),
('Hudba', 3, 'Kto zložil pieseň "Adagio for Strings"?', 'Barber'),
('Hudba', 3, 'Kto je speváčkou piesne "Wrecking Ball"?', 'Cyrus'),
('Hudba', 3, 'Kto je spevákom piesne "Zombie"?', 'Cranberries'),
('Hudba', 3, 'Kto zložil "The Magic Flute"?', 'Mozart'),
('Hudba', 3, 'Kto je speváčkou piesne "Fast Car"?', 'Tracy Chapman'),
('Hudba', 3, 'Kto je spevákom piesne "The Sound of Silence"?', 'Simon'),
('Hudba', 3, 'Kto je autorom piesne "Dancing Queen"?', 'ABBA'),
('Hudba', 3, 'Kto je spevákom piesne "Hurt"?', 'Cash'),
('Hudba', 3, 'Kto zložil "Largo" z "Xerxes"?', 'Handel'),
('Hudba', 3, 'Kto je autorom piesne "I Want It That Way"?', 'Backstreet Boys'),
('Hudba', 3, 'Kto je speváčkou piesne "The Greatest"?', 'Sia'),
('Hudba', 3, 'Kto je spevákom piesne "My Way"?', 'Sinatra'),
('Hudba', 3, 'Kto zložil pieseň "The Four Seasons"?', 'Vivaldi'),
('Hudba', 3, 'Kto je spevákom piesne "Take Me to Church"?', 'Hozier'),
('Hudba', 3, 'Kto je autorom piesne "Sound of Silence"?', 'Simon'),
('Hudba', 3, 'Kto je spevákom piesne "Fire and Rain"?', 'Taylor'),
('Hudba', 3, 'Kto zložil "Carnival of the Animals"?', 'Saint-Saëns'),
('Hudba', 3, 'Kto je spevákom piesne "American Pie"?', 'McLean'),
('Hudba', 3, 'Kto je spevákom piesne "Billie Jean"?', 'Jackson'),
('Hudba', 3, 'Kto je autorom piesne "Chopsticks"?', 'N/A'),
('Hudba', 3, 'Kto je speváčkou piesne "Tears in Heaven"?', 'Clapton'),
('Hudba', 3, 'Kto zložil "The Barber of Seville"?', 'Rossini'),
('Hudba', 3, 'Kto je spevákom piesne "Sweet Child o'' Mine"?', 'Axl Rose'),
('Hudba', 3, 'Kto je autorom piesne "Let It Be"?', 'Lennon McCartney'),
('Hudba', 3, 'Kto je spevákom piesne "Hotel California"?', 'Frey'),
('Hudba', 3, 'Kto zložil pieseň "Nessun dorma"?', 'Puccini'),
('Hudba', 3, 'Kto je spevákom piesne "Imagine"?', 'Lennon'),
('Hudba', 3, 'Kto je autorom piesne "A Change Is Gonna Come"?', 'Cooke'),
('Hudba', 3, 'Kto je speváčkou piesne "Vision of Love"?', 'Carey'),
('Hudba', 3, 'Kto je spevákom piesne "Born to Run"?', 'Springsteen'),
('Hudba', 3, 'Kto zložil pieseň "Peer Gynt"?', 'Grieg'),
('Hudba', 3, 'Kto je autorom piesne "Ain''t No Sunshine"?', 'Withers'),
('Hudba', 3, 'Kto je spevákom piesne "Karma Police"?', 'Yorke'),
('Hudba', 3, 'Kto je speváčkou piesne "Rolling in the Deep"?', 'Adele'),
('Hudba', 3, 'Kto je známy ako "Kráľ rock and rollu"?', 'Elvis'),
('Hudba', 3, 'Kto zložil "Fifth Symphony"?', 'Beethoven'),
('Hudba', 3, 'Kto je speváčkou piesne "All I Want"?', 'Kodaline'),
('Hudba', 3, 'Kto je spevákom piesne "Let It Go"?', 'Menzel'),
('Hudba', 3, 'Kto zložil operu "Tristan a Isolda"?', 'Wagner'),
('Hudba', 3, 'Kto je autorom piesne "In the Mood"?', 'Miller'),
('Hudba', 3, 'Kto je spevákom piesne "Creep"?', 'Radiohead'),
('Hudba', 3, 'Kto zložil "Fifth Symphony"?', 'Beethoven'),
('Hudba', 3, 'Kto je spevákom piesne "Black"?', 'Pearl Jam'),
('Hudba', 3, 'Kto zložil pieseň "The Rite of Spring"?', 'Stravinsky'),
('Hudba', 3, 'Kto je autorom piesne "Bohemian Rhapsody"?', 'Queen'),
('Hudba', 3, 'Kto je spevákom piesne "All Along the Watchtower"?', 'Dylan'),
('Hudba', 3, 'Kto zložil "The Magic Flute"?', 'Mozart'),
('Hudba', 3, 'Kto je spevákom piesne "Hurt"?', 'Nine Inch Nails'),
('Hudba', 3, 'Kto je autorom piesne "Take A Bow"?', 'Rihanna'),
('Hudba', 3, 'Kto je spevákom piesne "Baba O''Riley"?', 'The Who'),
('Hudba', 3, 'Kto je autorom piesne "Blackbird"?', 'McCartney'),
('Hudba', 3, 'Kto zložil pieseň "Adagio for Strings"?', 'Barber'),
('Hudba', 3, 'Kto je spevákom piesne "Zombie"?', 'The Cranberries'),
('Hudba', 3, 'Kto je autorom piesne "Toxic"?', 'Britney Spears'),
('Hudba', 3, 'Kto je spevákom piesne "Wish You Were Here"?', 'Pink Floyd'),
('Hudba', 3, 'Kto zložil pieseň "Carmen"?', 'Bizet'),
('Hudba', 3, 'Kto je autorom piesne "Dancing Queen"?', 'ABBA'),
('Hudba', 3, 'Kto je spevákom piesne "Back in Black"?', 'AC/DC'),
('Hudba', 3, 'Kto zložil pieseň "The Four Seasons"?', 'Vivaldi'),
('Hudba', 3, 'Kto je spevákom piesne "Sweet Caroline"?', 'Diamond'),
('Hudba', 3, 'Kto je autorom piesne "Another Brick in the Wall"?', 'Pink Floyd'),
('Hudba', 3, 'Kto zložil pieseň "Fur Elise"?', 'Beethoven'),
('Hudba', 3, 'Kto je spevákom piesne "Come Together"?', 'The Beatles'),
('Hudba', 3, 'Kto je autorom piesne "I Want You Back"?', 'Jackson 5'),
('Hudba', 3, 'Kto je speváčkou piesne "Someone Like You"?', 'Adele'),
('Hudba', 3, 'Kto zložil pieseň "Rhapsody in Blue"?', 'Gershwin'),
('Hudba', 3, 'Kto je autorom piesne "Chasing Cars"?', 'Snow Patrol'),
('Hudba', 3, 'Kto je spevákom piesne "Rude"?', 'Magic!'),
('Hudba', 3, 'Kto je autorom piesne "Take Me Home, Country Roads"?', 'John Denver'),
('Hudba', 3, 'Kto zložil pieseň "Ode to Joy"?', 'Beethoven'),
('Hudba', 3, 'Kto je spevákom piesne "No Woman, No Cry"?', 'Bob Marley'),
('Hudba', 3, 'Kto je autorom piesne "Under Pressure"?', 'Queen'),
('Hudba', 3, 'Kto je speváčkou piesne "Say So"?', 'Doja Cat'),
('Hudba', 3, 'Kto zložil pieseň "Boléro"?', 'Ravel'),
('Hudba', 3, 'Kto je spevákom piesne "Black Dog"?', 'Led Zeppelin'),
('Hudba', 3, 'Kto je autorom piesne "Fight Song"?', 'Rachel Platten'),
('Hudba', 3, 'Kto je speváčkou piesne "Vision of Love"?', 'Mariah Carey'),
('Hudba', 3, 'Kto zložil pieseň "Swan Lake"?', 'Tchaikovsky'),
('Hudba', 3, 'Kto je spevákom piesne "American Pie"?', 'Don McLean'),
('Hudba', 3, 'Kto je autorom piesne "Landslide"?', 'Fleetwood Mac'),
('Hudba', 3, 'Kto je spevákom piesne "Waiting on the World to Change"?', 'John Mayer'),
('Hudba', 3, 'Kto zložil pieseň "The Barber of Seville"?', 'Rossini'),
('Hudba', 3, 'Kto je autorom piesne "Ain''t No Sunshine"?', 'Bill Withers'),
('Hudba', 3, 'Kto je spevákom piesne "Desire"?', 'U2'),
('Hudba', 3, 'Kto je autorom piesne "My Immortal"?', 'Evanescence'),
('Hudba', 3, 'Kto je spevákom piesne "Hallelujah"?', 'Cohen'),
('Hudba', 3, 'Kto zložil pieseň "Peer Gynt"?', 'Grieg'),
('Hudba', 3, 'Kto je autorom piesne "Take a Chance on Me"?', 'ABBA'),
('Hudba', 3, 'Kto je speváčkou piesne "Bleeding Love"?', 'Leona Lewis'),
('Technológie', 1, 'Aký jazyk sa používa na webový vývoj?', 'HTML'),
('Technológie', 1, 'Aký je najpoužívanejší operačný systém na svete?', 'Windows'),
('Technológie', 1, 'Kto je zakladateľom spoločnosti Microsoft?', 'Gates'),
('Technológie', 1, 'Aký je skratka pre osobný počítač?', 'PC'),
('Technológie', 1, 'Aký produkt vyrába spoločnosť Google?', 'Android'),
('Technológie', 1, 'Ktorý prehliadač je od spoločnosti Mozilla?', 'Firefox'),
('Technológie', 1, 'Aký je skriptovací jazyk pre web?', 'JavaScript'),
('Technológie', 1, 'Aký typ pamäte je RAM?', 'Dočasná'),
('Technológie', 1, 'Aký je názov najpopulárnejšej sociálnej siete?', 'Facebook'),
('Technológie', 1, 'Aký je názov aplikácie pre videohovory od Microsoftu?', 'Teams'),
('Technológie', 1, 'Ktorý vyhľadávač je najpoužívanejší?', 'Google'),
('Technológie', 1, 'Aký je názov populárneho grafického editora?', 'Photoshop'),
('Technológie', 1, 'Ktorá spoločnosť vyvinula Windows?', 'Microsoft'),
('Technológie', 1, 'Aký je skratka pre rozhranie USB?', 'Universal'),
('Technológie', 1, 'Aký jazyk sa používa na vytváranie aplikácií pre iOS?', 'Swift'),
('Technológie', 1, 'Aký je názov cloudovej služby od Amazonu?', 'AWS'),
('Technológie', 1, 'Ktorý jazyk je vyvinutý na analýzu dát?', 'R'),
('Technológie', 1, 'Aký je názov známeho operačného systému pre servery?', 'Linux'),
('Technológie', 1, 'Kto vyvinul jazyk Python?', 'Guido'),
('Technológie', 1, 'Ktorá technológia sa používa na bezdrôtový prenos?', 'Wi-Fi'),
('Technológie', 1, 'Aký je názov najpopulárnejšej platformy pre videohry?', 'Steam'),
('Technológie', 1, 'Aký je názov technológie virtuálnej reality od Oculus?', 'Rift'),
('Technológie', 1, 'Ktorá spoločnosť vyrába MacBook?', 'Apple'),
('Technológie', 1, 'Aký je názov aplikácie pre poznámky od Microsoftu?', 'OneNote'),
('Technológie', 1, 'Aký je najpoužívanejší jazyk na programovanie webu?', 'JavaScript'),
('Technológie', 1, 'Aký je názov technológie pre prehliadanie internetu?', 'HTTP'),
('Technológie', 1, 'Ktorá firma vyrobila Xbox?', 'Microsoft'),
('Technológie', 1, 'Aký je názov populárnej platformy pre video streaming?', 'YouTube'),
('Technológie', 1, 'Ktorý jazyk je známy pre svoj syntax a čitateľnosť?', 'Python'),
('Technológie', 1, 'Aký je názov najpopulárnejšieho operačného systému pre mobily?', 'Android'),
('Technológie', 1, 'Aký je názov nástroja na správu verzí?', 'Git'),
('Technológie', 1, 'Kto je zakladateľom spoločnosti Apple?', 'Jobs'),
('Technológie', 1, 'Aký je názov populárneho operačného systému pre servery?', 'Ubuntu'),
('Technológie', 1, 'Aký je názov programovacieho jazyka od Sun Microsystems?', 'Java'),
('Technológie', 1, 'Aký je názov systému pre správu databáz od Oracle?', 'Oracle'),
('Technológie', 1, 'Aký je názov nástroja na analýzu webovej návštevnosti?', 'Google Analytics'),
('Technológie', 1, 'Aký je názov technológie pre bezdrôtové nabíjanie?', 'Qi'),
('Technológie', 1, 'Ktorá firma vyrába Surface?', 'Microsoft'),
('Technológie', 1, 'Aký je názov najpopulárnejšieho operačného systému pre serverové aplikácie?', 'Linux'),
('Technológie', 1, 'Aký je názov technológie pre zabezpečenie webových stránok?', 'SSL'),
('Technológie', 1, 'Aký jazyk sa používa na programovanie webových aplikácií?', 'PHP'),
('Technológie', 1, 'Aký je názov platformy pre online spoluprácu od Atlassian?', 'Confluence'),
('Technológie', 1, 'Ktorý jazyk je známy pre svoje použitie v data science?', 'R'),
('Technológie', 1, 'Aký je názov populárnej aplikácie pre správu úloh?', 'Todoist'),
('Technológie', 1, 'Aký je názov technológie pre automatizáciu marketingu?', 'CRM'),
('Technológie', 1, 'Ktorá firma vyrobila Chromebook?', 'Google'),
('Technológie', 1, 'Aký je názov technológie pre mobilné platby?', 'NFC'),
('Technológie', 1, 'Aký je názov operačného systému pre zariadenia Apple?', 'iOS'),
('Technológie', 1, 'Ktorý jazyk je známy pre svoju rýchlosť?', 'C++'),
('Technológie', 1, 'Aký je názov aplikácie na správu hesiel?', 'LastPass'),
('Technológie', 1, 'Kto je zakladateľom spoločnosti Facebook?', 'Zuckerberg\nTechnológie'),
('Technológie', 1, 'Aký jazyk sa používa na skriptovanie v prehliadači?', 'JavaScript'),
('Technológie', 1, 'Čo je skratka pre osobný počítač?', 'PC'),
('Technológie', 1, 'Aký je názov najpopulárnejšieho operačného systému pre mobilné zariadenia?', 'Android'),
('Technológie', 1, 'Ktorý produkt je známy ako „jablko“?', 'iPhone'),
('Technológie', 1, 'Aký jazyk sa často používa na serverovej strane?', 'PHP'),
('Technológie', 1, 'Čo je skratka pre hypertextový prenosový protokol?', 'HTTP'),
('Technológie', 1, 'Aký je názov najpopulárnejšieho operačného systému pre servery?', 'Linux'),
('Technológie', 1, 'Aká je skratka pre „Internet of Things“?', 'IoT'),
('Technológie', 1, 'Aký je názov cloudovej služby od Google?', 'Drive'),
('Technológie', 1, 'Čo je skratka pre bezpečnostný protokol?', 'SSL');